### ISSUE TITLE
Crash title

### ISSUE THREAD

**Issue by Andrey228322** [BluSunrize/ImmersiveEngineering#1024]
Crash client, when it points to the last item from the mode!
Fix pls

**Comment by Andrey228322** [comment]
`java.lang.NoSuchMethodError: blusunrize.immersiveengineering.client.IENixieFontRender.bindTexture(Lnet/minecraft/util/ResourceLocation;)V
	at blusunrize.immersiveengineering.client.IENixieFontRender.func_78277_a(IENixieFontRender.java:129)
	at net.minecraft.client.gui.FontRenderer.func_78278_a(FontRenderer.java:244)
	at net.minecraft.client.gui.FontRenderer.func_78255_a(FontRenderer.java:489)
	at net.minecraft.client.gui.FontRenderer.func_78258_a(FontRenderer.java:607)
	at net.minecraft.client.gui.FontRenderer.func_85187_a(FontRenderer.java:355)
	at blusunrize.immersiveengineering.client.IENixieFontRender.func_85187_a(IENixieFontRender.java:36)
	at net.minecraft.client.gui.FontRenderer.func_78276_b(FontRenderer.java:336)
	at blusunrize.immersiveengineering.client.render.ItemRenderRailgun.renderItem(ItemRenderRailgun.java:281)
	at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:183)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:489)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1358)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at launcher.client.ClientLauncher.launch(ClientLauncher.java:285)
	at launcher.client.ClientLauncher.main(ClientLauncher.java:186)`

**Comment by BluSunrize** [comment]
That's not how you do crashlogs. Use pastebin, and get me the full log.

**Comment by Andrey228322** [comment]
http://pastebin.com/xE4sRdFt

**Comment by BluSunrize** [comment]
Can you reproduce this without optifine?

**Comment by Andrey228322** [comment]
Unfortunately not.

**Comment by BluSunrize** [comment]
Then it's an optifine issue, and this is closed. I can't account for things that are broken by Optifine.

**Comment by Andrey228322** [comment]
Can you do something? Because without Optifine nowhere!

**Comment by BluSunrize** [comment]
No I can't. Optifine breaks shit. Stop using it, There are other performance improvements. Fastcraft, COFHTweaks. Both of those work well without breaking things.
Optifine is inconsiderate and badly hacks rendercode. I can't and won't account for that.

**Comment by Andrey228322** [comment]
http://pastebin.com/22k30EpQ
HELLO. Again no start MC!

**Comment by BluSunrize** [comment]
Update Minetweaker. Also, don't post in closed issues, make new ones for new crashes. And search the issue tracker. That saves you the trouble entirely. Because this has been reported countless times.

**Comment by Andrey228322** [comment]
Tell me right now, I can put your mod to their server. And do not amass large samples and more beautiful? How do you say? Map is now open all the way!

**Comment by BluSunrize** [comment]
...try that again in English?

**Comment by Andrey228322** [comment]
Can I put on the mod already working server?
Did not have any problems with bug, dupe, chash and any?
build server > http://prnt.sc/ahmcdc
build mc > http://prnt.sc/ahmcpa
What do you think?

**Comment by BluSunrize** [comment]
I dunno? That's up to you to decide, not me. As far as I can see, no known incompatabilities.
