### ISSUE TITLE
Redstone breaker causes crash upon server join

### ISSUE THREAD

**Issue by ViciousVinnyD** [BluSunrize/ImmersiveEngineering#1030]
When a player joins the server and there is a redstone breaker nearby the client crashes. Getting another player to destroy the breaker before the client joins prevents this.

Actually placing a breaker does not cause this, only joining while there are existing breakers does.

Using ImmersiveEngineering-0.7.3

[08:32:04] [Client thread/INFO]: Connecting to 203.87.104.222, 25565
[08:32:23] [Client thread/INFO]: [CHAT] Welcome to the server!
[08:32:50] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityRedstoneBreaker.getConnectionOffset(TileEntityRedstoneBreaker.java:48) ~[TileEntityRedstoneBreaker.class:?]
	at blusunrize.immersiveengineering.client.ClientUtils.drawConnection(ClientUtils.java:123) ~[ClientUtils.class:?]
	at blusunrize.immersiveengineering.client.ClientUtils.drawConnection(ClientUtils.java:117) ~[ClientUtils.class:?]
	at blusunrize.immersiveengineering.client.ClientUtils.renderAttachedConnections(ClientUtils.java:104) ~[ClientUtils.class:?]
	at blusunrize.immersiveengineering.client.render.BlockRenderMetalDevices.renderWorldBlock(BlockRenderMetalDevices.java:188) ~[BlockRenderMetalDevices.class:?]
	at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118) ~[RenderingRegistry.class:?]
	at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53) ~[FMLRenderAccessLibrary.class:?]
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296) ~[blm.class:?]
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181) ~[blo.class:?]
	at fastcraft.a.o.a(F:86) ~[fastcraft-1.21.jar:?]
	at fastcraft.Hooks.t(F:147) ~[fastcraft-1.21.jar:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187) ~[blt.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015) ~[blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by mindforger** [comment]
full crashlog via pastebin or as attachment please :)
