### ISSUE TITLE
world not loading

### ISSUE THREAD

**Issue by lunchboxxx19** [BluSunrize/ImmersiveEngineering#1063]
ive tried installing this mod a few times now and i can never get it to load with my other mods but if i load it on its own it loads perfectly fine. has anyone come across a mod its incompatible with or found a limitation to the amount of mods it will work alongside. im running 6gb dedicated and have tried it with 8gb as well. it doesnt crash or anything it just seems to get stuck on the world loading screen till i force close

**Comment by theunkn0wn1** [comment]
Can you please provide us with the full client log and the list of mods\modpack your are attempting to use with IE?

I run minecraft with 120+ mods with 8 GB dedicated to the MineCraft client.

**Comment by BluSunrize** [comment]
Exactly. Give me logs or I can't help you.

**Comment by lunchboxxx19** [comment]
the mod list is here - [modlist](https://www.dropbox.com/home?preview=Mods.txt)
the latest log is here - [latest log](https://www.dropbox.com/home?preview=latest.log)
game output is here - [game output](https://www.dropbox.com/home?preview=Game+output.txt)
fml-client-latest is here - [fml client latest](https://www.dropbox.com/home?preview=fml-client-latest.log)

**Comment by Joshwoo69** [comment]
links broken.you will have to share it in dropbox by pressing the link icon.

**Comment by lunchboxxx19** [comment]
sorry must have copied the wrong link. links have been updated now and should work

**Comment by theunkn0wn1** [comment]
Wow..... That log is a mess. Extracted what looks like the relevant piece. However the pack you got there is a real mess to begin with...

>[13:38:50] [Server thread/INFO] [ImmersiveEngineering/ImmersiveEngineering]: Starting recipe profiler for Arc Recycling, using 8 Threads
[13:38:50] [Thread-42/ERROR] [deconstruction/deconstruction]: Exception Caught: java.lang.NullPointerException
[13:38:50] [Thread-42/INFO] [STDERR/deconstruction]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[13:38:50] [Thread-42/INFO] [STDERR/deconstruction]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.item.ItemStack.func_77977_a(ItemStack.java:361)
[13:38:50] [Thread-42/INFO] [STDERR/deconstruction]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at deconstruction.deconTable.DeconRecipe.isNotRecursive(DeconRecipe.java:236)
[13:38:50] [Thread-42/INFO] [STDERR/deconstruction]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at deconstruction.deconTable.DeconRecipe.addShapelessRecipe(DeconRecipe.java:162)
[13:38:50] [Thread-42/INFO] [STDERR/deconstruction]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at deconstruction.common.RecipeMover.run(RecipeMover.java:36)
[13:38:50] [Thread-42/INFO] [STDERR/deconstruction]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Thread.run(Thread.java:745)
[13:38:50] [Thread-42/INFO] [deconstruction/deconstruction]: 11142 out of 20030 recipes added.

Might been caused by all those ID mismatches...

**Comment by lunchboxxx19** [comment]
Yeah i have 3 or 4 mods that tinker with crafting. Ill remove them and try again. Do you want me to post new logs after trying?

**Comment by theunkn0wn1** [comment]
Yes, please post updated logs in the event the previous suggestion does not resolve your issue. At this point I am attempting to discern whether an IE issue is occurring with or without other mods.

**Comment by lunchboxxx19** [comment]
sorry i been out of town with no internet the last couple days. i ended up taking a read through the "game output" and noticed that the game always freezes at the point where it starts adding arc furnace recipes so i changed the config to turn off the ability to recycle armour and tools. this resulted in the same crash then i started changing config options in "improving minecraft" and now the game seems to be loading no issues at all

**Comment by theunkn0wn1** [comment]
... So it was "improved Minecraft" that was causing the issue then?

If so, this thread should be closed.

**Comment by lunchboxxx19** [comment]
im not to sure, none of the config options i turned off should of affected the way this mod works... or perhaps it did im not sure im still learning. but yup can someone please close this thread. thank you for your help

**Comment by XFactHD** [comment]
You can close it yourself.

**Comment by lunchboxxx19** [comment]
woops didnt see that haha sorry
