### ISSUE TITLE
The Enderman/Enderdragon Game crash and toolbox game Crash

### ISSUE THREAD

**Issue by AsmundLindstrom** [BluSunrize/ImmersiveEngineering#1179]
[Crashlog Enderman.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/299054/Crashlog.Enderman.txt)

Launching an High explosive cartridge at either the dragon or the enderman, causes the game to crash upon either contact, damage registration or upon the general direction. 

Cant seem to upload the Txt from the toolbox, some weird shit, but just try to add a bottle of biodiesel to the toolbox wiring part, it crashes at my side. 

Ender Dragon Launcher-Side crash log 

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 5-6-16 0:19
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.entity.boss.EntityDragon.func_70965_a(EntityDragon.java:523)
	at net.minecraft.entity.boss.EntityDragonPart.func_70097_a(SourceFile:40)
	at blusunrize.immersiveengineering.common.entities.EntityRevolvershot.onImpact(EntityRevolvershot.java:302)
	at blusunrize.immersiveengineering.common.entities.EntityRevolvershot.func_70071_h_(EntityRevolvershot.java:211)
	at net.minecraft.world.World.func_72866_a(World.java:1862)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:700)
	at net.minecraft.world.World.func_72870_g(World.java:1831)
	at net.minecraft.world.World.func_72939_s(World.java:1663)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.entity.boss.EntityDragon.func_70965_a(EntityDragon.java:523)
	at net.minecraft.entity.boss.EntityDragonPart.func_70097_a(SourceFile:40)
	at blusunrize.immersiveengineering.common.entities.EntityRevolvershot.onImpact(EntityRevolvershot.java:302)
	at blusunrize.immersiveengineering.common.entities.EntityRevolvershot.func_70071_h_(EntityRevolvershot.java:211)
	at net.minecraft.world.World.func_72866_a(World.java:1862)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:700)
	at net.minecraft.world.World.func_72870_g(World.java:1831)

-- Entity being ticked --
Details:
	Entity Type: ImmersiveEngineering.revolverShot (blusunrize.immersiveengineering.common.entities.EntityRevolvershot)
	Entity ID: 75815
	Entity Name: entity.ImmersiveEngineering.revolverShot.name
	Entity's Exact location: -42,62, 62,38, 35,60
	Entity's Block location: -43,00,62,00,35,00 - World: (-43,62,35), Chunk: (at 5,3,3 in -3,2; contains blocks -48,0,32 to -33,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: -0,44, 0,50, -0,74
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1663)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)

-- Affected level --
Details:
	Level name: Test
	All players: 1 total; [EntityPlayerMP['AsmundLindstrom'/454, l='Test', x=-41,01, y=59,00, z=38,27]]
	Chunk stats: ServerChunkCache: 621 Drop: 0
	Level seed: -4785963183029674969
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 0,00,0,00,0,00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 263083336 bytes (250 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.19 Powered by Forge 11.15.1.1902 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCHIJAAAA	Forge{11.15.1.1902} [Minecraft Forge] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.8-27} [Immersive Engineering] (ImmersiveEngineering-0.8-27.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['AsmundLindstrom'/454, l='Test', x=-41,01, y=59,00, z=38,27]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

Didnt get the Txt for some reason, sorry.

**Comment by elkillo** [comment]
the adding non-block items to the tool box is a known bug and they are attempting to fix it, the explosive rounds however is a weird one.

**Comment by AsmundLindstrom** [comment]
Yeah i just posted the thing on the IE overvieuw thread and was told to drop it here. Also, in the last test i hit the dragon straight in the forehead with the pellet, pretty happy about that one :  ^)

**Comment by malte0811** [comment]
I know why this is crashing, the damagesource is null for exploding bullets (meta 3) and while the if-statement above the apply damage one only runs if the damagesource is not null, the entity is attacked with a null damage source. I'll add that to the misc fixes PR this afternoon, the tesla stuff should be ready then as well.
For now don't use exploding bullets, any othe type should be fine.

**Comment by BluSunrize** [comment]
Ohhhh. Fuck did I miss a dmg source on the explosive ones too? Thought I just fucked up on the silver ones x3

Feel free to chuck that into yours malte, my next PR is going to be that floodlight. It' a mess, but it's almost working. xD
