### ISSUE TITLE
Server Crash Tesla Coil

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [BluSunrize/ImmersiveEngineering#1198]
Issue: Server timeout and crash after dropping Tesla Coil on ground.
What happened before: I was dropping a different item and when i clicked Q on the Tesla Coil server froze and timed out which then crashed. 
AttemptFixed: Turning   B:removeErroringEntities=false to true only placed the item in the world or caused them to be placed but that made it worse, they cant be broken in creative, now we are trying to forcefully remove them

CrashLogPointingtoIME:
Time: 6/16/16 4:43 PM
Description: Ticking entity

java.lang.NoSuchFieldError: effectMap
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityTeslaCoil.<clinit>(TileEntityTeslaCoil.java:49)
	at blusunrize.immersiveengineering.common.blocks.metal.BlockMetalDevice1.func_149915_a(BlockMetalDevice1.java:138)
	at net.minecraft.block.Block.createTileEntity(Block.java:1309)
	at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:831)
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:848)
	at net.minecraft.world.World.func_175625_s(World.java:2295)
	at com.ternsip.stabilizermod.Chargeable.<init>(Chargeable.java:39)
	at com.ternsip.stabilizermod.Container.<init>(Container.java:24)
	at com.ternsip.stabilizermod.Registrant.register(Registrant.java:69)
	at com.ternsip.stabilizermod.Stabilizermod.watchChunk(Stabilizermod.java:43)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_620_Stabilizermod_watchChunk_Watch.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:298)
	at net.minecraft.world.World.func_72866_a(World.java:1862)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:700)
	at net.minecraft.world.World.func_72870_g(World.java:1831)
	at net.minecraft.world.World.func_72939_s(World.java:1663)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Unknown Source)

FullLog:
http://pastebin.com/N8a8qmvr
Minecraft:1.8.9
Forge:1902

**Comment by XFactHD** [comment]
Can you reproduce this without the stabilizer mod.

**Comment by BluSunrize** [comment]
You don't have to put part of the crashlog on here. Just give us the link. We don't want it on here. The point of the link is to not have 25 lines of stacktrace in the post.
Not stabilizermod's fault @XFactHD 
In fact, very much, my fault. Can't initialize a static client only field. Will fix.

**Comment by EPIICTHUNDERCAT** [comment]
the lines i provided are what made me know it was your mod, and the link should be a full crash log. and thank you!

**Comment by XFactHD** [comment]
Sorry for making a wrong assumption, maybe I should have looked at the code before replying.

**Comment by kotoroshinoto** [comment]
is there a build available with this fix in it yet?

**Comment by kotoroshinoto** [comment]
Would this cause a ticking entity crash?

**Comment by BluSunrize** [comment]
@kotoroshinoto 
A "ticking entity crash" is completely nondescript. Open a new issue with crashlog and version info and I'd be happy to help you.
