### ISSUE TITLE
Revolver w/ explosive ammunition causes crashes

### ISSUE THREAD

**Issue by Garbius** [BluSunrize/ImmersiveEngineering#1201]
The game crashes when firing explosive rounds at a creature (firing at the world works just fine). It has been tested in SP running Windows 7 x86_64, Java 1.8.0_25 with no other mods present and on a DS running Linux 4.6.2 (x86) and OpenJDK 1.8.0_92. Both are running forge 1.8.9-11.15.1.1902 and IE 0.8-27.

```
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:755)
        at net.minecraft.entity.monster.EntityMob.func_70097_a(SourceFile:53)
        at blusunrize.immersiveengineering.common.entities.EntityRevolvershot.onImpact(EntityRevolvershot.java:302)
        at blusunrize.immersiveengineering.common.entities.EntityRevolvershot.func_70071_h_(EntityRevolvershot.java:211)
        at net.minecraft.world.World.func_72866_a(World.java:1862)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:700)
        at net.minecraft.world.World.func_72870_g(World.java:1831)
        at net.minecraft.world.World.func_72939_s(World.java:1663)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by malte0811** [comment]
Duplicate of #1179.

**Comment by Garbius** [comment]
Oh. Didn't find that one.
