### ISSUE TITLE
ConcurrentModificationException (and possibly wire disappearing bug)

### ISSUE THREAD

**Issue by SanAndreasP** [BluSunrize/ImmersiveEngineering#128]
Minecraft: 1.7.10
Forge: 10.13.4.1451
Immersive Engineering: 0.3.2

I crashed after trying to replace the copper wire, which disappeared after world reload (possibly another bug, dunno if it's fixed now, since it happened in 0.2.4 and was updating to 0.3.2):
https://gist.githubusercontent.com/SanAndreasP/a39b08ae7e546eac52ba/raw/gistfile1.txt

There's a LV connector on the bottom of a Leadstone Energy cell and another on a Pulverizer, if this info is of any value.

Stacktrace:
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:486)
	at blusunrize.immersiveengineering.api.ImmersiveNetHandler.getIndirectEnergyConnections(ImmersiveNetHandler.java:228)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityConnectorLV.transferEnergy(TileEntityConnectorLV.java:185)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityConnectorLV.receiveEnergy(TileEntityConnectorLV.java:162)
	at cofh.thermalexpansion.block.cell.TileCell.transferEnergy(TileCell.java:201)
	at cofh.thermalexpansion.block.cell.TileCell.func_145845_h(TileCell.java:162)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at fastcraft.c.p.a(F:19)
	at fastcraft.Hooks.aq(F:153)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by SanAndreasP** [comment]
The disappearing bug seems to be fixed, I reloaded the world after placing some wire and they're still connected.
The CME appears to be a one-time occurrence as well, it didn't crash after trying to connect wire in the described setup again. But I think it's still something worth checking out.

**Comment by BluSunrize** [comment]
Yeah they happen from time to time with rendering too, and I've never been able to reproduce them.

**Comment by SanAndreasP** [comment]
Alright, seems like the disappearance bug is still persisting: Wires placed in creative mode stay, those placed in survival mode disappear on world reload :(

**Comment by BluSunrize** [comment]
Fixed version isn't built yet.

**Comment by SanAndreasP** [comment]
I see, glad it's fixed, though :+1:
