### ISSUE TITLE
Server Crash on Start Up MC 1.10.2 w/ ImmersiveEngineering-0.10-38.jar

### ISSUE THREAD

**Issue by adamscarcella** [BluSunrize/ImmersiveEngineering#1352]
I'm running 1.10.2 with ImmersiveEngineering-0.10-38.jar and received the following error during startup.

[crash-2016-08-29_09.02.05-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/442479/crash-2016-08-29_09.02.05-server.txt)

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BCModPlugin (Backpacks 1.10.2 - 3.1.1.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 8/29/16 9:02 AM
Description: Ticking block entity

java.lang.IllegalMonitorStateException
	at java.lang.Object.notifyAll(Native Method)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityFloodlight.func_73660_a(TileEntityFloodlight.java:70)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.lang.Object.notifyAll(Native Method)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityFloodlight.func_73660_a(TileEntityFloodlight.java:70)

-- Block entity being ticked --
Details:
	Name: immersiveengineering:Floodlight // blusunrize.immersiveengineering.common.blocks.metal.TileEntityFloodlight
	Block type: ID #587 (tile.immersiveengineering.metalDevice1 // blusunrize.immersiveengineering.common.blocks.metal.BlockMetalDevice1)
	Block data value: 9 / 0x9 / 0b1001
	Block location: World: (128,82,-22), Chunk: (at 0,5,10 in 8,-2; contains blocks 128,0,-32 to 143,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Actual block type: ID #587 (tile.immersiveengineering.metalDevice1 // blusunrize.immersiveengineering.common.blocks.metal.BlockMetalDevice1)
	Actual block data value: 9 / 0x9 / 0b1001
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)

-- Affected level --
Details:
	Level name: world_ScarcellaFamily
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: -3634376388372950441
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (8,64,156), Chunk: (at 8,4,12 in 0,9; contains blocks 0,0,144 to 15,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 97541520 game time, 98371863 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 53466 (now: false), thunder time: 64343 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3152528040 bytes (3006 MB) / 4036493312 bytes (3849 MB) up to 4036493312 bytes (3849 MB)
	JVM Flags: 2 total; -Xmx4096M -Xms4096M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.1.2073 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (custom_server.jar) 
	UCHIJAAAA	Forge{12.18.1.2073} [Minecraft Forge] (custom_server.jar) 
	UCHIJAAAA	backpacks16840{3.1.1} [Backpacks!] (Backpacks 1.10.2 - 3.1.1.jar) 
	UCHIJAAAA	immersiveengineering{${version}} [Immersive Engineering] (ImmersiveEngineering-0.10-38.jar) 
	UCHIJAAAA	mineralogy{3.2.0} [Mineralogy] (Mineralogy_1.10.2-3.2.0.jar) 
	UCHIJAAAA	pixelmon{5.0.0-beta6} [Pixelmon] (Pixelmon-1.10.2-5.0.0-beta6-universal.jar) 
	Loaded coremods (and transformers): 
BCModPlugin (Backpacks 1.10.2 - 3.1.1.jar)
  brad16840.common.asm.ClassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

In the "_fml-server-latest.log_" I found this: `Run the command /fml confirm or or /fml cancel to proceed.`, which seemed to work. Hopefully you'll be able to fix this when you return from vacation.

**Comment by BluSunrize** [comment]
Yup, has been reported already, see #1350 for a temporary workaround!
Solution happens later this week ^^
