### ISSUE TITLE
[0.10-40] JEI integration broken

### ISSUE THREAD

**Issue by 50m31-AW** [BluSunrize/ImmersiveEngineering#1416]
When I was running 0.10-38 JEI worked with IE recipes flawlessly, however upon looking up recipes in 0.10-40 I noticed that none of the Crusher/Arc Furnace/Metal Press/etc. recipes are showing up, be it by trying to look at recipes for items, the uses for items, or even looking at all recipes in general. I've tried using the latest release (3.9.0.244) and beta (3.9.0.248) of JEI, but  the recipes won't show in either of them.

IE: 0.10-40
Forge: 12.18.1.2076

**Comment by bondgb** [comment]
Same here. Found this error in fml-latest:

[13:39:33] [Client thread/INFO] [JEI/]: Registering plugin: blusunrize.immersiveengineering.common.util.compat.jei.JEIHelper
[13:39:33] [Client thread/ERROR] [JEI/]: Failed to register mod plugin: class blusunrize.immersiveengineering.common.util.compat.jei.JEIHelper
java.lang.NoClassDefFoundError: li/cil/oc/common/block/Item
	at blusunrize.immersiveengineering.common.util.compat.jei.JEIHelper.register(JEIHelper.java:56) ~[JEIHelper.class:?]
	at mezz.jei.ProxyCommonClient.startJEI(ProxyCommonClient.java:169) [ProxyCommonClient.class:?]
	at mezz.jei.ProxyCommonClient.onEntityJoinedWorld(ProxyCommonClient.java:142) [ProxyCommonClient.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_756_ProxyCommonClient_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168) [EventBus.class:?]
	at net.minecraft.world.World.func_72838_d(World.java:1129) [aid.class:?]
	at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:196) [bln.class:?]
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2451) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2359) [bcx.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:276) [bll.class:?]
	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:76) [gw.class:?]
	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:13) [gw.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ClassNotFoundException: li.cil.oc.common.block.Item
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	... 26 more
Caused by: java.lang.ArrayIndexOutOfBoundsException

**Comment by BluSunrize** [comment]
Please read the guidelines a spoiler your crashlogs.
I know what causes this and will be able to fix it, but I would like to put all the blame on OpenComputers for having a class called "Item" which also contains the function "getItemFromBlock", just like Vanilla. That's just bad style.

**Comment by BluSunrize** [comment]
Fixed for future release, see commit above
