### ISSUE TITLE
0.3.2 Crusher sound Crash on client

### ISSUE THREAD

**Issue by magnifikus** [BluSunrize/ImmersiveEngineering#144]
tell me if you need more information

[28/6/2015 19:10:33 PM] [19:10:33] [Client thread/FATAL]: Reported exception thrown!
[28/6/2015 19:10:33 PM] net.minecraft.util.ReportedException: Ticking block entity
[28/6/2015 19:10:33 PM] 	at net.minecraft.world.World.func_72939_s(World.java:1954) ~[ahb.class:?]
[28/6/2015 19:10:33 PM] 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006) ~[bao.class:?]
[28/6/2015 19:10:33 PM] 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]
[28/6/2015 19:10:33 PM] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
[28/6/2015 19:10:33 PM] 	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[28/6/2015 19:10:33 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
[28/6/2015 19:10:33 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
[28/6/2015 19:10:33 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
[28/6/2015 19:10:33 PM] 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
[28/6/2015 19:10:33 PM] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
[28/6/2015 19:10:33 PM] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[28/6/2015 19:10:33 PM] Caused by: java.lang.NullPointerException
[28/6/2015 19:10:33 PM] 	at blusunrize.immersiveengineering.client.ClientProxy.handleTileSound(ClientProxy.java:371) ~[ClientProxy.class:?]
[28/6/2015 19:10:33 PM] 	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityCrusher.func_145845_h(TileEntityCrusher.java:84) ~[TileEntityCrusher.class:?]
[28/6/2015 19:10:33 PM] 	at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
[28/6/2015 19:10:33 PM] 	... 10 more
[28/6/2015 19:10:33 PM] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
[28/6/2015 19:10:33 PM] // My bad.
[28/6/2015 19:10:33 PM] 
[28/6/2015 19:10:33 PM] Time: 6/28/15 7:10 PM
[28/6/2015 19:10:33 PM] Description: Ticking block entity
[28/6/2015 19:10:33 PM] 
[28/6/2015 19:10:33 PM] java.lang.NullPointerException: Ticking block entity
[28/6/2015 19:10:33 PM] 	at blusunrize.immersiveengineering.client.ClientProxy.handleTileSound(ClientProxy.java:371)
[28/6/2015 19:10:33 PM] 	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityCrusher.func_145845_h(TileEntityCrusher.java:84)
[28/6/2015 19:10:33 PM] 	at net.minecraft.world.World.func_72939_s(World.java:1939)
[28/6/2015 19:10:33 PM] 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
[28/6/2015 19:10:33 PM] 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[28/6/2015 19:10:33 PM] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[28/6/2015 19:10:33 PM] 	at net.minecraft.client.main.Main.main(SourceFile:148)
[28/6/2015 19:10:33 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[28/6/2015 19:10:33 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[28/6/2015 19:10:33 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[28/6/2015 19:10:33 PM] 	at java.lang.reflect.Method.invoke(Unknown Source)
[28/6/2015 19:10:33 PM] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[28/6/2015 19:10:33 PM] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[28/6/2015 19:10:33 PM] 
[28/6/2015 19:10:33 PM] 
[28/6/2015 19:10:33 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[28/6/2015 19:10:33 PM] ---------------------------------------------------------------------------------------
[28/6/2015 19:10:33 PM] 
[28/6/2015 19:10:33 PM] -- Head --
[28/6/2015 19:10:33 PM] Stacktrace:
[28/6/2015 19:10:33 PM] 	at blusunrize.immersiveengineering.client.ClientProxy.handleTileSound(ClientProxy.java:371)
[28/6/2015 19:10:33 PM] 	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityCrusher.func_145845_h(TileEntityCrusher.java:84)
[28/6/2015 19:10:33 PM] 
[28/6/2015 19:10:33 PM] -- Block entity being ticked --
[28/6/2015 19:10:33 PM] Details:
[28/6/2015 19:10:33 PM] 	Name: ImmersiveEngineering:Crusher // blusunrize.immersiveengineering.common.blocks.metal.TileEntityCrusher
[28/6/2015 19:10:33 PM] 	Block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
[28/6/2015 19:10:33 PM] 	Block data value: 0 / 0x0 / 0b0000
[28/6/2015 19:10:33 PM] 	Block location: World: (749,79,-2767), Chunk: (at 13,4,1 in 46,-173; contains blocks 736,0,-2768 to 751,255,-2753), Region: (1,-6; contains chunks 32,-192 to 63,-161, blocks 512,0,-3072 to 1023,255,-2561)
[28/6/2015 19:10:33 PM] 	Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
[28/6/2015 19:10:33 PM] 	Actual block data value: 0 / 0x0 / 0b0000
[28/6/2015 19:10:33 PM] Stacktrace:
[28/6/2015 19:10:33 PM] 	at net.minecraft.world.World.func_72939_s(World.java:1939)

**Comment by BluSunrize** [comment]
I need you too spoiler your crashlogs, first off.
Then you need to look at existing issues.
And you can download the just released v0.3.3 which fixes that bug.
