### ISSUE TITLE
lootEntries not found?

### ISSUE THREAD

**Issue by LemADEC** [BluSunrize/ImmersiveEngineering#1449]
When starting server with forge-1.10.2-12.18.1.2086-universal.jar and ImmersiveEngineering-0.10-40.jar, the following error is reported in console:
```
[17:44:34] [Server thread/INFO] [FML]: Loading dimension 0 (Zen) (net.minecraft.server.dedicated.DedicatedServer@4533c1cc)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]: java.lang.NoSuchFieldException: lootEntries
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at java.lang.Class.getDeclaredField(Class.java:2070)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at blusunrize.immersiveengineering.common.EventHandler.lootLoad(EventHandler.java:160)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_372_EventHandler_lootLoad_LootTableLoadEvent.invoke(
.dynamic)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraftforge.event.ForgeEventFactory.loadLootTable(ForgeEventFactory.java:595)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:1048)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraft.world.storage.loot.LootTableManager$Loader.func_186518_c(LootTableManager.java:148)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:71)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:52)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraft.world.storage.loot.LootTableManager.func_186521_a(LootTableManager.java:39)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraft.world.storage.loot.LootTableManager.func_186522_a(LootTableManager.java:48)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraft.world.storage.loot.LootTableManager.<init>(LootTableManager.java:34)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:152)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:252)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at java.lang.Thread.run(Thread.java:745)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]: java.lang.NoSuchFieldException: lootEntries
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at java.lang.Class.getDeclaredField(Class.java:2070)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at blusunrize.immersiveengineering.common.EventHandler.lootLoad(EventHandler.java:160)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_372_EventHandler_lootLoad_LootTableLoadEvent.invoke(.dynamic)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraftforge.event.ForgeEventFactory.loadLootTable(ForgeEventFactory.java:595)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:1048)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraft.world.storage.loot.LootTableManager$Loader.func_186518_c(LootTableManager.java:148)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:71)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:52)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraft.world.storage.loot.LootTableManager.func_186521_a(LootTableManager.java:39)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraft.world.storage.loot.LootTableManager.func_186522_a(LootTableManager.java:48)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraft.world.storage.loot.LootTableManager.<init>(LootTableManager.java:34)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:152)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:252)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
[17:44:34] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:170]:   at java.lang.Thread.run(Thread.java:745)
```

**Comment by BluSunrize** [comment]
Fixed for future releases, see commit above!

**Comment by malte0811** [comment]
And we pushed commits simultaneously again... You pushed at 12:40, I created the commit at 12:40 and pushed it at 12:44 :smile:
I think my solution is safer since

> The elements in the array returned are not sorted and are not in any particular order.

(From the [documentation of the `getDeclaredFields` method](https://docs.oracle.com/javase/7/docs/api/java/lang/Class.html#getDeclaredFields()))
`LootPool` declares multiple fields and while your solution might work with the Oracle JDK, there is no guarantee  that that will be the case with other versions like OpenJDK.

**Comment by BluSunrize** [comment]
hrmph. Alright, fair enough, you win =P

**Comment by C0rn3j** [comment]
Line 1645 - http://pastebin.com/hzFyhNV0

Forge 2092, IE build 42. Looks like a similar issue to me

**Comment by malte0811** [comment]
Looks like I messed up my fix. I'll look into it later today.

**Comment by Drakonas** [comment]
Not sure why this was closed... it's still happening.

**Comment by Drakonas** [comment]
Not sure why this was closed. It still happens in Release 42.

**Comment by BluSunrize** [comment]
I dunno. We never reopened it, and I don't think @malte0811 ever wrote a different fix either =P

**Comment by malte0811** [comment]
Yeah, I'll try to fix it right now.
