### ISSUE TITLE
[0.10-42] Server start crash

### ISSUE THREAD

**Issue by Gayanfalor** [BluSunrize/ImmersiveEngineering#1463]
Hello,

i got this  crash report when i try to launch the server with IE:
-http://pastebin.com/0uJzu4cS

but when i disable the mod its launching fine.

Using IE version on tittle
-forge 2085
Tc 2.3.3a with mantle 1.10.2-0.10.4

By the way in the server console i'm getting WARN messages like this:

`[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: ****************************************
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: * Dangerous alternative prefix `tconstruct` for name `molten_copper`, expected `immersiveengineering` invalid registry invocation/invalid name?
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:82)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:90)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:63)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.register(TinkerPulse.java:116)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:110)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:69)...
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: ****************************************
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: ****************************************
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: * Dangerous alternative prefix `tconstruct` for name `molten_copper`, expected `immersiveengineering` invalid registry invocation/invalid name?
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:82)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:90)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:63)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.register(TinkerPulse.java:116)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:111)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:69)...
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: ****************************************
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: ****************************************
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: * Dangerous alternative prefix `tconstruct` for name `molten_alubrass`, expected `immersiveengineering` invalid registry invocation/invalid name?
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:82)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:90)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:63)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.register(TinkerPulse.java:116)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:110)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:69)...
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: ****************************************
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: ****************************************
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: * Dangerous alternative prefix `tconstruct` for name `molten_alubrass`, expected `immersiveengineering` invalid registry invocation/invalid name?
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:82)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:90)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:63)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.register(TinkerPulse.java:116)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:111)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:69)...
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: ****************************************
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: ****************************************
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: * Dangerous alternative prefix `tconstruct` for name `molten_aluminum`, expected `immersiveengineering` invalid registry invocation/invalid name?
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:82)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:90)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:63)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.register(TinkerPulse.java:116)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:110)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:69)...
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: ****************************************
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: ****************************************
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: * Dangerous alternative prefix `tconstruct` for name `molten_aluminum`, expected `immersiveengineering` invalid registry invocation/invalid name?
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:82)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:90)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:63)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.register(TinkerPulse.java:116)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:111)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:69)...
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: ****************************************
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: ****************************************
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: * Dangerous alternative prefix `tconstruct` for name `molten_lead`, expected `immersiveengineering` invalid registry invocation/invalid name?
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:82)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:90)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:63)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.register(TinkerPulse.java:116)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:110)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:69)...
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: ****************************************
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: ****************************************
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: * Dangerous alternative prefix `tconstruct` for name `molten_lead`, expected `immersiveengineering` invalid registry invocation/invalid name?
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:82)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:90)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:63)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.register(TinkerPulse.java:116)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:111)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:69)...
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: ****************************************
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: ****************************************
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: * Dangerous alternative prefix `tconstruct` for name `molten_silver`, expected `immersiveengineering` invalid registry invocation/invalid name?
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:82)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:90)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:63)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.register(TinkerPulse.java:116)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:110)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:69)...
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: ****************************************
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: ****************************************
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: * Dangerous alternative prefix `tconstruct` for name `molten_silver`, expected `immersiveengineering` invalid registry invocation/invalid name?
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:82)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:90)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:63)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.register(TinkerPulse.java:116)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:111)
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: *  at slimeknights.tconstruct.common.TinkerPulse.registerBlock(TinkerPulse.java:69)...
[10:28:08] [Server thread/WARN] [FML/immersiveengineering]: ****************************************`

**Comment by GirafiStudios** [comment]
You need to update Tinkers Construct to atleast version 2.5.0

**Comment by Gayanfalor** [comment]
Ah ok thanks so if i want to keep my actual verison of Tconstruct i can use the v40 ver ? i've seen someone made dupplicate of this post  #1464 and talking its working fine with v40.

**Comment by BluSunrize** [comment]
That warning I can't do anything about, that's just Forge being super safe.
As for the crash: either use TCon 2.5.0 and later or downgrade your IE.

**Comment by Gayanfalor** [comment]
Ah for the warn message if its a just warning and causing nothing to crash game its ok.

What version of IE i could use to work with TC 2.3.3a ?
