### ISSUE TITLE
[1.10.2] Refinery GUI Bug

### ISSUE THREAD

**Issue by DrWarFighter** [BluSunrize/ImmersiveEngineering#1500]
The internal tanks of the refinery show as empty in the machines GUI when inserting fluids (plant oil and ethanol), it is accepting fluids because it stops taking fluid when the internal tanks are full. In this state it produces no bio diesel and doesn't seem to using any power. I've tried switching which side fluids come in from, connecting the squeezer/fermenter on different sides, piping in fluids from IE tanks, IE fluid pipes, EIO tanks and conduits.
I've tried the following versions with the same results:
0.10 - 38
0.10 - 39
0.10 - 40

**Comment by malte0811** [comment]
This works perfectly fine in my dev environment.
1. Does this happen with IE 0.10-42?
2. What other mods are you using?

**Comment by DrWarFighter** [comment]
1. I have tried .41 and .42 but both crash on loading, compat issues with Tinkers.
2. 
![ss 2016-09-22 at 03 05 15](https://cloud.githubusercontent.com/assets/12607270/18735959/34bf9726-80d6-11e6-94c7-b4878eb7fba3.png)
![ss 2016-09-22 at 03 05 28](https://cloud.githubusercontent.com/assets/12607270/18735960/3b6543b4-80d6-11e6-9b15-59a647e7627e.png)
![ss 2016-09-22 at 03 06 04](https://cloud.githubusercontent.com/assets/12607270/18735962/3e98d3b6-80d6-11e6-8d5e-e3e733a3ffb2.png)

**Comment by KnightMiner** [comment]
Build 41 and later require Tinkers 2.5.0 or later

**Comment by DrWarFighter** [comment]
Tried that, updated Mantle, Tinkers and IE-42. Errors out with : 

net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchFieldError: pickaxe
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:790)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:322)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchFieldError: pickaxe
	at de.universallp.va.core.compat.CompatTinkersConstruct.init(CompatTinkersConstruct.java:51)
	at de.universallp.va.core.compat.CompatTinkersConstruct.run(CompatTinkersConstruct.java:30)
	at de.universallp.va.core.CommonProxy.init(CommonProxy.java:52)
	at de.universallp.va.client.ClientProxy.init(ClientProxy.java:39)
	at de.universallp.va.VanillaAutomation.init(VanillaAutomation.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:595)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:788)
	... 10 more

**Comment by XFactHD** [comment]
Vanilla Automation is using the outdated TCon API. Either remove it or update it if possible.

**Comment by DrWarFighter** [comment]
Removing VA allowed the game to boot up fine, but sadly I'm still getting the same behaviour with IE-42.

**Comment by jzburda** [comment]
I'm getting a very similar problem with ImmersiveEngineering-0.10-44 where I can't input Plant Oil nor Ethanol into the refinery. I'll give you a list of my mods so we can hopefully narrow this down.
[https://puu.sh/rES13/eb405e0ec2.png](url)

**Comment by vlce-versa** [comment]
Same Problem here, the GUI shows empty tanks even when they are full and don't accept any more plant oil or ethanol. It's strange that in my single player world it works fine.
IE 0.10-44
Minecraft 1.10.2
