### ISSUE TITLE
[1.10, latest version]The Phial Cartridge crashes on impact

### ISSUE THREAD

**Issue by xbony2** [BluSunrize/ImmersiveEngineering#1508]
I pulled it straight from the creative inventory, so it didn't have any potion effects (I think that's part of the problem).

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.0-56.jar)
  IC2core (industrialcraft-2-2.6.69-ex110.jar)
  GregtechASM (gregtech-5.10.03.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.55-beta.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
  BetterMinecraftChat (BetterMinecraftChat_1.10.2-4.1.6.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 9/24/16 7:47 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.potion.PotionUtils.func_185191_c(SourceFile:114)
	at blusunrize.immersiveengineering.common.items.ItemBullet$PotionBullet.onHitTarget(ItemBullet.java:353)
	at blusunrize.immersiveengineering.common.entities.EntityRevolvershot.onImpact(EntityRevolvershot.java:253)
	at blusunrize.immersiveengineering.common.entities.EntityRevolvershot.func_70071_h_(EntityRevolvershot.java:208)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.potion.PotionUtils.func_185191_c(SourceFile:114)
	at blusunrize.immersiveengineering.common.items.ItemBullet$PotionBullet.onHitTarget(ItemBullet.java:353)
	at blusunrize.immersiveengineering.common.entities.EntityRevolvershot.onImpact(EntityRevolvershot.java:253)
	at blusunrize.immersiveengineering.common.entities.EntityRevolvershot.func_70071_h_(EntityRevolvershot.java:208)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
	Entity Type: immersiveengineering.revolverShot (blusunrize.immersiveengineering.common.entities.EntityRevolvershot)
	Entity ID: 7913365
	Entity Name: entity.immersiveengineering.revolverShot.name
	Entity's Exact location: 722.65, 4.84, -701.84
	Entity's Block location: World: (722,4,-702), Chunk: (at 2,0,2 in 45,-44; contains blocks 720,0,-704 to 735,255,-689), Region: (1,-2; contains chunks 32,-64 to 63,-33, blocks 512,0,-1024 to 1023,255,-513)
	Entity's Momentum: -0.61, -0.16, -0.77
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)

-- Affected level --
Details:
	Level name: flat
	All players: 1 total; [EntityPlayerMP['xbony2'/906, l='flat', x=726.28, y=4.28, z=-697.29]]
	Chunk stats: ServerChunkCache: 755 Drop: 0
	Level seed: -3293794770768538949
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (920,4,-747), Chunk: (at 8,0,5 in 57,-47; contains blocks 912,0,-752 to 927,255,-737), Region: (1,-2; contains chunks 32,-64 to 63,-33, blocks 512,0,-1024 to 1023,255,-513)
	Level time: 49064 game time, 49064 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 92368 (now: false), thunder time: 90710 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Mac OS X (x86_64) version 10.11.6
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1342372216 bytes (1280 MB) / 5250220032 bytes (5007 MB) up to 5250220032 bytes (5007 MB)
	JVM Flags: 3 total; -Xmx5120m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.1.2084 69 mods loaded, 69 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2084.jar) 
	UCHIJAAAAAAAAA	Forge{12.18.1.2084} [Minecraft Forge] (forge-1.10.2-12.18.1.2084.jar) 
	UCHIJAAAAAAAAA	OpenComputers|Core{1.6.0.3-rc.1} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAAAAAAA	actuallyadditions{1.10.2-r63} [Actually Additions] (ActuallyAdditions-1.10.2-r63.jar) 
	UCHIJAAAAAAAAA	thedragoncore{1.10.2-1.0.2.0} [TheDragonCore] (thedragoncore-1.10.2-1.0.2.0.jar) 
	UCHIJAAAAAAAAA	armorplus{1.10.2-7.0.0.0} [ArmorPlus] (armorplus-1.10.2-7.0.0.0.jar) 
	UCHIJAAAAAAAAA	Psi{r1.0-39} [Psi] (Psi-r1.0-39.jar) 
	UCHIJAAAAAAAAA	Quark{r1.0-56} [Quark] (Quark-r1.0-56.jar) 
	UCHIJAAAAAAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAAAAAAA	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UCHIJAAAAAAAAA	mantle{1.10.2-1.0.0.jenkins170} [Mantle] (Mantle-1.10.2-1.0.0.jar) 
	UCHIJAAAAAAAAA	tconstruct{1.10.2-2.5.2.jenkins352} [Tinkers' Construct] (TConstruct-1.10.2-2.5.2.jar) 
	UCHIJAAAAAAAAA	immersiveengineering{0.10-42} [Immersive Engineering] (ImmersiveEngineering-0.10-42.jar) 
	UCHIJAAAAAAAAA	betterwithmods{0.11 Beta hotfix 2} [Better With Mods] (Better With Mods-0.11-1.10.2-hotfix2.jar) 
	UCHIJAAAAAAAAA	betterminecraftchat{4.1.6} [BetterMinecraftChat] (BetterMinecraftChat_1.10.2-4.1.6.jar) 
	UCHIJAAAAAAAAA	BiomesOPlenty{5.0.0.2085} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2085-universal.jar) 
	UCHIJAAAAAAAAA	blockrenderer{1.0.0} [BlockRenderer] (BlockRenderer-1.0.0.jar) 
	UCHIJAAAAAAAAA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCHIJAAAAAAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.0.1.jar) 
	UCHIJAAAAAAAAA	JEI{3.10.0.267} [Just Enough Items] (jei_1.10.2-3.10.0.267.jar) 
	UCHIJAAAAAAAAA	BloodMagic{1.9.4-2.1.0-63} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.1.0-63.jar) 
	UCHIJAAAAAAAAA	bonemealablebabies{1.0.0a} [Bone Meal-able Babies] (bonemealablebabies-1.0.0a.jar) 
	UCHIJAAAAAAAAA	Botania{r1.9-324} [Botania] (Botania r1.9-324.jar) 
	UCHIJAAAAAAAAA	Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
	UCHIJAAAAAAAAA	ChestTransporter{2.5.2} [Chest Transporter] (ChestTransporter-1.10.2-2.5.2.jar) 
	UCHIJAAAAAAAAA	crossroads{1.10.2-1.1.4} [Crossroads] (crossroads-1.10.2-1.1.4.jar) 
	UCHIJAAAAAAAAA	CustomMainMenu{2.0.2} [Custom Main Menu] (CustomMainMenu-MC1.10.2-2.0.2.jar) 
	UCHIJAAAAAAAAA	cyberware{beta-0.2.2} [Cyberware] (cyberware-1.9.4-1.10.2-beta-0.2.2.jar) 
	UCHIJAAAAAAAAA	IC2{2.6.69-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.69-ex110.jar) 
	UCHIJAAAAAAAAA	forestry{5.2.12.258} [Forestry] (forestry_1.10.2-5.2.12.258.jar) 
	UCHIJAAAAAAAAA	ElecCore{1.5.311} [ElecCore] (ElecCore-1.9.4-1.5.311.jar) 
	UCHIJAAAAAAAAA	OpenComputers{1.6.0.3-rc.1} [OpenComputers] (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar) 
	UCHIJAAAAAAAAA	deepresonance{1.2.4} [DeepResonance] (deepresonance-1.10-1.2.4.jar) 
	UCHIJAAAAAAAAA	Ding{MC1.9.0v2} [Ding] (Ding-1.10.2-1.0.0.jar) 
	UCHIJAAAAAAAAA	endercore{1.10.2-0.4.1.55-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.55-beta.jar) 
	UCHIJAAAAAAAAA	EnderIO{1.10.2-3.0.1.112_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.112_beta.jar) 
	UCHIJAAAAAAAAA	EnderZoo{1.10-1.2.3.43} [Ender Zoo] (EnderZoo-1.10-1.2.3.43.jar) 
	UCHIJAAAAAAAAA	zerocore{1.10.2-0.0.8.0} [Zero CORE] (zerocore-1.10.2-0.0.8.0.jar) 
	UCHIJAAAAAAAAA	bigreactors{0.4.5.15} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.15.jar) 
	UCHIJAAAAAAAAA	forgeanalytics{0.0.0.13} [Forge Analytics] (ForgeAnalytics-1.10-0.0.0.19.jar) 
	UCHIJAAAAAAAAA	FotP{1.0} [Feast of the Pharaohs] (fotp -0.1.2.jar) 
	UCHIJAAAAAAAAA	substratum{1.8.1.0} [Substratum] (Substratum-1.10.2-1.8.1.0.jar) 
	UCHIJAAAAAAAAA	foundry{2.2.0.1} [Foundry] (Foundry-1.10.2-2.2.0.1.jar) 
	UCHIJAAAAAAAAA	ftbl{2.1.0} [FTBLib] (FTBLib-1.9.4-2.1.0-pre3.jar) 
	UCHIJAAAAAAAAA	ftbu{2.1.0} [FTBUtilities] (FTBUtilities-1.9.4-2.1.0-pre3.jar) 
	UCHIJAAAAAAAAA	gregtech{MC1.10.2} [GregTech] (gregtech-5.10.03.jar) 
	UCHIJAAAAAAAAA	hopperducts{1.4.8} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.8.jar) 
	UCHIJAAAAAAAAA	InventoryPets{1.4.8.1} [Inventory Pets] (inventorypets-1.10-1.4.8.1.jar) 
	UCHIJAAAAAAAAA	magneticraft{@VERSION@} [Magneticraft] (magneticraft-1.0.2-release.jar) 
	UCHIJAAAAAAAAA	Morpheus{1.10.2-3.1.7} [Morpheus] (Morpheus-1.10.2-3.1.7.jar) 
	UCHIJAAAAAAAAA	rblr{6.0.2.10} [Rabbits Breed Like Rabbits] (RabbitsBreedLikeRabbits-Forge-6.0.2.10.jar) 
	UCHIJAAAAAAAAA	randomthings{3.7.5} [Random Things] (RandomThings-MC1.10.2-3.7.5.jar) 
	UCHIJAAAAAAAAA	realstonetools{6.0.2.0} [Real Stone Tools] (RealStoneTools-Forge-6.0.2.0.jar) 
	UCHIJAAAAAAAAA	reborncore{2.7.2.45} [RebornCore] (RebornCore-1.10.2-2.7.2.45-universal.jar) 
	UCHIJAAAAAAAAA	reborncore-mcmultipart{2.7.2.45} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.7.2.45-universal.jar) 
	UCHIJAAAAAAAAA	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.9.4-1.7.4.jar) 
	UCHIJAAAAAAAAA	xreliquary{1.10.2-1.3.3.543} [Reliquary] (Reliquary-1.10.2-1.3.3.543.jar) 
	UCHIJAAAAAAAAA	rflux{0.0.1} [RF Lux] (rflux-0.0.1.jar) 
	UCHIJAAAAAAAAA	rftools{5.24} [RFTools] (rftools-1.10-5.24.jar) 
	UCHIJAAAAAAAAA	Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
	UCHIJAAAAAAAAA	roots{0.202} [Roots] (roots-1.10.2-0.202.0.jar) 
	UCHIJAAAAAAAAA	StorageDrawers{1.10.2-3.2.7} [Storage Drawers] (StorageDrawers-1.10.2-3.2.7.jar) 
	UCHIJAAAAAAAAA	techreborn{1.4.4.54} [TechReborn] (TechReborn-1.10.2-1.4.4.54-universal.jar) 
	UCHIJAAAAAAAAA	theoneprobe{1.1.2} [The One Probe] (theoneprobe-1.10-1.1.2.jar) 
	UCHIJAAAAAAAAA	Thump{@VERSION@} [Thump] (Thump-1.10.2-4.1.0.123.jar) 
	UCHIJAAAAAAAAA	tis3d{0.9.0.1} [TIS-3D] (TIS-3D-MC1.10-0.9.0.1.jar) 
	UCHIJAAAAAAAAA	totemic{1.9.4-0.7.8} [Totemic] (Totemic-1.9.4-0.7.8.jar) 
	UCHIJAAAAAAAAA	whosebed{1.0} [Whose bed?] (whosebed-1.1.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.0-56.jar)
  vazkii.quark.base.asm.ClassTransformer
IC2core (industrialcraft-2-2.6.69-ex110.jar)
  
GregtechASM (gregtech-5.10.03.jar)
  gregtech.asm.ASM
EnderCorePlugin (EnderCore-1.10.2-0.4.1.55-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  li.cil.oc.common.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
  lumien.randomthings.asm.ClassTransformer
BetterMinecraftChat (BetterMinecraftChat_1.10.2-4.1.6.jar)
  net.blay09.mods.bmc.coremod.ClassTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/Users/xbony2/Documents/Curse/Minecraft/Instances/WikiPack%202%20(1)/mods/mcjtylib-1.10-2.1.2.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/Users/xbony2/Documents/Curse/Minecraft/Instances/WikiPack%202%20(1)/mods/mcjtylib-1.10-2.1.2.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/Users/xbony2/Documents/Curse/Minecraft/Instances/WikiPack%202%20(1)/mods/mcjtylib-1.10-2.1.2.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/Users/xbony2/Documents/Curse/Minecraft/Instances/WikiPack%202%20(1)/mods/mcjtylib-1.10-2.1.2.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/Users/xbony2/Documents/Curse/Minecraft/Instances/WikiPack%202%20(1)/mods/mcjtylib-1.10-2.1.2.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/Users/xbony2/Documents/Curse/Minecraft/Instances/WikiPack%202%20(1)/mods/mcjtylib-1.10-2.1.2.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/Users/xbony2/Documents/Curse/Minecraft/Instances/WikiPack%202%20(1)/mods/mcjtylib-1.10-2.1.2.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/Users/xbony2/Documents/Curse/Minecraft/Instances/WikiPack%202%20(1)/mods/mcjtylib-1.10-2.1.2.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/Users/xbony2/Documents/Curse/Minecraft/Instances/WikiPack%202%20(1)/mods/mcjtylib-1.10-2.1.2.jar!/cofh/api/energy/TileEnergyHandler.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/Users/xbony2/Documents/Curse/Minecraft/Instances/WikiPack%202%20(1)/mods/mcjtylib-1.10-2.1.2.jar!/cofh/api/energy/TileEnergyHandler.class

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['xbony2'/906, l='flat', x=726.28, y=4.28, z=-697.29]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by BluSunrize** [comment]
For future reference, please spoiler your crashlogs ^_^

Fixed with: https://github.com/BluSunrize/ImmersiveEngineering/commit/2ba3055fd0747f1450447ea9cba13967ad48fa54

**Comment by xbony2** [comment]
Markdown has spoilers?

**Comment by BluSunrize** [comment]
No, but pastebin does. Contribution guidelines are your friend. >_>
