### ISSUE TITLE
Immersive Engineering Server Crash on version .42 "ArcRecyclingThreadHandler"

### ISSUE THREAD

**Issue by blkwind** [BluSunrize/ImmersiveEngineering#1520]
I keep getting this crash on our server and cannot figure out the cause of the issue. If I try booting a fresh world it crashes right away. I have been able to get it to boot without a crash by adding it to the server after the world has been created however if I reboot the server the crashes start again.

"Description: Watching Server

java.lang.Error
	at blusunrize.immersiveengineering.common.crafting.ArcRecyclingThreadHandler.doRecipeProfiling(ArcRecyclingThreadHandler.java:103)
	at blusunrize.immersiveengineering.ImmersiveEngineering.serverStarted(ImmersiveEngineering.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:597)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$0(LoadController.java:53)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
	at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:853)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:297)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:433)
	at java.lang.Thread.run(Unknown Source)"

I am hoping someone has an idea of what the issue is. We really would like to keep the mod on our server.

Thanks 
Blkwind

**Comment by blkwind** [comment]
Here is a link to the entire crash on pastebin. http://pastebin.com/cfNxdSxC

**Comment by malte0811** [comment]
Very weird crash. Does this happen with only IE and SpongeForge? Someone has reported a similar crash in 1.8, but the pastebin link on that one has expired, so I can't check whether they used SpongeForge as well.

**Comment by BluSunrize** [comment]
I've gotten this reported personally as well, by @MysticAura

http://pastebin.com/gLYNp1tM

Not sure what causes it myself, and it's hard to debug :/
can't be reproduced in singleplayer from what I was able to try.

**Comment by mindforger** [comment]
EnderIO has to deal with that too, i remember at least 2 issues maybe they got some more insight?

**Comment by BluSunrize** [comment]
Shit. I linked the wrong issue. My bad! xD

**Comment by malte0811** [comment]
I know what is causing this, it isn't related to other mods at all. I'll try to fix it later today.

**Comment by BluSunrize** [comment]
Care to share? I'd actually be interested to know.

**Comment by malte0811** [comment]
Look at the class called `ServerHangWatchdog`. It is only active on dedicated servers.
I would like to fix this myself since I have another minor fix waiting to be pushed. Are you planning to publish a release soon?

**Comment by BluSunrize** [comment]
I would love to get your fix and then distribute a prebuild to Mystic to use her as my guinea pig, if that's alright.

**Comment by blkwind** [comment]
This issue happens without sponge being installed also.

**Comment by malte0811** [comment]
I know.
This is what is happening: Some mod is adding a large amount of recipes. The arc recycling recipe generator has to look through all of these recipes to check what items should be recycled into what. Since there are a lot of recipes it takes some time for it to do so and it does so in the first server tick (which is what I am changing to fix it). And as I discovered this morning Minecraft has a thing called a `ServerHangWatchdog` which shuts down the server if a tick takes longer than a couple of seconds, which seems to be the case for the arc recipe calculations in your pack.

**Comment by blkwind** [comment]
Fantastic thanks malte, I'll keep an eye out for the fix. Keep up the good work. :)
