### ISSUE TITLE
Crash on initialization, -0.7.7, 1.7.10

### ISSUE THREAD

**Issue by Sorcererking** [BluSunrize/ImmersiveEngineering#1541]
Sorry I dont know how to post a spoiler box... Anyway Im having this bug and I am not sure how to fix it. 
full modlist I am running includes: Bibliocraft, Big Reactors, Code Chicken Core, COFH Core, COFH Lib, Extra Utilities, Forge Multipart, IC2, Mantle, NEI, Pam's Harvest Craft, Project Red Base and Initialization, Railcraft, TConstruct, Thaumcraft, Thermal Expansion, Thermal Foundation, Waila.

I have already tried changing the config of IE to false for all the mods it had accounted for with no change in the error log. I think it has something to do with the potion ID but I don't now how to fix that. Anyway heres the log:

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 10/6/16 1:09 AM
Description: Initializing game

java.lang.ArrayIndexOutOfBoundsException: 370
    at net.minecraft.potion.Potion.<init>(Potion.java:68)
    at blusunrize.immersiveengineering.common.util.IEPotions$IEPotion.<init>(IEPotions.java:95)
    at blusunrize.immersiveengineering.common.util.IEPotions.init(IEPotions.java:29)
    at blusunrize.immersiveengineering.common.IEContent.init(IEContent.java:508)
    at blusunrize.immersiveengineering.ImmersiveEngineering.init(ImmersiveEngineering.java:99)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.potion.Potion.<init>(Potion.java:68)
    at blusunrize.immersiveengineering.common.util.IEPotions$IEPotion.<init>(IEPotions.java:95)
    at blusunrize.immersiveengineering.common.util.IEPotions.init(IEPotions.java:29)
    at blusunrize.immersiveengineering.common.IEContent.init(IEContent.java:508)
    at blusunrize.immersiveengineering.ImmersiveEngineering.init(ImmersiveEngineering.java:99)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 138515848 bytes (132 MB) / 505257984 bytes (481 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 28 mods loaded, 28 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHI    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHI    FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHI    Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHI    CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCHI    NotEnoughItems{1.0.5.120} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
    UCHI    <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHI    BiblioCraft{1.11.5} [BiblioCraft](BiblioCraft[v1.11.5][MC1.7.10].jar) 
    UCHI    CoFHCore{1.7.10R3.1.3} [CoFH Core](CoFHCore-[1.7.10]3.1.3-327.jar) 
    UCHI    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHI    ThermalFoundation{1.7.10R1.2.5} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.5-115.jar) 
    UCHI    ThermalExpansion{1.7.10R4.1.4} [Thermal Expansion](ThermalExpansion-[1.7.10]4.1.4-247.jar) 
    UCHI    BigReactors{0.4.3A} [Big Reactors](BigReactors-0.4.3A.jar) 
    UCHI    ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHI    ExtraUtilities{1.2.12} [Extra Utilities](extrautilities-1.2.12.jar) 
    UCHI    Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCHI    IC2{2.2.823-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.823-experimental.jar) 
    UCHI    Railcraft{9.12.2.0} [Railcraft](Railcraft_1.7.10-9.12.2.0.jar) 
    UCHE    ImmersiveEngineering{0.7.7} [Immersive Engineering](ImmersiveEngineering-0.7.7.jar) 
    UCHI    Mantle{1.7.10-0.3.2.jenkins191} [Mantle](Mantle-1.7.10-0.3.2b.jar) 
    UCHI    harvestcraft{1.7.10j} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10Lb.jar) 
    UCHI    MrTJPCoreMod{1.1.0.33} [MrTJPCore](MrTJPCore-1.7.10-1.1.0.33-universal.jar) 
    UCHI    ProjRed|Core{4.7.0pre12.95} [ProjectRed Core](ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
    UCHI    ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration](ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
    UCHI    ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission](ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
    UCHI    Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHI    TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct](TConstruct-1.7.10-1.8.8.jar) 
    UCHI    McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHI    ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 372.70' Renderer: 'GeForce GTX 950/PCIe/SSE2'
    CoFHCore: -[1.7.10]3.1.3-327
    ThermalFoundation: -[1.7.10]1.2.5-115
    ThermalExpansion: -[1.7.10]4.1.4-247
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 950/PCIe/SSE2 GL version 4.5.0 NVIDIA 372.70, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by theunkn0wn1** [comment]
Spoiler tags don't seem to exist in markdown however put your logs in pastebin or ghist or something of the sort.

Also please see #1071
