### ISSUE TITLE
[1.10-44] (1.10.2) Crafting certain items crashes the game

### ISSUE THREAD

**Issue by Simbrine** [BluSunrize/ImmersiveEngineering#1549]
Every once in a while, when I craft something from Immersive Engineering such as the voltmeter or an engineer's cutter, the game crashes with an ArrayIndexOutOfBoundsException that has a variable value that corresponds to the crafted item as the reason. For example, crafting a voltmeter gives "ArrayIndexOutOfBoundsException: 6" while the cutter gives "ArrayIndexOutOfBoundsException: 4". Here's the error when crafting a voltmeter & as much of the stacktrace as Minecraft keeps.

```
net.minecraft.util.ReportedException: Updating screen events
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1713) ~[bcx.class:?]
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055) ~[bcx.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

Caused by: java.lang.ArrayIndexOutOfBoundsException: 6
        at blusunrize.immersiveengineering.common.crafting.RecipeShapedIngredient.func_179532_b(RecipeShapedIngredient.java:138) ~[RecipeShapedIngredient.class:?]
        at net.minecraft.item.crafting.CraftingManager.func_180303_b(SourceFile:1245) ~[age.class:?]
        at net.minecraft.inventory.SlotCrafting.func_82870_a(SlotCrafting.java:114) ~[acb.class:?]
        at net.minecraft.inventory.Container.func_184996_a(Container.java:324) ~[abd.class:?]
        at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:550) ~[blm.class:?]
        at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:630) ~[bgl.class:?]
        at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:389) ~[bgl.class:?]
        at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548) ~[bft.class:?]
        at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517) ~[bft.class:?]
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700) ~[bcx.class:?]
        ... 9 more
```

**Comment by malte0811** [comment]
Fixed, I'll push when I have more than one line to commit.

**Comment by The-Fireplace** [comment]
Yep, I just discovered this crash as well.
http://paste.ubuntu.com/23294539/

**Comment by ProsperCraft** [comment]
Same here http://pastebin.com/rPPukxrq

**Comment by 63502** [comment]
I think I am getting the same crash

[Crash Report](https://gist.github.com/63502/c3b7e977318536e666783217489bbdba)

**Comment by fwolle30** [comment]
Well, to be honest: The wire Cutter is one of the Items. This bug make it impossible to further proceed with your mod. So instead of waiting, I would push when the progress is stable enough and not wait until I've reached a certain amount of lines.

**Comment by codewarrior0** [comment]
Same crash here.

ImmersiveEngineering-0.10-44

**Comment by the1bladesmith** [comment]
Sam crash here as well

**Comment by mindforger** [comment]
Thank you for telling us you are having the same issue, but when you read the postts above your own comment, you would see that this issue is INDEED ALREADY SOLVED and waiting for a release .. telling "Same crash here" does not help at all ...

**Comment by BluSunrize** [comment]
hey @malte0811, can I just create a PR from your branch or do you want to put one up yourself? I really want to get a fix out.
