### ISSUE TITLE
.46 Still crashing on startup for server.

### ISSUE THREAD

**Issue by sherkas** [BluSunrize/ImmersiveEngineering#1614]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IC2core (industrialcraft-2-2.6.87-ex110.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
  CoreMod (TickProfiler-1.10.2.jenkins.10.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.0.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  ChiselCorePlugin (Chisel-MC1.9.4-0.0.6.53.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 10/18/16 1:35 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/gui/FontRenderer
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:617)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/gui/FontRenderer
	at blusunrize.immersiveengineering.common.Config.preInit(Config.java:333)
	at blusunrize.immersiveengineering.ImmersiveEngineering.preInit(ImmersiveEngineering.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:614)
	... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.FontRenderer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 33 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@4fce136b from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:253)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 35 more
Caused by: java.lang.RuntimeException: Attempted to load class bdl for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:56)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:249)
	... 37 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1167241200 bytes (1113 MB) / 2076049408 bytes (1979 MB) up to 5193859072 bytes (4953 MB)
	JVM Flags: 9 total; -Xms2048M -Xmx5124M -XX:PermSize=512M -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=2 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.2.2105 50 mods loaded, 50 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2105-universal.jar) 
	UCH	Forge{12.18.2.2105} [Minecraft Forge] (forge-1.10.2-12.18.2.2105-universal.jar) 
	UCH	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.0.jar) 
	UCH	Aroma1997CoreHelper{1.1.1.0} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.0.jar) 
	UCH	AromaBackup{1.0.1.1} [AromaBackup] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCH	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCH	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UCH	betterbuilderswands{0.6.5} [Better Builder's Wands] (BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar) 
	UCH	BiomesOPlenty{5.0.0.2068} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2068-universal.jar) 
	UCH	Botania{r1.8-321} [Botania] (Botania-unofficial.r1.8-321.jar) 
	UCH	chameleoncreepers{1.4.1} [Chameleon Creepers] (chameleoncreepers-1.4.1-1.10.2.jar) 
	UCH	chisel{MC1.9.4-0.0.6.53} [Chisel] (Chisel-MC1.9.4-0.0.6.53.jar) 
	UCH	endercore{1.10.2-0.4.1.56-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.56-beta.jar) 
	UCH	mantle{1.10.2-1.1.0.188} [Mantle] (Mantle-1.10.2-1.1.0.jar) 
	UCH	tconstruct{1.10.2-2.5.6.jenkins409} [Tinkers' Construct] (TConstruct-1.10.2-2.5.6.jar) 
	UCE	immersiveengineering{0.10-46} [Immersive Engineering] (ImmersiveEngineering-0.10-46.jar) 
	UCH	JEI{3.12.8.323} [Just Enough Items] (jei_1.10.2-3.12.8.323.jar) 
	UCH	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCH	EnderIO{1.10.2-3.0.1.120_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.120_beta.jar) 
	UCH	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.1.0c.jar) 
	UCH	ezstorage{2.2.5} [EZStorage 2] (ezstorage-2.2.5.jar) 
	UCH	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCH	gravestone{1.5.7} [Gravestone] (GraveStone Mod 1.5.7.jar) 
	UCH	IC2{2.6.87-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.87-ex110.jar) 
	UCH	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCH	journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
	UCH	lycanitesmobs{1.15.1.4 - MC 1.10.2} [Lycanites Mobs] (LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
	UCH	arcticmobs{1.15.1.4 - MC 1.10.2} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
	UCH	demonmobs{1.15.1.4 - MC 1.10.2} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
	UCH	desertmobs{1.15.1.4 - MC 1.10.2} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
	UCH	forestmobs{1.15.1.4 - MC 1.10.2} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
	UCH	freshwatermobs{1.15.1.4 - MC 1.10.2} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
	UCH	infernomobs{1.15.1.4 - MC 1.10.2} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
	UCH	junglemobs{1.15.1.4 - MC 1.10.2} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
	UCH	mountainmobs{1.15.1.4 - MC 1.10.2} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
	UCH	plainsmobs{1.15.1.4 - MC 1.10.2} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
	UCH	saltwatermobs{1.15.1.4 - MC 1.10.2} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
	UCH	shadowmobs{1.15.1.4 - MC 1.10.2} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
	UCH	swampmobs{1.15.1.4 - MC 1.10.2} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
	UCH	mcmultipart{1.2.1} [MCMultiPart] (MCMultiPart-1.2.1-universal.jar) 
	UCH	oretweaker{1.0.2-1.10.2} [Ore Tweaker] (OreTweaker-1.0.2-1.10.2.jar) 
	UCH	harvestcraft{1.9.4-1.10.2f} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2f.jar) 
	UCH	refinedstorage{1.1.3} [Refined Storage] (refinedstorage-1.1.3.jar) 
	UCH	rftools{5.54} [RFTools] (rftools-1.10-5.54.jar) 
	UCH	rftoolsdim{4.43} [RFTools Dimensions] (rftoolsdim-1.10-4.43.jar) 
	UCH	Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
	UCH	TickProfiler{1.10.2.jenkins.10} [TickProfiler] (TickProfiler-1.10.2.jenkins.10.jar) 
	UCH	UnifiedItems{1.3.2.54} [Unified Items] (UnifiedItems-1.10.2-1.3.2-54.jar) 
	UCH	UniDict{1.10.2-2.3b} [UniDict] (UniDict-1.10.2-2.3b.jar) 
	Loaded coremods (and transformers): 
IC2core (industrialcraft-2-2.6.87-ex110.jar)
  
EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
CoreMod (TickProfiler-1.10.2.jenkins.10.jar)
  
CoreMod (Aroma1997Core-1.9.4-1.1.1.0.jar)
  
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
ChiselCorePlugin (Chisel-MC1.9.4-0.0.6.53.jar)
  team.chisel.common.asm.ChiselTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)

	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Minecraft110server/mods/mcjtylib-1.10-2.1.4.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Minecraft110server/mods/mcjtylib-1.10-2.1.4.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Minecraft110server/mods/mcjtylib-1.10-2.1.4.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Minecraft110server/mods/mcjtylib-1.10-2.1.4.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Minecraft110server/mods/mcjtylib-1.10-2.1.4.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Minecraft110server/mods/mcjtylib-1.10-2.1.4.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Minecraft110server/mods/mcjtylib-1.10-2.1.4.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Minecraft110server/mods/mcjtylib-1.10-2.1.4.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Minecraft110server/mods/mcjtylib-1.10-2.1.4.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by BluSunrize** [comment]
Oh for crying out loud.

**Comment by BluSunrize** [comment]
I knew I should have tested it. Damn me and my blind trust.
