### ISSUE TITLE
[1.10.2] Client crash on multiplayer server NPE Tesselating block model.

### ISSUE THREAD

**Issue by ProsperCraft** [BluSunrize/ImmersiveEngineering#1677]
http://pastebin.com/jVKNXtek

java.lang.NullPointerException: Tesselating block model
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
    at com.google.common.collect.Lists.newArrayList(Lists.java:127)
    at blusunrize.immersiveengineering.client.models.IESmartObjModel.func_188616_a(IESmartObjModel.java:181)
    at blusunrize.immersiveengineering.client.models.smart.ConnModelReal$AssembledBakedModel.func_188616_a(ConnModelReal.java:133)
    at blusunrize.immersiveengineering.client.models.smart.ConnModelReal.func_188616_a(ConnModelReal.java:69)
    at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:117)
    at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:82)
    at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:46)
    at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:37)
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
    at codechicken.lib.render.block.CCExtendedBlockRendererDispatcher.func_175018_a(CCExtendedBlockRendererDispatcher.java:53)
    at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:199)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
    at java.lang.Thread.run(Thread.java:745)

**Comment by malte0811** [comment]
> Block: team.chisel.client.ChiselExtendedState@7202c13c

@Drullkus is Chisel using its own `ExtendedBlockState` implementation for other mods' blocks? What is the difference between your version and the default version? Do you add any properties, especially ones storing objects where `a.equals(a)` may be false or with randomly changing hash codes?

For reference: [the code that is crashing](https://github.com/BluSunrize/ImmersiveEngineering/blob/eaaac8513e59a5dc05ae5c909d9a3d5b2f495a7d/src/main/java/blusunrize/immersiveengineering/client/models/IESmartObjModel.java#L181). `modelCache.get(adapter)` seems to be null.
