### ISSUE TITLE
Crash when I install sponge on server

### ISSUE THREAD

**Issue by flier268** [BluSunrize/ImmersiveEngineering#1727]
I found a problem ,when the server install sponge and "enableVillagers=true
Server will crash,but "enableVillagers=false"

Log

```
Description: Exception ticking world

java.lang.IllegalStateException: Invalid Villager profession id is present! Found: 6 when the expected contain: [SpongeProfession{id=minecraft:farmer, name=farmer, type=0}, SpongeProfession{id=minecraft:librarian, name=librarian, type=1}, SpongeProfession{id=minecraft:priest, name=priest, type=2}, SpongeProfession{id=minecraft:blacksmith, name=blacksmith, type=3}, SpongeProfession{id=minecraft:butcher, name=butcher, type=4}, SpongeProfession{id=minecraft:farmer, name=farmer, type=0}, SpongeProfession{id=minecraft:librarian, name=librarian, type=1}, SpongeProfession{id=minecraft:priest, name=priest, type=2}, SpongeProfession{id=minecraft:blacksmith, name=blacksmith, type=3}, SpongeProfession{id=minecraft:butcher, name=butcher, type=4}, SpongeProfession{id=immersiveengineering:engineer, name=engineer, type=5}]
	at org.spongepowered.common.entity.EntityUtil.validateProfession(EntityUtil.java:618)
	at net.minecraft.entity.passive.EntityVillager.handler$onSetProfession$zfb000(EntityVillager.java:108)
	at net.minecraft.entity.passive.EntityVillager.func_70938_b(EntityVillager.java:382)
	at net.minecraftforge.fml.common.registry.VillagerRegistry.onSetProfession(VillagerRegistry.java:340)
	at net.minecraft.entity.passive.EntityVillager.setProfession(EntityVillager.java:395)
	at net.minecraftforge.fml.common.registry.VillagerRegistry.setRandomProfession(VillagerRegistry.java:316)
	at net.minecraft.entity.passive.EntityVillager.func_180482_a(EntityVillager.java:794)
	at net.minecraft.world.gen.structure.StructureVillagePieces$Village.func_74893_a(StructureVillagePieces.java:1788)
	at net.minecraft.world.gen.structure.StructureVillagePieces$House3.func_74875_a(StructureVillagePieces.java:1192)
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:47)
	at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:102)
	at net.minecraft.world.gen.structure.MapGenVillage.populate(SourceFile:53)
	at org.spongepowered.common.interfaces.world.gen.IFlaggedPopulator.populate(IFlaggedPopulator.java:40)
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:220)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$zom000(PlayerChunkMapEntry.java:79)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by BluSunrize** [comment]
More details.
Version numbers, etc.

**Comment by flier268** [comment]
Mod version : Immersive Engineering 0.10 - 50
Minecraft Version : 1.10.2
spongeforge : 1.10.2-2123-5.1.0-BETA-1891
