### ISSUE TITLE
[CRASH] IE capacitors and ExtraUtils2 capacitors do not like eachother

### ISSUE THREAD

**Issue by hron84** [BluSunrize/ImmersiveEngineering#1761]
**Note:** this is a cross-mod issue, take look into rwtema/extrautilities#1133 too.

After upgrading to build 51, i got this when i tried to load my world.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.0-60.jar)
  Crafting Harmonics Core (craftingharmonics-1.9.4_1.10_1.10.2-1.5.7.42.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.145-universal.jar)
  AppleCore (AppleCore-mc1.10.2-2.1.0.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
  LoadingHook (Mekanism-1.10.2-9.2.1.295.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 12/2/16 1:13 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at blusunrize.immersiveengineering.common.util.EnergyHelper$IEForgeEnergyWrapper.canReceive(EnergyHelper.java:143)
	at com.rwtema.extrautils2.utils.CapGetter$2.hasCapability(CapGetter.java:57)
	at com.rwtema.extrautils2.utils.CapGetter.getInterface(CapGetter.java:169)
	at com.rwtema.extrautils2.utils.CapGetter$2.getInterface(CapGetter.java:62)
	at com.rwtema.extrautils2.utils.CapGetter$2.getInterface(CapGetter.java:52)
	at com.rwtema.extrautils2.power.energy.EnergyTransfer.onServerTick(EnergyTransfer.java:104)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_418_EnergyTransfer_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1689103352 bytes (1610 MB) / 3049259008 bytes (2908 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.2.2171 74 mods loaded, 74 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2171.jar) 
	UCHIJAAAA	Forge{12.18.2.2171} [Minecraft Forge] (forge-1.10.2-12.18.2.2171.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.4.3.145-universal.jar) 
	UCHIJAAAA	JEI{3.13.6.387} [Just Enough Items] (jei_1.10.2-3.13.6.387.jar) 
	UCHIJAAAA	AppleCore{2.1.0} [AppleCore] (AppleCore-mc1.10.2-2.1.0.jar) 
	UCHIJAAAA	appleskin{1.0.4} [AppleSkin] (AppleSkin-mc1.10.2-1.0.4.jar) 
	UCHIJAAAA	Psi{r1.0-42} [Psi] (Psi-r1.0-42.jar) 
	UCHIJAAAA	Quark{r1.0-60} [Quark] (Quark-r1.0-60.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	Baubles{1.3.6} [Baubles] (Baubles-1.10.2-1.3.6.jar) 
	UCHIJAAAA	betterquesting{1.3.174} [Better Questing] (BetterQuesting-1.3.174.jar) 
	UCHIJAAAA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCHIJAAAA	BloodMagic{1.9.4-2.1.0-68} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.1.0-68.jar) 
	UCHIJAAAA	Botania{r1.9-339} [Botania] (Botania r1.9-339.jar) 
	UCHIJAAAA	Chameleon{1.10-2.2.0} [Chameleon] (Chameleon-1.10-2.2.0.jar) 
	UCHIJAAAA	mcmultipart{2.0.0_88} [MCMultiPart] (MCMultiPart-experimental-2.0.0_88-universal.jar) 
	UCHIJAAAA	CharsetLib{0.3.0-pre15} [â€˝] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAA	CharsetAudio{0.3.0-pre15} [â™«] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAA	CharsetCarts{0.3.0-pre15} [U] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAA	CharsetDecoration{0.3.0-pre15} [âš?] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAA	CharsetDrama{0.3.0-pre15} [!] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAA	CharsetFarming{0.3.0-pre15} [;] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAA	CharsetGates{0.3.0-pre15} [&] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAA	CharsetPipes{0.3.0-pre15} [|] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAA	CharsetStorage{0.3.0-pre15} [#] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAA	CharsetTweaks{0.3.0-pre15} [*] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAA	CharsetWires{0.3.0-pre15} [+] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAA	CharsetWrench{0.3.0-pre15} [/] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.0.7.7} [Chisel] (Chisel-MC1.10.2-0.0.7.7.jar) 
	UCHIJAAAA	chiselsandbits{12.7} [Chisels & Bits] (chiselsandbits-12.7.jar) 
	UCHIJAAAA	CodeChickenLib{2.4.3.145} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.4.3.145-universal.jar) 
	UCHIJAAAA	CodeChickenCore{2.3.5.91} [CodeChicken Core] (CodeChickenCore-1.10.2-2.3.5.91-universal.jar) 
	UCHIJAAAA	cookingforblockheads{4.2.26} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.26.jar) 
	UCHIJAAAA	NashornLib{1.9.4-1.8.77-1.3.1} [Nashorn Library] (NashornLib-1.9.4-1.8.77-1.3.1.8.jar) 
	UCHIJAAAA	craftingharmonics{1.9.4_1.10_1.10.2-1.5.7} [Crafting Harmonics] (craftingharmonics-1.9.4_1.10_1.10.2-1.5.7.42.jar) 
	UCHIJAAAA	cyberware{beta-0.2.4} [Cyberware] (cyberware-1.9.4-1.10.2-beta-0.2.4.jar) 
	UCHIJAAAA	easyBreeding{5.0.0} [Easy Breeding] (easybreeding-1.9.4-4.0.1.jar) 
	UCHIJAAAA	EnderStorage{2.1.5.84} [EnderStorage] (EnderStorage-1.10.2-2.1.5.84-universal.jar) 
	UCHIJAAAA	forestry{5.2.16.331} [Forestry] (forestry_1.10.2-5.2.16.331.jar) 
	UCHIJAAAA	exnihiloomnia{1.2.1} [Ex Nihilo Omnia] (exnihiloomnia-1.2.1.jar) 
	UCHIJAAAA	excompressum{2.0.56} [Ex Compressum] (ExCompressum_1.10.2-2.0.56.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.1.1.jar) 
	UCHIJAAAA	flatcoloredblocks{mc1.10-v4.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.4.jar) 
	UCHIJAAAA	foamfix{0.3.1} [FoamFix] (foamfix-0.3.2a-law.jar) 
	UCHIJAAAA	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.1.5.jar) 
	UCHIJAAAA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.1.4.jar) 
	UCHIJAAAA	immersiveengineering{0.10-51} [Immersive Engineering] (ImmersiveEngineering-0.10-51.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	JEFB{1.0.4} [Just Enough Forestry Bees] (jefb_1.10.2-1.0.4.jar) 
	UCHIJAAAA	Lockdown{${mod_version}} [Lockdown] (Lockdown-1.10.2-5.0.0-universal.jar) 
	UCHIJAAAA	Mekanism{9.2.1} [Mekanism] (Mekanism-1.10.2-9.2.1.295.jar) 
	UCHIJAAAA	MekanismGenerators{9.2.1} [MekanismGenerators] (MekanismGenerators-1.10.2-9.2.1.295.jar) 
	UCHIJAAAA	MekanismTools{9.2.1} [MekanismTools] (MekanismTools-1.10.2-9.2.1.295.jar) 
	UCHIJAAAA	Morpheus{1.10.2-3.1.12} [Morpheus] (Morpheus-1.10.2-3.1.12.jar) 
	UCHIJAAAA	mxtune{0.3.1.0-dev.9} [mxTune] (mxtune-1.10.2-0.3.1.0-dev.9.jar) 
	UCHIJAAAA	mychunkloader{1.9.4-1.10.2-03} [My Chunk Loader] (Mychunkloader-1.9.4-1.10.2-03.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJAAAA	progressiveautomation{1.6.53} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.53.jar) 
	UCHIJAAAA	ProjectE{1.10.2-PE1.1.0B} [ProjectE] (ProjectE-1.10.2-PE1.1.0B.jar) 
	UCHIJAAAA	psionup{15.1} [PSIonic Upgrades] (PSIonicUpgrades-r1.15.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.5.6} [Storage Drawers] (StorageDrawers-1.10.2-3.5.6.jar) 
	UCHIJAAAA	refinedstorage{1.2.8} [Refined Storage] (refinedstorage-1.2.8.jar) 
	UCHIJAAAA	xreliquary{1.10.2-1.3.3.585} [Reliquary] (Reliquary-1.10.2-1.3.3.585.jar) 
	UCHIJAAAA	rftools{5.62} [RFTools] (rftools-1.10-5.62.jar) 
	UCHIJAAAA	rftoolscontrol{1.5.2} [RFTools Control] (rftoolsctrl-1.10-1.5.2.jar) 
	UCHIJAAAA	roots{0.207} [Roots] (roots-0.207.jar) 
	UCHIJAAAA	soulshardstow{1.10.2-2.6.6-46} [Soul Shards - The Old Ways] (SoulShards-TOW-1.10.2-2.6.6-46.jar) 
	UCHIJAAAA	SpiceOfLife{1.3.6} [The Spice of Life] (SpiceOfLife-mc1.9.4-1.3.6.jar) 
	UCHIJAAAA	bq_standard{1.3.92} [Standard Expansion] (StandardExpansion-1.3.92.jar) 
	UCHIJAAAA	totemic{1.9.4-0.7.9.1} [Totemic] (Totemic-1.9.4-0.7.9.1.jar) 
	UCHIJAAAA	treegrowingsimulator{0.0.4} [Tree Growing Simulator 2016] (TreeGrowingSimulator2016-0.0.4.jar) 
	UCHIJAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.1.213.jar) 
	UCHIJAAAA	wawla{2.3.1.213} [What Are We Looking At] (Wawla-1.10.2-2.3.1.213.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.0-60.jar)
  vazkii.quark.base.asm.ClassTransformer
Crafting Harmonics Core (craftingharmonics-1.9.4_1.10_1.10.2-1.5.7.42.jar)
  org.winterblade.minecraft.harmony.asm.PotionRemovedHookTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.145-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
AppleCore (AppleCore-mc1.10.2-2.1.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  team.chisel.common.asm.ChiselTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
  
LoadingHook (Mekanism-1.10.2-9.2.1.295.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by hron84** [comment]
I have a setup of  4 thermoelectric generators hooked up to an LV capacitor which pushes the generated energy on its bottom to a ExtraUtils capacitor/RF storage block.

**Comment by BluSunrize** [comment]
Yep, see #1760
Known issue, gonna release a fix today.
