### ISSUE TITLE
Crash on server when player joins

### ISSUE THREAD

**Issue by thehobojoe** [BluSunrize/ImmersiveEngineering#1788]
Unsure of the exact cause, but it happens every few hours, and always right when a player joins.

```
java.lang.Error
    at net.minecraft.world.World.func_189508_F(World.java:2417)
    at net.minecraft.world.World.func_175625_s(World.java:2397)
    at blusunrize.immersiveengineering.common.blocks.BlockIETileProvider.func_176211_b(BlockIETileProvider.java:481)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185893_b(BlockStateContainer.java:400)
    at net.minecraft.world.World.func_175627_a(World.java:3176)
    at net.minecraft.world.World.func_175676_y(World.java:3211)
    at net.minecraft.world.World.func_175651_c(World.java:3244)
    at net.minecraft.world.World.func_175687_A(World.java:3258)
    at blusunrize.immersiveengineering.common.blocks.metal.TileEntityConnectorRedstone$RedstoneWireNetwork.updateValues(TileEntityConnectorRedstone.java:385)
    at blusunrize.immersiveengineering.common.blocks.metal.BlockConnector.func_189540_a(BlockConnector.java:132)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:463)
    at net.minecraft.world.World.func_180496_d(World.java:519)
    at net.minecraft.world.World.func_175685_c(World.java:465)
    at blusunrize.immersiveengineering.common.blocks.TileEntityIEBase.markBlockForUpdate(TileEntityIEBase.java:107)
    at blusunrize.immersiveengineering.common.blocks.TileEntityIEBase.markContainingBlockForUpdate(TileEntityIEBase.java:99)
    at blusunrize.immersiveengineering.common.blocks.metal.TileEntityConnectorRedstone$RedstoneWireNetwork.notifyOfChange(TileEntityConnectorRedstone.java:407)
    at blusunrize.immersiveengineering.common.blocks.metal.TileEntityConnectorRedstone$RedstoneWireNetwork.mergeNetwork(TileEntityConnectorRedstone.java:321)
    at blusunrize.immersiveengineering.common.blocks.metal.TileEntityConnectorRedstone$RedstoneWireNetwork.removeFromNetwork(TileEntityConnectorRedstone.java:352)
    at blusunrize.immersiveengineering.common.blocks.metal.TileEntityConnectorRedstone.func_73660_a(TileEntityConnectorRedstone.java:55)
    at net.minecraft.world.World.func_72939_s(World.java:1804)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Unknown Source)
```

Full log:

http://pastebin.com/jsBTsnPB

Using IE 0.10 - 52, forge 2139

**Comment by thehobojoe** [comment]
Update: Seems to only happen when a player is loading the overworld when no one else is in the overworld at the same time.

**Comment by BluSunrize** [comment]
It's erroring in a vanilla function for retrieving TileEntities. I have no idea why it would be doing that .-.
Are you running Spigot, Themos or any other 'special' servers?

**Comment by AEnterprise** [comment]
it's not realy erroring, if you look at the full log this is the server watchdog killing the server because it detects it's stuck (no ticks executed for a few minutes) so that is just whatever code was running at that time, most likely something in the area is stuck in an infinite loop or takes to long to load

i suspect there is eighter a bug in spigot where it gets in a loop or there is something that's loading before the IE block that is taking super long causing it to be killed while IE is loading it's block

**Comment by thehobojoe** [comment]
No, running nothing like spigot or sponge etc. Plain forge. I have about 20 crashes with this identical error that have all happened under the same circumstances (someone loading the overworld when it is unloaded). Seems like something is creating a loop that keeps everything from loading and causes a time out.

**Comment by AEnterprise** [comment]
looking at the threads: you have a mod that connects to discord and those threads are in the waiting state, can you remove that and see if it fixes it? if that reacts to players joining the word and fails to sync to a different thread that connects to discord it could lock up the main thread long enough to fail completing the load in time

**Comment by thehobojoe** [comment]
I'll give that a shot, thanks.

**Comment by thehobojoe** [comment]
Exact same crash reoccurred with DiscordChat removed.

**Comment by thehobojoe** [comment]
I re-added discord chat and told everyone to remove IE redstone wires and connectors. No crashes since that point.
