### ISSUE TITLE
crash alumınum

### ISSUE THREAD

**Issue by musto20** [BluSunrize/ImmersiveEngineering#1798]
--- Minecraft Crash Report ----

WARNING: coremods are present:
  DepLoader (BrandonsCore-1.10.2-2.1.1.61-universal.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.4.jar)
  llibrary (llibrary-1.7.2-1.10.2.jar)
  CAFMLPlugin ([1.10]CraftableAnimals v2.6.0.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
  DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 13.12.2016 15:11
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Immersive Engineering (immersiveengineering)
Caused by: java.lang.IllegalArgumentException: Block: class blusunrize.immersiveengineering.common.blocks.BlockIEBase has property: type with invalidly named value: alumınum
	at net.minecraft.block.state.BlockStateContainer.func_185919_a(BlockStateContainer.java:120)
	at net.minecraft.block.state.BlockStateContainer.<init>(BlockStateContainer.java:78)
	at net.minecraft.block.state.BlockStateContainer.<init>(BlockStateContainer.java:62)
	at blusunrize.immersiveengineering.common.blocks.BlockIEBase.func_180661_e(BlockIEBase.java:357)
	at net.minecraft.block.Block.<init>(Block.java:225)
	at net.minecraft.block.Block.<init>(Block.java:234)
	at blusunrize.immersiveengineering.common.blocks.BlockIEBase.<init>(BlockIEBase.java:56)
	at blusunrize.immersiveengineering.common.IEContent.preInit(IEContent.java:164)
	at blusunrize.immersiveengineering.ImmersiveEngineering.preInit(ImmersiveEngineering.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:614)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 263554696 bytes (251 MB) / 606875648 bytes (578 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_D4 36 mods loaded, 36 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCH	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCH	OpenComputers|Core{1.6.0.4} [OpenComputers (Core)] (minecraft.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCH	CraftableAnimals{2.6.0} [Craftable Animals] ([1.10]CraftableAnimals v2.6.0.jar) 
	UCH	movillages{1.5.2} [Mo' Villages] ([1.9.4]Mo' Villages-1.5.2.jar) 
	UCH	BetterAchievements{0.3.2.39} [Better Achievements] (BetterAchievements-1.10.2-0.3.2.39.jar) 
	UCH	CodeChickenLib{2.4.3.124} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.4.3.124-universal.jar) 
	UCH	brandonscore{2.1.1} [Brandon's Core] (BrandonsCore-1.10.2-2.1.1.61-universal.jar) 
	UCH	CodeChickenCore{2.3.5.91} [CodeChicken Core] (CodeChickenCore-1.10.2-2.3.5.91-universal.jar) 
	UCH	ChickenChunks{2.1.5.42} [ChickenChunks] (ChickenChunks-1.10.2-2.1.5.42-universal.jar) 
	UCH	draconicevolution{2.0.3} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.3.137-universal.jar) 
	UCH	eleccore{1.6.360} [ElecCore] (ElecCore-1.10.2-1.6.360.jar) 
	UCH	EnderStorage{2.1.5.84} [EnderStorage] (EnderStorage-1.10.2-2.1.5.84-universal.jar) 
	UCH	FastLeaveDecay{1.2.3} [Fast Leave Decay] (FastLeaveDecay-MC1.10.2-1.2.3.jar) 
	UCH	fishing{1.4.4} [Fishing Net Mod] (GiacomosFishingNet1.10.2-1.4.4.jar) 
	UCH	immcraft{1.1.8} [Immersive Craft] (immcraft-1.10-1.1.8.jar) 
	UCH	JEI{3.13.6.387} [Just Enough Items] (jei_1.10.2-3.13.6.387.jar) 
	UCH	mantle{1.10.2-1.1.3.199} [Mantle] (Mantle-1.10.2-1.1.3.jar) 
	UCH	tconstruct{1.10.2-2.6.1.464} [Tinkers' Construct] (TConstruct-1.10.2-2.6.1.jar) 
	UCE	immersiveengineering{0.10-53} [Immersive Engineering] (ImmersiveEngineering-0.10-53.jar) 
	UCH	llibrary{1.7.2} [LLibrary] (llibrary-1.7.2-1.10.2.jar) 
	UCH	jurassicraft{2.0.4} [JurassiCraft] (JurassiCraft-2.0.4.jar) 
	UCH	lucky{7.3.0} [Lucky Block] (LuckyBlock_1-10-2_v7-3-0.zip) 
	UCH	OpenComputers{1.6.0.4} [OpenComputers] (OpenComputers-MC1.10.2-1.6.0.4.jar) 
	UCH	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCH	progressiveautomation{1.6.53} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.53.jar) 
	UCH	railcraft{10.0.1} [Railcraft] (Railcraft_1.10.2-10.0.1.jar) 
	UCH	rftools{5.62} [RFTools] (rftools-1.10-5.62.jar) 
	UCH	spartanshields{1.1b} [Spartan Shields] (SpartanShields-1.10.2-1.1b.jar) 
	UCH	superores{1.7} [Super Ores] (SuperOres-1.7.jar) 
	UCH	Translocator{2.1.3.34} [Translocator] (Translocators-1.10.2-2.1.3.34-universal.jar) 
	UCH	vanillamagic{1.10.2-0.21.0.2} [Vanilla Magic] (vanillamagic-1.10.2-0.21.0.2.jar) 
	UCH	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCH	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
	Loaded coremods (and transformers): 
DepLoader (BrandonsCore-1.10.2-2.1.1.61-universal.jar)
  
TransformerLoader (OpenComputers-MC1.10.2-1.6.0.4.jar)
  li.cil.oc.common.asm.ClassTransformer
llibrary (llibrary-1.7.2-1.10.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CAFMLPlugin ([1.10]CraftableAnimals v2.6.0.jar)
  naruto1310.craftableAnimals.vanilla.CATransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 372.90' Renderer: 'GeForce GT 520M/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.10.2_HD_U_D4
	Render Distance Chunks: 9
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 372.90
	OpenGlRenderer: GeForce GT 520M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by XFactHD** [comment]
I think this caused by the fact that you do 'return this.toString().toLowerCase();' which returns the lower case in the system language. If my assumption is right, the fix would be to use 'toLowerCase(Locale.ENGLISH)' instead.

**Comment by musto20** [comment]
thanks

**Comment by BluSunrize** [comment]
What the...
I have to ask, what language is your system on then? I didn't realize that there is system languages that somehow fuck up the default ascii characters O_o

**Comment by musto20** [comment]
my pc language turkish

**Comment by musto20** [comment]
This is the first time I've ever met such a thing

**Comment by XFactHD** [comment]
Blu, you don't need to ask, you just need to force the use of English as language for this operation.

**Comment by BluSunrize** [comment]
"having to ask" is a phrasing, it means my curiosity overwhelmed me. I'm also fairly sure you are aware of that, so thank you kindly for not contributing to the issue at all ;)

I'll look into forcing local for this.

**Comment by XFactHD** [comment]
No problem :D

**Comment by musto20** [comment]
tanrı türkü korusun
