### ISSUE TITLE
Crash with auto workbench.

### ISSUE THREAD

**Issue by Malus-Lupo** [BluSunrize/ImmersiveEngineering#1833]
Crashed when I clicked one of the bullet icons inside the auto work bench after putting the blue thing in but with no ingredients in the bench. Keeps crashing now every time I try to log into my server.
[crash-2016-12-31_13.32.23-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/679767/crash-2016-12-31_13.32.23-client.txt)

**Comment by BluSunrize** [comment]
Wut. You're missing a javafx class somehow.
No idea how that happened.

Try updating Java and see if that helps.

**Comment by Malus-Lupo** [comment]
Hmm Ok I will give it a try.

**Comment by Malus-Lupo** [comment]
Hmm I updated to java 8 update 111, I think it is the latest and I still get the same crash.

**Comment by zuoanqh** [comment]
getting the same error here. screen turns sky color after i put blueprint in. then crash. 

java.lang.NoClassDefFoundError: javafx/util/Pair
	at blusunrize.immersiveengineering.client.render.TileRenderAutoWorkbench.getBlueprintDrawable(TileRenderAutoWorkbench.java:461)
	at blusunrize.immersiveengineering.client.render.TileRenderAutoWorkbench.getBlueprintDrawable(TileRenderAutoWorkbench.java:344)
	at blusunrize.immersiveengineering.client.render.TileRenderAutoWorkbench.renderTileEntityAt(TileRenderAutoWorkbench.java:272)
	at blusunrize.immersiveengineering.client.render.TileRenderAutoWorkbench.func_180535_a(TileRenderAutoWorkbench.java:40)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:701)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: javafx.util.Pair
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more
Caused by: java.lang.NullPointerException

**Comment by zuoanqh** [comment]
i did a quick search, and this is the only occasion you have imported javafx. what if javafx itself is not supported? there's no reason we don't have an up-to-date version of it, since the Pair class existed since 2.0. i bought my computer in 2016.

**Comment by XFactHD** [comment]
Java always contains javafx meaning you always have some version of it.
@Blusunrize why are you using the Pair from javafx and not the org.apache.commons.lang3.tuple.Pair? They don't seem that much different to me.

**Comment by BluSunrize** [comment]
There isn't really. I just imported what I happened to come across. x3

I'm still surprised that it is somehow missing from their Java installation. It shouldn't be JDK only, right?

**Comment by XFactHD** [comment]
No, I doubt it is JDK only, that would be kinda hilarious.

**Comment by zuoanqh** [comment]
well, my guess is there's something weird about javafx with minecraft. maybe. i remember importing wpf's pair class and failed miserably lol.

**Comment by XFactHD** [comment]
There are many mods (opis for example) that use javafx for special windows.

**Comment by zuoanqh** [comment]
interesting...

**Comment by zuoanqh** [comment]
I did some search around, changed curse's java version, and it still does not work. i then found this page, it seems to apply to your situation as there's no folder named "com" under the packed jar file.

http://stackoverflow.com/questions/16868446/javafx-exception-in-thread-main-java-lang-noclassdeffounderror-javafx-applica

**Comment by Malus-Lupo** [comment]
Thank you, I just downloaded my world from the server mc'edited away the bench and re-uploaded but I will remember that if I have another prob.
