### ISSUE TITLE
[1.10.2] Custom Arc Furnace Recipes

### ISSUE THREAD

**Issue by xSparky911x** [BluSunrize/ImmersiveEngineering#1895]
Forge: 2221
CraftTweaker: 3.0.20
Immersive Engineering: 0.10.56

I am trying to add a custom recipe to the Arc Furnace. Input would be minecraft:sand, output is libvulpes:productingot:3 (Silicon Ingot from Advanced Rocketry). Not sure what to have as the slag output so I chose <biomesoplenty:ash>. Minetweaker wiki shows the AdditiveArray and RecipeTypeString to be optional (plus I do not know what to put here) so I left them out.

The script:

`mods.immersiveengineering.ArcFurnace.addRecipe(<libvulpes:productingot:3>, <minecraft:sand>, <biomesoplenty:ash>, 4600, 3600);
`

The error:

> ERROR: Error executing immersiveengineering.zs: null

Minetweaker log: http://pastebin.com/eqL5GiTJ

EDIT: used "Code" markup instead of "Quote" markup. derp

**Comment by KnightMiner** [comment]
Read up on MineTweaker scrip format, you need <> brackets around items.

**Comment by xSparky911x** [comment]
Sorry the brackets are there. Git didn't post them because I used quote instead of code. 

`mods.immersiveengineering.ArcFurnace.addRecipe(<libvulpes:productingot:3>, <minecraft:sand>, <biomesoplenty:ash>, 4600, 3600);`

**Comment by BluSunrize** [comment]
Try it with two nulls behind it,  maybe optional is broken

**Comment by xSparky911x** [comment]
Just tried , null , null at the end and I still get Error executing immersiveengineering.zs: null. And for giggles I tried it also with <> and [] brackets but naturally those threw errors.

`mods.immersiveengineering.ArcFurnace.addRecipe(<libvulpes:productingot:3>, <minecraft:sand>, <biomesoplenty:ash>, 4600, 3600, null null);`

**Comment by xSparky911x** [comment]
this is the error I get in the log:

`ERROR: Error executing immersiveengineering.zs: null
java.lang.NullPointerException
	at blusunrize.immersiveengineering.api.crafting.ArcFurnaceRecipe.<init>(ArcFurnaceRecipe.java:52)
	at blusunrize.immersiveengineering.common.util.compat.crafttweaker.ArcFurnace.addRecipe(ArcFurnace.java:31)
	at Immersiveengineering.__script__(immersiveengineering.zs:18)
	at __ZenMain__.run(immersiveengineering.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:158)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:631)
	at minetweaker.MineTweakerImplementationAPI.lambda$static$0(MineTweakerImplementationAPI.java:73)
	at minetweaker.MineTweakerImplementationAPI$3.execute(MineTweakerImplementationAPI.java:616)
	at minetweaker.mc1102.server.MCServer$MCCommand.func_184881_a(MCServer.java:115)
	at com.feed_the_beast.ftbu.ranks.CmdOverride.func_184881_a(CmdOverride.java:54)
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:104)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:83)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892)
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at net.minecraft.util.Util.func_181617_a(SourceFile:45)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes`

**Comment by BluSunrize** [comment]
That log helps considerably more. 
I'll provide a proper fix with the next release, for now, make additives an empty array, that should work

**Comment by xSparky911x** [comment]
I hate to be the noob but could you give me an example? Im sorry I am not good with code (yet). Maybe someday lol
