### ISSUE TITLE
Error with Journey Map

### ISSUE THREAD

**Issue by darthvader45** [BluSunrize/ImmersiveEngineering#2132]
Noticed this, non-critical, but could use a bit of work:

`[10:08:18] [Client thread/ERROR] [journeymap]: Error calling blusunrize.immersiveengineering.client.models.smart.ConnModelReal.getQuads() (SUPPRESSED)
[10:08:18] [Client thread/ERROR] [journeymap]: java.lang.NullPointerException
	at blusunrize.immersiveengineering.client.models.IESmartObjModel.buildQuads(IESmartObjModel.java:237)
	at blusunrize.immersiveengineering.client.models.IESmartObjModel.getQuads(IESmartObjModel.java:210)
	at blusunrize.immersiveengineering.client.models.IESmartObjModel.func_188616_a(IESmartObjModel.java:177)
	at blusunrize.immersiveengineering.client.models.smart.ConnModelReal.func_188616_a(ConnModelReal.java:69)
	at journeymap.client.cartography.ColorHelper.getFirstFoundSprite(ColorHelper.java:183)
	at journeymap.client.cartography.ColorHelper.getDirectIcon(ColorHelper.java:164)
	at journeymap.client.cartography.ColorHelper.getTextureColor(ColorHelper.java:112)
	at journeymap.client.model.mod.vanilla.VanillaColorHandler.getTextureColor(VanillaColorHandler.java:24)
	at journeymap.client.model.BlockMD.ensureColor(BlockMD.java:408)
	at journeymap.client.cartography.ColorManager.initBlockColors(ColorManager.java:192)
	at journeymap.client.cartography.ColorManager.ensureCurrent(ColorManager.java:129)
	at journeymap.client.task.main.EnsureCurrentColorsTask.perform(EnsureCurrentColorsTask.java:15)
	at journeymap.client.task.main.MainTaskController.performTasks(MainTaskController.java:64)
	at journeymap.client.JourneymapClient.performMainThreadTasks(JourneymapClient.java:571)
	at journeymap.client.forge.event.StateTickHandler.onClientTick(StateTickHandler.java:75)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_473_StateTickHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)`

**Comment by mindforger** [comment]
just a hint, try using pastebin next time to upload such a wall of text :)
also you are missing version informations required (just in case blu didn't send you here directly)

for future reports, you can forcibly crash minecraft by pressing and holding F3 + C and post the resulting crashlog to share your modpack data :)

**Comment by darthvader45** [comment]
IE version 0.10 - 58 for Minecraft 1.10.2.  Also using Immersive Petroleum pre-release 4, if that's any help.
