### ISSUE TITLE
[1.11.2] Assembler NullPointerException

### ISSUE THREAD

**Issue by Purzelpu** [BluSunrize/ImmersiveEngineering#2196]
The assembler leads to a game crash. 
Steps to reproduce:
1. Build an assembler.
2. Use it to cut wood into planks (haven't tried sth. else).
3. Power it.
4. Crash.

No other mods used, MC 1.11.2, Forge 2315. 
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 6/20/17 9:02 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityAssembler.consumeItem(TileEntityAssembler.java:243)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityAssembler.func_73660_a(TileEntityAssembler.java:161)
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

**Comment by malte0811** [comment]
What version of IE are you using? There are a lot of versions for 1.11, even though only one is on Curse(forge).

**Comment by Purzelpu** [comment]
I tried the official 62 from curseforge and one of the newer builds (144?). Both show the same behaviour.

**Comment by LennartCockx** [comment]
I'm getting the same crash with the assembler with the version on curseforge. I created a crafting recipe for wheat to bread and powered it. As soon as the assembler is fed with enough items to start crafting the server crashes.

**Comment by malte0811** [comment]
Fixed for the next release. I was asking about the version used because @BluSunrize fixed a similar NPE quite recently and I wasn't sure whether you had updated to the official build yet.
