### ISSUE TITLE
server wont load textures

### ISSUE THREAD

**Issue by slothdemond** [BluSunrize/ImmersiveEngineering#2382]
the game shows that the mod is kinda there because of empty blocks in the immersive engineering section in creative mode but there are no textures or anything. here is the log for the server

[15:03:12] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[15:03:12] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[15:03:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
[15:03:12] [main/INFO] [FML]: Forge Mod Loader version 14.21.1.2426 for Minecraft 1.12 loading
[15:03:12] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_144, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_144
[15:03:12] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:03:12] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[15:03:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:03:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:03:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:03:13] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[15:03:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:03:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[15:03:13] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[15:03:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[15:03:14] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[15:03:17] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Starting minecraft server version 1.12
[15:03:17] [Server thread/INFO] [FML]: MinecraftForge v14.21.1.2426 Initialized
[15:03:17] [Server console handler/ERROR] [net.minecraft.server.dedicated.DedicatedServer]: Exception handling console input
java.io.IOException: The handle is invalid
	at java.io.FileInputStream.readBytes(Native Method) ~[?:1.8.0_144]
	at java.io.FileInputStream.read(Unknown Source) ~[?:1.8.0_144]
	at java.io.BufferedInputStream.read1(Unknown Source) ~[?:1.8.0_144]
	at java.io.BufferedInputStream.read(Unknown Source) ~[?:1.8.0_144]
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source) ~[?:1.8.0_144]
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source) ~[?:1.8.0_144]
	at sun.nio.cs.StreamDecoder.read(Unknown Source) ~[?:1.8.0_144]
	at java.io.InputStreamReader.read(Unknown Source) ~[?:1.8.0_144]
	at java.io.BufferedReader.fill(Unknown Source) ~[?:1.8.0_144]
	at java.io.BufferedReader.readLine(Unknown Source) ~[?:1.8.0_144]
	at java.io.BufferedReader.readLine(Unknown Source) ~[?:1.8.0_144]
	at net.minecraft.server.dedicated.DedicatedServer$2.run(DedicatedServer.java:102) [nx$2.class:?]
[15:03:17] [Server thread/INFO] [FML]: Replaced 921 ore ingredients
[15:03:17] [Server thread/INFO] [FML]: Found 1 mods from the command line. Injecting into mod discoverer
[15:03:17] [Server thread/INFO] [FML]: Searching C:\Users\Brad\Desktop\server\mods for mods
[15:03:17] [Server thread/INFO] [FML]: Forge Mod Loader has identified 6 mods to load
[15:03:17] [Server thread/WARN] [FML]: Missing English translation for FML: assets/fml/lang/en_us.lang
[15:03:17] [Server thread/WARN] [FML]: Missing English translation for worldedit: assets/worldedit/lang/en_us.lang
[15:03:17] [Server thread/INFO] [FML]: FML has found a non-mod file MercuriusUpdater-1.12.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[15:03:18] [Server thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, binocular, worldedit] at CLIENT
[15:03:18] [Server thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, binocular, worldedit] at SERVER
[15:03:19] [Server thread/INFO] [FML]: Processing ObjectHolder annotations
[15:03:19] [Server thread/INFO] [FML]: Found 1168 ObjectHolder annotations
[15:03:19] [Server thread/INFO] [FML]: Identifying ItemStackHolder annotations
[15:03:19] [Server thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[15:03:19] [Server thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[15:03:19] [Forge Version Check/INFO] [ForgeVersionCheck]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[15:03:19] [Server thread/INFO] [FML]: Applying holder lookups
[15:03:19] [Server thread/INFO] [FML]: Holder lookups applied
[15:03:19] [Server thread/INFO] [FML]: Applying holder lookups
[15:03:19] [Server thread/INFO] [FML]: Holder lookups applied
[15:03:19] [Server thread/INFO] [FML]: Applying holder lookups
[15:03:19] [Server thread/INFO] [FML]: Holder lookups applied
[15:03:19] [Server thread/INFO] [FML]: Applying holder lookups
[15:03:19] [Server thread/INFO] [FML]: Holder lookups applied
[15:03:19] [Server thread/INFO] [FML]: Injecting itemstacks
[15:03:19] [Server thread/INFO] [FML]: Itemstack injection complete
[15:03:19] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Loading properties
[15:03:19] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Default game type: SURVIVAL
[15:03:19] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Generating keypair
[15:03:19] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Starting Minecraft server on *:25565
[15:03:19] [Server thread/INFO] [net.minecraft.network.NetworkSystem]: Using default channel type
[15:03:19] [Forge Version Check/INFO] [ForgeVersionCheck]: [forge] Found status: OUTDATED Target: 14.21.1.2428
[15:03:20] [Server thread/INFO] [FML]: Applying holder lookups
[15:03:20] [Server thread/INFO] [FML]: Holder lookups applied
[15:03:20] [Server thread/INFO] [FML]: Injecting itemstacks
[15:03:20] [Server thread/INFO] [FML]: Itemstack injection complete
[15:03:20] [Server thread/INFO] [worldedit]: WorldEdit for Forge (version 6.1.8-SNAPSHOT) is loaded
[15:03:20] [Server thread/INFO] [FML]: Forge Mod Loader has successfully loaded 6 mods
[15:03:21] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Preparing level "world 1"
[15:03:21] [Server thread/INFO] [FML]: Loading dimension 0 (world 1) (net.minecraft.server.dedicated.DedicatedServer@237e8059)
[15:03:21] [Server thread/INFO] [net.minecraft.advancements.AdvancementList]: Loaded 488 advancements
[15:03:21] [Server thread/INFO] [FML]: Loading dimension 1 (world 1) (net.minecraft.server.dedicated.DedicatedServer@237e8059)
[15:03:21] [Server thread/INFO] [FML]: Loading dimension -1 (world 1) (net.minecraft.server.dedicated.DedicatedServer@237e8059)
[15:03:21] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing start region for level 0
[15:03:22] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 21%
[15:03:23] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 61%
[15:03:24] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Done (3.752s)! For help, type "help" or "?"
[15:03:40] [User Authenticator #1/INFO] [net.minecraft.server.network.NetHandlerLoginServer]: UUID of player zoey_willow4 is 8019cc83-3729-4250-8606-4b8aa1ce852c
[15:03:41] [Netty Server IO #2/INFO] [FML]: Client protocol version 2
[15:03:41] [Netty Server IO #2/INFO] [FML]: Client attempting to join with 5 mods : minecraft@1.12,FML@8.0.99.99,forge@14.21.1.2428,mcp@9.19,binocular@1.2
[15:03:41] [Netty Server IO #2/INFO] [FML]: Attempting connection with missing mods [worldedit] at CLIENT
[15:03:41] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[15:03:41] [Server thread/INFO] [net.minecraft.server.management.PlayerList]: zoey_willow4[/75.155.144.38:53168] logged in with entity id 626 at (283.73294369810935, 72.0, 321.2126845143609)
[15:03:41] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: zoey_willow4 joined the game
[15:04:14] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [zoey_willow4: Set the time to 0]
[15:04:26] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [zoey_willow4: Changing to clear weather]
[15:04:41] [User Authenticator #2/INFO] [net.minecraft.server.network.NetHandlerLoginServer]: UUID of player Slothdemond is 184d0e31-d128-4c6c-a52d-1e0fccd07fa8
[15:04:41] [Netty Server IO #4/INFO] [FML]: Client protocol version 2
[15:04:41] [Netty Server IO #4/INFO] [FML]: Client attempting to join with 7 mods : minecraft@1.12,FML@8.0.99.99,forge@14.21.1.2426,immersiveengineering@0.12-70,worldedit@6.1.8-SNAPSHOT,mcp@9.19,binocular@1.2
[15:04:42] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[15:04:42] [Server thread/INFO] [net.minecraft.server.management.PlayerList]: Slothdemond[/75.155.144.38:59560] logged in with entity id 1422 at (295.9873191913342, 83.0, 290.00704365487314)
[15:04:42] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Slothdemond joined the game
[15:04:57] [Netty Server IO #4/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_144]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_144]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_144]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_144]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_144]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[PooledUnsafeDirectByteBuf.class:?]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[AbstractByteBuf.class:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372) ~[NioSocketChannel.class:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [AbstractNioByteChannel$NioByteUnsafe.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [NioEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[15:04:57] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Slothdemond lost connection: Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host
[15:04:57] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Slothdemond left the game

**Comment by BluSunrize** [comment]
Closed, due to disregard of contribution guidelines.
No Version number, no modlist, and the log wasn't spoilered. 

Also, (but I cant fault you there, you probably weren't aware) for missing textures/models, I'd need the client log. 

Fix the stuff mentioned above and I'll reopen this.
