### ISSUE TITLE
0.12-72 incorrect MC version

### ISSUE THREAD

**Issue by kreezxil** [BluSunrize/ImmersiveEngineering#2495]
```
[18:05:25] [Server thread/FATAL] [FML]: The mod immersiveengineering does not wish to run in Minecraft version Minecraft 1.12. You will have to remove it to play.
[18:05:25] [Server thread/FATAL] [FML]: Wrong Minecraft version for immersiveengineering
[18:05:25] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraftforge.fml.common.WrongMinecraftVersionException: Wrong Minecraft version for immersiveengineering
Wrong Minecraft Versions!
Mod: immersiveengineering
Location: /root/1.12/skyblock-godless/mods/ImmersiveEnginnering-0.12-72.jar
Expected: [1.12.1,1.12.1]
Current: Minecraft 1.12


        at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:244) ~[Loader.class:?]
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:547) ~[Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97) ~[FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[nx.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:483) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

0.12-72 crashes dedicated server Forge 1.12 build 2443

Notes:
     on startup while looking for 1.12.1

crash report:
https://gist.github.com/57c0b787971716b2528a6de81326ae0e

fml server latest:
https://gist.github.com/701edfb4ad568f6d9eb056d1161c952f

**Comment by CharCharthemonkey** [comment]
yea i have
![2017-09-14_14 16 33](https://user-images.githubusercontent.com/30783285/30458357-c16cc5a0-9970-11e7-8d1d-1492ae7cd6a2.png)
 that issue to

**Comment by BluSunrize** [comment]
Go update to Minecraft 1.12.1 then. Other 1.12 mods should work on 1.12.1 easily.

**Comment by kreezxil** [comment]
You tagged the mod I reported as running in 1.12.

If it doesn't please remove the tag.

**Comment by BluSunrize** [comment]
The tag was removed 7 hours ago, and you can still update. Over 90% of the 1.12 mods are forwardcompatible to 1.12.1

**Comment by kreezxil** [comment]
Sorry I can't update the pack this is for is locked to 1.12 around a very
specific mod.

On Sep 15, 2017 1:27 AM, "BluSunrize" <notifications@github.com> wrote:

The tag was removed 7 hours ago, and you can still update. Over 90% of the
1.12 mods are forwardcompatible to 1.12.1

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BluSunrize/ImmersiveEngineering/issues/2495#issuecomment-329693644>,
or mute the thread

**Comment by BluSunrize** [comment]
Care to specify which mod? As far as I'm aware updating should be possible for most mods even if they don't specifically flag as 1.12.1 compatible. Only things that would have been affected is some coremods.
