### ISSUE TITLE
Botania magnet crash

### ISSUE THREAD

**Issue by cam72cam** [BluSunrize/ImmersiveEngineering#2572]
### Description of the issue:
I have a botania magnet ring and mana ring equipped.  I drop a ItemRailGun.  The game crashes.

### Crashlog:
```
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.ClassCastException: net.minecraft.item.ItemAir cannot be cast to blusunrize.immersiveengineering.common.util.EnergyHelper$IIEEnergyItem
	at blusunrize.immersiveengineering.common.util.EnergyHelper$ItemEnergyStorage.<init>(EnergyHelper.java:273) ~[EnergyHelper$ItemEnergyStorage.class:?]
	at blusunrize.immersiveengineering.common.items.ItemRailgun$1.<init>(ItemRailgun.java:113) ~[ItemRailgun$1.class:?]
	at blusunrize.immersiveengineering.common.items.ItemRailgun.initCapabilities(ItemRailgun.java:111) ~[ItemRailgun.class:?]
	at net.minecraft.item.ItemStack.forgeInit(ItemStack.java:1215) ~[aip.class:?]
	at net.minecraft.item.ItemStack.<init>(ItemStack.java:112) ~[aip.class:?]
	at net.minecraft.item.ItemStack.<init>(ItemStack.java:98) ~[aip.class:?]
	at vazkii.botania.api.BotaniaAPI.isItemBlacklistedFromMagnet(BotaniaAPI.java:366) ~[BotaniaAPI.class:?]
	at vazkii.botania.api.BotaniaAPI.isItemBlacklistedFromMagnet(BotaniaAPI.java:358) ~[BotaniaAPI.class:?]
	at vazkii.botania.common.item.equipment.bauble.ItemMagnetRing.canPullItem(ItemMagnetRing.java:112) ~[ItemMagnetRing.class:?]
	at vazkii.botania.common.item.equipment.bauble.ItemMagnetRing.onWornTick(ItemMagnetRing.java:92) ~[ItemMagnetRing.class:?]
	at baubles.common.event.EventHandlerEntity.playerTick(EventHandlerEntity.java:110) ~[EventHandlerEntity.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_186_EventHandlerEntity_playerTick_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:554) ~[ForgeHooks.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2082) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:232) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
```

### Versions & Modlist
ImmersiveEngineering-0.12-74.jar
Botania r1.10-349.jar
forge-1.12.2-14.23.0.2503

I have a current workaround where I wrap "return new IEItemStackHandler(stack){...}"  in a try catch, return null and don't log the exception.

It seems that botania is copying the itemstack using the new ItemStack(stack.getItem(), count, meta) method which is causing the crash.  Could stack.getItem() be returning AIR?

https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/api/BotaniaAPI.java#L366

**Comment by malte0811** [comment]
I'll deal with it. We had the same issue with capacitor packs some time ago, seems like I just didn't think about other items being affected by this as well.

**Comment by malte0811** [comment]
Fixed.
@Vazkii I think the code @cam72cam linked is at least partially broken. A zero-size item stack is empty and returns air in `getItem` (Probably since 1.11?). The code looks a bit weird in general as well (Couldn't the recursion be replaced with an assignment to `stack`?).
