### ISSUE TITLE
Can't join LAN server with only Immersive Engineering (1.12.2)

### ISSUE THREAD

**Issue by RareBeast** [BluSunrize/ImmersiveEngineering#2621]
### Description of the issue:
Both PC's can load their own single player worlds with no issues.   When the laptop tries to connect to my main PC via the "Open to Lan" option it get the error message - 

`Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host`

### Crashlog:
The MultiMC log (on the server) comes up with -

```
[17:40:05] [main/INFO]: Using default channel type
[17:40:05] [main/INFO]: Started on 53803
[17:40:05] [main/INFO]: [CHAT] Local game hosted on port 53803
[17:40:34] [User Authenticator #1/INFO]: UUID of player HarryDavid is d0faabe5-f964-4ecf-a04e-963c31cdc145
[17:40:34] [Netty Server IO #4/INFO] [FML]: Client protocol version 2
[17:40:34] [Netty Server IO #4/INFO] [FML]: Client attempting to join with 5 mods : minecraft@1.12.2,FML@8.0.99.99,forge@14.23.0.2545,immersiveengineering@0.12-74,mcp@9.42
[17:40:35] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[17:40:35] [Server thread/INFO]: HarryDavid[/192.168.1.5:59786] logged in with entity id 5325 at (-194.5, 69.0, 260.5)
[17:40:35] [Server thread/INFO]: HarryDavid joined the game
[17:40:35] [main/INFO]: [CHAT] HarryDavid joined the game
[17:40:35] [Netty Server IO #4/ERROR] [FML]: NetworkDispatcher exception
io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1408) ~[AbstractByteBuf.class:4.1.9.Final]
	at io.netty.buffer.UnpooledHeapByteBuf.array(UnpooledHeapByteBuf.java:154) ~[UnpooledHeapByteBuf.class:4.1.9.Final]
	at net.minecraft.network.PacketBuffer.array(PacketBuffer.java:1264) ~[gy.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.toS3FPackets(FMLProxyPacket.java:151) ~[FMLProxyPacket.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:538) ~[NetworkDispatcher.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:4.1.9.Final]
	at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245) [gw$4.class:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [AbstractEventExecutor.class:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [SingleThreadEventExecutor.class:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) [NioEventLoop.class:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
[17:40:35] [Server thread/INFO]: HarryDavid lost connection: Internal Exception: io.netty.util.IllegalReferenceCountException: refCnt: 0
[17:40:35] [Server thread/INFO]: HarryDavid left the game
[17:40:35] [main/INFO]: [CHAT] HarryDavid left the game
```

The MultiMC on the client trying to connect comes up with -
```

[17:40:32] [main/INFO]: Connecting to 192.168.1.16, 53803
[17:40:34] [Netty Client IO #2/INFO] [FML]: Server protocol version 2
[17:40:34] [Netty Client IO #2/INFO] [FML]: Injecting existing registry data into this client instance
[17:40:34] [Netty Client IO #2/INFO] [FML]: Applying holder lookups
[17:40:34] [Netty Client IO #2/INFO] [FML]: Holder lookups applied
[17:40:34] [Netty Client IO #2/INFO] [FML]: [Netty Client IO #2] Client side modded connection established
[17:40:36] [Netty Client IO #2/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_131]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_131]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_131]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_131]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_131]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[PooledUnsafeDirectByteBuf.class:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[AbstractByteBuf.class:4.1.9.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372) ~[NioSocketChannel.class:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [AbstractNioByteChannel$NioByteUnsafe.class:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624) [NioEventLoop.class:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [NioEventLoop.class:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [NioEventLoop.class:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [NioEventLoop.class:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[17:40:37] [main/INFO] [FML]: Applying holder lookups
[17:40:37] [main/INFO] [FML]: Holder lookups applied
```

### Versions & Modlist

Minecraft 1.12.2
Forge 14.23.0.2545
Immersive Engineering 0.12-74

No other mods or resource packs.

(I have been able to connect to 1.12.2 minecraft with another 20+ mods loaded as long as IE isn't one of them.)

**Comment by RareBeast** [comment]
Solved this by rolling the version of Forge back to 14.23.0.2517

Thanks anyway - love the mod!

**Comment by AEnterprise** [comment]
related to forge patching up a memory leak caused by bytebuffers needed to be released. Forge releases to the bytebuff after it called the frombytes method

can be fixed/worked around by calling retain on the buffer in the frombytes method and calling release when you are done with it

**Comment by BluSunrize** [comment]
@AEnterprise got a link to a correct implementation for that which I could ~~steal~~ draw inspiration from?

**Comment by AEnterprise** [comment]
here is the explanation on github after poking people, it's applied to sonarcore but applies to any syncing for retaining and releasing:
https://github.com/SonarSonic/Sonar-Core/issues/50#issuecomment-345067314

**Comment by malte0811** [comment]
I'm pretty sure that's irrelevant here, we don't keep a reference to the buffer AFAIK. I'd think this is related to LAN since we use Forge 2544 with IE on BTMMoon without any issues (2545 added a new event, no networking changes). LAN multiplayer is a bit weird with networking anyway IIRC (or it used to be).

**Comment by BluSunrize** [comment]
@malte0811, while I got you here, any unpushed changes? I *really* want to get a build out.

**Comment by AEnterprise** [comment]
well the error is definatly from someone somewhere trying to read a bytebuff after forge relased it

could be a lan only codepath (in IE or even forge? don't know IE internals)

**Comment by bs2609** [comment]
See https://github.com/MinecraftForge/MinecraftForge/pull/4536.

**Comment by malte0811** [comment]
Great, thanks for telling us!
