### ISSUE TITLE
Crash at launch of the game of minecraft with the modpack the simple life 2. the last version.

### ISSUE THREAD

**Issue by Kazzinga** [BluSunrize/ImmersiveEngineering#2654]
EDIT (by @malte0811): Incomplete crashlog: https://gist.github.com/malte0811/e73942d69cccc12fac3215f1248ad2a6 The original post contained just the issue template, this incomplete crash report was posted as a comment directly afterwards.

**Comment by Kazzinga** [comment]
[net.minecraft.init.Bootstrap:func_179870_a:560]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  ForgelinPlugin (Forgelin-1.5.1.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  Extra Alchemy ASM (extraalchemy-0.3.3.1-release.jar)
  AstralCore (astralsorcery-1.4.5.jar)
  llibrary (llibrary-1.7.7-1.10.2.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  CTMCorePlugin (CTM-MC1.10.2-0.2.2.24.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  IvToolkit (IvToolkit-1.3.3-1.10.jar)
  Plugin (NotEnoughIDs-1.5.3.1.jar)
  PSLoadingPlugin (PerfectSpawn-MC1.10.2-1.4.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 12/7/17 6:25 PM
Description: Initializing game

java.lang.OutOfMemoryError: GC overhead limit exceeded
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad$Builder.<init>(UnpackedBakedQuad.java:112)
	at net.minecraftforge.client.model.ItemLayerModel.buildQuad(ItemLayerModel.java:369)
	at net.minecraftforge.client.model.ItemLayerModel.buildSideQuad(ItemLayerModel.java:353)
	at net.minecraftforge.client.model.ItemLayerModel.addSideQuad(ItemLayerModel.java:278)
	at net.minecraftforge.client.model.ItemLayerModel.getQuadsForSprite(ItemLayerModel.java:217)
	at net.minecraftforge.client.model.ItemLayerModel.bake(ItemLayerModel.java:126)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bake(ModelLoader.java:549)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:193)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:350)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by malte0811** [comment]
How much memory are you allocating for MC?

**Comment by Kazzinga** [comment]
i don't know with the new launcher

**Comment by Kazzinga** [comment]
and i don't know where i can see and change

**Comment by malte0811** [comment]
The new launcher isn't the best description. What new launcher?
Also, this isn't IRC/Discord where it is normal to post multiple short messages directly after each other. Write down everything you want to say and press comment once you are done with that.

**Comment by Kazzinga** [comment]
sorry, the new launcher that Microsoft develop for minecraft. with the older i know where change ram for MC. but with this i don't know how. i thinked that it is automatic. so it give MC the ram that its need

**Comment by malte0811** [comment]
![](https://i.imgur.com/ZrH91sF.png)

**Comment by Kazzinga** [comment]
ohhh ok thanks a lot
