### ISSUE TITLE
Arc furnace (technical block?) is available in the creative tab

### ISSUE THREAD

**Issue by planetguy32** [BluSunrize/ImmersiveEngineering#268]
![2015-08-04_09 21 08](https://cloud.githubusercontent.com/assets/2831434/9066061/52c50190-3a8a-11e5-8d0b-fb34f4cc9c2d.png)

When placed, it's shaped like a half-slab and has no texture. It has a TileEntityArcFurnace, and when I punched it I got this crash:

java.lang.ArrayIndexOutOfBoundsException: -1
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityArcFurnace.getOriginalBlock(TileEntityArcFurnace.java:50)
	at blusunrize.immersiveengineering.common.blocks.metal.BlockMetalMultiblocks.breakBlock(BlockMetalMultiblocks.java:138)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:658)
	at net.minecraft.world.World.setBlock(World.java:519)
	at net.minecraft.world.World.setBlockToAir(World.java:651)
	at net.minecraft.block.Block.removedByPlayer(Block.java:1670)
	at net.minecraft.block.Block.removedByPlayer(Block.java:1664)
	at net.minecraft.server.management.ItemInWorldManager.removeBlock(ItemInWorldManager.java:270)
	at net.minecraft.server.management.ItemInWorldManager.removeBlock(ItemInWorldManager.java:263)
	at net.minecraft.server.management.ItemInWorldManager.tryHarvestBlock(ItemInWorldManager.java:304)
	at net.minecraft.server.management.ItemInWorldManager.onBlockClicked(ItemInWorldManager.java:168)
	at net.minecraft.network.NetHandlerPlayServer.processPlayerDigging(NetHandlerPlayServer.java:523)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.processPacket(C07PacketPlayerDigging.java:61)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.processPacket(C07PacketPlayerDigging.java:94)
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:241)
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:182)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:726)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752)

I'm using version 0.5.0-deobf downloaded from Curse, in a development environment.

**Comment by theunkn0wn1** [comment]
I can confirm this.
Running FTB infinity (pack version 1.9.0) no extra mods added excluding IE.
Built off aae0fcac37281664526e2ebfb2f20209864e98c5

log: http://paste.feed-the-beast.com/view/05a9ea45

**Comment by BluSunrize** [comment]
You gave yourself the fake block of a multiblock construct. That thing is not aquireable via any means usually, so this isn't really a bug report either.

**Comment by theunkn0wn1** [comment]
This is a bug as the developer(s) left something available to the end user that causes unexpected behavior within the software, leading to a fatal error.
 the item in question *is* acquirable as it stands by normal means by any user with creative mode privileges on the client/server or cheat mode enabled on NEI, regardless if the item is craftable or not.



I do understand it is a fake block and that it is not *supposed* to be accessible by users... however the fact it is exposed to users, and the lack(?) of error checking to verify the blast furnace was made and not fake-placed is an correctable oversight.

**Comment by planetguy32** [comment]
The bug we're reporting is that while it SHOULDN'T be acquirable, it's available __in the creative tab__. For someone on creative, that's as acquirable as something gets.

**Comment by theunkn0wn1** [comment]
^ this
