### ISSUE TITLE
[1.12.2] Garden cloche Crash when replacing seeds

### ISSUE THREAD

**Issue by Nerucius** [BluSunrize/ImmersiveEngineering#2706]
### Description of the issue
On an activated and working garden cloche, instant crash when replacing wheat seeds by reeds, followed by server-wide timeout of all players in range of cloche. Issue is only client-side on the Render method.

### Crashlog
*Relevant:*
```
Description: Rendering Block Entity

java.lang.IllegalStateException: Zero length vector
	at org.lwjgl.util.vector.Vector.normalise(Vector.java:91)
	at blusunrize.immersiveengineering.client.ClientUtils.renderModelTESRFancy(ClientUtils.java:1831)
	at blusunrize.immersiveengineering.client.render.TileRenderBelljar.render(TileRenderBelljar.java:107)
	at blusunrize.immersiveengineering.client.render.TileRenderBelljar.func_192841_a(TileRenderBelljar.java:37)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:197)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:153)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:1008)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1781)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1606)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1377)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
Full report: [Pastebin](https://pastebin.com/iHN92WHa)

**Comment by Nerucius** [comment]
Sorry, duplicated at #2680
