### ISSUE TITLE
[1.12.2] NullPointerException with Hwyla and Fluid Router

### ISSUE THREAD

**Issue by LiskoSlayer63** [BluSunrize/ImmersiveEngineering#2766]
So, I was building some engineering stuff and needed the Fluid Router. I placed it to the ground and just looked at it and suddenly everything freezed on the server, then everyone got kicked out. It seems that the Fluid Router gives `null` information to Hwyla/Waila.

**The server was flooding errors so much that I couldn't copy text from the console but I managed to get a screenshot:**
![npe_flood](https://user-images.githubusercontent.com/10125529/35783093-b571bc78-0a0a-11e8-991a-3fe904d55f94.png)

**I tried this on single player and managed to reproduce it and I was able to copy the error from the console:**
```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
	at mcp.mobius.waila.addons.capability.HUDHandlerTank.getNBTData(HUDHandlerTank.java:61) ~[HUDHandlerTank.class:?]
	at mcp.mobius.waila.network.MessageRequestTile$Handler.lambda$onMessage$0(MessageRequestTile.java:93) ~[MessageRequestTile$Handler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source)
```

**Immersive Engineering version:** 0.12-76
**Hwyla version:** 1.8.23
**Forge version:** 14.23.1.2586
**Minecraft version:** 1.12.2

**Comment by malte0811** [comment]
Yeah, I see what's going on. I'll push a fix tomorrow.

**Comment by LiskoSlayer63** [comment]
@malte0811 I already did [this](https://github.com/LiskoSlayer63/ImmersiveEngineering/commit/106f49d60d57360d5f6343604bf6d6fe03d7872f), because I use slightly modded version of your mod. Can you say if it's right or not?

**Comment by malte0811** [comment]
It's roughly right. If you use a modified version of IE (or anything that isn't a CurseForge build) you need to tell us about it when you report the bug! It isn't relevant in this case, but even if the bug isn't caused by your changes the changes may have shifted the line numbers (and that can get very confusing).

**Comment by LiskoSlayer63** [comment]
Oh, that's a very good point, didn't even think about that. Very often the mod developers don't even bother to look at the error if they heard that it's not original version, so that's why I didn't tell anything.

Thanks for your help, though!
