### ISSUE TITLE
[0.12-77] UncheckedExecutionException when breaking feedthrough connector made from a Chisel block

### ISSUE THREAD

**Issue by CplPibald** [BluSunrize/ImmersiveEngineering#2797]
Client crash when breaking a feedthrough connector made from a Chisel block from the side.  Custom 1.12 modpack.

Repro: Make a feedthrough connector using a block from Chisel.

I can break the feedthrough if I break one of the "connector" bits.  But if I use a pickaxe on the block itself from a side face, I get the following exception:

```
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060)
	at blusunrize.immersiveengineering.client.models.smart.FeedthroughModel.func_188616_a(FeedthroughModel.java:108)
	at blusunrize.immersiveengineering.client.models.smart.ConnModelReal.func_188616_a(ConnModelReal.java:96)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.func_188644_a(SourceFile:113)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.<init>(SourceFile:100)
	at net.minecraftforge.client.ForgeHooksClient.getDamageModel(ForgeHooksClient.java:657)
```
[Full crash report](https://pastebin.com/1QURZcbM).  Found on dedicated server, but confirmed in single player.

It looks like the line in question has a try/catch protecting from `ExecutionException` but not the unchecked version which is apparently used by Chisel.

**Comment by CplPibald** [comment]
As an aside, feedthrough connectors should probably drop three items when broken - the source block and two wire connectors - since that's what was used to create them.  The current method of dropping the full feedthrough "multiblock" as a single item is unexpected.
