### ISSUE TITLE
[1.12] [0.12-78] Crash

### ISSUE THREAD

**Issue by yurioh89** [BluSunrize/ImmersiveEngineering#2829]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-0.12-78-core.jar)
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  OTGCorePlugin (OTG-Core.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.3.0-58.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 2/27/18 2:03 PM
Description: Rendering item

com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: not enough data
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060)
	at blusunrize.immersiveengineering.client.models.smart.FeedthroughModel$FeedthroughItemOverride.handleItemState(FeedthroughModel.java:190)
	at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at Reflector.call(Reflector.java:943)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:390)
	at codechicken.lib.render.item.CCRenderItem.func_184393_a(CCRenderItem.java:258)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:210)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at Reflector.callVoid(Reflector.java:636)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1454)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: not enough data
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad$Builder.build(UnpackedBakedQuad.java:175)
	at blusunrize.immersiveengineering.client.models.smart.FeedthroughModel$SpecificFeedthroughModel.getConnQuads(FeedthroughModel.java:347)
	at blusunrize.immersiveengineering.client.models.smart.FeedthroughModel$SpecificFeedthroughModel.init(FeedthroughModel.java:296)
	at blusunrize.immersiveengineering.client.models.smart.FeedthroughModel$SpecificFeedthroughModel.<init>(FeedthroughModel.java:248)
	at blusunrize.immersiveengineering.client.models.smart.FeedthroughModel$FeedthroughItemOverride.lambda$handleItemState$0(FeedthroughModel.java:191)
	at blusunrize.immersiveengineering.client.models.smart.FeedthroughModel$FeedthroughItemOverride$$Lambda$2148/242765927.call(Unknown Source)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:5065)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 29 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060)
	at blusunrize.immersiveengineering.client.models.smart.FeedthroughModel$FeedthroughItemOverride.handleItemState(FeedthroughModel.java:190)
	at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at Reflector.call(Reflector.java:943)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:390)
	at codechicken.lib.render.item.CCRenderItem.func_184393_a(CCRenderItem.java:258)

-- Item being rendered --
Details:
	Item Type: blusunrize.immersiveengineering.common.blocks.ItemBlockIEBase@38749fad
	Item Aux: 14
	Item NBT: null
	Item Foil: false
Stacktrace:
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:210)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at Reflector.callVoid(Reflector.java:636)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (564, 234). Absolute: (1129, 516)
	Screen size: Scaled: (960, 493). Absolute: (1920, 986). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['EnigmaMasterXD'/190, l='MpServer', x=196.32, y=83.00, z=485.08]]
	Chunk stats: MultiplayerChunkCache: 1658, 1658
	Level seed: 0
	Level generator: ID 10 - OTG, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (176,63,252), Chunk: (at 0,3,12 in 11,15; contains blocks 176,0,240 to 191,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 641441 game time, 2095 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 99 total; [EntitySheep['Ovelha'/256, l='MpServer', x=251.42, y=64.00, z=454.14], EntityZombie['Zumbi'/1792, l='MpServer', x=156.50, y=30.00, z=424.50], EntitySheep['Ovelha'/257, l='MpServer', x=255.55, y=64.00, z=451.72], EntityCreeper['Creeper'/2052, l='MpServer', x=161.50, y=11.00, z=522.50], EntityPig['Porco'/267, l='MpServer', x=265.30, y=73.00, z=531.49], EntityPig['Porco'/274, l='MpServer', x=145.80, y=77.00, z=503.55], EntityPlayerSP['EnigmaMasterXD'/190, l='MpServer', x=196.32, y=83.00, z=485.08], EntityCreeper['Creeper'/1814, l='MpServer', x=176.18, y=35.00, z=472.50], EntityPig['Porco'/282, l='MpServer', x=248.70, y=75.00, z=536.51], EntityPig['Porco'/284, l='MpServer', x=148.47, y=68.00, z=513.32], EntityBat['Morcego'/1826, l='MpServer', x=264.75, y=34.10, z=507.72], EntityPig['Porco'/293, l='MpServer', x=246.50, y=71.00, z=547.32], EntityPig['Porco'/294, l='MpServer', x=246.28, y=71.00, z=552.45], EntityBat['Morcego'/1831, l='MpServer', x=254.78, y=27.10, z=517.43], EntityPig['Porco'/299, l='MpServer', x=271.23, y=73.00, z=540.49], EntityPig['Porco'/300, l='MpServer', x=260.72, y=73.00, z=543.52], EntityPig['Porco'/301, l='MpServer', x=235.59, y=67.00, z=523.01], EntityPig['Porco'/302, l='MpServer', x=230.51, y=68.00, z=533.30], EntityPig['Porco'/303, l='MpServer', x=227.53, y=64.00, z=520.72], EntitySkeleton['Esqueleto'/2108, l='MpServer', x=222.50, y=35.00, z=425.50], EntitySkeleton['Esqueleto'/1609, l='MpServer', x=237.69, y=26.00, z=511.49], EntityZombieVillager['Aldeão zumbi'/1870, l='MpServer', x=243.81, y=22.00, z=564.50], EntitySheep['Ovelha'/87, l='MpServer', x=143.22, y=63.00, z=405.32], EntityMinecartChest['Carrinho com baú'/88, l='MpServer', x=143.81, y=16.00, z=428.23], EntitySheep['Ovelha'/90, l='MpServer', x=149.90, y=64.00, z=420.55], EntitySheep['Ovelha'/91, l='MpServer', x=138.55, y=65.00, z=423.22], EntityBat['Morcego'/2142, l='MpServer', x=265.00, y=35.17, z=503.52], EntityMinecartChest['Carrinho com baú'/98, l='MpServer', x=145.50, y=34.06, z=407.50], EntitySheep['Ovelha'/100, l='MpServer', x=164.09, y=69.00, z=436.48], EntityPig['Porco'/105, l='MpServer', x=163.45, y=69.00, z=435.45], EntitySkeleton['Esqueleto'/2153, l='MpServer', x=241.50, y=39.00, z=416.50], EntitySpider['Aranha'/2156, l='MpServer', x=253.30, y=31.00, z=428.32], EntityCreeper['Creeper'/2157, l='MpServer', x=253.17, y=31.00, z=429.57], EntityCreeper['Creeper'/2158, l='MpServer', x=253.49, y=31.00, z=424.79], EntityCreeper['Creeper'/1905, l='MpServer', x=267.50, y=36.00, z=499.50], EntityZombieVillager['Aldeão zumbi'/2162, l='MpServer', x=140.50, y=12.00, z=498.50], EntityPig['Porco'/115, l='MpServer', x=184.33, y=78.00, z=440.52], EntityPig['Porco'/116, l='MpServer', x=191.50, y=79.00, z=440.75], EntityCreeper['Creeper'/2164, l='MpServer', x=146.50, y=10.00, z=547.50], EntityPig['Porco'/117, l='MpServer', x=187.36, y=80.00, z=434.71], EntitySpider['Aranha'/1398, l='MpServer', x=181.50, y=23.00, z=436.50], EntityBat['Morcego'/2175, l='MpServer', x=143.51, y=43.00, z=412.17], EntityCreeper['Creeper'/2178, l='MpServer', x=149.50, y=10.00, z=548.50], EntitySkeleton['Esqueleto'/1923, l='MpServer', x=152.50, y=30.00, z=415.50], EntityCreeper['Creeper'/2179, l='MpServer', x=149.50, y=10.00, z=550.50], EntityPig['Porco'/132, l='MpServer', x=213.77, y=82.00, z=412.70], EntitySkeleton['Esqueleto'/1924, l='MpServer', x=153.50, y=30.00, z=415.50], EntityPig['Porco'/134, l='MpServer', x=209.55, y=79.00, z=431.45], EntityPig['Porco'/135, l='MpServer', x=218.55, y=77.00, z=423.45], EntityPig['Porco'/136, l='MpServer', x=214.75, y=77.00, z=431.46], EntitySheep['Ovelha'/137, l='MpServer', x=214.73, y=77.00, z=432.49], EntityBat['Morcego'/2186, l='MpServer', x=189.45, y=27.10, z=415.40], EntityPig['Porco'/139, l='MpServer', x=210.50, y=80.00, z=425.97], EntityBat['Morcego'/2187, l='MpServer', x=193.62, y=25.58, z=413.69], EntityPig['Porco'/140, l='MpServer', x=219.45, y=71.00, z=435.84], EntityPig['Porco'/141, l='MpServer', x=210.45, y=77.00, z=437.44], EntityCreeper['Creeper'/2192, l='MpServer', x=190.81, y=8.00, z=556.18], EntityCreeper['Creeper'/2193, l='MpServer', x=192.58, y=8.00, z=555.66], EntitySkeleton['Esqueleto'/2195, l='MpServer', x=243.50, y=43.00, z=536.50], EntityPig['Porco'/151, l='MpServer', x=230.55, y=66.00, z=442.55], EntityZombie['Zumbi'/2199, l='MpServer', x=144.48, y=54.00, z=421.71], EntityMinecartChest['Carrinho com baú'/156, l='MpServer', x=253.50, y=28.06, z=436.50], EntityCreeper['Creeper'/1948, l='MpServer', x=121.60, y=47.00, z=409.21], EntityCreeper['Creeper'/2212, l='MpServer', x=269.50, y=45.00, z=549.50], EntityChicken['Galinha'/165, l='MpServer', x=270.52, y=67.00, z=412.85], EntityMinecartChest['Carrinho com baú'/166, l='MpServer', x=266.50, y=30.06, z=437.50], EntitySkeleton['Esqueleto'/2214, l='MpServer', x=143.50, y=12.00, z=499.50], EntitySheep['Ovelha'/167, l='MpServer', x=269.51, y=63.00, z=446.26], EntityZombieVillager['Aldeão zumbi'/2215, l='MpServer', x=208.50, y=55.00, z=456.50], EntitySheep['Ovelha'/168, l='MpServer', x=266.51, y=65.00, z=437.81], EntityZombieVillager['Aldeão zumbi'/2216, l='MpServer', x=208.50, y=55.00, z=461.50], EntityZombie['Zumbi'/2222, l='MpServer', x=252.50, y=33.00, z=508.50], EntityZombie['Zumbi'/2230, l='MpServer', x=143.50, y=54.00, z=423.50], EntityZombieVillager['Aldeão zumbi'/2231, l='MpServer', x=187.50, y=52.00, z=475.50], EntityCreeper['Creeper'/2232, l='MpServer', x=220.47, y=64.00, z=439.22], EntityCreeper['Creeper'/2233, l='MpServer', x=187.50, y=55.00, z=451.50], EntityCreeper['Creeper'/2238, l='MpServer', x=188.50, y=55.00, z=451.50], EntityCreeper['Creeper'/2246, l='MpServer', x=229.38, y=54.18, z=499.50], EntityBat['Morcego'/1992, l='MpServer', x=254.88, y=35.10, z=442.48], EntitySkeleton['Esqueleto'/2250, l='MpServer', x=233.89, y=56.00, z=500.50], EntityBat['Morcego'/1995, l='MpServer', x=225.09, y=47.19, z=469.42], EntityBat['Morcego'/204, l='MpServer', x=174.79, y=64.10, z=458.59], EntityZombie['Zumbi'/2253, l='MpServer', x=249.50, y=33.00, z=508.50], EntityCreeper['Creeper'/2257, l='MpServer', x=177.50, y=22.00, z=408.50], EntityPig['Porco'/210, l='MpServer', x=229.51, y=69.00, z=537.22], EntityCreeper['Creeper'/2002, l='MpServer', x=187.50, y=40.00, z=507.50], EntityCreeper['Creeper'/2262, l='MpServer', x=126.50, y=10.00, z=553.50], EntitySpider['Aranha'/2263, l='MpServer', x=233.50, y=22.00, z=549.50], EntityPig['Porco'/216, l='MpServer', x=263.51, y=63.00, z=455.71], EntityZombie['Zumbi'/2265, l='MpServer', x=173.43, y=57.00, z=512.59], EntitySpider['Aranha'/2015, l='MpServer', x=134.50, y=34.00, z=409.50], EntityZombie['Zumbi'/2274, l='MpServer', x=137.50, y=30.00, z=407.50], EntityCreeper['Creeper'/1764, l='MpServer', x=151.50, y=30.00, z=457.50], EntityPig['Porco'/232, l='MpServer', x=118.49, y=67.00, z=560.30], EntityBabySkeleton['Esqueleto Bebê'/2025, l='MpServer', x=164.56, y=8.00, z=522.10], EntityPig['Porco'/246, l='MpServer', x=254.73, y=70.00, z=555.46], EntityBat['Morcego'/2042, l='MpServer', x=139.13, y=40.10, z=432.57], EntityPig['Porco'/251, l='MpServer', x=173.28, y=74.00, z=534.45], EntityPig['Porco'/252, l='MpServer', x=149.55, y=67.00, z=545.26]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by malte0811** [comment]
1. Put crashlogs on gist or pastebin, not directly in the issue.
2. That crashlog isn't complete.
3. Are you using Optifine?

**Comment by yurioh89** [comment]
Are you using Optifine?
R: Yes

**Comment by BSKCorp** [comment]
Same Issue
[crash-2018-02-28_13.59.45-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1768631/crash-2018-02-28_13.59.45-client.txt)

- Varified it is a Optfine fine Issue. Disabled Optifine and no crash. Hope this helps.

**Comment by BluSunrize** [comment]
Excellent. Optifine issues are not supported.
