### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by rx80** [BluSunrize/ImmersiveEngineering#2873]
Not sure if this is a fault of ImmersiveEngineering, but exception is triggered in your code. Server crashes as startup:

```
WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-0.12-78-core.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 3/12/18 9:26 AM
Description: Exception in server tick loop

java.lang.ClassCastException: mekanism.common.tile.TileEntityRotaryCondensentrator cannot be cast to blusunrize.
immersiveengineering.common.blocks.metal.TileEntityLadder
        at blusunrize.immersiveengineering.common.blocks.metal.BlockMetalLadder.func_189540_a(BlockMetalLadder.j
ava:142)
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.j
ava:481)
        at ic2.core.energy.grid.EnergyNetLocal.onTickStart(EnergyNetLocal.java:163)
        at ic2.core.energy.grid.EventHandler.onWorldTick(EventHandler.java:61)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_279_EventHandler_onWorldTick_WorldTickEven
t.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:286)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:750)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
        at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- System Details --
Details:
        Minecraft Version: 1.12.2
        Operating System: Linux (amd64) version 4.15.7-gentoo-r1
        Java Version: 1.8.0_162, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 566991840 bytes (540 MB) / 2130051072 bytes (2031 MB) up to 2130051072 bytes (2031 MB)
        JVM Flags: 7 total; -Xmx2G -Xms2G -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=2 -XX:+AggressiveOpts
        IntCache: cache: 0, tcache: 6, allocated: 13, tallocated: 96
        FML: MCP 9.42 Powered by Forge 14.23.2.2625 64 mods loaded, 64 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored


```

**Comment by BluSunrize** [comment]
Please read the contribution guidelines next time.
This issue is already being adressed here:
https://github.com/BluSunrize/ImmersiveEngineering/issues/2844
