### ISSUE TITLE
Coremods Are Present

### ISSUE THREAD

**Issue by MaxzZed** [BluSunrize/ImmersiveEngineering#2936]
I keep getting this crash and I don't know what to do. Anyone else out there got a fix?
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-0.12-80-core.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 4/11/18 3:54 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thermal Expansion (thermalexpansion)
Caused by: java.lang.NoClassDefFoundError: cofh/thermalexpansion/plugins/top/PluginTOP
	at cofh.thermalexpansion.init.TEPlugins.preInit(TEPlugins.java:18)
	at cofh.thermalexpansion.ThermalExpansion.preInit(ThermalExpansion.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: cofh.thermalexpansion.plugins.top.PluginTOP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more
Caused by: java.lang.NoClassDefFoundError: cofh/core/util/ModPlugin
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 44 more
Caused by: java.lang.ClassNotFoundException: cofh.core.util.ModPlugin
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 48 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.13.0-37-generic
	Java Version: 1.8.0_162, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 171165048 bytes (163 MB) / 471519232 bytes (449 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 5 total; -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 33 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version      | Source                                           | Signature                                |
	|:----- |:--------------------- |:------------ |:------------------------------------------------ |:---------------------------------------- |
	| UCH   | minecraft             | 1.12.2       | minecraft.jar                                    | None                                     |
	| UCH   | mcp                   | 9.42         | minecraft.jar                                    | None                                     |
	| UCH   | FML                   | 8.0.99.99    | forge-1.12.2-14.23.2.2611.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                 | 14.23.2.2611 | forge-1.12.2-14.23.2.2611.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | mercurius_updater     | 1.0          | MercuriusUpdater-1.12.2.jar                      | None                                     |
	| UCH   | appliedenergistics2   | rv5-stable-8 | appliedenergistics2-rv5-stable-8.jar             | None                                     |
	| UCH   | buildcraftlib         | 7.99.15      | buildcraft-7.99.15.jar                           | None                                     |
	| UCH   | buildcraftcore        | 7.99.15      | buildcraft-7.99.15.jar                           | None                                     |
	| UCH   | buildcraftbuilders    | 7.99.15      | buildcraft-7.99.15.jar                           | None                                     |
	| UCH   | buildcraftenergy      | 7.99.15      | buildcraft-7.99.15.jar                           | None                                     |
	| UCH   | buildcraftfactory     | 7.99.15      | buildcraft-7.99.15.jar                           | None                                     |
	| UCH   | buildcraftrobotics    | 7.99.15      | buildcraft-7.99.15.jar                           | None                                     |
	| UCH   | buildcraftsilicon     | 7.99.15      | buildcraft-7.99.15.jar                           | None                                     |
	| UCH   | buildcrafttransport   | 7.99.15      | buildcraft-7.99.15.jar                           | None                                     |
	| UCH   | codechickenlib        | 3.1.6.339    | CodeChickenLib-1.12.2-3.1.6.339-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | redstoneflux          | 2.0.1        | RedstoneFlux-1.12-2.0.1.2-universal.jar          | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCH   | cofhcore              | 4.3.11       | CoFHCore-1.12.2-4.3.11.6-universal.jar           | None                                     |
	| UCH   | cofhworld             | 1.1.1        | CoFHWorld-1.12.2-1.1.1.12-universal.jar          | None                                     |
	| UCH   | forgemultipartcbe     | 2.4.0.55     | ForgeMultipart-1.12.2-2.4.0.55-universal (1).jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | microblockcbe         | 2.4.0.55     | ForgeMultipart-1.12.2-2.4.0.55-universal (1).jar | None                                     |
	| UCH   | minecraftmultipartcbe | 2.4.0.55     | ForgeMultipart-1.12.2-2.4.0.55-universal (1).jar | None                                     |
	| UCH   | ichunutil             | 7.1.4        | iChunUtil-1.12.2-7.1.4.jar                       | None                                     |
	| UCH   | jei                   | 4.8.5.147    | jei_1.12.2-4.8.5.147.jar                         | None                                     |
	| UCH   | immersiveengineering  | 0.12-80      | ImmersiveEngineering-0.12-80 (1).jar             | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCH   | journeymap            | 1.12.2-5.5.2 | JourneyMap-1.12.2.jar                            | None                                     |
	| UCH   | morph                 | 7.1.0        | Morphing-Mod-1.12.2.jar                          | None                                     |
	| UCH   | nei                   | 2.4.1        | NotEnoughItems-1.12.2-2.4.1.233-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | thermalfoundation     | 2.3.11       | ThermalFoundation-1.12.2-2.3.11.8-universal.jar  | None                                     |
	| UCE   | thermalexpansion      | 5.3.10       | ThermalExpansion-1.12.2-5.3.10.15-universal.jar  | None                                     |
	| UCE   | simplyjetpacks        | 2.2.1.20     | Simply-Jetpacks-2-Mod-1.11.2.jar                 | None                                     |
	| UCH   | thermaldynamics       | 2.3.11       | ThermalDynamics-1.12.2-2.3.11.7-universal.jar    | None                                     |
	| UCH   | wearablebackpacks     | 3.1.0        | Wearable-Backpacks-Mod-1.12.2.jar                | None                                     |
	| UCH   | wrcbe                 | 2.3.0        | WR-CBE-1.12.2-2.3.0.27-universal.jar             | f1850c39b2516232a2108a7bd84d1cb5df93b261 |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-0.12-80-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
	GL info: ' Vendor: 'X.Org' Version: '3.0 Mesa 17.2.8' Renderer: 'AMD KAVERI (DRM 2.50.0 / 4.13.0-37-generic, LLVM 5.0.0)'
	AE2 Version: stable rv5-stable-8 for Forge 14.23.1.2554

**Comment by PrincessRTFM** [comment]
There's a problem in Thermal Expansion. Part (or all) of COFH Core appears to be missing. Is it installed? If so, try redownloading it. If not, there's your problem.
