### ISSUE TITLE
gregtech compatibility causing console spam

### ISSUE THREAD

**Issue by LemADEC** [BluSunrize/ImmersiveEngineering#306]
With ImmersiveEngineering-0.5.2.jar and gregtech_1.7.10-6.00.50.jar, after connecting both mods, console is getting spammed with this:
```
[19:28:37 WARN]: java.lang.ClassNotFoundException: gregtech.api.interfaces.tileentity.IEnergyConnected
[19:28:37 WARN]:        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[19:28:37 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[19:28:37 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[19:28:37 WARN]:        at java.lang.Class.forName0(Native Method)
[19:28:37 WARN]:        at java.lang.Class.forName(Class.java:264)
[19:28:37 WARN]:        at blusunrize.immersiveengineering.common.util.compat.GregTechHelper.gregtech_isEnergyConnected(GregTechHelper.java:49)
[19:28:37 WARN]:        at blusunrize.immersiveengineering.common.blocks.metal.TileEntityConnectorLV.outputEnergy(TileEntityConnectorLV.java:97)
[19:28:37 WARN]:        at blusunrize.immersiveengineering.common.blocks.metal.TileEntityConnectorLV.transferEnergy(TileEntityConnectorLV.java:191)
[19:28:37 WARN]:        at blusunrize.immersiveengineering.common.blocks.metal.TileEntityConnectorLV.receiveEnergy(TileEntityConnectorLV.java:160)
[19:28:37 WARN]:        at blusunrize.immersiveengineering.common.blocks.metal.TileEntityCapacitorLV.transferEnergy(TileEntityCapacitorLV.java:96)
[19:28:37 WARN]:        at blusunrize.immersiveengineering.common.blocks.metal.TileEntityCapacitorLV.func_145845_h(TileEntityCapacitorLV.java:73)
[19:28:37 WARN]:        at net.minecraft.world.World.func_72939_s(World.java:2513)
[19:28:37 WARN]:        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
[19:28:37 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
[19:28:37 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[19:28:37 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[19:28:37 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[19:28:37 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

Looks like the mod is using an old gregtech api (gregtech.api vs gregapi).

**Comment by BluSunrize** [comment]
I am building for GT5 not GT6 and I'm not using the API since Greg does not want people to use the API. Until GT6 is "done" I wont make the switch.

**Comment by LemADEC** [comment]
Looks like there's a misunderstanding here. It's not specific to Gregtech, it's just good design practice: no mods should ever distribute the API from another mod, it should only link to it. 
FML comes with attributes to delete methods and interfaces for missing mods, so your links are dynmically removed when the game starts. Your code will be easier to maintain, faster to run without reflexion, check cpw.mods.fml.common.Optional.

**Comment by BluSunrize** [comment]
Have you looked at my mod? I don't package Gregtech's API. I reflect into it.

**Comment by LemADEC** [comment]
Yes, you reflect into in real time, which is bad, you should cache it at boot time, but that's not the point.
I was answering about you saying "Greg does not want people to use the API". It's not about "using", it's about delivering it inside your mod.

**Comment by BluSunrize** [comment]
that does not change the fact that GT6 probably uses different declarations, so you're SoL in that regard anyway.

**Comment by LemADEC** [comment]
yes, I'm still stuck with GT5 anyway.
