### ISSUE TITLE
Crash with 1.12.2 forge 2718+

### ISSUE THREAD

**Issue by ClockwerkKaiser** [BluSunrize/ImmersiveEngineering#3071]
I'm getting this crash whenever I try to access the inventory of any storage crates. 

```
java.lang.ClassCastException: it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap cannot be cast to gnu.trove.map.hash.TIntObjectHashMap
    at team.chisel.ctm.client.model.ModelUtil.lambda$getMesh$0(ModelUtil.java:51)
    at java.util.Optional.map(Unknown Source)
    at team.chisel.ctm.client.model.ModelUtil.getMesh(ModelUtil.java:51)
    at team.chisel.ctm.client.model.AbstractCTMBakedModel$Overrides.handleItemState(AbstractCTMBakedModel.java:84)
    at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at Reflector.call(Reflector.java:955)
    at net.minecraft.client.renderer.RenderItem.getItemModelWithOverrides(RenderItem.java:398)
    at codechicken.lib.render.item.CCRenderItem.getItemModelWithOverrides(CCRenderItem.java:258)
    at codechicken.lib.render.item.CCRenderItem.renderItemAndEffectIntoGUI(CCRenderItem.java:210)
    at net.minecraft.client.gui.inventory.GuiContainer.drawSlot(GuiContainer.java:265)
    at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:98)
    at blusunrize.immersiveengineering.client.gui.GuiIEContainerBase.drawScreen(GuiIEContainerBase.java:28)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
    at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at Reflector.callVoid(Reflector.java:648)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1456)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1117)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3938)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

I updated forge earlier, and tested a few versions. It's seems to happen with forge version 14.23.4.2718 and up. I'm assuming it has something to do with the changes below. 

```
Build 1.12.2-14.23.4.2718:
	tterrag1098: Fix MC-234: Z-fighting when viewing break animation side-on (#4928)
	latvianmodder: Added Item#readNBTShareTag(ItemStack, NBTTagCompound) (#4932)
	bs2609: Switch from trove to fastutil collections (#4933)
	UnRealDinnerbone: Add Farmland Trample Event  (#4895)
```

Not sure if this is on IE or CTM, so I'll post this to both.

**Comment by PanSzelescik** [comment]
https://github.com/Chisel-Team/ConnectedTexturesMod/issues/63

**Comment by bothie** [comment]
```at blusunrize.immersiveengineering.client.gui.GuiIEContainerBase.drawScreen(GuiIEContainerBase.java:28)```

This doesn't point to immersive engineering?

The reporter said: "any storage crates"

Forge 2718 is known to cause many mods to fail, don't expect to be an exception.

Here, I tried to get a steel scaffolding out of my ME system (Forge = 14.23.4.2747):

```
Time: 8/4/18 11:08 AM
Description: Rendering entity in world

java.lang.ClassCastException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
   at net.minecraft.client.renderer.entity.RenderManager.func_188391_a
      (RenderManager.java:419)

-- Entity being rendered --
Details:
   Entity Type: null (appeng.entity.EntityFloatingItem)
   Entity ID: 5881600
   Entity Name: item.tile.immersiveengineering.metal_decoration1.steel_scaffolding_0
   Entity's Exact location: -77.50, 63.50, 214.50
   Entity's Block location: World: (-78,63,214),
      Chunk: (at 2,3,6 in -5,13; contains blocks -80,0,208 to -65,255,223),
      Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
   Entity's Momentum: 0.00, 0.00, 0.00
   Entity's Passengers: []
   Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
   at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:419)
   at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
   at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
   at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
   at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
   at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
   at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
   at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
   at net.minecraft.client.main.Main.main(SourceFile:123)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:498)
   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Renderer details --
Details:
   Assigned renderer: appeng.entity.RenderFloatingItem@2bc9b820
   Location: 3.65,-6.50,1.89 - World: (3,-7,1),
      Chunk: (at 3,-1,1 in 0,0; contains blocks 0,0,0 to 15,255,15),
      Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
   Rotation: 0.0
      Delta: 0.10002661
```

**Comment by BluSunrize** [comment]
The initial stacktrace crashed in chisel, after being called by inserted codechicken code. IE is responsible for the draw call, but not the crash.

The crashlog you supplied (which, btw., please use pastebin or gist) crashes in a default render function, and while the item is an IE scaffold, the actual crash appears to be caused by `appeng.entity.EntityFloatingItem` implying that Applied Energistics caused this.

Lastly, please don't necropost unless you have the same issue, yours is clearly quite different.
