### ISSUE TITLE
'rendering item error' = CTM and Forge interactions causing CTDs when using IE

### ISSUE THREAD

**Issue by Tingcat** [BluSunrize/ImmersiveEngineering#3073]
### Resolved the issue myself, but I thought you might want to know anyway
Okay so. Did some digging whilst writing all this up, and I know this isn't actually an IE issue. But, I thought it might be important to put the issue up here anyway given that I had to play detective with little to know knowledge of how to actually code and that there might be others who probably don't want to spend two hours of their life running minimal instances. I also can't say, but I suspect it might have something to do with some other issues floating around, so I'll reference this issue on those.

To summarize, it's a preexisting issue with CTM having some weird interactions with Forge right now. [Here's a link to the relevant issue on the CTM github.](/Chisel-Team/ConnectedTexturesMod/issues/63) So to solve this, you have to downgrade to Forge-14.23.4.2717 until CTM pushes an update.

### What I was originally going to say:
Excuse me if this isn't reported correctly; I don't really code or anything I'm probably doing it wrong.

Attempted to see what recipes a bucket of water is used in by right-clicking (can also press 'u') on the item in JEI and it shut down the server and crashed to desktop, giving me a 'rendering item' error. I was able to reproduce this multiple times. I'm definitely not using Optifine, and there don't seem to be any other issues open about this kind of error that have definitive solutions.

I checked the crash reports and it seems to be something to do with Immersive Engineering? It feels beyond my nonexistent experience with coding and I can kinda ignore it for the time being, but it might be useful to know?

```
-- Item being rendered --
Details:
    Item Type: blusunrize.immersiveengineering.common.blocks.ItemBlockIEBase@cd6f916
    Item Aux: 7
    Item NBT: null
    Item Foil: false
```

[Full Crash Log Here](https://pastebin.com/faptuVuW)

Tested and reproducible using only IE 0.12-82, JEI 1.12.2-4.10.0.198, Forge 14.23.4.2725 and CTM MC1.12-0.3.0.15.

**Comment by stclaus4** [comment]
i have the same deal

-- Head --
Thread: Client thread
Stacktrace:
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:222)

-- Item being rendered --
Details:
	Item Type: blusunrize.immersiveengineering.common.blocks.ItemBlockIEBase@5aed54c5
	Item Aux: 6
	Item NBT: null
	Item Foil: false
Stacktrace:
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:222)
	at codechicken.lib.render.item.CCRenderItem.func_180450_b(CCRenderItem.java:202)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:922)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:758)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
 
https://pastebin.com/jJRC6utS

**Comment by BluSunrize** [comment]
CTM fixed this, apparently.
