### ISSUE TITLE
Tesselating block in world

### ISSUE THREAD

**Issue by therodet** [BluSunrize/ImmersiveEngineering#3101]
Modern Skyblock 3; Was attempting to dismantle a solar tower from Immerisive Tech, and the game crashed. Now I get the crash below every time I try to re-enter the world (SSP).
`
Time: 7/14/18 4:39 PM
Description: Tesselating block in world

java.lang.NullPointerException: Tesselating block in world
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityFluidPipe.getConnectionByte(TileEntityFluidPipe.java:417)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityFluidPipe.getOBJState(TileEntityFluidPipe.java:636)
	at blusunrize.immersiveengineering.common.blocks.BlockIETileProvider.getExtendedState(BlockIETileProvider.java:346)
	at blusunrize.immersiveengineering.common.blocks.metal.BlockMetalDevice1.getExtendedState(BlockMetalDevice1.java:113)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:79)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:69)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Unknown Source)
`

**Comment by BluSunrize** [comment]
Update IE

And read the issue template next time.
