### ISSUE TITLE
[crash] crusher recipe 

### ISSUE THREAD

**Issue by ImelchorI** [BluSunrize/ImmersiveEngineering#313]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 14.08.15 00:16
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: blusunrize/immersiveengineering/api/tool/CrusherRecipe
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: blusunrize/immersiveengineering/api/tool/CrusherRecipe
	at ganymedes01.aobd.recipes.modules.ImmersiveEngineering.initOre(ImmersiveEngineering.java:16)
	at ganymedes01.aobd.recipes.RecipesModule.init(RecipesModule.java:37)
	at ganymedes01.aobd.recipes.ModulesHandler.init(ModulesHandler.java:31)
	at ganymedes01.aobd.AOBD.init(AOBD.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	... 10 more
Caused by: java.lang.ClassNotFoundException: blusunrize.immersiveengineering.api.tool.CrusherRecipe
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 40 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 235159288 bytes (224 MB) / 591814656 bytes (564 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 85 mods loaded, 85 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHI	Forge{10.13.4.1492} [Minecraft Forge] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHI	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) 
	UCHI	NotEnoughItems{1.0.4.94} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.94-universal.jar) 
	UCHI	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCHI	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) 
	UCHI	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHI	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar) 
	UCHI	DamageIndicatorsMod{3.2.0} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.0.jar) 
	UCHI	StartingInventory{1.7.10.r03} [StartingInventory] ([1.7.10]StartingInventory-universal-1.7.10.r03.jar) 
	UCHI	StatusEffectHUD{1.27} [StatusEffectHUD] ([1.7.10]StatusEffectHUD-client-1.27.jar) 
	UCHI	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHI	antiqueatlas{4.2.2-1.7.10} [Antique Atlas] (antiqueatlas-4.2.2-1.7.10.jar) 
	UCHI	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) 
	UCHI	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHI	Artifacts{1.1.1} [Artifacts] (Artifacts-1.1.1.jar) 
	UCHI	asielib{0.3.8} [asielib] (AsieLib-1.7.10-0.3.8.jar) 
	UCHI	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHI	Waila{1.5.8} [Waila] (Waila-1.5.8a_1.7.10.jar) 
	UCHI	Automagy{0.26.3} [Automagy] (Automagy-1.7.10-0.26.3.jar) 
	UCHI	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UCHI	BetterFoliage{1.0.4} [Better Foliage] (BetterFoliage-mc1.7-1.0.4.jar) 
	UCHI	BiblioCraft{1.9.1} [BiblioCraft] (BiblioCraft[v1.9.1][MC1.7.10].jar) 
	UCHI	BiblioWoodsHighlands{1.4} [BiblioWoods Highlands Edition] (BiblioWoods[Highlands][v1.4].jar) 
	UCHI	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHI	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UCHI	BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.5].jar) 
	UCHI	Botania{r1.7-208} [Botania] (Botania r1.7-208.jar) 
	UCHI	CarpentersBlocks{3.3.7 DEV} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 DEV - MC 1.7.10.jar) 
	UCHI	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCHI	ForgeMultipart{1.1.1.324} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.324-universal.jar) 
	UCHI	TwilightForest{2.3.5} [The Twilight Forest] (twilightforest-1.7.10-2.3.5.jar) 
	UCHI	chisel{2.3.9.36} [Chisel 2] (Chisel2-2.3.9.36.jar) 
	UCHI	DeadlyWorld{1.0.2} [Deadly World] (DeadlyWorld-1.7.10-1.0.2.jar) 
	UCHI	EnderZoo{1.7.10-1.0.9.18} [Ender Zoo] (EnderZoo-1.7.10-1.0.9.18.jar) 
	UCHI	ExtraUtilities{1.2.5} [Extra Utilities] (extrautilities-1.2.5.jar) 
	UCHI	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHI	Steamcraft{0.28.7} [Flaxbeard's Steam Power] (Flaxbeard'sSteamPower-1.7.10-0.28.7.jar) 
	UCHI	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-440.jar) 
	UCHI	ForbiddenMagic{1.7.10-0.562} [Forbidden Magic] (Forbidden Magic-1.7.10-0.562.jar) 
	UCHI	McMultipart{1.1.1.324} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.324-universal.jar) 
	UCHI	fossil{1.7.10 Build 7.2.1} [Fossils and Archeology Revival] (Fossils_Archeology_Revival-1.7.10_Build-7.2.1.jar) 
	UCHI	funkylocomotion{1.0} [Funky Locomotion] (funky-locomotion-1.7.10-beta-5c.jar) 
	UCHI	HardcoreEnderExpansion{1.8.1} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.1.jar) 
	UCHI	HopperDuctMod{1.3.2} [Hopper Ducts] (hopperductmod-1.7.10-1.3.2.jar) 
	UCHI	ImmersiveEngineering{0.5.2} [Immersive Engineering] (ImmersiveEngineering-0.5.2.jar) 
	UCHI	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
	UCHI	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHI	ironchestminecarts{1.0.3} [Iron Chest Minecarts] (IronChestMinecarts-1.0.3.jar) 
	UCHI	JABBA{1.1.4} [JABBA] (Jabba-1.1.4_1.7.10.jar) 
	UCHI	LavaMonsters{2.2.1} [Lava Monsters] (LavaMonsters-1.7.10-2.2.1.jar) 
	UCHI	malisiscore{1.7.10-0.12.5} [MalisisCore] (malisiscore-1.7.10-0.12.5.jar) 
	UCHI	malisisdoors{1.7.10-1.9.3} [Malisis' Doors] (malisisdoors-1.7.10-1.9.3.jar) 
	UCHI	MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C.jar) 
	UCHI	modtweaker2{0.7} [Mod Tweaker 2] (ModTweaker2-1.7.X-0.7.1.jar) 
	UCHI	MutantCreatures{1.4.8} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.8.jar) 
	UCHI	NEIAddons{1.12.5.17} [NEI Addons] (neiaddons-mc1710-1.12.5.17.jar) 
	UCHI	NEIAddons|Botany{1.12.5.17} [NEI Addons: Botany] (neiaddons-mc1710-1.12.5.17.jar) 
	UCHI	NEIAddons|Forestry{1.12.5.17} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.5.17.jar) 
	UCHI	NEIAddons|CraftingTables{1.12.5.17} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.5.17.jar) 
	UCHI	NEIAddons|ExNihilo{1.12.5.17} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.5.17.jar) 
	UCHI	neiintegration{1.0.7} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.7.jar) 
	UCHI	Oceancraft{1.4.1} [Oceancraft] (Oceancraft-1.4.1.jar) 
	UCHI	onlysilver{1.9.4-1.7.2} [OnlySilver] (OnlySilver-1.9.4-1.7.2.jar) 
	UCHI	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6.jar) 
	UCHI	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3.jar) 
	UCHI	primitivemobs{1.0} [Primitive Mobs] (primitivemobs-1.0c-1.7.10.jar) 
	UCHI	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
	UCHI	SpecialMobs{3.1.1} [Special Mobs] (SpecialMobs-1.7.10-3.1.1.jar) 
	UCHI	SpiceOfLife{1.2.3} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.2.3.jar) 
	UCHI	statues{2.1.4} [Statues] (statues-1.7.10-2.1.4.jar) 
	UCHI	TaintedMagic{1.1.5.4} [Tainted Magic] (TaintedMagic-1.1.5.4.jar) 
	UCHI	testdummy{1.0} [MmmMmmMmmMmm] (test dummy.jar) 
	UCHI	ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects] (ThaumcraftMobAspects-1.7.2-2A.jar) 
	UCHI	thaumcraftneiplugin{1.7.10-1.7} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7.jar) 
	UCHI	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-53.jar) 
	UCHI	ThaumicHorizons{1.1.5} [Thaumic Horizons] (thaumichorizons-1.7.10-1.1.6.jar) 
	UCHI	Translocator{1.1.1.14} [Translocator] (Translocator-1.7.10-1.1.1.14-universal.jar) 
	UCHI	TravellersGear{1.16.4} [Traveller's Gear] (TravellersGear-1.7.10-1.16.4.jar) 
	UCHI	UtilityMobs{3.1.1} [Utility Mobs] (UtilityMobs-1.7.10-3.1.1.jar) 
	UCHI	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) 
	UCHI	libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) 
	UCHE	aobd{2.7.1} [Another One Bites The Dust] (AOBD-2.7.1.jar) 
	UCHI	ForgeMicroblock{1.1.1.324} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.324-universal.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.4.0 NVIDIA 344.48' Renderer: 'GeForce GT 630/PCIe/SSE2'
	OpenModsLib crash transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Mantle Environment: Environment healthy.
	Stencil buffer state: Function set: GL30, pool: internal, bits: 8

**Comment by theunkn0wn1** [comment]
@ImelchorI 
please refer to #309 or #293  or...

@BluSunrize we need an FAQ or something.....

**Comment by BluSunrize** [comment]
Outdated AOBD

@theunkn0wn1 Meh. People wouldn't read it anyway, I had that experience with Witching Gadgets

**Comment by ImelchorI** [comment]
oops, thank you. sorry, but this isnt really a well layed out platform for these kind of things. do you guys have a thread opened in the minecraft forum?

**Comment by BluSunrize** [comment]
Nope.
I kinda gave up on MCF because their editor is pretty terrible, and I never get good reports there (reports with errorlogs and stuff).
Most of these tiny errors are solveable in 5 minutes, and if people just take a look at past github issues (you for instance will know that now =P) it's not too bad to handle
