### ISSUE TITLE
My item wont show up in game with the png in the right place and all files working

### ISSUE THREAD

**Issue by iiwdc2001** [BluSunrize/ImmersiveEngineering#3193]
2018-08-31 16:36:22,309 main WARN Disabling terminal, you're running in an unsupported environment.
[16:36:22] [main/INFO] [GradleStart]: Extra: []
[16:36:22] [main/INFO] [GradleStart]: Running with arguments: [--userProperties, {}, --assetsDir, C:/Users/warne/.gradle/caches/minecraft/assets, --assetIndex, 1.12, --accessToken{REDACTED}, --version, 1.12.2, --tweakClass, net.minecraftforge.fml.common.launcher.FMLTweaker, --tweakClass, net.minecraftforge.gradle.tweakers.CoremodTweaker]
[16:36:22] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:36:22] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:36:22] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.CoremodTweaker
[16:36:22] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[16:36:22] [main/INFO] [FML]: Forge Mod Loader version 14.23.4.2705 for Minecraft 1.12.2 loading
[16:36:22] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_152, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_152
[16:36:22] [main/ERROR] [FML]: Apache Maven library folder was not in the format expected. Using default libraries directory.
[16:36:22] [main/ERROR] [FML]: Full: C:\Users\warne\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-artifact\3.5.3\7dc72b6d6d8a6dced3d294ed54c2cc3515ade9f4\maven-artifact-3.5.3.jar
[16:36:22] [main/ERROR] [FML]: Trimmed: c:/users/warne/.gradle/caches/modules-2/files-2.1/org.apache.maven/maven-artifact/3.5.3/
[16:36:22] [main/INFO] [FML]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[16:36:22] [main/INFO] [FML]: Ignoring missing certificate for coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin), we are in deobf and it's a forge core plugin
[16:36:22] [main/INFO] [FML]: Ignoring missing certificate for coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin), we are in deobf and it's a forge core plugin
[16:36:22] [main/INFO] [FML]: Searching C:\Users\warne\OneDrive\Desktop\pls\GUI\run\.\mods for mods
[16:36:22] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.CoremodTweaker
[16:36:22] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.fml.relauncher.FMLCorePlugin
[16:36:22] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.classloading.FMLForgePlugin
[16:36:22] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:36:22] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:36:22] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[16:36:22] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:36:22] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:36:22] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:36:26] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[16:36:26] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:36:26] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:36:27] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[16:36:27] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[16:36:27] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[16:36:27] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[16:36:28] [main/INFO] [net.minecraft.client.Minecraft]: Setting user: Player495
[16:36:34] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: lastServer:
[16:36:34] [main/INFO] [net.minecraft.client.Minecraft]: LWJGL Version: 2.9.4
[16:36:36] [main/INFO] [FML]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_152, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 782018472 bytes (745 MB) / 1037959168 bytes (989 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.01' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
[16:36:36] [main/INFO] [FML]: MinecraftForge v14.23.4.2705 Initialized
[16:36:36] [main/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[16:36:36] [main/INFO] [FML]: Replaced 1036 ore ingredients
[16:36:36] [main/INFO] [FML]: Searching C:\Users\warne\OneDrive\Desktop\pls\GUI\run\.\mods for mods
[16:36:37] [main/INFO] [FML]: Forge Mod Loader has identified 5 mods to load
[16:36:38] [Thread-3/INFO] [FML]: Using sync timing. 200 frames of Display.update took 113859484 nanos
[16:36:38] [main/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, r] at CLIENT
[16:36:38] [main/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, r] at SERVER
[16:36:39] [main/INFO] [net.minecraft.client.resources.SimpleReloadableResourceManager]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:REF
[16:36:39] [main/INFO] [FML]: Processing ObjectHolder annotations
[16:36:39] [main/INFO] [FML]: Found 1168 ObjectHolder annotations
[16:36:39] [main/INFO] [FML]: Identifying ItemStackHolder annotations
[16:36:39] [main/INFO] [FML]: Found 0 ItemStackHolder annotations
[16:36:40] [main/INFO] [FML]: Configured a dormant chunk cache size of 0
[16:36:40] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[16:36:40] [main/INFO] [FML]: Applying holder lookups
[16:36:40] [main/INFO] [FML]: Holder lookups applied
[16:36:40] [main/INFO] [FML]: Applying holder lookups
[16:36:40] [main/INFO] [FML]: Holder lookups applied
[16:36:40] [main/INFO] [FML]: Applying holder lookups
[16:36:40] [main/INFO] [FML]: Holder lookups applied
[16:36:40] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Found status: UP_TO_DATE Target: null
[16:36:40] [main/INFO] [FML]: Applying holder lookups
[16:36:40] [main/INFO] [FML]: Holder lookups applied
[16:36:40] [main/INFO] [FML]: Injecting itemstacks
[16:36:40] [main/INFO] [FML]: Itemstack injection complete
[16:36:46] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Starting up SoundSystem...
[16:36:47] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: Initializing LWJGL OpenAL
[16:36:47] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[16:36:47] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: OpenAL initialized.
[16:36:47] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Sound engine started
[16:36:55] [main/INFO] [FML]: Max texture size: 16384
[16:36:55] [main/INFO] [net.minecraft.client.renderer.texture.TextureMap]: Created: 512x512 textures-atlas
[16:36:57] [main/ERROR] [FML]: Exception loading model for variant minecraft:schest#inventory for item "r:schest", normal location exception: 
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model minecraft:item/schest with loader VanillaLoader.INSTANCE, skipping
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) ~[ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoader.loadItemModels(ModelLoader.java:304) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.loadVariantItemModels(ModelBakery.java:175) ~[ModelBakery.class:?]
	at net.minecraftforge.client.model.ModelLoader.setupModelRegistry(ModelLoader.java:153) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.onResourceManagerReload(ModelManager.java:28) [ModelManager.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.registerReloadListener(SimpleReloadableResourceManager.java:121) [SimpleReloadableResourceManager.class:?]
	at net.minecraft.client.Minecraft.init(Minecraft.java:559) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:421) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_152]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_152]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:25) [start/:?]
Caused by: java.io.FileNotFoundException: minecraft:models/item/schest.json
	at net.minecraft.client.resources.FallbackResourceManager.getResource(FallbackResourceManager.java:69) ~[FallbackResourceManager.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.getResource(SimpleReloadableResourceManager.java:65) ~[SimpleReloadableResourceManager.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.loadModel(ModelBakery.java:334) ~[ModelBakery.class:?]
	at net.minecraftforge.client.model.ModelLoader.access$1600(ModelLoader.java:117) ~[ModelLoader.class:?]
	at net.minecraftforge.client.model.ModelLoader$VanillaLoader.loadModel(ModelLoader.java:870) ~[ModelLoader$VanillaLoader.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) ~[ModelLoaderRegistry.class:?]
	... 20 more
[16:36:57] [main/ERROR] [FML]: Exception loading model for variant minecraft:schest#inventory for item "r:schest", blockstate location exception: 
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model minecraft:schest#inventory with loader VariantLoader.INSTANCE, skipping
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) ~[ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoader.loadItemModels(ModelLoader.java:312) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.loadVariantItemModels(ModelBakery.java:175) ~[ModelBakery.class:?]
	at net.minecraftforge.client.model.ModelLoader.setupModelRegistry(ModelLoader.java:153) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.onResourceManagerReload(ModelManager.java:28) [ModelManager.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.registerReloadListener(SimpleReloadableResourceManager.java:121) [SimpleReloadableResourceManager.class:?]
	at net.minecraft.client.Minecraft.init(Minecraft.java:559) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:421) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_152]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_152]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:25) [start/:?]
Caused by: net.minecraft.client.renderer.block.model.ModelBlockDefinition$MissingVariantException
	at net.minecraft.client.renderer.block.model.ModelBlockDefinition.getVariant(ModelBlockDefinition.java:83) ~[ModelBlockDefinition.class:?]
	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1182) ~[ModelLoader$VariantLoader.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) ~[ModelLoaderRegistry.class:?]
	... 20 more
[16:36:58] [main/INFO] [FML]: Applying holder lookups
[16:36:58] [main/INFO] [FML]: Holder lookups applied
[16:36:58] [main/INFO] [FML]: Injecting itemstacks
[16:36:58] [main/INFO] [FML]: Itemstack injection complete
[16:36:58] [main/INFO] [FML]: Forge Mod Loader has successfully loaded 5 mods
[16:36:58] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: lastServer:
[16:36:58] [main/INFO] [com.mojang.text2speech.NarratorWindows]: Narrator library for x64 successfully loaded
[16:36:59] [Realms Notification Availability checker #1/INFO] [com.mojang.realmsclient.client.RealmsClient]: Could not authorize you against Realms server: Invalid session id
[16:37:04] [Server thread/INFO] [net.minecraft.server.integrated.IntegratedServer]: Starting integrated minecraft server version 1.12.2
[16:37:04] [Server thread/INFO] [net.minecraft.server.integrated.IntegratedServer]: Generating keypair
[16:37:04] [Server thread/INFO] [FML]: Injecting existing registry data into this server instance
[16:37:05] [Server thread/INFO] [FML]: Registry Item: Found a missing id from the world minecraft:schest
[16:37:05] [Server thread/ERROR] [FML]: Unidentified mapping from registry minecraft:items
[16:37:05] [Server thread/ERROR] [FML]:     minecraft:schest: 4096
[16:37:07] [Server thread/INFO] [FML]: World backup created at C:\Users\warne\OneDrive\Desktop\pls\GUI\run\saves\New World-20180831-163707.zip.
[16:37:07] [Server thread/ERROR] [FML]: There are unidentified mappings in this world - we are going to attempt to process anyway
[16:37:07] [Server thread/WARN] [FML]: Registry Item: Object did not get ID it asked for. Name: r:schest Expected: 4096 Got: 4097
[16:37:08] [Server thread/INFO] [FML]: Applying holder lookups
[16:37:08] [Server thread/INFO] [FML]: Holder lookups applied
[16:37:08] [Server thread/INFO] [FML]: Loading dimension 0 (New World) (net.minecraft.server.integrated.IntegratedServer@153a85af)
[16:37:09] [Server thread/INFO] [net.minecraft.advancements.AdvancementList]: Loaded 488 advancements
[16:37:09] [Server thread/INFO] [FML]: Loading dimension 1 (New World) (net.minecraft.server.integrated.IntegratedServer@153a85af)
[16:37:09] [Server thread/INFO] [FML]: Loading dimension -1 (New World) (net.minecraft.server.integrated.IntegratedServer@153a85af)
[16:37:09] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing start region for level 0
[16:37:10] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 7%
[16:37:11] [Server thread/INFO] [FML]: Unloading dimension -1
[16:37:11] [Server thread/INFO] [FML]: Unloading dimension 1
[16:37:11] [Server thread/INFO] [net.minecraft.server.integrated.IntegratedServer]: Changing view distance to 12, from 10
[16:37:14] [Netty Local Client IO #0/INFO] [FML]: Server protocol version 2
[16:37:14] [Netty Server IO #1/INFO] [FML]: Client protocol version 2
[16:37:14] [Netty Server IO #1/INFO] [FML]: Client attempting to join with 5 mods : minecraft@1.12.2,r@1.0,FML@8.0.99.99,forge@14.23.4.2705,mcp@9.42
[16:37:14] [Netty Local Client IO #0/INFO] [FML]: [Netty Local Client IO #0] Client side modded connection established
[16:37:14] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[16:37:14] [Server thread/INFO] [net.minecraft.server.management.PlayerList]: Player495[local:E:8a87f0a3] logged in with entity id 346 at (220.58229347082263, 78.0, 277.1074811898455)
[16:37:14] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Player495 joined the game
[16:37:15] [Server thread/INFO] [net.minecraft.server.integrated.IntegratedServer]: Saving and pausing game...
[16:37:15] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'New World'/overworld
[16:37:15] [pool-2-thread-1/WARN] [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@1d42e4f6[id=598e33a2-e636-3db6-ba2f-6b9836ee1bdd,name=Player495,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:79) ~[YggdrasilAuthenticationService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) [YggdrasilMinecraftSessionService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService$1.load(YggdrasilMinecraftSessionService.java:60) [YggdrasilMinecraftSessionService$1.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService$1.load(YggdrasilMinecraftSessionService.java:57) [YggdrasilMinecraftSessionService$1.class:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) [guava-21.0.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:170) [YggdrasilMinecraftSessionService.class:?]
	at net.minecraft.client.Minecraft.getProfileProperties(Minecraft.java:3178) [Minecraft.class:?]
	at net.minecraft.client.resources.SkinManager$3.run(SkinManager.java:138) [SkinManager$3.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_152]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_152]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]
[16:43:41] [Server thread/INFO] [net.minecraft.server.integrated.IntegratedServer]: Saving and pausing game...
[16:43:41] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'New World'/overworld
[16:43:42] [main/INFO] [net.minecraft.client.Minecraft]: Stopping!
[16:43:42] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[16:43:42] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
[16:43:42] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
[16:43:42] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'New World'/overworld
[16:43:43] [Server thread/INFO] [FML]: Unloading dimension 0
[16:43:43] [Server thread/INFO] [FML]: Applying holder lookups
[16:43:43] [Server thread/INFO] [FML]: Holder lookups applied
[16:43:43] [main/INFO] [net.minecraft.client.audio.SoundManager]: SoundSystem shutting down...
[16:43:43] [main/WARN] [net.minecraft.client.audio.SoundManager]: Author: Paul Lamb, www.paulscode.com
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

**Comment by mindforger** [comment]
Please edit your post and post a pastebin link, this is painfull to read

**Comment by BluSunrize** [comment]
I'm afraid I don't quite understand your issue.
The log you have provided looks like a normal startup log for the MC client, and your issue title has me confused as to if this is an IE issue at all.

Could you please detail the problems you are experiencing when using IE?
