### ISSUE TITLE
Crashing caused by... potions?

### ISSUE THREAD

**Issue by truehunterethan** [BluSunrize/ImmersiveEngineering#3243]
### Description of the issue:
Crashed on startup. not much to say.

### Crashlog:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-85.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 10/5/18 4:24 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Immersive Engineering (immersiveengineering)
Caused by: java.lang.IllegalAccessError: tried to access class net.minecraft.potion.PotionHelper$MixPredicate from class blusunrize.immersiveengineering.common.IEContent
	at blusunrize.immersiveengineering.common.IEContent.postInit(IEContent.java:1014)
	at blusunrize.immersiveengineering.ImmersiveEngineering.postInit(ImmersiveEngineering.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_172, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 622493120 bytes (593 MB) / 1857552384 bytes (1771 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version                  | Source                              | Signature                                |
	|:------ |:-------------------- |:------------------------ |:----------------------------------- |:---------------------------------------- |
	| UCHIJ  | minecraft            | 1.12.2                   | minecraft.jar                       | None                                     |
	| UCHIJ  | mcp                  | 9.42                     | minecraft.jar                       | None                                     |
	| UCHIJ  | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2768.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | forge                | 14.23.5.2768             | forge-1.12.2-14.23.5.2768.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | buildinggadgets      | 1.6.2                    | BuildingGadgets-1.6.2.jar           | None                                     |
	| UCHIJ  | jei                  | 4.12.1.217               | jei_1.12.2-4.12.1.217.jar           | None                                     |
	| UCHIJ  | forestry             | 5.8.1.322                | forestry_1.12.2-5.8.1.322.jar       | None                                     |
	| UCHIJ  | gravestone           | 1.10.1                   | gravestone-1.10.1.jar               | None                                     |
	| UCHIEE | immersiveengineering | 0.12-85                  | ImmersiveEngineering-0.12-85.jar    | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHI   | immersivecables      | 1.3.2                    | ImmersiveCables-1.12.2-1.3.2.jar    | None                                     |
	| UCHI   | immersivepetroleum   | 1.1.9                    | immersivepetroleum-1.12.2-1.1.9.jar | None                                     |
	| UCHI   | immersivetech        | 1.3.10                   | immersivetech-1.12-1.3.10.jar       | None                                     |
	| UCHI   | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar            | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHI   | trackapi             | 1.1                      | TrackAPI-1.1_1.12.jar               | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-85.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.36' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	
	

### Versions & Modlist

Minecraft version 1.12.2
[All other info in this screenshot](https://gyazo.com/a59b9b335244c479c7aa0383d4c0a64a)

**Comment by lildale03** [comment]
Im geting the same thing xD

**Comment by mindforger** [comment]
Downgrade forge, they changed the potion registry without notice

**Comment by truehunterethan** [comment]
Thanks!

**Comment by IgSparkzy** [comment]
did it help?

**Comment by IgSparkzy** [comment]
if yes what version did you take
