### ISSUE TITLE
[1.12] Compat module TiC in combination with Moar Tinkers

### ISSUE THREAD

**Issue by scrouthtv** [BluSunrize/ImmersiveEngineering#3421]
possible duplicate with #2562 
I know it's only a stacktrace and no major problem, but here's what I was told to report anywys:

`[18:30:32] [Server thread/ERROR] [immersiveengineering]: Compat module for tconstruct could not be preInitialized. Report this and include the error message below!
slimeknights.tconstruct.library.TinkerAPIException: [TCon API] Could not register Material "constantan": It was already registered by Moar Tinkers
        at slimeknights.tconstruct.library.TinkerRegistry.error(TinkerRegistry.java:951) ~[TinkerRegistry.class:?]
        at slimeknights.tconstruct.library.TinkerRegistry.addMaterial(TinkerRegistry.java:129) ~[TinkerRegistry.class:?]
        at slimeknights.tconstruct.library.MaterialIntegration.preInit(MaterialIntegration.java:101) ~[MaterialIntegration.class:?]
        at blusunrize.immersiveengineering.common.util.compat.TConstructHelper.preInit(TConstructHelper.java:92) ~[TConstructHelper.class:?]
        at blusunrize.immersiveengineering.common.util.compat.IECompatModule.doModulesPreInit(IECompatModule.java:94) [IECompatModule.class:?]
        at blusunrize.immersiveengineering.ImmersiveEngineering.preInit(ImmersiveEngineering.java:93) [ImmersiveEngineering.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]`

Moar Tinkers' Constantan conflicts with the one of immersive engineering. That's all.

**Comment by Alex-hawks** [comment]
alright, you have two choices, disable Constantan and Treated Wood in Moar Tinkers, or disable the TiCon Integration module in IE

**Comment by BluSunrize** [comment]
That's not really true and a pretty dumb statement from Alex, actually =P

The proper solution is that I start catching that error rather than letting it propagate.
The reason I currently don't is that no other mod added Constantan until IE did.
