### ISSUE TITLE
[1.12] Server crash when assembling railcraft steel -> minecart recipes in Assembler

### ISSUE THREAD

**Issue by chaserhkj** [BluSunrize/ImmersiveEngineering#3473]
### Description of the issue:

Server crashes a few minutes after assembler was setup and started to batch craft Railcraft steel -> minecart x2 recipes.

### Crashlog:

I don't have the full crashlog since I'm not the server owner but the server owner @arition shared this with me:
```
[03:48:42] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 4
        at mods.railcraft.common.util.crafting.ShapedRailcraftRecipe.func_179532_b(ShapedRailcraftRecipe.java:68)
 ~[ShapedRailcraftRecipe.class:?]
        at blusunrize.immersiveengineering.common.blocks.metal.TileEntityAssembler.func_73660_a(TileEntityAssembl
er.java:193) ~[TileEntityAssembler.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1835) ~[amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
        ... 4 more
[03:48:42] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /root/mc5/./cr
ash-reports/crash-2019-05-16_03.48.42-server.txt
[03:48:42] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[03:48:42] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[03:48:42] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[03:48:42] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'world'/
```

@arition : Can you help upload the full crashlog to this issue?

### Versions & Modlist

- IE Version `0.12-89`
- Forge version: `14.23.5.2836`
- Railcraft version: `12.0.0`

**I am not sure if this is a RailCraft issue or an IE issue, but I'm posting it here anyway. I can help fix the problem as long as someone can help me pinpoint where the bug actually is.**

**Comment by the-eater** [comment]
Currently having the same issue with the assembler but for the Wooden Tie recipe (3x slab + creosote oil)

```
[19:38:13] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 4
        at mods.railcraft.common.util.crafting.ShapedRailcraftRecipe.func_179532_b(ShapedRailcraftRecipe.java:68) ~[ShapedRailcraftRecipe.class:?]
        at blusunrize.immersiveengineering.common.blocks.metal.TileEntityAssembler.func_73660_a(TileEntityAssembler.java:193) ~[TileEntityAssembler.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1835) ~[amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
        ... 4 more
```
Seems there was a similar issue with Thermal Expansion crafter:

https://github.com/Railcraft/Railcraft/issues/1812 & https://github.com/Railcraft/Railcraft/issues/1813

**Comment by BluSunrize** [comment]
So, given the stacktrace, it looks like Railcraft tries to use the size of the crafting grid to iterate its recipe parts.
Now, I can't tell in advance how big the grid *should* be, so I do what I suppose Thermal does as well, and use 3x3. The default crafting grid size.
If Railcraft doesn't handle that properly, I believe that's upon them. And given that Thermal causes the same issue, that does indicate the issue to be on RC's side.
