### ISSUE TITLE
Railgun keeps charged after firing

### ISSUE THREAD

**Issue by LiskoSlayer63** [BluSunrize/ImmersiveEngineering#3505]
When I install a shaderpack for my railgun and use it on a server, it can be fired again and again with no recharging needed. It does use the RF/IF and projectiles, though. It seems to be connected to SpongeForge somehow according to the error message it spams everytime I fire the railgun.

**Error message:**
```
[01:47:10] [Server thread/FATAL] [VanillaFix]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.entity.EntityLivingBase.func_189651_aD()Lnet/minecraft/util/math/Vec3d;
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_201]
        at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:307) [SpongeImplHooks.class:1.12.2-2825-7.1.6]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjo000(MinecraftServer.java:3970) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.EntityLivingBase.func_189651_aD()Lnet/minecraft/util/math/Vec3d;
        at blusunrize.immersiveengineering.common.items.ItemRailgun.onPlayerStoppedUsing(ItemRailgun.java:254) ~[ItemRailgun.class:?]
        at net.minecraft.item.ItemStack.onPlayerStoppedUsing(ItemStack.java:548) ~[aip.class:?]
        at net.minecraft.entity.EntityLivingBase.redirect$onStopPlayerUsing$zeg000(EntityLivingBase.java:4303) ~[vp.class:?]
        at net.minecraft.entity.EntityLivingBase.stopActiveHand(EntityLivingBase.java:2816) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.stopActiveHand(EntityPlayerMP.java:4645) ~[oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.processPlayerDigging(NetHandlerPlayServer.java:666) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(SourceFile:40) ~[lp.class:?]
        at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(SourceFile:10) ~[lp.class:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) ~[PacketPhaseUtil.class:1.12.2-2825-7.1.6]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlk000(SourceFile:539) ~[hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_201]
        at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
        ... 7 more
```

**Immersive Engineering version:** 0.12-89 ([custom fork](https://github.com/LiskoSlayer63/ImmersiveEngineering))
**Forge version:** 14.23.5.2825
**SpongeForge version:** 1.12.2-2825-7.1.6

**Comment by PrincessRTFM** [comment]
1) If you're using a custom fork, you should probably be reporting to that custom fork.

2) Isn't a custom modified version against the license? I swear I remember someone a few years back who edited the source and played with that, reported some issue, and got told they were violating the license...

**Comment by LiskoSlayer63** [comment]
That's my fork and at least last time Blu himself helped me. I've only modified the default setting values and added support to pump any liquid infinitely. For what I know, I haven't touched any code which is related to this issue.

**Comment by PrincessRTFM** [comment]
I somehow managed to completely miss that it's your own fork (don't read issues when you haven't slept, kids) so my bad on that, and if Blu's helping/helped you then you must have his okay for it. Disregard my earlier comment!

**Comment by BluSunrize** [comment]
Your fork is a bunch of commits behind.
One of those commits addressed a client access exception in the Railgun code. Entity.getForward is client only. It was replaced with user.getLookVec in this commit:

https://github.com/BluSunrize/ImmersiveEngineering/commit/780a1f984281ab5129a0c24059627065b413e6fb

Keep your fork updated.

**Comment by LiskoSlayer63** [comment]
Apologies for the possible false issue, I'll update my fork when I have time. Thanks for your reply!
