### ISSUE TITLE
Railcraft biodiesel tank issue

### ISSUE THREAD

**Issue by Antikiller** [BluSunrize/ImmersiveEngineering#354]
When I tried to put drill inside the biodiesel tank from the railcraft mod, my server has been crashed and can not be restored 
(I need to destroy the tank in the world editor)

Server log: 

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 22.08.15 16:43
Description: Ticking block entity

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/IIconRegister
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetMethodRecursive(Unknown Source)
	at java.lang.Class.getMethod0(Unknown Source)
	at java.lang.Class.privateGetMethodRecursive(Unknown Source)
	at java.lang.Class.getMethod0(Unknown Source)
	at java.lang.Class.privateGetMethodRecursive(Unknown Source)
	at java.lang.Class.getMethod0(Unknown Source)
	at java.lang.Class.privateGetMethodRecursive(Unknown Source)
	at java.lang.Class.getMethod0(Unknown Source)
	at java.lang.Class.getMethod(Unknown Source)
	at mods.railcraft.common.fluids.FluidItemHelper.drainContainer(FluidItemHelper.java:62)
	at mods.railcraft.common.fluids.FluidHelper.drainContainers(FluidHelper.java:144)
	at mods.railcraft.common.fluids.FluidHelper.processContainers(FluidHelper.java:113)
	at mods.railcraft.common.fluids.FluidHelper.processContainers(FluidHelper.java:100)
	at mods.railcraft.common.fluids.FluidHelper.processContainers(FluidHelper.java:94)
	at mods.railcraft.common.blocks.machine.beta.TileTankBase.func_145845_h(TileTankBase.java:573)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.texture.IIconRegister
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 24 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 26 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetMethodRecursive(Unknown Source)
	at java.lang.Class.getMethod0(Unknown Source)
	at java.lang.Class.privateGetMethodRecursive(Unknown Source)
	at java.lang.Class.getMethod0(Unknown Source)
	at java.lang.Class.privateGetMethodRecursive(Unknown Source)
	at java.lang.Class.getMethod0(Unknown Source)
	at java.lang.Class.privateGetMethodRecursive(Unknown Source)
	at java.lang.Class.getMethod0(Unknown Source)
	at java.lang.Class.getMethod(Unknown Source)
	at mods.railcraft.common.fluids.FluidItemHelper.drainContainer(FluidItemHelper.java:62)
	at mods.railcraft.common.fluids.FluidHelper.drainContainers(FluidHelper.java:144)
	at mods.railcraft.common.fluids.FluidHelper.processContainers(FluidHelper.java:113)
	at mods.railcraft.common.fluids.FluidHelper.processContainers(FluidHelper.java:100)
	at mods.railcraft.common.fluids.FluidHelper.processContainers(FluidHelper.java:94)
	at mods.railcraft.common.blocks.machine.beta.TileTankBase.func_145845_h(TileTankBase.java:573)

-- Block entity being ticked --
Details:
	Name: RCSteelTankWallTile // mods.railcraft.common.blocks.machine.beta.TileTankSteelWall
	Block type: ID #181 (tile.railcraft.machine.beta // mods.railcraft.common.blocks.machine.BlockMachine)
	Block data value: 13 / 0xD / 0b1101
	Block location: World: (-246,71,649), Chunk: (at 10,4,9 in -16,40; contains blocks -256,0,640 to -241,255,655), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Actual block type: ID #181 (tile.railcraft.machine.beta // mods.railcraft.common.blocks.machine.BlockMachine)
	Actual block data value: 13 / 0xD / 0b1101
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: SoS
	All players: 2 total; [EntityPlayerMP['Antikiller'/34862, l='SoS', x=-364,77, y=63,94, z=624,27], EntityPlayerMP['Plyg'/65333, l='SoS', x=-248,79, y=71,00, z=645,49]]
	Chunk stats: ServerChunkCache: 937 Drop: 0
	Level seed: 1901997514
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-43,64,203), Chunk: (at 5,4,11 in -3,12; contains blocks -48,0,192 to -33,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 9943733 game time, 11306458 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 83472 (now: false), thunder time: 17222 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 591051720 bytes (563 MB) / 1038614528 bytes (990 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 2 total; -Xmx2048M -Xms1024M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1492-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1492} [Minecraft Forge] (forge-1.7.10-10.13.4.1492-1.7.10-universal.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) 
	UCHIJAAAA	BuildCraft|Core{7.0.20} [BuildCraft] (buildcraft-7.0.20-core.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.0.20} [BuildCraft Factory] (buildcraft-7.0.20-factory.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.0.20} [Buildcraft Transport] (buildcraft-7.0.20-transport.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJAAAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJAAAA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
	UCHIJAAAA	Railcraft{9.7.0.0} [Railcraft] (Railcraft_1.7.10-9.7.0.0.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.5.4} [Immersive Engineering] (ImmersiveEngineering-0.5.4.jar) 
	UCHIJAAAA	integratedcircuits{1.7.10-0.9r36} [Integrated Circuits] (integratedcircuits-1.7.10-0.9r36.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.1.0.31-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre8.92} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre8.92-Base.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre8.92} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre8.92-Integration (1).jar) 
	UCHIJAAAA	ProjRed|Transportation{4.7.0pre8.92} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre8.92-Mechanical.jar) 
	UCHIJAAAA	ProjRed|Exploration{4.7.0pre8.92} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre8.92-World.jar) 
	UCHIJAAAA	ProjRed|Compatibility{4.7.0pre8.92} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre8.92-Compat.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre8.92} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre8.92-Integration (1).jar) 
	UCHIJAAAA	ProjRed|Fabrication{4.7.0pre8.92} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre8.92-Fabrication.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre8.92} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre8.92-Lighting.jar) 
	UCHIJAAAA	ProjRed|Expansion{4.7.0pre8.92} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre8.92-Mechanical.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 2 / 20; [EntityPlayerMP['Antikiller'/34862, l='SoS', x=-364,77, y=63,94, z=624,27], EntityPlayerMP['Plyg'/65333, l='SoS', x=-248,79, y=71,00, z=645,49]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by malte0811** [comment]
For anyone who wants to reproduce this crash: it only works on a dedicated server.
@BluSunrize This one is very easy to fix, you are missing 2 `@SideOnly(Side.CLIENT)` annotations in `ItemIEBase`, for `registerIcons` (this causes the crash, since it has a client only class as a parameter) and probably for `getIconFromDamage` as well. Railcraft calls `getMethod`, which tries to read all the current classes (`ItemDrill`) and it's superclasses methods and fails at trying to read `registerIcons`.

**Comment by BluSunrize** [comment]
Thanks @malte0811 and @Antikiller /please/ spoiler your crashlogs by using pastebin or something similar. Reading these on git is terrible.
