### ISSUE TITLE
[1.12.2] NoClassDefFoundError server crash interacting with revolver parts

### ISSUE THREAD

**Issue by CplPibald** [BluSunrize/ImmersiveEngineering#3560]
Dedicated server
ImmersiveEngineering-0.12-91
forge-1.12.2-14.23.5.2838
thutessentials-1.12.2-2.2.21

To repro: player on server opens village chest and finds revolver parts.

```
Description: Ticking player

java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at blusunrize.immersiveengineering.common.items.ItemRevolver$RevolverPerk.getFormattedName(ItemRevolver.java:865)
	at blusunrize.immersiveengineering.common.items.ItemMaterial.func_77653_i(ItemMaterial.java:42)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:617)
	at thut.essentials.util.InventoryLogger$Listener.func_71111_a(InventoryLogger.java:66)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:91)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:324)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
```

When evaluating item description, [`RevolverPerk.getFormattedName()`](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/items/ItemRevolver.java#L865) calls into client-only `I18n` class, which does not exist on server.

[Full crash report](https://paste.ubuntu.com/p/NRfnbMcyRp/)

**Comment by CplPibald** [comment]
When do you expect to release a build with this fix in?  Thanks.

**Comment by BluSunrize** [comment]
I hope to get it out this weekend.
