### ISSUE TITLE
[1.12.2] IE causing crash through dedicated server.

### ISSUE THREAD

**Issue by oldtrain1** [BluSunrize/ImmersiveEngineering#3569]
Forge Version 1.12.2 - 14.23.5.2784 - universal
The crash report:
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SoundUnpack (OpenSecurity-MC1.12.2-1.0-35.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-91.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 28/09/19 19:16
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Immersive Engineering (immersiveengineering)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/event/village/MerchantTradeOffersEvent
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetPublicMethods(Unknown Source)
	at java.lang.Class.getMethods(Unknown Source)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82)
	at blusunrize.immersiveengineering.ImmersiveEngineering.init(ImmersiveEngineering.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.event.village.MerchantTradeOffersEvent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 41 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2914439048 bytes (2779 MB) / 5953814528 bytes (5678 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 3 total; -Xmx8g -Xms512M -XX:+UseG1GC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2784 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version        | Source                                   | Signature                                |
	|:----- |:-------------------- |:-------------- |:---------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft            | 1.12.2         | minecraft.jar                            | None                                     |
	| LCHI  | mcp                  | 9.42           | minecraft.jar                            | None                                     |
	| LCHI  | FML                  | 8.0.99.99      | forge-1.12.2-14.23.5.2784-universal.jar  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge                | 14.23.5.2784   | forge-1.12.2-14.23.5.2784-universal.jar  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | opencomputers|core   | 1.7.4.153      | minecraft.jar                            | None                                     |
	| LCHE  | immersiveengineering | 0.12-91        | ImmersiveEngineering-0.12-91.jar         | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCH   | alternatingflux      | 0.12.2-2       | alternatingflux-0.12.2-2.jar             | None                                     |
	| LCH   | engineersdoors       | 0.8.0          | engineers_doors-1.12.2-0.8.0.jar         | None                                     |
	| LCH   | tardis               | 0.1.1A         | tardis-0.1.1A.jar                        | None                                     |
	| LCH   | handles              | 1.12.2-1.5.1.4 | handles-1.12.2-1.5.1.4.jar               | None                                     |
	| LCH   | immersivepetroleum   | 1.1.9          | immersivepetroleum-1.12.2-1.1.9.jar      | None                                     |
	| LCH   | trackapi             | 1.1            | TrackAPI-1.1_1.12.jar                    | None                                     |
	| LCH   | immersiverailroading | 1.6.1          | ImmersiveRailroading-1.6.1_1.12-1138.jar | None                                     |
	| LCH   | immersivetech        | 1.3.10         | immersivetech-1.12-1.3.10.jar            | None                                     |
	| LCH   | opencomputers        | 1.7.4.153      | OpenComputers-MC1.12.2-1.7.4.153.jar     | None                                     |
	| LCH   | opensecurity         | 1.0-35         | OpenSecurity-MC1.12.2-1.0-35.jar         | None                                     |
	| LCH   | industrialwires      | 1.7-36         | IndustrialWires-1.7-36.jar               | 7e11c175d1e24007afec7498a1616bef0000027d |

	Loaded coremods (and transformers): 
SoundUnpack (OpenSecurity-MC1.12.2-1.0-35.jar)
  
TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  li.cil.oc.common.asm.ClassTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-91.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server 

> (map_server.txt)
```

Whenever I launch the server, it crashes saying it was IE's fault but I cannot find the fault. I've reinstalled all the mods and such but I cannot find a fix.

**Comment by BluSunrize** [comment]
See #3554

Update forge.
