### ISSUE TITLE
[1.12.2] [IE 0.12-91] CTD Ticking Block Entity ArrayIndexOutofBoundsException DieselGenerator

### ISSUE THREAD

**Issue by kontu** [BluSunrize/ImmersiveEngineering#3614]
Have been playing FTB Revelations 3.2.1, which includes IE 0.12-91 in it on a multiplayer server -- Have had several players reach a few different area's in the map where we crash to desktop from Ticking Block Entity's, ArrayIndexOutOfBoundsException: 0 pointed at the Diesel Generator

I gathered a few couple crash reports myself - only workaround we can find right now is to get moved somewhere else while offline and then never go back to the locations. The crash reports I have are from the same location on the map, but there are other locations as well with the same crash dumps.

Crash dump 1 (first loading the area): https://pastebin.com/raw/Wp4QUADz
Crash dump 2 (trying to log back in a second time after the first crash without changing player location): https://pastebin.com/raw/yPUsGPG2

I went ahead and created a single player world (brand new world) in the same modpack (so same mods as the crash dump lists), crafting it in the world did not have the same issue. 

snippet - 
`Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: 0
	at blusunrize.immersiveengineering.common.blocks.TileEntityMultiblockPart.isDummy(TileEntityMultiblockPart.java:284)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityDieselGenerator.func_73660_a(TileEntityDieselGenerator.java:83)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
`

Let me know if there's more info I can provide, I tried to capture everything I could

**Comment by TeamSpen210** [comment]
Sounds like there's bad tile entity data for that block or something, perhaps. Below the trace you've posted it prints the block position (`3174 60 3451`) you could try `/setblock`ing it to air or the like. Potentially use `/fill` to only replace the multiblock blocks to prevent destroying others.

**Comment by kontu** [comment]
I'll have to harass the staff team to try to do that, that would be a potential workaround since they shouldn't have any issue with that...

**Comment by lJHKl** [comment]
any updates?

**Comment by BluSunrize** [comment]
The update is: We don't support 1.12 anymore.
