### ISSUE TITLE
Crash when placing trains or searching

### ISSUE THREAD

**Issue by AndyNS1701** [BluSunrize/ImmersiveEngineering#3640]
Alright so i used to be able to play this and its a really great mod but this is what it says. I dont know if you need the crash report but if you do here you go :/

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 1/24/20 3:32 PM
Description: Rendering screen

org.lwjgl.opengl.OpenGLException: Cannot use Buffers when Array Buffer Object is enabled
	at org.lwjgl.opengl.GLChecks.ensureArrayVBOdisabled(GLChecks.java:71)
	at org.lwjgl.opengl.GL11.glVertexPointer(GL11.java:2700)
	at net.minecraft.client.renderer.GlStateManager.func_187427_b(SourceFile:770)
	at net.minecraftforge.client.ForgeHooksClient.preDraw(ForgeHooksClient.java:468)
	at net.minecraft.client.renderer.vertex.VertexFormatElement$EnumUsage.preDraw(VertexFormatElement.java:169)
	at net.minecraft.client.renderer.WorldVertexBufferUploader.func_181679_a(WorldVertexBufferUploader.java:31)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:22)
	at net.minecraft.client.gui.Gui.func_73733_a(SourceFile:89)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:109)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.opengl.GLChecks.ensureArrayVBOdisabled(GLChecks.java:71)
	at org.lwjgl.opengl.GL11.glVertexPointer(GL11.java:2700)
	at net.minecraft.client.renderer.GlStateManager.func_187427_b(SourceFile:770)
	at net.minecraftforge.client.ForgeHooksClient.preDraw(ForgeHooksClient.java:468)
	at net.minecraft.client.renderer.vertex.VertexFormatElement$EnumUsage.preDraw(VertexFormatElement.java:169)
	at net.minecraft.client.renderer.WorldVertexBufferUploader.func_181679_a(WorldVertexBufferUploader.java:31)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:22)
	at net.minecraft.client.gui.Gui.func_73733_a(SourceFile:89)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:109)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (164, 152). Absolute: (1152, 619)
	Screen size: Scaled: (458, 241). Absolute: (3200, 1683). Scale factor of 7

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['AndyNS1701'/23, l='MpServer', x=910.29, y=4.00, z=238.22]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (902,4,235), Chunk: (at 6,0,11 in 56,14; contains blocks 896,0,224 to 911,255,239), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Level time: 451 game time, 451 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['AndyNS1701'/23, l='MpServer', x=910.29, y=4.00, z=238.22]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 369667784 bytes (352 MB) / 1174405120 bytes (1120 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version      | Source                                | Signature                                |
	|:------ |:-------------------- |:------------ |:------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2       | minecraft.jar                         | None                                     |
	| LCHIJA | mcp                  | 9.42         | minecraft.jar                         | None                                     |
	| LCHIJA | FML                  | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar         | None                                     |
	| LCHIJA | forge                | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar         | None                                     |
	| LCHIJA | trackapi             | 1.2          | TrackAPI-1.2.jar                      | None                                     |
	| LCHIJA | immersiverailroading | 1.7.2        | ImmersiveRailroading-1.7.2_1.12.2.jar | None                                     |
	| LCHIJA | universalmodcore     | 1.0.0        | ImmersiveRailroading-1.7.2_1.12.2.jar | None                                     |
	| LCHIJA | immersiveengineering | 0.12-89      | ImmersiveEngineering-0.12-89.jar      | 4cb49fcde3b43048c9889e0a3d083225da926334 |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.25' Renderer: 'Quadro K1100M/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: Quadro K1100M/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.25, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: DarkRaider's+Freight.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz

**Comment by BluSunrize** [comment]
Please use pastebin to spoiler your crashlog, like it says in the issue template rather than just blatantly ignoring it.

Could you try giving the client more memory? 2 gigs may not cut it.

**Comment by mindforger** [comment]
I think this is a gfx issue, it is a Notebook with a kinda rare quadro nvidia card, assuming you have optifine installed, try disabling VBO like in the report described or check if you can update your gfx drivers

**Comment by AndyNS1701** [comment]
thanks turning off vbos worked :D

**Comment by leonpano2006** [comment]
same issue on rtx a5000

> I think this is a gfx issue, it is a Notebook with a kinda rare quadro nvidia card, assuming you have optifine installed, try disabling VBO like in the report described or check if you can update your gfx drivers

**Comment by BluSunrize** [comment]
Don't necropost an issue that was closed 2 years ago.
