### ISSUE TITLE
Client crashed with GT

### ISSUE THREAD

**Issue by DeckerCHAN** [BluSunrize/ImmersiveEngineering#370]
``` Java
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 8/30/15 2:31 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at blusunrize.immersiveengineering.common.util.compat.GregTechHelper.gregtech_isEnergyConnected(GregTechHelper.java:54)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityConnectorLV.outputEnergy(TileEntityConnectorLV.java:97)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityConnectorLV.transferEnergy(TileEntityConnectorLV.java:194)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityConnectorLV.receiveEnergy(TileEntityConnectorLV.java:160)
	at buildcraft.transport.PipeTransportPower.updateEntity(PipeTransportPower.java:290)
	at buildcraft.transport.Pipe.updateEntity(Pipe.java:149)
	at buildcraft.transport.TileGenericPipe.func_145845_h(TileGenericPipe.java:387)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at blusunrize.immersiveengineering.common.util.compat.GregTechHelper.gregtech_isEnergyConnected(GregTechHelper.java:54)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityConnectorLV.outputEnergy(TileEntityConnectorLV.java:97)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityConnectorLV.transferEnergy(TileEntityConnectorLV.java:194)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityConnectorLV.receiveEnergy(TileEntityConnectorLV.java:160)
	at buildcraft.transport.PipeTransportPower.updateEntity(PipeTransportPower.java:290)
	at buildcraft.transport.Pipe.updateEntity(Pipe.java:149)
	at buildcraft.transport.TileGenericPipe.func_145845_h(TileGenericPipe.java:387)

-- Block entity being ticked --
Details:
	Name: net.minecraft.src.buildcraft.transport.GenericPipe // buildcraft.transport.TileGenericPipe
	Block type: ID #631 (tile.pipeBlock // buildcraft.transport.BlockGenericPipe)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-160,72,319), Chunk: (at 0,4,15 in -10,19; contains blocks -160,0,304 to -145,255,319), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #631 (tile.pipeBlock // buildcraft.transport.BlockGenericPipe)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [GCEntityPlayerMP['DeckerCHAN'/378, l='world', x=-153.72, y=71.99, z=317.61]]
	Chunk stats: ServerChunkCache: 458 Drop: 0
	Level seed: -546665553014403062
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-156,64,256), Chunk: (at 4,4,0 in -10,16; contains blocks -160,0,256 to -145,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 98039905 game time, 98248244 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 96623 (now: false), thunder time: 41738 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 409493816 bytes (390 MB) / 3038773248 bytes (2898 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 96 mods loaded, 96 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.6.43} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	bspkrsCore{6.14} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.14.jar) 
	UCHIJAAAA	ArmorStatusHUD{1.27} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.27.jar) 
	UCHIJAAAA	IC2{2.2.763-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.763-experimental.jar) 
	UCHIJAAAA	ImmibisCore{59.0.3} [Immibis Core] ([A]immibis-core-59.0.3.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] ([A]Mantle-1.7.10-0.3.2.jar) 
	UCHIJAAAA	ComputerCraft{1.65} [ComputerCraft] ([CC]ComputerCraft1.65.jar) 
	UCHIJAAAA	ImmibisPeripherals{59.0.1} [Immibis's Peripherals] ([CC]immibis-peripherals-59.0.1.jar) 
	UCHIJAAAA	IC2NuclearControl{2.0.5b-Unicorn} [Nuclear Control 2] ([IC2]IC2NuclearControl-2.0.5b-Unicorn.jar) 
	UCHIJAAAA	NEIPlugins{1.1.0.11-unofficial} [NEI Plugins Unofficial] ([NEI]NEIPlugins-MC1.7.10-1.1.0.11-unofficial.jar) 
	UCHIJAAAA	Waila{1.5.5} [Waila] ([NEI]Waila-1.5.5_1.7.10.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAA	BuildCraft|Core{7.0.20} [BuildCraft] (buildcraft-7.0.20.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.0.20} [BC Builders] (buildcraft-7.0.20.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.0.20} [BC Energy] (buildcraft-7.0.20.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.0.20} [BC Factory] (buildcraft-7.0.20.jar) 
	UCHIJAAAA	Railcraft{9.6.1.0} [Railcraft] (Railcraft_1.7.10-9.6.1.0.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.5.4} [Immersive Engineering] (ImmersiveEngineering-0.5.4.jar) 
	UCHIJAAAA	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.1-182.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) 
	UCHIJAAAA	cookiecore{1.3.1} [Cookie Core] (CookieCore-1.7.10-1.3.1-7.jar) 
	UCHIJAAAA	TSteelworks{1.7.10-1.1.0} [Tinkers' Steelworks] (TSteelworks-1.7.10-1.1.0-16.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.0} [Waila Harvestability] ([NEI]WailaHarvestability-mc1.7.x-1.1.0.jar) 
	UCHIJAAAA	TwilightForest{2.3.2} [The Twilight Forest] ([WG]twilightforest-1.7.10-2.3.2.jar) 
	UCHIJAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAAAA	Forestry{3.6.2.19} [Forestry for Minecraft] (forestry_1.7.10-3.6.2.19.jar) 
	UCHIJAAAA	BinnieCore{2.0-pre14} [Binnie Core] (binnie-mods-2.0-pre14.jar) 
	UCHIJAAAA	Botany{2.0-pre14} [Botany] (binnie-mods-2.0-pre14.jar) 
	UCHIJAAAA	ExtraBees{2.0-pre14} [Extra Bees] (binnie-mods-2.0-pre14.jar) 
	UCHIJAAAA	ExtraTrees{2.0-pre14} [Extra Trees] (binnie-mods-2.0-pre14.jar) 
	UCHIJAAAA	Genetics{2.0-pre14} [Genetics] (binnie-mods-2.0-pre14.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.0.20} [BC Silicon] (buildcraft-7.0.20.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.0.20} [BC Transport] (buildcraft-7.0.20.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.0.20} [BC Robotics] (buildcraft-7.0.20.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.16-universal.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCHIJAAAA	EnderStorage{1.4.7.33} [EnderStorage] (EnderStorage-1.7.10-1.4.7.33-universal.jar) 
	UCHIJAAAA	extracells{2.2.74} [Extra Cells 2] (ExtraCells-1.7.10-2.2.74b136.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.6} [Extra Utilities] (extrautilities-1.2.6.jar) 
	UCHIJAAAA	factorization.notify{1.0} [Factorization Notification System] (Factorization-1.7.10-0.8.95.jar) 
	UCHIJAAAA	factorization.dimensionalSlice{0.8.95} [Factorization Dimensional Slices] (Factorization-1.7.10-0.8.95.jar) 
	UCHIJAAAA	factorization{0.8.95} [Factorization] (Factorization-1.7.10-0.8.95.jar) 
	UCHIJAAAA	factorization.misc{0.8.95} [Factorization Miscellaneous Nonsense] (Factorization-1.7.10-0.8.95.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.349.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.349.jar) 
	UCHIJAAAA	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3.jar) 
	UCHIJAAAA	gregtech{MC1710} [GregTech] (gregtech_1.7.10-5.08.27.jar) 
	UCHIJAAAA	iChunUtil{4.0.0} [iChunUtil] (iChunUtil-4.0.0.jar) 
	UCHIJAAAA	IGWMod{1.1.4-20} [In-Game wiki Mod] (IGW-Mod.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	IronChest{6.0.60.741} [Iron Chest] (ironchest-1.7.10-6.0.60.741-universal.jar) 
	UCHIJAAAA	ItemSearch{1.3} [Briman's Item Search] (ItemSearch-1.3.1.jar) 
	UCHIJAAAA	minechem{5.0.5.406} [Minechem] (Minechem-1.7.10-5.0.5.406.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MobAmputation{4.0.0} [MobAmputation] (MobAmputation-4.0.0.jar) 
	UCHIJAAAA	MobDismemberment{4.0.0} [MobDismemberment] (MobDismemberment-4.0.0.jar) 
	UCHIJAAAA	NEIAddons{1.12.10.33} [NEI Addons] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.10.33} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.10.33} [NEI Addons: Botany] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.10.33} [NEI Addons: Forestry] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.10.33} [NEI Addons: Crafting Tables] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.10.33} [NEI Addons: Ex Nihilo] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHIJAAAA	neiintegration{1.0.11} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.11.jar) 
	UCHIJAAAA	numina{0.4.0.101} [Numina] (Numina-0.4.0.101.jar) 
	UCHIJAAAA	RedstoneArsenal{1.7.10R1.1.0} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0-80.jar) 
	UCHIJAAAA	TiCTooltips{1.2.3} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.3.jar) 
	UCHIJAAAA	TMechworks{0.2.14.100} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.14.100.jar) 
	UCHIJAAAA	voxelmap{1.7.10} [VoxelMap No Radar] (voxelmap С��ͼ(���״�) v1.7.10-1.0.jar) 
	UCHIJAAAA	WailaNBT{1.4} [Waila NBT] (WailaNBT-1.7.10-1.4.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Mantle Environment: Environment healthy.
	CoFHCore: -[1.7.10]3.0.3-303
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	ThermalFoundation: -[1.7.10]1.0.0-81
	ThermalExpansion: -[1.7.10]4.0.1-182
	TConstruct Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: gregtech
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	RedstoneArsenal: -[1.7.10]1.1.0-80
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:ON, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [GCEntityPlayerMP['DeckerCHAN'/378, l='world', x=-153.72, y=71.99, z=317.61]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by TheN1K0L4Z** [comment]
I was afraid of this. Until IE has interoperability with GT5, I won't use it.

**Comment by bear989** [comment]
I use IE and GT5 for my GT5u modpack and we use them together on the server I play on, I haven't had any crashes do to the two mods interactions.

**Comment by BluSunrize** [comment]
Yeah this is probably fixed thanks to the rewrite of the gregtech compat.
OP can reopen if issue persists.
