### ISSUE TITLE
1.14.4 Immersive Engineering

### ISSUE THREAD

**Issue by smogg11** [BluSunrize/ImmersiveEngineering#3720]
So this is my problem

 

Description: Rendering entity in world

java.lang.ClassCastException: net.minecraft.entity.item.minecart.ChestMinecartEntity cannot be cast to net.minecraft.entity.item.minecart.MinecartEntity
    at blusunrize.immersiveengineering.client.models.ShaderMinecartModel.func_78088_a(ShaderMinecartModel.java:31) ~[?:?] {re:classloading}
    at net.minecraft.client.renderer.entity.MinecartRenderer.func_76986_a(SourceFile:107) ~[?:?] {re:classloading,pl:accesstransformer:B}
    at net.minecraft.client.renderer.entity.MinecartRenderer.func_76986_a(SourceFile:15) ~[?:?] {re:classloading,pl:accesstransformer:B}
    at net.minecraft.client.renderer.entity.EntityRendererManager.func_188391_a(EntityRendererManager.java:370) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:add-render,pl:runtimedistcleaner:A}
    at net.minecraft.client.renderer.entity.EntityRendererManager.func_188388_a(EntityRendererManager.java:359) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:add-render,pl:runtimedistcleaner:A}
    at net.minecraft.client.renderer.WorldRenderer.func_215326_a(WorldRenderer.java:543) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:journeymap:WorldRenderer.markForRerender,pl:runtimedistcleaner:A}
    at net.minecraft.client.renderer.GameRenderer.func_181560_a(GameRenderer.java:713) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.client.renderer.GameRenderer.func_78471_a(GameRenderer.java:640) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:494) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:890) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
    at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.2.3.jar:28.2] {}
    at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$410/1370709582.call(Unknown Source) [forge-1.14.4-28.2.3.jar:28.2] {}
    at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
    at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
    at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
    at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
    at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
    at blusunrize.immersiveengineering.client.models.ShaderMinecartModel.func_78088_a(ShaderMinecartModel.java:31)
    at net.minecraft.client.renderer.entity.MinecartRenderer.func_76986_a(SourceFile:107)
    at net.minecraft.client.renderer.entity.MinecartRenderer.func_76986_a(SourceFile:15)

-- Entity being rendered --
Details:
    Entity Type: minecraft:chest_minecart (net.minecraft.entity.item.minecart.ChestMinecartEntity)
    Entity ID: 7
    Entity Name: Minecart with Chest
    Entity's Exact location: 26.50, 25.06, -192.50
    Entity's Block location: World: (26,25,-193), Chunk: (at 10,1,15 in 1,-13; contains blocks 16,0,-208 to 31,255,-193), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Entity's Momentum: 0.00, 0.00, 0.00
    Entity's Passengers: []
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null

**Comment by BluSunrize** [comment]
Your problem is that you didn't read the issue template.
