### ISSUE TITLE
[FIXED IN LAST UPDATE - PLEASE DELETE][1.14.4] Crash randomly while exploring: "java.lang.ClassCastException: net.minecraft.entity.item.minecart.ChestMinecartEntity cannot be cast to net.minecraft.entity.item.minecart.MinecartEntity"

### ISSUE THREAD

**Issue by DanNetwalker** [BluSunrize/ImmersiveEngineering#3732]
### Situation:

While exploring, the game crashes. Posibly while loading a mine with chest minecarts

### Crash log:

`---- Minecraft Crash Report ----
// Don't do that.

Time: 3/30/20 12:17 AM
Description: Rendering entity in world

java.lang.ClassCastException: net.minecraft.entity.item.minecart.ChestMinecartEntity cannot be cast to net.minecraft.entity.item.minecart.MinecartEntity
	at blusunrize.immersiveengineering.client.models.ShaderMinecartModel.func_78088_a(ShaderMinecartModel.java:31) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.entity.MinecartRenderer.func_76986_a(SourceFile:107) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.renderer.entity.MinecartRenderer.func_76986_a(SourceFile:15) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_188391_a(EntityRendererManager.java:370) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:add-render,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_188388_a(EntityRendererManager.java:359) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:add-render,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_215326_a(WorldRenderer.java:543) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:journeymap:WorldRenderer.markForRerender,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_181560_a(GameRenderer.java:713) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_78471_a(GameRenderer.java:640) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:494) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:890) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.2.3.jar:28.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$411/1710422448.call(Unknown Source) [forge-1.14.4-28.2.3.jar:28.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at blusunrize.immersiveengineering.client.models.ShaderMinecartModel.func_78088_a(ShaderMinecartModel.java:31)
	at net.minecraft.client.renderer.entity.MinecartRenderer.func_76986_a(SourceFile:107)
	at net.minecraft.client.renderer.entity.MinecartRenderer.func_76986_a(SourceFile:15)

-- Entity being rendered --
Details:
	Entity Type: minecraft:chest_minecart (net.minecraft.entity.item.minecart.ChestMinecartEntity)
	Entity ID: 135587
	Entity Name: Minecart with Chest
	Entity's Exact location: -138.50, 33.06, -640.50
	Entity's Block location: World: (-139,33,-641), Chunk: (at 5,2,15 in -9,-41; contains blocks -144,0,-656 to -129,255,-641), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.MinecartRenderer@3284748c
	Location: -52.60,-47.56,1.59 - World: (-53,-48,1), Chunk: (at 11,-3,1 in -4,0; contains blocks -64,0,0 to -49,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Rotation: 0.0
	Delta: 0.20098889
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_188391_a(EntityRendererManager.java:370)
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_188388_a(EntityRendererManager.java:359)
	at net.minecraft.client.renderer.WorldRenderer.func_215326_a(WorldRenderer.java:543)
	at net.minecraft.client.renderer.GameRenderer.func_181560_a(GameRenderer.java:713)
	at net.minecraft.client.renderer.GameRenderer.func_78471_a(GameRenderer.java:640)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['DanNetwalker'/97, l='MpServer', x=-85.96, y=79.00, z=-642.14]]
	Chunk stats: Client Chunk Cache: 529, 323
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 07 - wildnature, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-80,77,-191), Chunk: (at 0,4,1 in -5,-12; contains blocks -80,0,-192 to -65,255,-177), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 464606 game time, 603739 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:410)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1750)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$411/1710422448.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2079340112 bytes (1983 MB) / 3905421312 bytes (3724 MB) up to 3905421312 bytes (3724 MB)
	CPUs: 12
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.5-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.3
	FML Language Providers: 
		javafml@28.2
		minecraft@1
		kotlinfml@1.4.0
	Mod List: 
		forge-1.14.4-28.2.3-client.jar Minecraft {minecraft@1.14.4 DONE}
		useful_backpacks-1.14.4-1.7.6.60.jar Useful Backpacks {usefulbackpacks@1.7.6.60 DONE}
		Notes-1.14.4-1.2.0.jar Notes {notes@1.14.4-1.2.0 DONE}
		theoneprobe-1.14-1.4.37.jar The One Probe {theoneprobe@NONE DONE}
		swingthroughgrass-1.14.4-1.3.2.jar SwingThroughGrass {swingthroughgrass@1.14.4-1.3.2 DONE}
		embellishcraft-1.14.4-1.5.0.jar EmbellishCraft {embellishcraft@1.14.4-1.5.0 DONE}
		Cucumber-1.14.4-2.0.6.jar Cucumber Library {cucumber@2.0.6 DONE}
		ImmersiveEngineering-0.14-93.jar Immersive Engineering {immersiveengineering@0.14-testing-8737d9a7 DONE}
		jei-1.14.4-6.0.0.27.jar Just Enough Items {jei@6.0.0.27 DONE}
		JustEnoughCalculation-1.14.4-3.4.2.jar Just Enough Calculation {jecalculation@3.4.2 DONE}
		SlashBlade-1.14-0.0.8.jar Slash Blade {slashblade@0.0.8 DONE}
		fairylights-2.1.15-1.14.4.jar Fairy Lights {fairylights@2.1.15 DONE}
		astikorcarts-1.0.2-1.14.4.jar AstikorCarts {astikorcarts@1.0.2 DONE}
		wildnature-2.1.6.4.jar WildNature {wildnature@2.1.6.4 DONE}
		Uppers-0.1.11.jar Uppers {uppers@0.1.11 DONE}
		ChineseWorkshop-1.14.4-2.4.1.jar ChineseWorkshop {chineseworkshop@2.4.1 DONE}
		Kiwi-1.14.4-2.6.3.jar Kiwi {kiwi@2.6.3 DONE}
		Industrial Agriculture[Core]-1.14.4-1.6.7.jar Industrial Agriculture {industrialagriculture@1.14.4-1.6.7 DONE}
		curios-FORGE-1.14.4-1.0.6.1.jar Curios API {curios@FORGE-1.14.4-1.0.6.1 DONE}
		Botania r1.11-378.jar Botania {botania@r1.11-378 DONE}
		Patchouli-1.14.4-1.1-26.jar Patchouli {patchouli@1.14.4-1.1-25 DONE}
		create-mc1.14.4_v0.2.1.jar Create {create@mc1.14-0.2.1 DONE}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 DONE}
		journeymap-1.14.4-5.7.0b1.jar Journeymap {journeymap@1.14.4-5.7.0b1 DONE}
		StorageDrawers-1.14.4-6.0.6.jar Storage Drawers {storagedrawers@1.14.4-6.0.6 DONE}
		gardenofglass-1.1.jar Garden of Glass {gardenofglass@1.1 DONE}
		libnonymous-1.14.4-1.0.4.25.jar Libnonymous {libnonymous@1.0.4.25 DONE}
		structurize-0.10.200-ALPHA.jar Structurize {structurize@0.10.200-ALPHA DONE}
		pneumaticcraft-repressurized-1.14.4-1.0.0-8.jar PneumaticCraft: Repressurized {pneumaticcraft@1.14.4-1.0.0-8 DONE}
		u_team_core-1.14.4-2.8.2.150.jar U Team Core {uteamcore@2.8.2.150 DONE}
		BonsaiTrees-2.0.2.35.jar Bonsai Trees 2 {bonsaitrees2@2.0.2.35 DONE}
		minecolonies-0.10.715-RELEASE-universal.jar Minecolonies {minecolonies@0.10.715-RELEASE DONE}
		solcarrot-1.14.4-1.9.4.jar Spice of Life: Carrot Edition {solcarrot@1.14.4-1.9.4 DONE}
		WaterStrainer-1.14.4-7.0.2.jar Water Strainer {waterstrainer@1.14.4-7.0.2 DONE}
		eqex-rev-1.0.1.2.jar Equivalent Exchange Revived {eqex@1.0.1.2 DONE}
		JustEnoughResources-1.14.4-0.10.1.76.jar Just Enough Resources {jeresources@0.10.1.76 DONE}
		forge-1.14.4-28.2.3-universal.jar Forge {forge@28.2.3 DONE}
		Bountiful-1.14.4-3.1.0.jar Bountiful {bountiful@1.14.4-3.1.0 DONE}
		Quark-r2.0-212.jar Quark {quark@r2.0-212 DONE}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 DONE}
		refinedstorage-1.7.3.jar Refined Storage {refinedstorage@1.7.3 DONE}
		MysticalAgriculture-1.14.4-2.0.6.jar Mystical Agriculture {mysticalagriculture@2.0.6 DONE}
	Kiwi Modules: 
		chineseworkshop:blocks
		chineseworkshop:debug_stick
		chineseworkshop:decorations
		chineseworkshop:materials
		chineseworkshop:retexture
		kiwi:contributors
	Launched Version: forge-28.2.3
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1650 with Max-Q Design/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.91, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz`

**Comment by DanNetwalker** [comment]
Sorry, false alarm. I updated the mod after last of four crashes (didn't see the update before). Now working. Please close or delete.
