### ISSUE TITLE
[Build 97] Server/Client mapping issue

### ISSUE THREAD

**Issue by GordonHollow** [BluSunrize/ImmersiveEngineering#3878]
Server crashing on start, forge-1.14.4-28.2.16, IE new release

```
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at blusunrize.immersiveengineering.api.crafting.MultiblockRecipe.func_77571_b(MultiblockRecipe.java:34) ~[?:?] {re:classloading}
	at net.blay09.mods.cookingforblockheads.registry.CookingRegistry.initFoodRegistry(CookingRegistry.java:68) ~[?:7.4.4] {re:classloading}
	at net.blay09.mods.cookingforblockheads.CookingForBlockheads.serverStarted(CookingForBlockheads.java:120) ~[?:7.4.4] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:94) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:601) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241] {}
```

**Comment by BluSunrize** [comment]
Known issue, fixed for next release. Please actually use the issue template next time.

Try this development build, to see if it resolves the issue:
https://ci.blamejared.com/job/Immersive%20Engineering/679/

**Comment by GordonHollow** [comment]
> 
> 
> Known issue, fixed for next release. Please actually use the issue template next time.
> 
> Try this development build, to see if it resolves the issue:
> https://ci.blamejared.com/job/Immersive%20Engineering/679/

with this version don't crash server on startup, but cant' connect to server anyway

Failed to synchronyze registry data from the server, closing connection

**Comment by BluSunrize** [comment]
You gotta use the same version on server and client.

**Comment by GordonHollow** [comment]
> 
> 
> You gotta use the same version on server and client.

and i got it, the same version on server and client. check this twice.

**Comment by BluSunrize** [comment]
Full server and client logs then. On pastebin.

**Comment by GordonHollow** [comment]
Server logs says only this

> [Server thread/INFO] [net.minecraft.network.login.ServerLoginNetHandler/]: com.mojang.authlib.GameProfile@73f9345e[id=<null>,name=Gordon,properties={},legacy=false] (/127.0.0.1:58787) lost connection: Disconnected

Full log server
[latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/4677129/latest.log)

Full log client:
[latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/4677134/latest.log)

PS: Patebin don't let me download this, more than 500kb logs

**Comment by malte0811** [comment]
This seems to be caused by Industrial Foregoing, they're adding new elements to the enum at a fairly undefined point during startup [here](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/blob/9a4fbb3694cdf4b6f70516fc29411c16b524f70e/src/main/java/com/buuz135/industrial/block/MachineFrameBlock.java#L16-L19). This is a bad idea, on the other hand, I'm not sure whether registering an item for every entry in a extendable enum is a much better idea.

**Comment by GordonHollow** [comment]
Industrial Foregoing now on 1.15.2. There is no more updates for 1.14.4 =(

**Comment by BluSunrize** [comment]
Yeah, but we can't fix their stuff, can we?

**Comment by GordonHollow** [comment]
So...it's their issue? It works with previous version of IE, i don't change anything else, only updates IE
