### ISSUE TITLE
[1.14.4] Incompatibility with Quark - Freeze on World-Load

### ISSUE THREAD

**Issue by thwinston** [BluSunrize/ImmersiveEngineering#3885]
Forge Version: 28.2.16
IE Version 0.14-96
Quark Version: r2.0-212

Mod List:
Quark r2.0-212
Immersive Engineering 0.14-96
AutoRegLib 1.4-35

Game stops responding after worldgen reaches 100%, does not stop until force-closed. Works again if either mod is removed.

**Crash Report:** 

`---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 5/29/20 10:23 AM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at blusunrize.immersiveengineering.api.crafting.MultiblockRecipe.func_77571_b(MultiblockRecipe.java:34) ~[?:?] {re:classloading}
	at vazkii.quark.tweaks.module.AutomaticRecipeUnlockModule.lambda$onPlayerLoggedIn$0(AutomaticRecipeUnlockModule.java:52) ~[?:r2.0-212] {re:classloading}
	at java.util.ArrayList.removeIf(Unknown Source) ~[?:1.8.0_251] {}
	at vazkii.quark.tweaks.module.AutomaticRecipeUnlockModule.onPlayerLoggedIn(AutomaticRecipeUnlockModule.java:52) ~[?:r2.0-212] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_88_AutomaticRecipeUnlockModule_onPlayerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:43) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:206) ~[?:?] {re:classloading}
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:116) ~[?:?] {re:classloading}
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:63) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:224) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:848) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:766) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at blusunrize.immersiveengineering.api.crafting.MultiblockRecipe.func_77571_b(MultiblockRecipe.java:34)
	at vazkii.quark.tweaks.module.AutomaticRecipeUnlockModule.lambda$onPlayerLoggedIn$0(AutomaticRecipeUnlockModule.java:52)
	at java.util.ArrayList.removeIf(Unknown Source)
	at vazkii.quark.tweaks.module.AutomaticRecipeUnlockModule.onPlayerLoggedIn(AutomaticRecipeUnlockModule.java:52)
	at net.minecraftforge.eventbus.ASMEventHandler_88_AutomaticRecipeUnlockModule_onPlayerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:43)
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:206)
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:116)
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:63)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:224)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@650a46c8
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:848)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:766)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4547511720 bytes (4336 MB) / 5277933568 bytes (5033 MB) up to 6177423360 bytes (5891 MB)
	CPUs: 8
	JVM Flags: 7 total; -Xmn2G -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=60 -XX:-UseAdaptiveSizePolicy -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4048m -Xmx6096m
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.16-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.16-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.5-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.16-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.16-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.2.16-launcher.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.16
	FML Language Providers: 
		javafml@28.2
		minecraft@1
	Mod List: 
		forge-1.14.4-28.2.16-client.jar Minecraft {minecraft@1.14.4 DONE}
		forge-1.14.4-28.2.16-universal.jar Forge {forge@28.2.16 DONE}
		ImmersiveEngineering-0.14-96.jar Immersive Engineering {immersiveengineering@0.14-96 DONE}
		AutoRegLib-1.4-35 (1).jar AutoRegLib {arl@1.4-35 DONE}
		Quark-r2.0-212.jar Quark {quark@r2.0-212 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['Fang28'/94, l='New World', x=-259.50, y=85.00, z=113.50]]
	Data Packs: vanilla, mod:arl, mod:forge, mod:immersiveengineering, mod:quark
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'`

**Comment by thwinston** [comment]
Closed: appears to be fixed in dev version #679
