### ISSUE TITLE
[1.14.4] Issue with Quark AutomaticRecipeUnlock (workaround inside)

### ISSUE THREAD

**Issue by ipedroni** [BluSunrize/ImmersiveEngineering#3895]
Some kind of error pops up when trying out Quark 212 + IE 14-96.
It appears to be related to the Automatic Recipe Unlock enabled in quark by default. Game freezes at 100% world load or crashes to desktop altogether. Disabling it in Quark's config file seems to fix this.

- **Minecraft 1.14.4**
- **Forge 1.14.4-forge-28.2.17**
- **Quark-r2.0-212**
- **ImmersiveEngineering-0.14-96**
- **OptiFine_1.14.4_HD_U_F5** present 
- **OptiForge-MC1.14.4-0.1.1** present
- 12GB Ram allocated

Crash log bit:

```
java.lang.NullPointerException: Ticking memory connection
	at blusunrize.immersiveengineering.api.crafting.MultiblockRecipe.func_77571_b(MultiblockRecipe.java:34) ~[?:?] {re:classloading}
	at vazkii.quark.tweaks.module.AutomaticRecipeUnlockModule.lambda$onPlayerLoggedIn$0(AutomaticRecipeUnlockModule.java:52) ~[?:r2.0-212] {re:classloading}
	at vazkii.quark.tweaks.module.AutomaticRecipeUnlockModule$$Lambda$8898/2090700137.test(Unknown Source) ~[?:?] {}
```

**Comment by BluSunrize** [comment]
Yep, duplicate issue, see here: #3885
Fixed for next release.

Please use the search function next time =)
