### ISSUE TITLE
NPE while trying to cut wires

### ISSUE THREAD

**Issue by SanAndreasP** [BluSunrize/ImmersiveEngineering#401]
Forge: 10.13.4.1492
Immersive Engineering: 0.5.4

So, I'm trying to remove MV wired via the wire cutter, but every time I do it I get a NPE:
```
java.lang.NullPointerException: Ticking memory connection
	at blusunrize.immersiveengineering.api.energy.ImmersiveNetHandler.clearAllConnectionsFor(ImmersiveNetHandler.java:149)
	at blusunrize.immersiveengineering.common.items.ItemIETool.onItemUseFirst(ItemIETool.java:74)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:360)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at fastcraft.r.a(F:21)
	at fastcraft.Hooks.aq(F:155)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

Here's the full log:
https://gist.githubusercontent.com/SanAndreasP/49f311e2d2c96c0984c9/raw/91a200b1b9a022ee677e1c2131a50d1a50626a70/fml-client-latest.log

The MV connector I'm rightclicking is connected to 3 other connections: 2 MV connectors and one MV to LV transformer.
It had 2 other connections, which I broke by just removing the connectors with a pickaxe.

**Comment by GirafiStudios** [comment]
I think this might be cause by, that you're using a test version of Fastcraft. Try to see if this happens with Fastcraft version 1.21

**Comment by cobra** [comment]
Better try without any fastcraft version at all. Does it crash only when fastcraft is installed? Report this to player. If you want to test 1.21 to see if it's a regression, do so and tell him the results.
Does it still crash without fastcraft? Please paste the new log.

**Comment by SanAndreasP** [comment]
I don't see why it's caused by fastcraft (because I see there's an NPE in the <tt>blusunrize.immersiveengineering.api.energy.ImmersiveNetHandler.clearAllConnectionsFor()</tt> method), but I can try without it, sure (when I get home).

**Comment by GirafiStudios** [comment]
Both Fastcraft and Optifine is doing stuff that sometimes can break mods. + that Fastcraft is a part of crashlog :3

**Comment by BluSunrize** [comment]
Yeah, you see that IE NPE, and then you follow the trace down to
  at fastcraft.r.a(F:21)
  at fastcraft.Hooks.aq(F:155)

So check again without Fastcraft =P

**Comment by SanAndreasP** [comment]
Meh, after rewiring stuff it seems to have fixed the problem... I can't reproduce it either, so... I'll close this now. Thanks for the replies, though.
I will reopen a new issue if I can reproduce it reliably (and w/o fastcraft next time :P )
