### ISSUE TITLE
IE 1.16.1 Forge 32.0.99

### ISSUE THREAD

**Issue by Lurihan** [BluSunrize/ImmersiveEngineering#4174]
First i think it works finde with the new Update. But then i cant join my Server cause my Game broke giving me this Report. A single Player game i can start but not on a Server. Server is updated on the newest Version of IE and Forge. And all other Mods are updated too. Pls help me

---- Minecraft Crash Report ----
// There are four lights!

Time: 05.08.20 18:34
Description: Unexpected error

java.lang.RuntimeException: No net handler found for dimension minecraft:overworld, remote: true
	at blusunrize.immersiveengineering.api.wires.GlobalWireNetwork.getNetwork(GlobalWireNetwork.java:74) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.api.wires.ImmersiveConnectableTileEntity.func_226984_a_(ImmersiveConnectableTileEntity.java:79) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.Chunk.func_177426_a(Chunk.java:408) ~[?:?] {re:classloading}
	at net.minecraft.world.World.func_175690_a(World.java:683) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:391) ~[?:?] {re:classloading}
	at net.minecraft.world.World.func_175625_s(World.java:641) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at blusunrize.immersiveengineering.common.blocks.IETileProviderBlock.func_220071_b(IETileProviderBlock.java:378) ~[?:?] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215685_b(AbstractBlock.java:538) ~[?:?] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196952_d(AbstractBlock.java:534) ~[?:?] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_235785_r_(AbstractBlock.java:716) ~[?:?] {re:classloading}
	at net.minecraft.client.world.ClientWorld.func_184153_a(ClientWorld.java:531) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.world.ClientWorld.func_73029_E(ClientWorld.java:499) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1491) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:928) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:582) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.99.jar:32.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$421/15910024.call(Unknown Source) [forge-1.16.1-32.0.99.jar:32.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at blusunrize.immersiveengineering.api.wires.GlobalWireNetwork.getNetwork(GlobalWireNetwork.java:74)
	at blusunrize.immersiveengineering.api.wires.ImmersiveConnectableTileEntity.func_226984_a_(ImmersiveConnectableTileEntity.java:79)
	at net.minecraft.world.chunk.Chunk.func_177426_a(Chunk.java:408)
	at net.minecraft.world.World.func_175690_a(World.java:683)
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:391)
	at net.minecraft.world.World.func_175625_s(World.java:641)
	at blusunrize.immersiveengineering.common.blocks.IETileProviderBlock.func_220071_b(IETileProviderBlock.java:378)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215685_b(AbstractBlock.java:538)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196952_d(AbstractBlock.java:534)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_235785_r_(AbstractBlock.java:716)
	at net.minecraft.client.world.ClientWorld.func_184153_a(ClientWorld.java:531)
	at net.minecraft.client.world.ClientWorld.func_73029_E(ClientWorld.java:499)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Lurihan'/87, l='ClientLevel', x=-868.36, y=64.56, z=-419.70]]
	Chunk stats: Client Chunk Cache: 729, 424
	Level dimension: minecraft:overworld
	Level spawn location: World: (48,65,-176), Chunk: (at 0,4,0 in 3,-11; contains blocks 48,0,-176 to 63,255,-161), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 31524946 game time, 23298632 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:616)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:603)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$421/15910024.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1240454744 bytes (1182 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.99.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.99.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.99.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.99.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/preview_OptiFine_1.16.1_HD_U_G2_pre4.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.1-32.0.99.jar fml TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.99
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		forge-1.16.1-32.0.99-client.jar Minecraft {minecraft@1.16.1 DONE}
		movingelevators-1.2.17a-mc1.16.jar Moving Elevators {movingelevators@1.2.17a DONE}
		forge-1.16.1-32.0.99-universal.jar Forge {forge@32.0.99 DONE}
		ImmersiveEngineering-1.16.1-3.1-112.jar Immersive Engineering {immersiveengineering@1.16.1-3.1-112 DONE}
		WorldEdit-1.16.1.jar WorldEdit {worldedit@7.2.0-beta-02+d10d7d6 DONE}
		YUNGs-Better-Caves-Mod-1.16.1.jar YUNG's Better Caves {bettercaves@1.16.1-1.0 DONE}
		travellers_map-1.16.1-0.5.3.jar Travellers Map {travellers_map@1.16.1-0.5.2 DONE}
		jei-1.16.1-7.0.0.6.jar Just Enough Items {jei@7.0.0.6 DONE}
	Launched Version: 1.16.1-forge-32.0.99
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.67, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: mod_resources, vanilla
	Current Language: Deutsch (Deutschland)
	CPU: 8x Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
	OptiFine Version: OptiFine_1.16.1_HD_U_G2_pre4
	OptiFine Build: 20200711-211327
	Render Distance Chunks: 12
	Mipmaps: 3
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 451.67
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by malte0811** [comment]
WTF, I thought they fixed that in Forge... And it's working fine in dev... I'll look into it later.

**Comment by Lurihan** [comment]
ty mate

**Comment by Lurihan** [comment]
dont know why. but now after doing nothing and replacing no files everything works. think here it was a picnic.
 problem in chair not in computer. think i was the problem. it was a buggy file in the mod folder

**Comment by Hero0fhellaS** [comment]
i do get that crash as well on singleplayer everytime i place an HV connector or when lookin at one and after that cant access the save file

**Comment by BluSunrize** [comment]
@Hero0fhellaS could you please provide all the necessary info? Crashlog, version numbers?

**Comment by Hero0fhellaS** [comment]
yes ofc.
Although i think it was optifine that was causing problems 
[crash-2020-08-10_10.21.51-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5049584/crash-2020-08-10_10.21.51-client.txt)

**Comment by BluSunrize** [comment]
So the crash is gone without optifine?

**Comment by Hero0fhellaS** [comment]
yes

**Comment by BluSunrize** [comment]
Great. @malte0811 can this be closed then?

**Comment by malte0811** [comment]
Yes, it can. Someone on Discord reported that updating OF fixed it as well IIRC.
