### ISSUE TITLE
Crash when Placing Connector onto Windmill

### ISSUE THREAD

**Issue by RennocDrac** [BluSunrize/ImmersiveEngineering#4195]
I get this crash everytime i place a connector on the windmill and also crashes world and does not allow to play anymore

---- Minecraft Crash Report ----
// Don't do that.

Time: 8/10/20 8:04 PM
Description: Unexpected error

java.lang.RuntimeException: No net handler found for dimension minecraft:overworld, remote: true
	at blusunrize.immersiveengineering.api.wires.GlobalWireNetwork.getNetwork(GlobalWireNetwork.java:74) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.api.wires.ImmersiveConnectableTileEntity.func_226984_a_(ImmersiveConnectableTileEntity.java:79) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.Chunk.func_177426_a(Chunk.java:408) ~[?:?] {re:classloading}
	at net.minecraft.world.World.func_175690_a(World.java:683) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:290) ~[?:?] {re:classloading}
	at net.minecraft.world.World.func_241211_a_(World.java:241) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.World.func_180501_a(World.java:218) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_180501_a(ClientWorld.java:735) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default}
	at net.minecraft.item.BlockItem.func_195941_b(BlockItem.java:149) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.common.blocks.BlockItemIE.func_195941_b(BlockItemIE.java:106) ~[?:?] {re:classloading}
	at net.minecraft.item.BlockItem.func_195942_a(BlockItem.java:54) ~[?:?] {re:classloading}
	at net.minecraft.item.BlockItem.func_195939_a(BlockItem.java:39) ~[?:?] {re:classloading}
	at net.minecraft.item.ItemStack.lambda$onItemUse$5(ItemStack.java:185) ~[?:?] {re:classloading}
	at net.minecraft.item.ItemStack$$Lambda$8634/80531371.apply(Unknown Source) ~[?:?] {}
	at net.minecraft.item.ItemStack.onItemUse(ItemStack.java:200) ~[?:?] {re:classloading}
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:185) ~[?:?] {re:classloading}
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:302) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.optifine.override.PlayerControllerOF.func_217292_a(PlayerControllerOF.java:97) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1340) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1597) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1434) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:928) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:582) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.107.jar:32.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$439/2021601975.call(Unknown Source) [forge-1.16.1-32.0.107.jar:32.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at blusunrize.immersiveengineering.api.wires.GlobalWireNetwork.getNetwork(GlobalWireNetwork.java:74)
	at blusunrize.immersiveengineering.api.wires.ImmersiveConnectableTileEntity.func_226984_a_(ImmersiveConnectableTileEntity.java:79)
	at net.minecraft.world.chunk.Chunk.func_177426_a(Chunk.java:408)
	at net.minecraft.world.World.func_175690_a(World.java:683)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:290)
	at net.minecraft.world.World.func_241211_a_(World.java:241)
	at net.minecraft.world.World.func_180501_a(World.java:218)
	at net.minecraft.client.world.ClientWorld.func_180501_a(ClientWorld.java:735)
	at net.minecraft.item.BlockItem.func_195941_b(BlockItem.java:149)
	at blusunrize.immersiveengineering.common.blocks.BlockItemIE.func_195941_b(BlockItemIE.java:106)
	at net.minecraft.item.BlockItem.func_195942_a(BlockItem.java:54)
	at net.minecraft.item.BlockItem.func_195939_a(BlockItem.java:39)
	at net.minecraft.item.ItemStack.lambda$onItemUse$5(ItemStack.java:185)
	at net.minecraft.item.ItemStack$$Lambda$8634/80531371.apply(Unknown Source)
	at net.minecraft.item.ItemStack.onItemUse(ItemStack.java:200)
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:185)
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:302)
	at net.optifine.override.PlayerControllerOF.func_217292_a(PlayerControllerOF.java:97)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1340)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1597)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['RennocDrac'/251, l='ClientLevel', x=13.35, y=70.66, z=157.15]]
	Chunk stats: Client Chunk Cache: 441, 289
	Level dimension: minecraft:overworld
	Level spawn location: World: (-16,63,144), Chunk: (at 0,3,0 in -1,9; contains blocks -16,0,144 to -1,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1509 game time, 1509 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:616)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:603)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$439/2021601975.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 16627739496 bytes (15857 MB) / 19058917376 bytes (18176 MB) up to 19327352832 bytes (18432 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx18G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.107.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.107.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.107.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.107.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/preview_OptiFine_1.16.1_HD_U_G2_pre12.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.1-32.0.107.jar fml TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.107
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		forge-1.16.1-32.0.107-client.jar Minecraft {minecraft@1.16.1 DONE}
		Industrial-Foregoing-Mod-1.16.1.jar Industrial Foregoing {industrialforegoing@3.0.4 DONE}
		Ranged-Pumps-Mod-1.16.1.jar Ranged Pumps {rangedpumps@0.8 DONE}
		Mutant-Beasts-Mod-1.16.1.jar Mutant Beasts {mutantbeasts@1.16.1-1.1.0 DONE}
		Titanium-Library-1.16.1.jar Titanium {titanium@3.0.4 DONE}
		ImmersiveEngineering-1.16.1-3.1-112.jar Immersive Engineering {immersiveengineering@1.16.1-3.1-112 DONE}
		Biomes-O-Plenty-Mod-1.16.1.jar Biomes O' Plenty {biomesoplenty@1.16.1-11.0.0.393 DONE}
		Hwyla-forge-1.10.10-B77_1.16.1.jar Waila {waila@1.10.10-B77_1.16.1 DONE}
		jei-1.16.1-7.0.0.7.jar Just Enough Items {jei@7.0.0.7 DONE}
		Forbidden-Arcanus-Mod-1.16.1.jar Forbidden & Arcanus {forbidden_arcanus@1.16.1-1.0.1 DONE}
		Towers-of-the-Wild-Mod-1.16.1.jar Towers Of the Wild {towers_of_the_wild@1.16.1-1.2.2 DONE}
		Falling-Tree-Mod-1.16.1.jar Falling Tree {falling_tree@2.2.1 DONE}
		JustEnoughResources-1.16.1-0.11.1.93.jar Just Enough Resources {jeresources@0.11.1.93 DONE}
		forge-1.16.1-32.0.107-universal.jar Forge {forge@32.0.107 DONE}
		Mantle-Mod-1.16.1.jar Mantle {mantle@1.6.20 DONE}
		Waystones_1.16.1-7.0.2.jar Waystones {waystones@7.0.2 DONE}
		ForgeEndertech-1.16.1-7.0.0.0-build.0006.jar Forge Endertech {forgeendertech@7.0.0.0 DONE}
		AdLods-1.16.1-4.0.0.0-build.0007.jar Large Ore Deposits {adlods@4.0.0.0 DONE}
		WailaHarvestability-mc1.16.1-forge-1.1.12.jar Waila Harvestability {wailaharvestability@1.1.12 DONE}
		ironchest-1.16.1-11.0.1.jar Iron Chests {ironchest@1.16.1-11.0.1 DONE}
		Applied-Energistics-2-Mod-1.16.1.jar Applied Energistics 2 {appliedenergistics2@8.0.0-alpha.1 DONE}
		xptome-1.16.1-v1.1.6.jar XP Tome {xpbook@v1.1.6 DONE}
		StorageDrawers-1.16.1-8.0.0.jar Storage Drawers {storagedrawers@1.16.1-8.0.0 DONE}
	Launched Version: 1.16.1-forge-32.0.107
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon (TM) R9 380 Series GL version 4.6.14736 Compatibility Profile Context 20.7.2 27.20.2001.9003, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x AMD A10-7850K Radeon R7, 12 Compute Cores 4C+8G
	OptiFine Version: OptiFine_1.16.1_HD_U_G2_pre12
	OptiFine Build: 20200730-021109
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.14736 Compatibility Profile Context 20.7.2 27.20.2001.9003
	OpenGlRenderer: AMD Radeon (TM) R9 380 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by malte0811** [comment]
Known issue with OptiFine. I think there's an update fixing it, in any case it's not an IE issue.
