### ISSUE TITLE
Crash When using minning drill.

### ISSUE THREAD

**Issue by RennocDrac** [BluSunrize/ImmersiveEngineering#4224]
Game crashed when using the mining drill with steel tip.

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 8/17/20 12:13 PM
Description: Unexpected error

java.lang.IllegalStateException: Already building!
	at net.minecraft.client.renderer.BufferBuilder.func_181668_a(BufferBuilder.java:177) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemRenderer.func_181565_a(ItemRenderer.java:336) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemRenderer.func_180453_a(ItemRenderer.java:310) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemRenderer.func_175030_a(ItemRenderer.java:286) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at blusunrize.immersiveengineering.client.ClientUtils.renderItemWithOverlayIntoGUI(ClientUtils.java:1279) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.client.ClientEventHandler.lambda$onRenderOverlayPost$3(ClientEventHandler.java:661) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.client.ClientEventHandler$$Lambda$10415/1544789664.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161) ~[?:?] {re:mixin,re:classloading}
	at blusunrize.immersiveengineering.client.ClientEventHandler.onRenderOverlayPost(ClientEventHandler.java:636) ~[?:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_318_ClientEventHandler_onRenderOverlayPost_Post.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.client.gui.ForgeIngameGui.post(ForgeIngameGui.java:832) ~[?:?] {re:classloading}
	at net.minecraftforge.client.gui.ForgeIngameGui.renderHUDText(ForgeIngameGui.java:658) ~[?:?] {re:classloading}
	at net.minecraftforge.client.gui.ForgeIngameGui.func_238445_a_(ForgeIngameGui.java:187) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:461) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:951) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:582) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.108.jar:32.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$435/169916747.call(Unknown Source) [forge-1.16.1-32.0.108.jar:32.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.BufferBuilder.func_181668_a(BufferBuilder.java:177)
	at net.minecraft.client.renderer.ItemRenderer.func_181565_a(ItemRenderer.java:336)
	at net.minecraft.client.renderer.ItemRenderer.func_180453_a(ItemRenderer.java:310)
	at net.minecraft.client.renderer.ItemRenderer.func_175030_a(ItemRenderer.java:286)
	at blusunrize.immersiveengineering.client.ClientUtils.renderItemWithOverlayIntoGUI(ClientUtils.java:1279)
	at blusunrize.immersiveengineering.client.ClientEventHandler.lambda$onRenderOverlayPost$3(ClientEventHandler.java:661)
	at blusunrize.immersiveengineering.client.ClientEventHandler$$Lambda$10415/1544789664.accept(Unknown Source)
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161)
	at blusunrize.immersiveengineering.client.ClientEventHandler.onRenderOverlayPost(ClientEventHandler.java:636)
	at net.minecraftforge.eventbus.ASMEventHandler_318_ClientEventHandler_onRenderOverlayPost_Post.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraftforge.client.gui.ForgeIngameGui.post(ForgeIngameGui.java:832)
	at net.minecraftforge.client.gui.ForgeIngameGui.renderHUDText(ForgeIngameGui.java:658)
	at net.minecraftforge.client.gui.ForgeIngameGui.func_238445_a_(ForgeIngameGui.java:187)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['RennocDrac'/173, l='ClientLevel', x=92.95, y=51.00, z=60.31]]
	Chunk stats: Client Chunk Cache: 441, 244
	Level dimension: minecraft:overworld
	Level spawn location: World: (-16,64,-137), Chunk: (at 0,4,7 in -1,-9; contains blocks -16,0,-144 to -1,255,-129), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 568430 game time, 70126 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:446)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:603)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$435/169916747.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 15417990448 bytes (14703 MB) / 19327352832 bytes (18432 MB) up to 19327352832 bytes (18432 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx18G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.1-32.0.108.jar fml TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.108
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		forge-1.16.1-32.0.108-client.jar Minecraft {minecraft@1.16.1 DONE}
		Industrial-Foregoing-Mod-1.16.1.jar Industrial Foregoing {industrialforegoing@3.0.4 DONE}
		inventorysorter-1.16.1-18.0.0.jar Simple Inventory Sorter {inventorysorter@18.0.0 DONE}
		Titanium-Library-1.16.1.jar Titanium {titanium@3.0.4 DONE}
		ImmersiveEngineering-1.16.1-3.1-112.jar Immersive Engineering {immersiveengineering@1.16.1-3.1-112 DONE}
		Biomes-O-Plenty-Mod-1.16.1.jar Biomes O' Plenty {biomesoplenty@1.16.1-11.0.0.393 DONE}
		valhelsia_structures-16.0.1.jar Valhelsia Structures {valhelsia_structures@16.0.1 DONE}
		dungeons-plus-1.16.1-1.0.2.jar Dungeons Plus {dungeons_plus@1.0.2 DONE}
		mining_dimension-1.16.1-1.0.5.jar Mining World {mining_dimension@1.16.1-1.0.5 DONE}
		jei-1.16.1-7.0.0.7.jar Just Enough Items {jei@7.0.0.7 DONE}
		Forbidden-Arcanus-Mod-1.16.1.jar Forbidden & Arcanus {forbidden_arcanus@1.16.1-1.0.1 DONE}
		Towers-of-the-Wild-Mod-1.16.1.jar Towers Of the Wild {towers_of_the_wild@1.16.1-1.2.2 DONE}
		Falling-Tree-Mod-1.16.1.jar Falling Tree {falling_tree@2.2.1 DONE}
		portality-1.16.1-3.1.0.jar Portality {portality@3.1.0 DONE}
		invtweaks-1.16.1-1.0.6.jar Inventory Tweaks Renewed {invtweaks@1.16.1-1.0.6 DONE}
		Mantle-Mod-1.16.1.jar Mantle {mantle@1.6.20 DONE}
		Waystones_1.16.1-7.0.2.jar Waystones {waystones@7.0.2 DONE}
		ForgeEndertech-1.16.1-7.0.0.0-build.0006.jar Forge Endertech {forgeendertech@7.0.0.0 DONE}
		AdLods-1.16.1-4.0.0.0-build.0007.jar Large Ore Deposits {adlods@4.0.0.0 DONE}
		pamhc2foodcore-1.16.1-1.0.5.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		dankstorage-3.7b.jar Dank Storage {dankstorage@3.7b DONE}
		appliedenergistics2-8.0.0-beta.1.jar Applied Energistics 2 {appliedenergistics2@8.0.0-beta.1 DONE}
		StorageDrawers-1.16.1-8.0.0.jar Storage Drawers {storagedrawers@1.16.1-8.0.0 DONE}
		Ranged-Pumps-Mod-1.16.1.jar Ranged Pumps {rangedpumps@0.8 DONE}
		DungeonCrawl-1.16.1-2.0.2.jar Dungeon Crawl {dungeoncrawl@2.0.2 DONE}
		Mutant-Beasts-Mod-1.16.1.jar Mutant Beasts {mutantbeasts@1.16.1-1.1.0 DONE}
		pneumaticcraft-repressurized-1.16.1-2.1.0-11.jar PneumaticCraft: Repressurized {pneumaticcraft@1.16.1-2.1.0-11 DONE}
		Hwyla-forge-1.10.10-B77_1.16.1.jar Waila {waila@1.10.10-B77_1.16.1 DONE}
		JustEnoughResources-1.16.1-0.11.1.93.jar Just Enough Resources {jeresources@0.11.1.93 DONE}
		forge-1.16.1-32.0.108-universal.jar Forge {forge@32.0.108 DONE}
		WailaHarvestability-mc1.16.1-forge-1.1.12.jar Waila Harvestability {wailaharvestability@1.1.12 DONE}
		structure-gel-api-1.16.1-1.2.1.jar Structure Gel API {structure_gel@1.2.1 DONE}
		ironchest-1.16.1-11.0.1.jar Iron Chests {ironchest@1.16.1-11.0.1 DONE}
		xptome-1.16.1-v1.1.6.jar XP Tome {xpbook@v1.1.6 DONE}
	Launched Version: 1.16.1-forge-32.0.108
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon (TM) R9 380 Series GL version 4.6.14736 Compatibility Profile Context 20.7.2 27.20.2001.9003, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x AMD A10-7850K Radeon R7, 12 Compute Cores 4C+8G

**Comment by BluSunrize** [comment]
Update IE.

And follow the issue template next time.
