### ISSUE TITLE
[1.15.2] ConcurrentModificationException in world save

### ISSUE THREAD

**Issue by OreCruncher** [BluSunrize/ImmersiveEngineering#4297]
### Description of the issue:
Just exploring and the server crashed.  The server is a dedicated.  When the world restarted everything looked fine.  I believe that new chunks were being generated as I was exploring.

### Crashlog:
https://gist.github.com/OreCruncher/822dcd553a47b218ac5af0de946bbfc3

Snip - complete stack in crash log:
```
java.util.ConcurrentModificationException: null
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911) ~[?:1.8.0_265] {}
at java.util.ArrayList$Itr.next(ArrayList.java:861) ~[?:1.8.0_265] {}
at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:496) ~[server-1.15.2-extra.jar:?] {}
at blusunrize.immersiveengineering.common.IESaveData.func_189551_b(IESaveData.java:106) ~[?:?] {re:classloading}
at net.minecraft.world.storage.WorldSavedData.func_215158_a(WorldSavedData.java:44) ~[?:?] {re:classloading}
at net.minecraft.world.storage.DimensionSavedDataManager.func_212775_b(DimensionSavedDataManager.java:125) ~[?:?] {re:classloading}
at net.minecraft.world.server.ServerWorld.func_73042_a(ServerWorld.java:761) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,xf:fml:immersiveengineering:IE block update callback,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.world.server.ServerWorld.func_217445_a(ServerWorld.java:748) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,xf:fml:immersiveengineering:IE block update callback,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:528) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:804) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265] {}
```

### Versions & Modlist
forge-1.15.2-31.2.36
ImmersiveEngineering-1.15.2-3.2.0-114
Mod List in crash report (All the Mods 5 2.18)

**Comment by BluSunrize** [comment]
You're not using the latest release of IE. Please try to replicate this on latest version and then open a new issue.
