### ISSUE TITLE
The mod crashed on startup :c

### ISSUE THREAD

**Issue by xXMolgadoGamer01Xx** [BluSunrize/ImmersiveEngineering#4385]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 16/10/20 02:15 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:494) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$4889/1488869438.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:418) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:490) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$4676/1384781563.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:totaldarkness.mixins.json:MixinGameRenderer,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.19.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$482/444380068.call(Unknown Source) [forge-1.16.3-34.1.19.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1353) ~[?:1.8.0_51] {}
-- MOD immersiveengineering --
Details:
	Caused by 0: java.lang.ExceptionInInitializerError
		at blusunrize.immersiveengineering.common.blocks.metal.conveyors.BasicConveyor.<clinit>(BasicConveyor.java:308) ~[?:?] {re:classloading}
		at blusunrize.immersiveengineering.common.IEContent.modConstruction(IEContent.java:140) ~[?:?] {re:classloading}
		at blusunrize.immersiveengineering.ImmersiveEngineering.<init>(ImmersiveEngineering.java:107) ~[?:?] {re:classloading}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51] {}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51] {}
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
		at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:34.1] {re:classloading}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3042/1325269327.run(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:111) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModContainer$$Lambda$3149/1128958264.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

	Mod File: ImmersiveEngineering-1.16.3-4.1.0-124.jar
	Failure message: Immersive Engineering (immersiveengineering) has failed to load correctly
		java.lang.ExceptionInInitializerError: null
	Mod Version: 1.16.3-4.1.0-124
	Mod Issue URL: https://github.com/BluSunrize/ImmersiveEngineering/issues
	Exception message: java.util.ConcurrentModificationException
Stacktrace:
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1353) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:469) ~[?:1.8.0_51] {}
	at blusunrize.immersiveengineering.common.data.DataGenUtils.createWrapperTag(DataGenUtils.java:114) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.common.data.DataGenUtils.createItemWrapper(DataGenUtils.java:100) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.api.IETags.<clinit>(IETags.java:39) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.common.blocks.metal.conveyors.BasicConveyor.<clinit>(BasicConveyor.java:308) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.common.IEContent.modConstruction(IEContent.java:140) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.ImmersiveEngineering.<init>(ImmersiveEngineering.java:107) ~[?:?] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:34.1] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3042/1325269327.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:111) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3149/1128958264.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1803419856 bytes (1719 MB) / 3019898880 bytes (2880 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.19.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.19.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.19.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.19.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/preview_OptiFine_1.16.3_HD_U_G4_pre2.jar OptiFine TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.3-0.3.4.jar optiforge TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.19.jar fml TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.3-0.3.4.jar FakeOptiFine TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.3-0.3.4.jar optiforgewrapper TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.19
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		UnionLib-1.16.3-3.0.0.jar UnionLib {unionlib@3.0.0 CREATE_REGISTRIES}
		NetherPortalFix_1.16.3-7.2.0.jar NetherPortalFix {netherportalfix@7.2.0 CREATE_REGISTRIES}
		spiders-2.0-1.16.3-1.0.1.jar Spiders 2.0 {spiderstpo@1.0.1 CREATE_REGISTRIES}
		giantspawn_1.16.3-2.2.jar Giant Spawn {giantspawn@2.2 CREATE_REGISTRIES}
		ceiling_carpets-mc1.16.1_v0.0.1.jar Ceiling Carpets {ceiling_carpets@0.0.1 CREATE_REGISTRIES}
		OptiForge-MC1.16.3-0.3.4.jar OptiForge {optiforge@0.3.4 CREATE_REGISTRIES}
		the-conjurer-1.16.3-1.0.11.jar The Conjurer {conjurer_illager@1.0.11 CREATE_REGISTRIES}
		caelus-forge-1.16.3-2.0.0.3.jar Caelus API {caelus@1.16.3-2.0.0.3 CREATE_REGISTRIES}
		TextDamageIndicators-1.16.3-2.0.1.jar TextDamageIndicators {textdamageindicators@2.0.1 CREATE_REGISTRIES}
		BetterCaves-1.16.2-1.0.3.jar YUNG's Better Caves {bettercaves@1.16.2-1.0.3 CREATE_REGISTRIES}
		Waystones_1.16.3-7.3.0.jar Waystones {waystones@7.3.0 CREATE_REGISTRIES}
		totaldarkness-1.1-1.16.3.jar Total Darkness {totaldarkness@1.1-1.16.3 CREATE_REGISTRIES}
		villagernames_1.16.3-2.5.jar Villager Names {villagernames@2.5 CREATE_REGISTRIES}
		Clumps-6.0.0.11.jar Clumps {clumps@6.0.0.11 CREATE_REGISTRIES}
		Placebo-1.16.3-4.3.2.jar Placebo {placebo@4.3.2 CREATE_REGISTRIES}
		comforts-forge-1.16.3-4.0.0.1.jar Comforts {comforts@1.16.3-4.0.0.1 CREATE_REGISTRIES}
		citadel-1.4.0.jar Citadel {citadel@1.4.0 CREATE_REGISTRIES}
		champions-forge-1.16.3-2.0.0.1.jar Champions {champions@1.16.3-2.0.0.1 CREATE_REGISTRIES}
		Bookshelf-1.16.3-8.4.15.jar Bookshelf {bookshelf@8.4.15 CREATE_REGISTRIES}
		Coins-1.16.3-4.0.2.jar Coins {coins@4.0.2 CREATE_REGISTRIES}
		guardvillagers-1.16.3-1.1.5.jar Guard Villagers {guardvillagers@1.1.5 CREATE_REGISTRIES}
		randompatches-1.16.2-1.22.1.2.jar RandomPatches {randompatches@1.16.2-1.22.1.2 CREATE_REGISTRIES}
		unbreakables-1.16.2-1.0.0.jar Unbreakable Spawners {unbreakables@1.16.2-1.0.0 CREATE_REGISTRIES}
		iceandfire-2.1.0-1.16.3.jar Ice and Fire {iceandfire@2.0.3-1.16.3 CREATE_REGISTRIES}
		forge-1.16.3-34.1.19-universal.jar Forge {forge@34.1.19 CREATE_REGISTRIES}
		scuba-gear-1.16.3-1.0.1.jar Scuba Gear {scuba_gear@1.0.1 CREATE_REGISTRIES}
		morewires-1.16.3-1.1.0.0.jar More Wires {morewires@1.16.3-1.1.0.0 CREATE_REGISTRIES}
		structure-gel-api-1.16.3-1.4.0.jar Structure Gel API {structure_gel@1.4.0 CREATE_REGISTRIES}
		forge-1.16.3-34.1.19-client.jar Minecraft {minecraft@1.16.3 CREATE_REGISTRIES}
		repurposed_structures-1.16.3-2.2.8.jar Repurposed Structures {repurposed_structures@1.16.3-2.2.8 CREATE_REGISTRIES}
		ImmersiveEngineering-1.16.3-4.1.0-124.jar Immersive Engineering {immersiveengineering@1.16.3-4.1.0-124 ERROR}
		SaveYourPets-1.16.2-1.0.0.4.jar Save Your Pets {syp@1.0.0.4 CREATE_REGISTRIES}
		practicaltools-1.16.3-1.8.jar Practical Tools {practicaltools@1.16.3-1.8 CREATE_REGISTRIES}
		rare-ice-0.2.2.jar Rare Ice {rare-ice@version CREATE_REGISTRIES}
		curios-forge-1.16.3-4.0.2.0.jar Curios API {curios@1.16.3-4.0.2.0 CREATE_REGISTRIES}
		collective-1.16.3-1.51.jar Collective {collective@1.51 CREATE_REGISTRIES}
		levelhearts-1.16.2-2.2.0.jar LevelHearts {levelhearts@2.2.0 CREATE_REGISTRIES}
		betterweather-1.0.3.jar Better Weather {betterweather@1.0.1 CREATE_REGISTRIES}
		FastWorkbench-1.16.3-4.4.0.jar FastWorkbench {fastbench@4.4.0 CREATE_REGISTRIES}
		[1.16.2]+SecurityCraft+v1.8.19.3.jar SecurityCraft {securitycraft@v1.8.19.3 CREATE_REGISTRIES}
		sit-1.16.2-v1.3.jar Sit {sit@v1.3 CREATE_REGISTRIES}
		backpacked-1.5.2-1.16.3.jar Backpacked {backpacked@1.5.2 CREATE_REGISTRIES}
		Survive-1.16.3-3.0.0.jar Survive {survive@1.16.3-3.0.0 CREATE_REGISTRIES}
		illagersweararmor-1.0.1.jar Illagers Wear Armor {illagersweararmor@1.0.1 CREATE_REGISTRIES}
		hunterillager-1.16.3-1.1.0.jar HunterIllager {hunterillager@1.16.3-1.1.0 CREATE_REGISTRIES}
		curiouselytra-forge-1.16.3-4.0.0.1.jar Curious Elytra {curiouselytra@1.16.3-4.0.0.1 CREATE_REGISTRIES}
		byg-1.0.7.jar Oh The Biomes You'll Go {byg@1.0.7 CREATE_REGISTRIES}
		Aquaculture-1.16.3-2.1.1.jar Aquaculture 2 {aquaculture@1.16.3-2.1.1 CREATE_REGISTRIES}
		enchantwithmob-1.16.3-1.7.0.jar Enchant With Mob {enchantwithmob@1.16.3-1.7.0 CREATE_REGISTRIES}
		BetterBurning-1.16.3-4.0.2.jar BetterBurning {betterburning@4.0.2 CREATE_REGISTRIES}
		CosmeticArmorReworked-1.16.3-v1.jar CosmeticArmorReworked {cosmeticarmorreworked@1.16.3-v1 CREATE_REGISTRIES}
		BetterMineshaftsForge-1.16.2-1.0.jar YUNG's Better Mineshafts {bettermineshafts@1.16.2-1.0 CREATE_REGISTRIES}
		ettubrute-1.16.2+1.16.3-2.0.0.jar Et Tu, Brute? {ettubrute@2.0.0 CREATE_REGISTRIES}
		farlanders-1.16.3-1.3.4.jar The Farlanders {farlanders@1.3.4 CREATE_REGISTRIES}
	Crash Report UUID: 43d84b11-81b0-452f-b6e4-e0acdb570587
	OptiFine Version: OptiFine_1.16.3_HD_U_G4_pre2
	OptiFine Build: 20201007-190609
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.14736 Compatibility Profile Context 20.8.3 27.20.12027.1001
	OpenGlRenderer: AMD Radeon(TM) R5 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by mpmxyz** [comment]
Have you tried to run your Minecraft without Optifine/OptiForge?
According to the [Contributing Guidelines](https://github.com/BluSunrize/ImmersiveEngineering/blob/1.15/CONTRIBUTING.md) they may be a cause for all kinds of errors.

**Comment by BluSunrize** [comment]
Can you reproduce this issue with just Forge and IE?

**Comment by BluSunrize** [comment]
Closed due to lack of response
