### ISSUE TITLE
Immersive Engineering (immersiveengineering) encountered an error during the load_registries event phase.

### ISSUE THREAD

**Issue by mrh0** [BluSunrize/ImmersiveEngineering#4424]
Launching IE in a custom modpack.
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 11/2/20 2:16 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:494) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$9777/2103744471.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(SourceFile:404) [?:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:490) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$9567/902195457.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:480) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.42.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$467/1134237170.call(Unknown Source) [forge-1.16.3-34.1.42.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:56) ~[?:?] {re:classloading}
-- MOD immersiveengineering --
Details:
	Caused by 0: java.lang.ExceptionInInitializerError
		at blusunrize.immersiveengineering.common.util.RecipeSerializers$$Lambda$4930/595651989.get(Unknown Source) ~[?:?] {}
		at net.minecraftforge.registries.DeferredRegister.lambda$register$0(DeferredRegister.java:124) ~[?:?] {re:classloading}
		at net.minecraftforge.registries.DeferredRegister$$Lambda$3124/215694469.get(Unknown Source) ~[?:?] {}
		at net.minecraftforge.registries.DeferredRegister.addEntries(DeferredRegister.java:200) ~[?:?] {re:classloading}
		at net.minecraftforge.registries.DeferredRegister.access$000(DeferredRegister.java:61) ~[?:?] {re:classloading}
		at net.minecraftforge.registries.DeferredRegister$EventDispatcher.handleEvent(DeferredRegister.java:172) ~[?:?] {re:classloading}
		at net.minecraftforge.eventbus.ASMEventHandler_6_EventDispatcher_handleEvent_Register.invoke(.dynamic) ~[?:?] {}
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:34.1] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:111) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModContainer$$Lambda$3578/894818308.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
		at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:242) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:229) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:195) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2895/1685820260.run(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2896/191614132.run(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraft.client.Minecraft.<init>(Minecraft.java:424) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
		at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
		at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
		at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.42.jar:34.1] {}
		at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$467/1134237170.call(Unknown Source) [forge-1.16.3-34.1.42.jar:34.1] {}
		at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
		at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
		at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

	Mod File: ImmersiveEngineering-1.16.3-4.1.0-124.jar
	Failure message: Immersive Engineering (immersiveengineering) encountered an error during the load_registries event phase
		java.lang.ExceptionInInitializerError: null
	Mod Version: 1.16.3-4.1.0-124
	Mod Issue URL: https://github.com/BluSunrize/ImmersiveEngineering/issues
	Exception message: java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods.
Stacktrace:
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:56) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:72) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.NamespacedWrapper.func_218381_a(NamespacedWrapper.java:40) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.Registry.func_218322_a(Registry.java:456) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.util.registry.Registry.func_218325_a(Registry.java:452) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.item.crafting.IRecipeSerializer.func_222156_a(IRecipeSerializer.java:39) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.common.crafting.serializers.RevolverAssemblyRecipeSerializer.<clinit>(RevolverAssemblyRecipeSerializer.java:27) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.common.util.RecipeSerializers$$Lambda$4930/595651989.get(Unknown Source) ~[?:?] {}
	at net.minecraftforge.registries.DeferredRegister.lambda$register$0(DeferredRegister.java:124) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.DeferredRegister$$Lambda$3124/215694469.get(Unknown Source) ~[?:?] {}
	at net.minecraftforge.registries.DeferredRegister.addEntries(DeferredRegister.java:200) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.DeferredRegister.access$000(DeferredRegister.java:61) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.DeferredRegister$EventDispatcher.handleEvent(DeferredRegister.java:172) ~[?:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_6_EventDispatcher_handleEvent_Register.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:34.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:111) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3578/894818308.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:242) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:229) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:195) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2895/1685820260.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2896/191614132.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:424) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.42.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$467/1134237170.call(Unknown Source) [forge-1.16.3-34.1.42.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 816828208 bytes (778 MB) / 2775056384 bytes (2646 MB) up to 5726797824 bytes (5461 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6144m -Xms256m -XX:PermSize=256m
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.42.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.42.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.42.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.42.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.42.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.42
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		QuarkOddities-1.16.3.jar                          |Quark Oddities                |quarkoddities                 |1.16.3              |COMMON_SET|NOSIGNATURE
		inventorysorter-1.16.1-18.1.0.jar                 |Simple Inventory Sorter       |inventorysorter               |18.1.0              |COMMON_SET|NOSIGNATURE
		ClientTweaks_1.16.3-5.2.0.jar                     |Client Tweaks                 |clienttweaks                  |5.2.0               |COMMON_SET|NOSIGNATURE
		SimplyJetpacks2-1.16.3-2.6.3.0.jar                |Simply Jetpacks 2             |simplyjetpacks                |1.16.3-2.6.3.0      |COMMON_SET|NOSIGNATURE
		Cucumber-1.16.3-4.1.3.jar                         |Cucumber Library              |cucumber                      |4.1.3               |COMMON_SET|NOSIGNATURE
		Bountiful Baubles FORGE-1.16.3-0.0.1.jar          |Bountiful Baubles             |bountifulbaubles              |NONE                |COMMON_SET|NOSIGNATURE
		jei-1.16.3-7.6.0.49.jar                           |Just Enough Items             |jei                           |7.5.0.43            |COMMON_SET|NOSIGNATURE
		DoggyTalents-1.16.3-2.0.1.0.jar                   |Doggy Talents 2               |doggytalents                  |2.0.1.0             |COMMON_SET|NOSIGNATURE
		Mekanism-1.16.3-10.0.15.441.jar                   |Mekanism                      |mekanism                      |10.0.15             |COMMON_SET|NOSIGNATURE
		caelus-forge-1.16.3-2.0.0.3.jar                   |Caelus API                    |caelus                        |1.16.3-2.0.0.3      |COMMON_SET|NOSIGNATURE
		rsgauges-1.16.3-1.2.4.jar                         |Gauges and Switches           |rsgauges                      |1.2.4               |COMMON_SET|NOSIGNATURE
		essentials-1.16.3-2.9.4.jar                       |Essentials                    |essentials                    |1.16.3-2.9.4        |COMMON_SET|NOSIGNATURE
		BetterCaves-1.16.2-1.0.4.jar                      |YUNG's Better Caves           |bettercaves                   |1.16.2-1.0.4        |COMMON_SET|NOSIGNATURE
		ForgeEndertech-1.16.3-7.0.6.0-build.0024.jar      |Forge Endertech               |forgeendertech                |7.0.6.0             |COMMON_SET|NOSIGNATURE
		Placebo-1.16.3-4.3.3.jar                          |Placebo                       |placebo                       |4.3.3               |COMMON_SET|NOSIGNATURE
		citadel-1.4.1.jar                                 |Citadel                       |citadel                       |1.4.1               |COMMON_SET|NOSIGNATURE
		appliedenergistics2-8.1.0-beta.2.jar              |Applied Energistics 2         |appliedenergistics2           |8.1.0-beta.2        |COMMON_SET|95:58:cc:83:9d:a8:fa:4f:e9:f3:54:90:66:61:c8:ae:9c:08:88:11:52:52:df:2d:28:5f:05:d8:28:57:0f:98
		Powah-1.16.3-2.3.4.jar                            |Powah                         |powah                         |2.3.4               |COMMON_SET|NOSIGNATURE
		decorative_blocks-1.16.2-1.1.jar                  |Decorative Blocks             |decorative_blocks             |1.5                 |COMMON_SET|NOSIGNATURE
		rangedpumps-0.8.2.jar                             |Ranged Pumps                  |rangedpumps                   |0.8.2               |COMMON_SET|NOSIGNATURE
		engineerstools-1.16.3-1.1.0.jar                   |Engineer's Tools              |engineerstools                |1.1.0               |COMMON_SET|NOSIGNATURE
		curioofundying-forge-1.16.3-5.0.0.1.jar           |Curio of Undying              |curioofundying                |1.16.3-5.0.0.1      |COMMON_SET|NOSIGNATURE
		culinaryconstruct-forge-1.16.3-4.0.0.1.jar        |Culinary Construct            |culinaryconstruct             |1.16.3-4.0.0.1      |COMMON_SET|NOSIGNATURE
		Bookshelf-1.16.3-8.7.20.jar                       |Bookshelf                     |bookshelf                     |8.7.20              |COMMON_SET|NOSIGNATURE
		reliquary-1.16.3-1.3.4.1048.jar                   |Reliquary                     |xreliquary                    |1.16.3-1.3.4.1048   |COMMON_SET|NOSIGNATURE
		DarkUtilities-1.16.3-6.0.1.jar                    |Dark Utilities                |darkutils                     |6.0.1               |COMMON_SET|NOSIGNATURE
		mcw-doors-1.0.1fix-mc1.16.3-1.16.2.jar            |Macaw's Doors                 |mcwdoors                      |1.0.1               |COMMON_SET|NOSIGNATURE
		MekanismGenerators-1.16.3-10.0.15.441.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.15             |COMMON_SET|NOSIGNATURE
		JEITweaker-1.16.3-1.0.1.4.jar                     |JEI Tweaker                   |jeitweaker                    |1.0.1.4             |COMMON_SET|NOSIGNATURE
		mininggadgets-1.6.0.jar                           |Mining Gadgets                |mininggadgets                 |1.6.0               |COMMON_SET|NOSIGNATURE
		JustEnoughResources-1.16.3-0.12.0.100.jar         |Just Enough Resources         |jeresources                   |0.12.0.100          |COMMON_SET|NOSIGNATURE
		CraftTweaker-1.16.3-7.0.0.48.jar                  |CraftTweaker                  |crafttweaker                  |7.0.0.48            |COMMON_SET|NOSIGNATURE
		forge-1.16.3-34.1.42-universal.jar                |Forge                         |forge                         |34.1.42             |COMMON_SET|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		MysticalAgradditions-1.16.3-4.1.0.jar             |Mystical Agradditions         |mysticalagradditions          |4.1.0               |COMMON_SET|NOSIGNATURE
		absentbydesign-1.16.3-1.1.1.jar                   |Absent By Design Mod          |absentbydesign                |1.16.3-1.1.1        |COMMON_SET|1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		MysticalAgriculture-1.16.3-4.1.1.jar              |Mystical Agriculture          |mysticalagriculture           |4.1.1               |COMMON_SET|NOSIGNATURE
		ironchest-1.16.3-11.2.6.jar                       |Iron Chests                   |ironchest                     |1.16.3-11.2.6       |COMMON_SET|NOSIGNATURE
		ZeroCore2-1.16.3-2.0.0.jar                        |Zero CORE 2                   |zerocore                      |1.16.3-2.0.0        |COMMON_SET|NOSIGNATURE
		forge-1.16.3-34.1.42-client.jar                   |Minecraft                     |minecraft                     |1.16.3              |COMMON_SET|NOSIGNATURE
		cofh_core-1.16.3-1.0.0.jar                        |CoFH Core                     |cofh_core                     |1.0.0               |COMMON_SET|NOSIGNATURE
		thermal-1.16.3-1.0.1.jar                          |Thermal Series                |thermal                       |1.0.1               |COMMON_SET|NOSIGNATURE
		repurposed_structures-1.16.3-2.2.11.jar           |Repurposed Structures         |repurposed_structures         |1.16.3-2.2.11       |COMMON_SET|NOSIGNATURE
		AmbientSounds_v3.0.21_mc1.16.2.jar                |Ambient Sounds                |ambientsounds                 |3.0.3               |COMMON_SET|NOSIGNATURE
		thermal_innovation-1.16.3-1.0.0.jar               |Thermal Innovation            |thermal_innovation            |1.0.0               |COMMON_SET|NOSIGNATURE
		MouseTweaks-2.13-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.13                |COMMON_SET|NOSIGNATURE
		titanium-1.16.3-3.1.0.jar                         |Titanium                      |titanium                      |3.1.0               |COMMON_SET|NOSIGNATURE
		ImmersiveEngineering-1.16.3-4.1.0-124.jar         |Immersive Engineering         |immersiveengineering          |1.16.3-4.1.0-124    |VALIDATE  |44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		BiomesOPlenty-1.16.3-12.0.0.416-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.3-12.0.0.416   |COMMON_SET|NOSIGNATURE
		MekanismAdditions-1.16.3-10.0.15.441.jar          |Mekanism: Additions           |mekanismadditions             |10.0.15             |COMMON_SET|NOSIGNATURE
		valhelsia_structures-16.0.5.jar                   |Valhelsia Structures          |valhelsia_structures          |16.0.5              |COMMON_SET|NOSIGNATURE
		Lollipop-1.16.3-3.2.2.jar                         |Lollipop                      |lollipop                      |3.2.2               |COMMON_SET|NOSIGNATURE
		mcw-trapdors-1.0.0-mc1.16.3.jar                   |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.0               |COMMON_SET|NOSIGNATURE
		AdLods-1.16.3-4.1.1.0-build.0026.jar              |Large Ore Deposits            |adlods                        |4.1.1.0             |COMMON_SET|NOSIGNATURE
		jeiintegration_1.16.3-6.0.0.8.jar                 |JEI Integration               |jeiintegration                |6.0.0.8             |COMMON_SET|NOSIGNATURE
		portality-1.16.3-3.1.1.jar                        |Portality                     |portality                     |3.1.1               |COMMON_SET|NOSIGNATURE
		curios-forge-1.16.3-4.0.2.0.jar                   |Curios API                    |curios                        |1.16.3-4.0.2.0      |COMMON_SET|NOSIGNATURE
		Botania-1.16.3-409.jar                            |Botania                       |botania                       |1.16.3-409          |COMMON_SET|NOSIGNATURE
		Patchouli-1.16.2-47.jar                           |Patchouli                     |patchouli                     |1.16.2-47           |COMMON_SET|NOSIGNATURE
		rats-7.0.0-1.16.3.jar                             |Rats                          |rats                          |7.0.0               |COMMON_SET|NOSIGNATURE
		gravestone-1.16.3-1.0.2.jar                       |Gravestone Mod                |gravestone                    |1.16.3-1.0.2        |COMMON_SET|NOSIGNATURE
		thermal_cultivation-1.16.3-1.0.0.jar              |Thermal Cultivation           |thermal_cultivation           |1.0.0               |COMMON_SET|NOSIGNATURE
		FastWorkbench-1.16.3-4.4.0.jar                    |FastWorkbench                 |fastbench                     |4.4.0               |COMMON_SET|NOSIGNATURE
		polymorph-forge-1.16.3-0.15.jar                   |Polymorph                     |polymorph                     |1.16.3-0.15         |COMMON_SET|NOSIGNATURE
		AutoRegLib-1.6-46.jar                             |AutoRegLib                    |autoreglib                    |1.6-46              |COMMON_SET|NOSIGNATURE
		Quark-r2.4-272.jar                                |Quark                         |quark                         |r2.4-272            |COMMON_SET|NOSIGNATURE
		StorageDrawers-1.16.3-8.2.1.jar                   |Storage Drawers               |storagedrawers                |8.2.1               |COMMON_SET|NOSIGNATURE
		FluxNetworks-1.16.3-6.0.1.4.jar                   |Flux Networks                 |fluxnetworks                  |1.16.3-6.0.1.4      |COMMON_SET|NOSIGNATURE
		thermal_expansion-1.16.3-1.0.1.jar                |Thermal Expansion             |thermal_expansion             |1.0.1               |COMMON_SET|NOSIGNATURE
		obfuscate-0.5.0-1.16.3.jar                        |Obfuscate                     |obfuscate                     |0.5.0               |COMMON_SET|e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		vehicle-mod-0.45.1-1.16.3.jar                     |MrCrayfish's Vehicle Mod      |vehicle                       |0.45.1              |COMMON_SET|NOSIGNATURE
		Runelic-1.16.3-5.0.1.jar                          |Runelic                       |runelic                       |5.0.1               |COMMON_SET|NOSIGNATURE
		MekanismTools-1.16.3-10.0.15.441.jar              |Mekanism: Tools               |mekanismtools                 |10.0.15             |COMMON_SET|NOSIGNATURE
		mcws-roofs-1.16.3-v2.0.0.jar                      |Macaw's Roofs                 |mcwroofs                      |2.0.0               |COMMON_SET|NOSIGNATURE
		furniture-7.0.0-pre19-1.16.3.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre19         |COMMON_SET|NOSIGNATURE
		engineersdecor-1.16.3-1.1.2.jar                   |Engineer's Decor              |engineersdecor                |1.1.2               |COMMON_SET|NOSIGNATURE
		curiouselytra-forge-1.16.3-4.0.0.1.jar            |Curious Elytra                |curiouselytra                 |1.16.3-4.0.0.1      |COMMON_SET|NOSIGNATURE
		cc-tweaked-1.16.3-1.93.1.jar                      |CC: Tweaked                   |computercraft                 |1.93.1              |COMMON_SET|NOSIGNATURE
		ExtremeReactors2-1.16.3-2.0.0.jar                 |Extreme Reactors 2            |bigreactors                   |1.16.3-2.0.0        |COMMON_SET|NOSIGNATURE
		BetterMineshaftsForge-1.16.2-1.0.1.jar            |YUNG's Better Mineshafts      |bettermineshafts              |1.16.2-1.0.1        |COMMON_SET|NOSIGNATURE
	Crash Report UUID: 9c9b438c-7d75-4a02-9940-9775098c9e8b

**Comment by mrh0** [comment]
The logs mentioned botania but I get the same error (without a mention of botania) when I removed botania.

I find this line interesting: "Exception message: java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods."

**Comment by BluSunrize** [comment]
Downgrade to Forge version 34.1.25 until the next release of IE. And please search recent issues next time.
