### ISSUE TITLE
[1.16.4] Updating Treated Wood Stairs causes a CCL Rendering Exception

### ISSUE THREAD

**Issue by Knightofknox** [BluSunrize/ImmersiveEngineering#4527]
**Description of the issue:**
Placing a treated wood stair in this exact spot, regardless of orientation, will cause a CCL Exception and cause wooden and aluminum posts to render in the way shown below. Updating the stair after exiting and reentering Minecraft will also cause the bug. After the bug has occurred, breaking and replacing the stair will cause it to have the proper texture. This bug occurred on a dedicated server with the mods listed below. This bug also persists in all worlds entered after the bug occurred. I tried to cause the bug to happen with a steel post, but it did not happen. After closing and reopening Minecraft, the bug was resolved.

Testing in a world with only IE yielded no bug.

https://imgur.com/kXJVs7P
https://imgur.com/gibKWCe

**CCL Crash Report**
CCL has caught an exception whilst rendering a block
  BlockPos:      x:37, y:68, z:-321
  Block Class:   class blusunrize.immersiveengineering.common.blocks.IEStairsBlock
  Registry Name: immersiveengineering:stairs_treated_wood_horizontal
  State:         Block{immersiveengineering:stairs_treated_wood_horizontal}[facing=north,half=bottom,shape=straight,waterlogged=false]
 Tile at position
  Tile Class:    null
  Tile Id:       null
  Tile NBT:      null
You can turn off player messages in the CCL config file.

net.minecraft.crash.ReportedException: Tesselating block model
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:68) ~[?:?]
	at codechicken.lib.render.block.CCBlockRendererDispatcher.renderModel(CCBlockRendererDispatcher.java:73) [?:1.16.4-3.5.0.398]
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_228940_a_(ChunkRenderDispatcher.java:527) [?:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_225618_a_(ChunkRenderDispatcher.java:449) [?:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender.func_228936_k_(ChunkRenderDispatcher.java:383) [?:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_228902_a_(ChunkRenderDispatcher.java:164) [?:?]
	at net.minecraft.client.renderer.WorldRenderer.func_228437_a_(WorldRenderer.java:842) [?:?]
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:931) [?:?]
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:607) [?:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.13.jar:35.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$477/1178160997.call(Unknown Source) [forge-1.16.4-35.1.13.jar:35.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 8128
	at net.minecraft.client.renderer.chunk.ChunkRenderCache.func_180495_p(SourceFile:103) ~[?:?]
	at blusunrize.immersiveengineering.common.blocks.generic.PostBlock.hasConnection(PostBlock.java:313) ~[?:?]
	at blusunrize.immersiveengineering.common.blocks.generic.PostBlock.getConnectionShapes(PostBlock.java:242) ~[?:?]
	at blusunrize.immersiveengineering.common.blocks.generic.PostBlock.func_220053_a(PostBlock.java:199) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215700_a(AbstractBlock.java:535) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196954_c(AbstractBlock.java:531) ~[?:?]
	at net.minecraft.block.AbstractBlock.func_196247_c(AbstractBlock.java:226) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_235754_c_(AbstractBlock.java:427) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_200015_d(AbstractBlock.java:517) ~[?:?]
	at blusunrize.immersiveengineering.common.blocks.IEBaseBlock.func_200011_d(IEBaseBlock.java:144) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_200016_a(AbstractBlock.java:419) ~[?:?]
	at net.minecraft.client.renderer.BlockModelRenderer$AmbientOcclusionFace.func_239285_a_(BlockModelRenderer.java:302) ~[?:?]
	at net.minecraft.client.renderer.BlockModelRenderer.func_228799_a_(BlockModelRenderer.java:121) ~[?:?]
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:75) ~[?:?]
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:89) ~[?:?]
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:51) ~[?:?]
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:63) ~[?:?]
	... 23 more
[15:08:20] [Render thread/INFO]: [CHAT] CCL Caught an exception rendering a block. See the log for info.

**Minecraft Crash Report**
N/A

**Modlist**
Bookshelf (by DarkhaxDev)
Mana and Artifice (by AWildCanadianEh)
Just Enough Items (JEI) (by mezz)
Mekanism Additions (by bradyaidanc)
Light Overlay (Rift/Forge/Fabric) (by shedaniel)
ConnectedTexturesMod (by tterrag1098)
Pam's HarvestCraft 2 - Food Extended (by pamharvestcraft)
Ars Nouveau (by baileyholl2)
Ender Storage 1.8.+ (by covers1624)
Discord Integration (by ErdbeerbaerLP)
JEITweaker (by Jaredlll08)
Powah! (by owmii)
Storage Drawers (by Texelsaur)
Connected Glass (by SuperMartijn642)
AppleSkin (by squeek502)
Industrial Foregoing (by Buuz135)
Lollipop (by owmii)
FTB GUI Library (by FTB)
FTB Teams (by FTB)
GraveStone Mod (by henkelmax)
Cloth Config API (Forge) (by shedaniel)
Waystones (by BlayTheNinth)
Thermal Innovation (by TeamCoFH)
Waila Harvestability (by squeek502)
Wawla - What Are We Looking At (by DarkhaxDev)
U Team Core (by HyCraftHD)
Chisels & Bits (by AlgorithmX2)
World Pre Generator (by GeheimagentNr1)
Citadel (by alex1the1666)
Titanium (by hrznstudio)
GeckoLib (by ThanosGecko)
Pam's HarvestCraft 2 - Trees (by pamharvestcraft)
Thermal Cultivation (by TeamCoFH)
Immersive Engineering (by BluSunrize)
Useful Backpacks (by HyCraftHD)
Fairy Lights (by pau101)
Immersive Petroleum (by Flaxbeard)
Create (by simibubi)
Psi (by Vazkii)
Chicken Chunks 1.8.+ (by covers1624)
mGui (by mickelus)
Construction Wand (by ThetaDev)
Patchouli (by Vazkii)
Building Gadgets (by Direwolf20)
Ranged Pumps (by raoulvdberge)
PneumaticCraft: Repressurized (by desht_08)
Blood Magic (by WayofTime)
Morpheus (by Quetzi)
CraftTweaker (by Jaredlll08)
OpenBlocks Elevator (by vsngarcia)
Mekanism (by bradyaidanc)
Ensorcellation (by TeamCoFH)
Neat (by Vazkii)
Mekanism Generators (by bradyaidanc)
Mekanism Tools (by bradyaidanc)
Botania (by Vazkii)
CodeChicken Lib 1.8.+ (by covers1624)
Mahou Tsukai (by stepcros)
Thermal Foundation (by TeamCoFH)
Pam's HarvestCraft 2 - Crops (by pamharvestcraft)
JAOPCA (by TheLMiffy1111)
CoFH Core (by TeamCoFH)
Thermal Expansion (by TeamCoFH)
Quark (by Vazkii)
Just Enough Resources (JER) (by way2muchnoise)
Cosmetic Armor Reworked (by LainMI)
Oh The Biomes You'll Go (by AOCAWOL)
Clumps (by Jaredlll08)
Security Craft (by Geforce132)
ObserverLib (by HellFirePvP)
Better Advancements (by way2muchnoise)
Dank Storage (by tfarecnim)
Iron Chests (by ProgWML6)
AutoRegLib (by Vazkii)
FTB Chunks (by FTB)
Fast Leaf Decay (by olafskiii)
Curios API (Forge) (by TheIllusiveC4)
Pam's HarvestCraft 2 - Food Core (by pamharvestcraft)
Tetra (by mickelus)
Ice and Fire: Dragons (by alex1the1666)
FastWorkbench (by Shadows_of_Fire)
Applied Energistics 2 (by AlgorithmX2)
Inventory Tweaks Renewed (by David1544)
Mouse Tweaks (by YaLTeR)
Torchmaster (by xalcon)
Controlling (by Jaredlll08)
Placebo (by Shadows_of_Fire)
*Versions were not included as I did not know how to force a crash report to be made.

Forge Version: 35.1.13
IE Version: 4.1.2-129

**Comment by malte0811** [comment]
Same problem as in #4512 (though I accept that it would have been hard to find when opening this issue).
