### ISSUE TITLE
RuntimeException: No OpenGL context found in the current thread.

### ISSUE THREAD

**Issue by Ffestiniog** [BluSunrize/ImmersiveEngineering#4571]
Hi,

I have had this error when trying to open a world I created on another minecraft installation, could someone help? Here is the whole crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 1/15/21 2:28 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at cam72cam.immersiverailroading.tile.TileRail.save(TileRail.java:107)
	at cam72cam.mod.block.tile.TileEntity.save(TileEntity.java:375)
	at cam72cam.mod.block.tile.TileEntity.func_189515_b(TileEntity.java:112)
	at cam72cam.mod.block.tile.TileEntity.func_189517_E_(TileEntity.java:138)
	at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:52)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:157)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at cam72cam.immersiverailroading.tile.TileRail.save(TileRail.java:107)
	at cam72cam.mod.block.tile.TileEntity.save(TileEntity.java:375)
	at cam72cam.mod.block.tile.TileEntity.func_189515_b(TileEntity.java:112)
	at cam72cam.mod.block.tile.TileEntity.func_189517_E_(TileEntity.java:138)
	at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:52)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:157)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)

-- Affected level --
Details:
	Level name: Henry
	All players: 1 total; [EntityPlayerMP['HP361'/260, l='Henry', x=-1257.43, y=73.62, z=854.29]]
	Chunk stats: ServerChunkCache: 966 Drop: 253
	Level seed: 1621597456123477036
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-840,73,858), Chunk: (at 8,4,10 in -53,53; contains blocks -848,0,848 to -833,255,863), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Level time: 1729948 game time, 5181 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 612701544 bytes (584 MB) / 1275068416 bytes (1216 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version      | Source                                | Signature |
	|:------ |:-------------------- |:------------ |:------------------------------------- |:--------- |
	| LCHIJA | minecraft            | 1.12.2       | minecraft.jar                         | None      |
	| LCHIJA | mcp                  | 9.42         | minecraft.jar                         | None      |
	| LCHIJA | FML                  | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar         | None      |
	| LCHIJA | forge                | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar         | None      |
	| LCHIJA | trackapi             | 1.1          | TrackAPI-1.1_1.12.jar                 | None      |
	| LCHIJA | immersiverailroading | 1.7.3        | ImmersiveRailroading-1.7.3_1.12.2.jar | None      |
	| LCHIJA | universalmodcore     | 1.0.0        | ImmersiveRailroading-1.7.3_1.12.2.jar | None      |
	| LCHIJA | immersiveengineering | 0.12-98      | ImmersiveEngineering-0.12-98.jar      | None      |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['HP361'/260, l='Henry', x=-1257.43, y=73.62, z=854.29]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

TIA

**Comment by malte0811** [comment]
1. That crash looks like it's caused by Immersive *Railroading*, which is not the same as Immersive *Engineering*.
2. 1.12 is not longer supported here (even if it was an IE issue).
3. For future reports please put the crashlog on https://gist.github.com or https://pastebin.com (or a similar site).
