### ISSUE TITLE
ImmersiveEngineering Manual Crash

### ISSUE THREAD

**Issue by Denjo83** [BluSunrize/ImmersiveEngineering#4593]
Good morning,:grin:

Info: My English is not very good and work partly with translator!

The following:
When I use the manual from immersiveengineering, my game closes.

1.) what i found out is that if i leave the textures out it works!
2.) if I leave only the block texture in it also goes!

we play minecraft version 1.16.4 and the forge version is 35.1.20

Could someone take a look at this?

here the crash-reports.

[code]---- Minecraft Crash Report ----
```
// I let you down. Sorry :(

Time: 1/21/21 1:20 PM
Description: Unexpected error

java.lang.RuntimeException: 1 manual entries failed to load, see log for details!
	at blusunrize.lib.manual.ManualInstance.reload(ManualInstance.java:391) ~[immersiveengineering:?] {re:classloading}
	at blusunrize.lib.manual.ManualInstance.getGui(ManualInstance.java:258) ~[immersiveengineering:?] {re:classloading}
	at blusunrize.lib.manual.ManualInstance.getGui(ManualInstance.java:248) ~[immersiveengineering:?] {re:classloading}
	at blusunrize.immersiveengineering.client.ClientProxy.openManual(ClientProxy.java:583) ~[immersiveengineering:?] {re:classloading}
	at blusunrize.immersiveengineering.common.items.ManualItem.func_77659_a(ManualItem.java:34) ~[immersiveengineering:?] {re:classloading}
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:214) ~[?:?] {re:computing_frames,re:classloading,re:mixin}
	at net.minecraft.client.multiplayer.PlayerController.func_187101_a(PlayerController.java:328) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.PlayerControllerAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.optifine.override.PlayerControllerOF.func_187101_a(PlayerControllerOF.java:81) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1389) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:valhelsia_tweaks.mixins.json:RemoveExperimentalSettingsWarningMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:DisplayMemoryWarningScreenMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1645) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:valhelsia_tweaks.mixins.json:RemoveExperimentalSettingsWarningMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:DisplayMemoryWarningScreenMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1460) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:valhelsia_tweaks.mixins.json:RemoveExperimentalSettingsWarningMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:DisplayMemoryWarningScreenMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:valhelsia_tweaks.mixins.json:RemoveExperimentalSettingsWarningMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:DisplayMemoryWarningScreenMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:valhelsia_tweaks.mixins.json:RemoveExperimentalSettingsWarningMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:DisplayMemoryWarningScreenMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.4-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_192] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.20-launcher.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_192] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at blusunrize.lib.manual.ManualInstance.reload(ManualInstance.java:391) ~[immersiveengineering:?] {re:classloading}
	at blusunrize.lib.manual.ManualInstance.getGui(ManualInstance.java:258) ~[immersiveengineering:?] {re:classloading}
	at blusunrize.lib.manual.ManualInstance.getGui(ManualInstance.java:248) ~[immersiveengineering:?] {re:classloading}
	at blusunrize.immersiveengineering.client.ClientProxy.openManual(ClientProxy.java:583) ~[immersiveengineering:?] {re:classloading}
	at blusunrize.immersiveengineering.common.items.ManualItem.func_77659_a(ManualItem.java:34) ~[immersiveengineering:?] {re:classloading}
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:214) ~[?:?] {re:computing_frames,re:classloading,re:mixin}
	at net.minecraft.client.multiplayer.PlayerController.func_187101_a(PlayerController.java:328) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.PlayerControllerAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.optifine.override.PlayerControllerOF.func_187101_a(PlayerControllerOF.java:81) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1389) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:valhelsia_tweaks.mixins.json:RemoveExperimentalSettingsWarningMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:DisplayMemoryWarningScreenMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1645) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:valhelsia_tweaks.mixins.json:RemoveExperimentalSettingsWarningMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:DisplayMemoryWarningScreenMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 3 total; [ClientPlayerEntity['Denjo83'/1465130, l='ClientLevel', x=-167.50, y=64.00, z=203.96], RemoteClientPlayerEntity['Bettimine'/1394125, l='ClientLevel', x=-185.47, y=64.00, z=218.61], RemoteClientPlayerEntity['Melodramos'/1383925, l='ClientLevel', x=-187.07, y=64.00, z=210.83]]
	Chunk stats: Client Chunk Cache: 961, 722
	Level dimension: minecraft:overworld
	Level spawn location: World: (-192,75,16), Chunk: (at 0,4,0 in -12,1; contains blocks -192,0,16 to -177,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 6634574 game time, 7593784 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2024) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:valhelsia_tweaks.mixins.json:RemoveExperimentalSettingsWarningMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:DisplayMemoryWarningScreenMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:valhelsia_tweaks.mixins.json:RemoveExperimentalSettingsWarningMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:DisplayMemoryWarningScreenMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.4-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_192] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.20-launcher.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_192] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_192, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5322467144 bytes (5075 MB) / 16206790656 bytes (15456 MB) up to 22459449344 bytes (21419 MB)
	CPUs: 6
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4040m -Xmx24096m
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.20-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.20-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.20-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.20-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/preview_OptiFine_1.16.4_HD_U_G6_pre12.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.20-launcher.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.20
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		simplemagnets-1.0.11-mc1.16.4.jar                 |Simple Magnets                |simplemagnets                 |1.0.11              |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.1.65.jar                           |Just Enough Items             |jei                           |7.6.1.65            |DONE      |NOSIGNATURE
		Mekanism-1.16.4-10.0.18.445.jar                   |Mekanism                      |mekanism                      |10.0.18             |DONE      |NOSIGNATURE
		sleeping_bags-1.16.4-1.0.1.jar                    |Sleeping Bags                 |sleeping_bags                 |1.16.4-1.0.1        |DONE      |NOSIGNATURE
		CookingForBlockheads_1.16.3-9.2.2.jar             |Cooking for Blockheads        |cookingforblockheads          |9.2.2               |DONE      |NOSIGNATURE
		sweetconcrete-1.16.4-1.7.1.jar                    |Sweet Concrete                |sweetconcrete                 |1.16.3-1.7.1        |DONE      |NOSIGNATURE
		Powah-1.16.4-2.3.8.jar                            |Powah                         |powah                         |2.3.8               |DONE      |NOSIGNATURE
		ftb-gui-library-1604.1.1.26.jar                   |FTB GUI Library               |ftbguilibrary                 |1604.1.1.26         |DONE      |NOSIGNATURE
		decorative_blocks-1.16.4-1.7.2.jar                |Decorative Blocks             |decorative_blocks             |1.7.2               |DONE      |NOSIGNATURE
		DungeonCrawl-1.16.3-2.2.4.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.2.4               |DONE      |NOSIGNATURE
		Bookshelf-1.16.4-9.3.24.jar                       |Bookshelf                     |bookshelf                     |9.3.24              |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		BotanyPots-1.16.4-6.0.7.jar                       |BotanyPots                    |botanypots                    |6.0.7               |DONE      |ea:45:b3:82:b6:9d:50:16:95:e7:2e:34:e1:92:d5:b4:9b:69:90:d3:4f:2e:71:99:b0:be:40:80:27:1f:3e:b0
		bottleyourxp_1.16.4-1.3.jar                       |Bottle Your Xp                |bottleyourxp                  |1.3                 |DONE      |NOSIGNATURE
		buildinggadgets-1.16.4-3.7.3.jar                  |Building Gadgets              |buildinggadgets               |3.7.3               |DONE      |NOSIGNATURE
		mcw-doors-1.0.1fix-mc1.16.4.jar                   |Macaw's Doors                 |mcwdoors                      |1.0.1               |DONE      |NOSIGNATURE
		Morpheus-1.16.4-4.2.68.jar                        |Morpheus                      |morpheus                      |4.2.68              |DONE      |NOSIGNATURE
		mapperbase-1.16.4-2.3.0.0.jar                     |Mapper Base                   |mapperbase                    |1.16.4-2.3.0.0      |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.20-universal.jar                |Forge                         |forge                         |35.1.20             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		refinedstorage-1.9.11.jar                         |Refined Storage               |refinedstorage                |1.9.11              |DONE      |NOSIGNATURE
		ironchest-1.16.4-11.2.10.jar                      |Iron Chests                   |ironchest                     |1.16.4-11.2.10      |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.20-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		mcw-bridges-1.0.4-mc1.16.4.jar                    |Macaw's Bridges               |mcwbridges                    |1.0.4               |DONE      |NOSIGNATURE
		theoneprobe-1.16-3.0.7.jar                        |The One Probe                 |theoneprobe                   |1.16-3.0.7          |DONE      |NOSIGNATURE
		ImmersiveEngineering-1.16.4-4.1.2-129.jar         |Immersive Engineering         |immersiveengineering          |1.16.4-4.1.2-129    |DONE      |44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		BotanyTrees-1.16.4-2.0.4.jar                      |BotanyTrees                   |botanytrees                   |2.0.4               |DONE      |ea:45:b3:82:b6:9d:50:16:95:e7:2e:34:e1:92:d5:b4:9b:69:90:d3:4f:2e:71:99:b0:be:40:80:27:1f:3e:b0
		BiomesOPlenty-1.16.4-13.0.0.428-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.428   |DONE      |NOSIGNATURE
		BuildingWands-Forge_1.16.4-1.3.1.jar              |Building Wands Mod            |wands                         |1.3.1               |DONE      |NOSIGNATURE
		valhelsia_structures-16.0.5.jar                   |Valhelsia Structures          |valhelsia_structures          |16.0.5              |DONE      |NOSIGNATURE
		Lollipop-1.16.4-3.2.4.jar                         |Lollipop                      |lollipop                      |3.2.4               |DONE      |NOSIGNATURE
		movingelevators-1.2.31a-mc1.16.4.jar              |Moving Elevators              |movingelevators               |1.2.31a             |DONE      |NOSIGNATURE
		Botania-1.16.4-410.jar                            |Botania                       |botania                       |1.16.4-410          |DONE      |NOSIGNATURE
		simplybackpacks-1.16.3-1.4.13.jar                 |Simply Backpacks              |simplybackpacks               |1.16.3-1.4.13       |DONE      |NOSIGNATURE
		curios-forge-1.16.4-4.0.3.4.jar                   |Curios API                    |curios                        |1.16.4-4.0.3.4      |DONE      |NOSIGNATURE
		sisser-1.7.jar                                    |Sisser                        |sisser                        |1.7                 |DONE      |NOSIGNATURE
		Patchouli-1.16.4-48.jar                           |Patchouli                     |patchouli                     |1.16.4-48           |DONE      |NOSIGNATURE
		gravestone-1.16.4-1.0.8.jar                       |Gravestone Mod                |gravestone                    |1.16.4-1.0.8        |DONE      |NOSIGNATURE
		collective-1.16.4-1.53.jar                        |Collective                    |collective                    |1.53                |DONE      |NOSIGNATURE
		roadstuff-1.16.4-4.2.0.jar                        |Road Stuff                    |roadstuff                     |1.16.4-4.2.0        |DONE      |NOSIGNATURE
		StorageDrawers-1.16.3-8.2.1.jar                   |Storage Drawers               |storagedrawers                |8.2.1               |DONE      |NOSIGNATURE
		elevatorid-1.16.4-1.7.9.jar                       |Elevator Mod                  |elevatorid                    |1.16.4-1.7.9        |DONE      |NOSIGNATURE
		buildersaddition-1.16.4-20210113c.jar             |Builders Crafts & Addition    |buildersaddition              |1.16.4-20210113c    |DONE      |NOSIGNATURE
		worldedit-forge-mc1.16.3-7.2.1-dist.jar           |WorldEdit                     |worldedit                     |7.2.1+299386a       |DONE      |NOSIGNATURE
		mcws-roofs-2.0.0-mc1.16.4.jar                     |Macaw's Roofs                 |mcwroofs                      |2.0.0               |DONE      |NOSIGNATURE
		furniture-7.0.0-pre19-1.16.3.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre19         |DONE      |NOSIGNATURE
		EasyPaxel(1.16.4)+-+1.0.9.jar                     |Easy Paxel                    |easypaxelmod                  |1.16.4-1.0.9        |DONE      |NOSIGNATURE
		trashcans-1.0.6-mc1.16.4.jar                      |Trash Cans                    |trashcans                     |1.0.6               |DONE      |NOSIGNATURE
		forgemod_VoxelMap-1.10.14_for_1.16.4(1).jar       |VoxelMap                      |voxelmap                      |1.10.14             |DONE      |NOSIGNATURE
		valhelsia_tweaks-16.0.3.jar                       |Valhelsia Tweaks              |valhelsia_tweaks              |16.0.3              |DONE      |NOSIGNATURE
		RingOfUnseen-1.16.4-1.0.6.jar                     |Ring of Unseen                |ring_of_unseen                |1.0.6               |DONE      |NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |DONE      |NOSIGNATURE
		chiselsandbits-0.2.8-RELEASE.jar                  |Chisels & bits                |chiselsandbits                |NONE                |DONE      |NOSIGNATURE
		lumberjack-2.1.4.jar                              |LumberJack                    |lumberjack                    |2.1.4               |DONE      |NOSIGNATURE
	Crash Report UUID: f5491102-507c-49c3-b78c-0d5c2f4c6d84
	Patchouli open book context: n/a
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2070 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.09, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: mod_resources, vanilla, file/Spahx128x1.16.4 (incompatible), file/PureBDcraft Customisation MC116, file/PureBDcraft 128x MC116
	Current Language: English (United Kingdom)
	CPU: 6x Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
	OptiFine Version: OptiFine_1.16.4_HD_U_G6_pre12
	OptiFine Build: 20210110-191159
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 461.09
	OpenGlRenderer: GeForce RTX 2070 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6
```

A thank you before starting!

**Comment by BluSunrize** [comment]
Crashlogs belong on *pastebin* not in the report. Please actually read the issue template and contribution guidelines next time.

Also, this issue is fixed for the next release already.

https://github.com/BluSunrize/ImmersiveEngineering/commit/858e8615ccdf22eca12c9204d6be8e5ab78f9796
