### ISSUE TITLE
[1.16.5-4.2.0-130] Arc Recycling Exceptions

### ISSUE THREAD

**Issue by Moleculor** [BluSunrize/ImmersiveEngineering#4605]
### Description of the issue:

This exception shows up four times in my debug.log. No idea what impact it might have.

```
[25Jan2021 14:25:39.608] [Immersive Engineering Registry Iteration Thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: java.util.ConcurrentModificationException
[25Jan2021 14:25:39.608] [Immersive Engineering Registry Iteration Thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1226)
[25Jan2021 14:25:39.608] [Immersive Engineering Registry Iteration Thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at blusunrize.immersiveengineering.api.IEApi.getPreferredTagStack(IEApi.java:77)
[25Jan2021 14:25:39.608] [Immersive Engineering Registry Iteration Thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at blusunrize.immersiveengineering.api.ApiUtils.breakStackIntoPreciseIngots(ApiUtils.java:171)
[25Jan2021 14:25:39.608] [Immersive Engineering Registry Iteration Thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at blusunrize.immersiveengineering.common.crafting.ArcRecyclingThreadHandler.getRecycleCalculation(ArcRecyclingThreadHandler.java:198)
[25Jan2021 14:25:39.608] [Immersive Engineering Registry Iteration Thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at blusunrize.immersiveengineering.common.crafting.ArcRecyclingThreadHandler$RegistryIterationThread.run(ArcRecyclingThreadHandler.java:167)
```

[debug.log](https://gist.github.com/Moleculor/8bd7fbac3c43b8af7f88f2efae47f823)

### Versions & Modlist
```
-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 14.0.2, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
	Memory: 5092105680 bytes (4856 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 8
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms6144m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.0.1.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.1.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.5-36.0.1.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.0.1.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.0.1.jar fml TRANSFORMATIONSERVICE 
	FML: 36.0
	Forge: net.minecraftforge:36.0.1
	FML Language Providers: 
		javafml@36.0
		minecraft@1
	Mod List: 
		astralsorcery-1.16.4-1.13.9.jar                   |Astral Sorcery                |astralsorcery                 |1.16.4-1.13.9       |DONE      |45:2b:0a:49:6b:65:3b:39:a9:dd:d2:5b:55:7f:82:47:a5:1d:7a:cc:7f:a8:69:73:72:53:6f:57:4d:b2:1a:b7
		areas_1.16.5-1.1.jar                              |Areas                         |areas                         |1.1                 |DONE      |NOSIGNATURE
		PreGenForge-0.2.2-mc1.16.4.jar                    |PreGenForge                   |pregenforge                   |0.2.2               |DONE      |NOSIGNATURE
		DeathCounter-1.16.3-1.2.1.jar                     |Death Counter                 |deathcounter                  |1.2.1               |DONE      |NOSIGNATURE
		refinedpipes-0.5.jar                              |Refined Pipes                 |refinedpipes                  |0.5                 |DONE      |NOSIGNATURE
		mcw-windows-1.0.2-mc1.16.4.jar                    |Macaw's Windows               |mcwwindows                    |1.0.2               |DONE      |NOSIGNATURE
		windowlogging-mc1.16.3_v0.0.2.jar                 |Windowlogging                 |windowlogging                 |0.0.2               |DONE      |NOSIGNATURE
		findme-1.16.3-2.1.0.0.jar                         |Find Me                       |findme                        |NONE                |DONE      |NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.1.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.1        |DONE      |NOSIGNATURE
		TerraForged-1.16.4-0.2.0-RC-3.jar                 |TerraForged                   |terraforged                   |0.2.0-RC-3          |DONE      |7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3
		XaerosWorldMap_1.11.9_Forge_1.16.5.jar            |Xaero's World Map             |xaeroworldmap                 |1.11.9              |DONE      |NOSIGNATURE
		CTM-MC1.16.1-1.1.2.6.jar                          |ConnectedTexturesMod          |ctm                           |MC1.16.1-1.1.2.6    |DONE      |NOSIGNATURE
		CookingForBlockheads_1.16.3-9.2.2.jar             |Cooking for Blockheads        |cookingforblockheads          |9.2.2               |DONE      |NOSIGNATURE
		Controlling-7.0.0.12.jar                          |Controlling                   |controlling                   |7.0.0.12            |DONE      |NOSIGNATURE
		Placebo-1.16.4-4.4.1.jar                          |Placebo                       |placebo                       |4.4.1               |DONE      |NOSIGNATURE
		YungsApi-1.16.4-Forge-3.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-3      |DONE      |NOSIGNATURE
		worldborder_1.16.5-2.0.jar                        |World Border                  |worldborder                   |2.0                 |DONE      |NOSIGNATURE
		Bookshelf-1.16.5-10.0.1.jar                       |Bookshelf                     |bookshelf                     |10.0.1              |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Tips-1.16.4-3.0.2.jar                             |Tips                          |tips                          |3.0.2               |DONE      |ea:45:b3:82:b6:9d:50:16:95:e7:2e:34:e1:92:d5:b4:9b:69:90:d3:4f:2e:71:99:b0:be:40:80:27:1f:3e:b0
		u_team_core-1.16.4-3.1.17.192.jar                 |U Team Core                   |uteamcore                     |3.1.17.192          |DONE      |f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		randompatches-2.2.0-forge.jar                     |RandomPatches                 |randompatches                 |2.2.0-forge         |DONE      |92:f6:29:d4:09:89:f5:f5:98:5e:20:34:31:d0:7b:58:22:06:bd:a5:d1:6a:92:6e:ac:3d:8d:18:c5:b2:5b:d7
		mcw-doors-1.0.1fix-mc1.16.4.jar                   |Macaw's Doors                 |mcwdoors                      |1.0.1               |DONE      |NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |NOSIGNATURE
		SnowRealMagic-1.16.4-2.3.0.jar                    |Snow! Real Magic!             |snowrealmagic                 |2.3.0               |DONE      |NOSIGNATURE
		JustEnoughResources-1.16.4-0.12.0.104.jar         |Just Enough Resources         |jeresources                   |0.12.0.104          |DONE      |NOSIGNATURE
		horsestandstill-1.16.3-1.0.1.jar                  |Stupid Horse Stand Still      |horsestandstill               |1.16.3-1.0.1        |DONE      |1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		shetiphiancore-1.16-3.8.4.jar                     |ShetiPhian-Core               |shetiphiancore                |3.8.4               |DONE      |NOSIGNATURE
		supplementaries-0.9.22d.jar                       |Supplementaries               |supplementaries               |0.9.22c             |DONE      |NOSIGNATURE
		Buddycards-1.16.4-1.6.2.jar                       |Buddycards                    |buddycards                    |1.16.4-1.6.2        |DONE      |NOSIGNATURE
		refinedstorage-1.9.11.jar                         |Refined Storage               |refinedstorage                |1.9.11              |DONE      |NOSIGNATURE
		chocolate-1.3.0-1.16.4.jar                        |Chocolate                     |chocolate                     |1.3.0-1.16.4        |DONE      |NOSIGNATURE
		mcw-bridges-1.0.4-mc1.16.4.jar                    |Macaw's Bridges               |mcwbridges                    |1.0.4               |DONE      |NOSIGNATURE
		FarmersDelight-1.16.3-0.3.1.jar                   |Farmer's Delight              |farmersdelight                |1.16.3-0.3.1        |DONE      |NOSIGNATURE
		useful_backpacks-1.16.4-1.11.6.87.jar             |Useful Backpacks              |usefulbackpacks               |1.11.6.87           |DONE      |f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		AmbientSounds_v3.1.4_mc1.16.4.jar                 |Ambient Sounds                |ambientsounds                 |3.0.3               |DONE      |NOSIGNATURE
		ftb-ranks-1604.1.1.10.jar                         |FTB Ranks                     |ftbranks                      |1604.1.1.10         |DONE      |NOSIGNATURE
		mcw-trapdors-1.0.0-mc1.16.4.jar                   |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.0               |DONE      |NOSIGNATURE
		Botania-1.16.4-411.jar                            |Botania                       |botania                       |1.16.4-411          |DONE      |NOSIGNATURE
		spark-forge.jar                                   |spark                         |spark                         |1.4.3               |DONE      |NOSIGNATURE
		pamhc2foodextended-1.16.3-1.0.0.jar               |Pam's HarvestCraft 2 Food Exte|pamhc2foodextended            |version             |DONE      |NOSIGNATURE
		curios-forge-1.16.4-4.0.3.5.jar                   |Curios API                    |curios                        |1.16.4-4.0.3.5      |DONE      |NOSIGNATURE
		eidolon-0.2.7.jar                                 |Eidolon                       |eidolon                       |0.2.7               |DONE      |NOSIGNATURE
		Patchouli-1.16.4-48.jar                           |Patchouli                     |patchouli                     |1.16.4-48           |DONE      |NOSIGNATURE
		overworld_two-1.0-Forge-1.16.4.jar                |Overworld 2                   |overworld_two                 |1.0                 |DONE      |NOSIGNATURE
		collective-1.16.5-1.53.jar                        |Collective                    |collective                    |1.53                |DONE      |NOSIGNATURE
		DummyPlayers-1.0.0-release+1.jar                  |DummyPlayers                  |dummyplayers                  |1.0.0-release+1     |DONE      |NOSIGNATURE
		miraisoftloginmessages-1.16.2-1.16.4-1.0.2.jar    |Custom login messages         |miraisoftloginmessages        |1.0.2               |DONE      |NOSIGNATURE
		mcws-roofs-2.0.0-mc1.16.4.jar                     |Macaw's Roofs                 |mcwroofs                      |2.0.0               |DONE      |NOSIGNATURE
		architectury-1.4.98-forge.jar                     |Architectury                  |architectury                  |1.4.98              |DONE      |NOSIGNATURE
		ftb-gui-library-1604.2.0.30-forge.jar             |FTB GUI Library               |ftbguilibrary                 |1604.2.0.30         |DONE      |NOSIGNATURE
		ftb-teams-1604.1.0.14-forge.jar                   |FTB Teams                     |ftbteams                      |version             |DONE      |NOSIGNATURE
		observerlib-1.16.4-1.5.1.jar                      |ObserverLib                   |observerlib                   |1.16.4-1.5.1        |DONE      |NOSIGNATURE
		moreoverlays-1.18.13-mc1.16.5.jar                 |More Overlays Updated         |moreoverlays                  |1.18.13-mc1.16.5    |DONE      |NOSIGNATURE
		cloth-config-forge-4.1.3.jar                      |Cloth Config v4 API           |cloth-config                  |4.1.3               |DONE      |NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.1.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.1        |DONE      |NOSIGNATURE
		BetterAdvancements-1.16.4-0.1.0.104.jar           |Better Advancements           |betteradvancements            |0.1.0.104           |DONE      |NOSIGNATURE
		Kiwi-1.16.3-3.4.1.jar                             |Kiwi                          |kiwi                          |3.4.1               |DONE      |NOSIGNATURE
		TrashSlot_1.16.3-12.2.1.jar                       |TrashSlot                     |trashslot                     |12.2.1              |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.1.65.jar                           |Just Enough Items             |jei                           |7.6.1.65            |DONE      |NOSIGNATURE
		FallingTree-Forge-1.16.5-2.10.0.jar               |Falling Tree                  |falling_tree                  |2.10.0              |DONE      |NOSIGNATURE
		WAWLA-1.16.4-7.0.2.jar                            |WAWLA                         |wawla                         |7.0.2               |DONE      |ea:45:b3:82:b6:9d:50:16:95:e7:2e:34:e1:92:d5:b4:9b:69:90:d3:4f:2e:71:99:b0:be:40:80:27:1f:3e:b0
		create-mc1.16.3_v0.3e.jar                         |Create                        |create                        |mc1.16.3_v0.3e      |DONE      |NOSIGNATURE
		Clumps-6.0.0.13.jar                               |Clumps                        |clumps                        |6.0.0.13            |DONE      |NOSIGNATURE
		shutupexperimentalsettings-1.0.1.jar              |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.1               |DONE      |NOSIGNATURE
		comforts-forge-1.16.4-4.0.1.0.jar                 |Comforts                      |comforts                      |1.16.4-4.0.1.0      |DONE      |NOSIGNATURE
		NaturesCompass-1.16.4-1.8.6.jar                   |Nature's Compass              |naturescompass                |1.16.4-1.8.6        |DONE      |NOSIGNATURE
		SereneSeasons-1.16.5-4.0.1.89-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.89     |DONE      |NOSIGNATURE
		FarmingForBlockheads_1.16.3-7.2.1.jar             |Farming for Blockheads        |farmingforblockheads          |7.2.1               |DONE      |NOSIGNATURE
		pneumaticcraft-repressurized-1.16.4-2.9.3-120.jar |PneumaticCraft: Repressurized |pneumaticcraft                |1.16.4-2.9.3-120    |DONE      |NOSIGNATURE
		snowundertrees-1.16.4-v1.1.3.jar                  |Snow Under Trees              |snowundertrees                |v1.1.3              |DONE      |NOSIGNATURE
		DataFixerSlayer 1.0-3.jar                         |DataFixerSlayer               |datafixerslayer               |1.0-3               |DONE      |NOSIGNATURE
		environmentalcreepers-forge-1.16.3-1.6.0.jar      |Environmental Creepers        |environmentalcreepers         |1.6.0               |DONE      |NOSIGNATURE
		Toast-Control-1.16.4-4.3.1.jar                    |Toast Control                 |toastcontrol                  |4.3.1               |DONE      |NOSIGNATURE
		dismountentity_1.16.5-1.2.jar                     |Dismount Entity               |dismountentity                |1.2                 |DONE      |NOSIGNATURE
		immersive-portals-0.14-mc1.16.4-forge.jar         |Immersive Portals             |immersive_portals             |0.14                |DONE      |NOSIGNATURE
		ImmersivePetroleum-1.16.4-3.1.0-2.jar             |Immersive Petroleum           |immersivepetroleum            |3.1.0-2             |DONE      |NOSIGNATURE
		forge-1.16.5-36.0.1-universal.jar                 |Forge                         |forge                         |36.0.1              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		DynamicSurroundings-1.16.4-4.0.3.5.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.3.5      |DONE      |b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		ironchest-1.16.4-11.2.10.jar                      |Iron Chests                   |ironchest                     |1.16.4-11.2.10      |DONE      |NOSIGNATURE
		forge-1.16.5-36.0.1-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		cofh_core-1.16.3-1.1.6.jar                        |CoFH Core                     |cofh_core                     |1.1.6               |DONE      |NOSIGNATURE
		thermal_foundation-1.16.3-1.1.6.jar               |Thermal Series                |thermal                       |1.1.6               |DONE      |NOSIGNATURE
		thermal_innovation-1.16.3-1.1.7.jar               |Thermal Innovation            |thermal_innovation            |1.1.7               |DONE      |NOSIGNATURE
		thermal_expansion-1.16.3-1.1.6.jar                |Thermal Expansion             |thermal_expansion             |1.1.6               |DONE      |NOSIGNATURE
		thermal_locomotion-1.16.3-1.1.6.jar               |Thermal Locomotion            |thermal_locomotion            |1.1.6               |DONE      |NOSIGNATURE
		EnchantmentDescriptions-1.16.4-6.0.3.jar          |EnchantmentDescriptions       |enchdesc                      |6.0.3               |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		MouseTweaks-2.13-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.13                |DONE      |NOSIGNATURE
		Psi 1.16-91.jar                                   |Psi                           |psi                           |1.16-91             |DONE      |NOSIGNATURE
		ImmersiveEngineering-1.16.5-4.2.0-130.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-4.2.0-130    |DONE      |44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		durability101-1.16-0.0.3.jar                      |Durability101                 |durability101                 |0.0.3               |DONE      |NOSIGNATURE
		CreativeCore_v2.0.10_mc1.16.4.jar                 |CreativeCore                  |creativecore                  |2.0.0               |DONE      |NOSIGNATURE
		jeiintegration_1.16.4-6.1.1.11.jar                |JEI Integration               |jeiintegration                |6.1.1.11            |DONE      |NOSIGNATURE
		Xaeros_Minimap_21.1.0_Forge_1.16.5.jar            |Xaero's Minimap               |xaerominimap                  |21.1.0              |DONE      |NOSIGNATURE
		pamhc2foodcore-1.16.3-1.0.1.jar                   |Pam's HarvestCraft 2 Food Core|pamhc2foodcore                |version             |DONE      |NOSIGNATURE
		gravestone-1.16.5-1.0.0.jar                       |Gravestone Mod                |gravestone                    |1.16.5-1.0.0        |DONE      |NOSIGNATURE
		ftb-backups-2.1.1.6.jar                           |FTB Backups                   |ftbbackups                    |2.1.1.6             |DONE      |NOSIGNATURE
		thermal_cultivation-1.16.3-1.1.6.jar              |Thermal Cultivation           |thermal_cultivation           |1.1.6               |DONE      |NOSIGNATURE
		polymorph-forge-1.16.4-0.23.jar                   |Polymorph                     |polymorph                     |1.16.4-0.23         |DONE      |NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |DONE      |NOSIGNATURE
		Quark-r2.4-297.jar                                |Quark                         |quark                         |r2.4-297            |DONE      |NOSIGNATURE
		enderchests-1.16-1.7.5.jar                        |EnderChests                   |enderchests                   |1.7.5               |DONE      |NOSIGNATURE
		globaldataandresourcepacks-1.16.4-1.7.4.jar       |Global Data- & Resourcepacks  |globaldataandresourcepacks    |1.16.4-1.7.3        |DONE      |NOSIGNATURE
		structurize-0.13.113-ALPHA-universal.jar          |Structurize                   |structurize                   |0.13.113-ALPHA      |DONE      |NOSIGNATURE
		AmbientEnvironment-4.0.0.6.jar                    |Ambient Environment           |ambientenvironment            |4.0.0.6             |DONE      |NOSIGNATURE
		minecolonies-0.13.587-ALPHA-universal.jar         |MineColonies                  |minecolonies                  |0.13.587-ALPHA      |DONE      |NOSIGNATURE
		World Stripper-1.16.4-2.0.1.jar                   |World Stripper                |worldstripper                 |2.0.1               |DONE      |NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |DONE      |NOSIGNATURE
		lootr-1.16.4-0.0.4.11.jar                         |Lootr                         |lootr                         |1.16.4-0.0.4.11     |DONE      |NOSIGNATURE
		ferritecore-1.1.1.jar                             |Ferrite Core                  |ferritecore                   |1.1.1               |DONE      |41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		engineersdecor-1.16.4-1.1.7.jar                   |Engineer's Decor              |engineersdecor                |1.1.7               |DONE      |bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		moredragoneggs-1.4.jar                            |More Dragon Eggs              |moredragoneggs                |1.4                 |DONE      |NOSIGNATURE
		durabilityviewer-1.16.4-forge35.0.7-1.10.jar      |Giselbaers Durability Viewer  |durabilityviewer              |1.16.4-forge35.0.7-1|DONE      |NOSIGNATURE
		easyelytrato_1.16.5-1.5.jar                       |Easy Elytra Takeoff           |easyelytrato                  |1.5                 |DONE      |NOSIGNATURE
		refinedstorageaddons-0.7.2.jar                    |Refined Storage Addons        |refinedstorageaddons          |0.7.2               |DONE      |NOSIGNATURE
		CosmeticArmorReworked-1.16.5-v1.jar               |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.5-v1           |DONE      |NOSIGNATURE
		EnderMail-1.16.4-1.2.0.jar                        |Ender Mail                    |endermail                     |1.16.4-1.2.0        |DONE      |NOSIGNATURE
```

I "only" get those exceptions *three* times when I'm running a much smaller mod list.

[debug.log](https://gist.github.com/Moleculor/a6b0af2d63ab622b764a1c8cf5d29315)

```
-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 14.0.2, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
	Memory: 3219653912 bytes (3070 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 8
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms6144m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.0.1.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.1.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.5-36.0.1.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.0.1.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.0.1.jar fml TRANSFORMATIONSERVICE 
	FML: 36.0
	Forge: net.minecraftforge:36.0.1
	FML Language Providers: 
		javafml@36.0
		minecraft@1
	Mod List: 
		forge-1.16.5-36.0.1-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		forge-1.16.5-36.0.1-universal.jar                 |Forge                         |forge                         |36.0.1              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		ImmersiveEngineering-1.16.5-4.2.0-130.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-4.2.0-130    |DONE      |44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		jei-1.16.4-7.6.1.65.jar                           |Just Enough Items             |jei                           |7.6.1.65            |DONE      |NOSIGNATURE
```

**Comment by BluSunrize** [comment]
This should be resolved by Malte's refactor of the entire recycling code. Next release should fix this.
