### ISSUE TITLE
Issues with Engineers Manual

### ISSUE THREAD

**Issue by HydrogenC** [BluSunrize/ImmersiveEngineering#4616]
### Description of the issue:
It shows a message "5 entries failed to load! Please report this as an issue with your log file!" when trying to open an Engineers Manual. 

### Crashlog:
> [30一月2021 08:59:04.134] [Render thread/WARN] [immersiveengineering-manual/]: Tried to access invalid anchor "caps"
> [30一月2021 08:59:04.134] [Render thread/WARN] [immersiveengineering-manual/]: Tried to access invalid anchor "caps"
> [30一月2021 08:59:04.135] [Render thread/WARN] [immersiveengineering-manual/]: Tried to access invalid anchor "caps"
> [30一月2021 08:59:04.135] [Render thread/WARN] [immersiveengineering-manual/]: Tried to access invalid anchor "caps"
> [30一月2021 08:59:04.135] [Render thread/WARN] [immersiveengineering-manual/]: Tried to access invalid anchor "caps"
> [30一月2021 08:59:04.135] [Render thread/WARN] [immersiveengineering-manual/]: Tried to access invalid anchor "caps"
> [30一月2021 08:59:04.135] [Render thread/WARN] [immersiveengineering-manual/]: Tried to access invalid anchor "caps"
> [30一月2021 08:59:04.135] [Render thread/WARN] [immersiveengineering-manual/]: Tried to access invalid anchor "caps"
> [30一月2021 08:59:04.135] [Render thread/WARN] [immersiveengineering-manual/]: Tried to access invalid anchor "caps"
> [30一月2021 08:59:04.135] [Render thread/WARN] [immersiveengineering-manual/]: Tried to access invalid anchor "caps"
> [30一月2021 08:59:04.135] [Render thread/WARN] [immersiveengineering-manual/]: Tried to access invalid anchor "caps"
> [30一月2021 08:59:04.135] [Render thread/WARN] [immersiveengineering-manual/]: Tried to access invalid anchor "caps"
> [30一月2021 08:59:04.135] [Render thread/WARN] [immersiveengineering-manual/]: Tried to access invalid anchor "caps"
> [30一月2021 08:59:04.135] [Render thread/WARN] [immersiveengineering-manual/]: Tried to access invalid anchor "caps"
> [30一月2021 08:59:04.135] [Render thread/WARN] [immersiveengineering-manual/]: Tried to access invalid anchor "caps"
> [30一月2021 08:59:04.135] [Render thread/WARN] [immersiveengineering-manual/]: Tried to access invalid anchor "caps"
> [30一月2021 08:59:04.151] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: java.lang.RuntimeException: Exception while refreshing manual entry immersiveengineering:excavator for manual 工程师手册
> [30一月2021 08:59:04.151] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at blusunrize.lib.manual.ManualEntry.refreshPages(ManualEntry.java:89)
> [30一月2021 08:59:04.151] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at blusunrize.lib.manual.ManualInstance.loadEntriesInArray(ManualInstance.java:515)
> [30一月2021 08:59:04.152] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at blusunrize.lib.manual.ManualInstance.autoloadEntriesFromJson(ManualInstance.java:482)
> [30一月2021 08:59:04.152] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at blusunrize.lib.manual.ManualInstance.autoloadEntriesFromJson(ManualInstance.java:487)
> [30一月2021 08:59:04.152] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at blusunrize.lib.manual.ManualInstance.loadAutoEntries(ManualInstance.java:454)
> [30一月2021 08:59:04.152] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at blusunrize.lib.manual.ManualInstance.reload(ManualInstance.java:406)
> [30一月2021 08:59:04.152] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at blusunrize.lib.manual.ManualInstance.getGui(ManualInstance.java:262)
> [30一月2021 08:59:04.152] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at blusunrize.lib.manual.ManualInstance.getGui(ManualInstance.java:252)
> [30一月2021 08:59:04.153] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at blusunrize.immersiveengineering.client.ClientProxy.openManual(ClientProxy.java:583)
> [30一月2021 08:59:04.153] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at blusunrize.immersiveengineering.common.items.ManualItem.func_77659_a(ManualItem.java:38)
> [30一月2021 08:59:04.153] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:214)
> [30一月2021 08:59:04.153] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at net.minecraft.client.multiplayer.PlayerController.func_187101_a(PlayerController.java:328)
> [30一月2021 08:59:04.153] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at net.optifine.override.PlayerControllerOF.func_187101_a(PlayerControllerOF.java:81)
> [30一月2021 08:59:04.153] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1389)
> [30一月2021 08:59:04.154] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1645)
> [30一月2021 08:59:04.154] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1460)
> [30一月2021 08:59:04.154] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953)
> [30一月2021 08:59:04.154] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
> [30一月2021 08:59:04.154] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at net.minecraft.client.main.Main.main(Main.java:184)
> [30一月2021 08:59:04.154] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [30一月2021 08:59:04.154] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> [30一月2021 08:59:04.155] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> [30一月2021 08:59:04.155] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at java.lang.reflect.Method.invoke(Unknown Source)
> [30一月2021 08:59:04.155] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
> [30一月2021 08:59:04.155] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
> [30一月2021 08:59:04.155] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
> [30一月2021 08:59:04.155] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
> [30一月2021 08:59:04.156] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
> [30一月2021 08:59:04.156] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
> [30一月2021 08:59:04.156] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Can not set com.electronwill.nightconfig.core.Config field net.minecraftforge.common.ForgeConfigSpec.childConfig to blusunrize.immersiveengineering.common.config.CachedConfig
> [30一月2021 08:59:04.156] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at flaxbeard.immersivepetroleum.common.IPConfig.getRawConfig(IPConfig.java:49)
> [30一月2021 08:59:04.156] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at flaxbeard.immersivepetroleum.client.ClientProxy.lambda$completed$0(ClientProxy.java:174)
> [30一月2021 08:59:04.156] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at blusunrize.immersiveengineering.client.manual.IEManualInstance.formatConfigEntry(IEManualInstance.java:330)
> [30一月2021 08:59:04.157] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at blusunrize.immersiveengineering.client.manual.IEManualInstance.formatText(IEManualInstance.java:96)
> [30一月2021 08:59:04.157] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at blusunrize.lib.manual.ManualEntry.refreshPages(ManualEntry.java:72)
> [30一月2021 08:59:04.157] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 28 more
> [30一月2021 08:59:04.157] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.IllegalArgumentException: Can not set com.electronwill.nightconfig.core.Config field net.minecraftforge.common.ForgeConfigSpec.childConfig to blusunrize.immersiveengineering.common.config.CachedConfig
> [30一月2021 08:59:04.157] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
> [30一月2021 08:59:04.157] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
> [30一月2021 08:59:04.157] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(Unknown Source)
> [30一月2021 08:59:04.157] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at sun.reflect.UnsafeObjectFieldAccessorImpl.get(Unknown Source)
> [30一月2021 08:59:04.158] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.reflect.Field.get(Unknown Source)
> [30一月2021 08:59:04.158] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at flaxbeard.immersivepetroleum.common.IPConfig.getRawConfig(IPConfig.java:46)
> [30一月2021 08:59:04.158] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 32 more
> [30一月2021 08:59:04.158] [Render thread/INFO] [immersiveengineering-manual/]: Manual reload took 112 ms
> [30一月2021 08:59:04.158] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] 5 entries failed to load! Please report this as an issue with your log file!

### Versions & Modlist
ImmersiveEngineering-1.16.5-4.2.0-130
ImmersivePetroleum-1.16.4-3.1.0-2

**Comment by BluSunrize** [comment]
Can you reproduce this without ImmersivePetroleum?

**Comment by frank89722** [comment]
This happened under zh_cn lang without ImmersivePetroleum

Log:
```
[02Feb2021 03:06:44.488] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: java.lang.RuntimeException: Exception while refreshing manual entry immersiveengineering:excavator for manual ¤uµ{?¤⿍
[02Feb2021 03:06:44.488] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at blusunrize.lib.manual.ManualEntry.refreshPages(ManualEntry.java:89)
[02Feb2021 03:06:44.488] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at blusunrize.lib.manual.ManualInstance.loadEntriesInArray(ManualInstance.java:515)
[02Feb2021 03:06:44.488] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at blusunrize.lib.manual.ManualInstance.autoloadEntriesFromJson(ManualInstance.java:482)
[02Feb2021 03:06:44.488] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at blusunrize.lib.manual.ManualInstance.autoloadEntriesFromJson(ManualInstance.java:487)
[02Feb2021 03:06:44.488] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at blusunrize.lib.manual.ManualInstance.loadAutoEntries(ManualInstance.java:454)
[02Feb2021 03:06:44.488] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at blusunrize.lib.manual.ManualInstance.reload(ManualInstance.java:406)
[02Feb2021 03:06:44.488] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at blusunrize.lib.manual.ManualInstance.getGui(ManualInstance.java:262)
[02Feb2021 03:06:44.489] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at blusunrize.lib.manual.ManualInstance.getGui(ManualInstance.java:252)
[02Feb2021 03:06:44.489] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at blusunrize.immersiveengineering.client.ClientProxy.openManual(ClientProxy.java:583)
[02Feb2021 03:06:44.489] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at blusunrize.immersiveengineering.common.items.ManualItem.func_77659_a(ManualItem.java:38)
[02Feb2021 03:06:44.489] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:214)
[02Feb2021 03:06:44.489] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at net.minecraft.client.multiplayer.PlayerController.func_187101_a(PlayerController.java:328)
[02Feb2021 03:06:44.489] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1389)
[02Feb2021 03:06:44.489] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1645)
[02Feb2021 03:06:44.489] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1460)
[02Feb2021 03:06:44.489] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953)
[02Feb2021 03:06:44.489] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
[02Feb2021 03:06:44.489] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at net.minecraft.client.main.Main.main(Main.java:184)
[02Feb2021 03:06:44.489] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02Feb2021 03:06:44.489] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[02Feb2021 03:06:44.489] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[02Feb2021 03:06:44.489] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[02Feb2021 03:06:44.489] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[02Feb2021 03:06:44.489] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[02Feb2021 03:06:44.490] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[02Feb2021 03:06:44.490] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[02Feb2021 03:06:44.490] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[02Feb2021 03:06:44.490] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[02Feb2021 03:06:44.490] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50)
[02Feb2021 03:06:44.490] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02Feb2021 03:06:44.490] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[02Feb2021 03:06:44.490] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[02Feb2021 03:06:44.490] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[02Feb2021 03:06:44.490] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[02Feb2021 03:06:44.490] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[02Feb2021 03:06:44.490] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[02Feb2021 03:06:44.490] [Render thread/INFO] [STDERR/]: [blusunrize.lib.manual.ManualInstance:loadEntriesInArray:518]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[02Feb2021 03:06:44.490] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.IllegalStateException: Config key machines.excavator_consumption does not exist
[02Feb2021 03:06:44.490] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at com.google.common.base.Preconditions.checkState(Preconditions.java:518)
[02Feb2021 03:06:44.490] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at blusunrize.immersiveengineering.client.manual.IEManualInstance.formatConfigEntry(IEManualInstance.java:334)
[02Feb2021 03:06:44.491] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at blusunrize.immersiveengineering.client.manual.IEManualInstance.formatText(IEManualInstance.java:96)
[02Feb2021 03:06:44.491] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at blusunrize.lib.manual.ManualEntry.refreshPages(ManualEntry.java:72)
[02Feb2021 03:06:44.491] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 36 more
```

**Comment by HydrogenC** [comment]
It still happens under zh_CN without IP.
