### ISSUE TITLE
[1.16.5] Jerrycan plus Bucket crafting result in server stacktrace

### ISSUE THREAD

**Issue by SvenRtbg** [BluSunrize/ImmersiveEngineering#4690]
### Description of the issue:
Trying to figure out how to fill the jerrycan, when putting both an empty jerrycan and a bucket of biodiesel onto a crafting table, my local server console immediately printed this stacktrace error.

It wasn't the end of the world, I could continue playing without issues. However previously when encountering it, some effect created an additional jerrycan that seemed to be somehow broken. After all, I'd expect to be able to put stuff onto any crafting area without glitches. I hope you can resolve that issue.

### Crashlog:
[22:16:11] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
net.minecraft.crash.ReportedException: Container click
        at net.minecraft.inventory.container.Container.func_184996_a(Container.java:174) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ContainerAccess,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.network.play.ServerPlayNetHandler.func_147351_a(ServerPlayNetHandler.java:1265) ~[?:?] {re:classloading}
        at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:34) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:12) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281] {}
Caused by: java.lang.RuntimeException
        at java.util.Optional.orElseThrow(Unknown Source) ~[?:1.8.0_281] {}
        at blusunrize.immersiveengineering.common.crafting.JerrycanRefillRecipe.matches(JerrycanRefillRecipe.java:47) ~[immersiveengineering:?] {re:classloading}
        at blusunrize.immersiveengineering.common.crafting.JerrycanRefillRecipe.func_77569_a(JerrycanRefillRecipe.java:31) ~[immersiveengineering:?] {re:classloading}
        at net.minecraft.item.crafting.IRecipeType.func_222148_a(SourceFile:30) ~[?:?] {re:classloading}
        at net.minecraft.item.crafting.RecipeManager.lambda$getRecipe$2(RecipeManager.java:82) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:accessors.RecipeManagerAccess,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(Unknown Source) ~[?:1.8.0_281] {}
        at com.google.common.collect.CollectSpliterators$1WithCharacteristics.tryAdvance(CollectSpliterators.java:60) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.stream.ReferencePipeline.findFirst(Unknown Source) ~[?:1.8.0_281] {}
        at net.minecraft.item.crafting.RecipeManager.func_215371_a(RecipeManager.java:83) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:accessors.RecipeManagerAccess,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.inventory.container.WorkbenchContainer.func_217066_a(SourceFile:66) ~[?:?] {re:classloading}
        at net.minecraft.inventory.container.WorkbenchContainer.func_217069_a(SourceFile:80) ~[?:?] {re:classloading}
        at net.minecraft.util.IWorldPosCallable.func_221487_a(SourceFile:35) ~[?:?] {re:classloading}
        at net.minecraft.util.IWorldPosCallable$2.func_221484_a(SourceFile:22) ~[?:?] {re:classloading}
        at net.minecraft.util.IWorldPosCallable.func_221486_a(SourceFile:34) ~[?:?] {re:classloading}
        at net.minecraft.inventory.container.WorkbenchContainer.func_75130_a(SourceFile:80) ~[?:?] {re:classloading}
        at net.minecraft.inventory.CraftingInventory.func_70299_a(SourceFile:70) ~[?:?] {re:classloading}
        at net.minecraft.inventory.container.Slot.func_75215_d(Slot.java:61) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.inventory.container.Container.func_241440_b_(Container.java:278) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ContainerAccess,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.inventory.container.Container.func_184996_a(Container.java:160) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ContainerAccess,pl:mixin:A,pl:runtimedistcleaner:A}
        ... 17 more

### Versions & Modlist
IE 1.16.5-4.2.1-131
Forge 1.16.5-36.0.42
No other mods on the server.

Client using Optifine 1.16.5_HD_U_G6
and JustEnoughItems 1.16.4-7.6.1.71 (I experienced that even without JEI before).

**Comment by mindforger** [comment]
can you stuff that wall of text inside pastebin or similar please, like requested in the issue template

**Comment by BluSunrize** [comment]
You are using an outdated version of IE.
