### ISSUE TITLE
IDK But its spam super fast

### ISSUE THREAD

**Issue by Rezanans-wow** [BluSunrize/ImmersiveEngineering#4732]
### Before reporting:
1.16.5

### Description of the issue:
Error super fast error

### Crashlog:
no

### Versions & Modlist
Forge 1.16.5 last
![изображение](https://user-images.githubusercontent.com/49691442/111884951-7211c400-89cd-11eb-9569-b6d8ab1ac34e.png)
![изображение](https://user-images.githubusercontent.com/49691442/111884955-7807a500-89cd-11eb-9728-fe6342574dd7.png)
![изображение](https://user-images.githubusercontent.com/49691442/111884961-7d64ef80-89cd-11eb-9ca9-963256882116.png)
![изображение](https://user-images.githubusercontent.com/49691442/111884965-83f36700-89cd-11eb-88b6-ad86aa66fcb9.png)

![изображение](https://user-images.githubusercontent.com/49691442/111884971-8bb30b80-89cd-11eb-80c8-b10f8df89681.png)

### Lastly (you may delete this from the report itself)
[23:39:34] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: null
        Index: 1
        Listeners:
                0: NORMAL
                1: net.minecraftforge.eventbus.EventBus$$Lambda$2709/170954749@306a11b3
                2: ASM: class com.simibubi.create.events.CommonEvents onChunkUnloaded(Lnet/minecraftforge/event/world/ChunkEvent$Unload;)V
                3: ASM: net.minecraftforge.common.ForgeInternalHandler@6015fe56 onChunkUnload(Lnet/minecraftforge/event/world/ChunkEvent$Unload;)V
                4: ASM: class com.performant.coremod.event.ForgeBusEventHandler onChunkUnload(Lnet/minecraftforge/event/world/ChunkEvent$Unload;)V
                5: ASM: class blusunrize.immersiveengineering.api.wires.NetworkSanitizer chunkUnload(Lnet/minecraftforge/event/world/ChunkEvent$Unload;)V
                6: ASM: com.simibubi.create.foundation.command.ChunkUtil@1b9e97d4 chunkUnload(Lnet/minecraftforge/event/world/ChunkEvent$Unload;)V
java.lang.NullPointerException
        at appeng.hooks.TickHandler.onUnloadChunk(TickHandler.java:180)
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraft.world.server.ChunkManager.func_219185_a(ChunkManager.java:403)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
        at net.minecraft.world.server.ChunkManager.func_223155_b(ChunkManager.java:388)
        at net.minecraft.world.server.ChunkManager.func_219204_a(ChunkManager.java:366)
        at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:323)
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
        at java.lang.Thread.run(Thread.java:748)

**Comment by BluSunrize** [comment]
Wow, what a shitty error report.
