### ISSUE TITLE
[1.16.5] Player get "soft-banned" when walking on a conveyor belt

### ISSUE THREAD

**Issue by DreiPixel** [BluSunrize/ImmersiveEngineering#4858]
### Description of the issue:
for some reason players get disconnected when walking on top a conveyor belt and they cant join until the get moved away from it (have to edit nbt data). i dont know if its relevant but it was in a 2 block high tunnel.
i have on the Server Performant. but i removed it and the issue is still existing.

### Crashlog:
[gist](https://gist.github.com/DreiPixel/a9b139c7eed38590a47ea2e085c9bda3)+
relevant part is maybe this:
`Caused by: java.lang.IllegalAccessError: net.minecraft.network.play.ServerPlayNetHandler.setFloating(Z)V
        at blusunrize.immersiveengineering.api.utils.PlayerUtils.resetFloatingState(PlayerUtils.java:15) ~[immersiveengineering:?] {re:classloading}
        at blusunrize.immersiveengineering.api.tool.ConveyorHandler$IConveyorBelt.onEntityCollision(ConveyorHandler.java:433) ~[immersiveengineering:?] {re:classloading,pl:runtimedistcleaner:A}
        at blusunrize.immersiveengineering.common.blocks.metal.conveyors.BasicConveyor.onEntityCollision(BasicConveyor.java:132) ~[immersiveengineering:?] {re:classloading,pl:runtimedistcleaner:A}
        at blusunrize.immersiveengineering.common.blocks.metal.ConveyorBeltTileEntity.onEntityCollision(ConveyorBeltTileEntity.java:72) ~[immersiveengineering:?] {re:classloading}
        at blusunrize.immersiveengineering.common.blocks.IETileProviderBlock.func_196262_a(IETileProviderBlock.java:434) ~[immersiveengineering:?] {re:classloading}
        at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196950_a(AbstractBlock.java:628) ~[?:?] `

### Versions & Modlist
IE Version: 5.0.0-135
Forge: 36.1.10
[modlist](https://gist.github.com/DreiPixel/d0c419ab9dd109bff43064e92d34b7c3) its the modpack Engineer's Life 2

**Comment by BluSunrize** [comment]
Update Tetra
