### ISSUE TITLE
[1.15.2] Full world crash & won't reboot.

### ISSUE THREAD

**Issue by jordan8396** [BluSunrize/ImmersiveEngineering#4884]
**Describe the bug**

My World was working fine, then I discovered ProjectRed was finally on 1.15.2 So installed it. All was working fine for a good few hours, then the next time I open the map it immediately crashes. I reported it to the Project Red team who upon reading the crash report suggested it may have been an issue with IE, quoting:
```
java.lang.IllegalArgumentException: null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108) ~[guava-21.0.jar:?] {}
	at blusunrize.immersiveengineering.api.wires.utils.WireUtils.getVecForIICAt(WireUtils.java:210) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.api.ApiUtils.getVecForIICAt(ApiUtils.java:299) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.api.wires.Connection.generateCatenaryData(Connection.java:121) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.api.wires.ImmersiveConnectableTileEntity.genConnBlockstate(ImmersiveConnectableTileEntity.java:140) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.api.wires.ImmersiveConnectableTileEntity.getModelData(ImmersiveConnectableTileEntity.java:153) ~[?:?] {re:classloading}
```
This could well be a non-IE related crash (I don't know how to read crash logs), however I would like to explore all options to restore my world back to working order (if possible, even if I have to contact every mod dev 😕)

**Crash Log**

The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: null
Exit Code: -1
[Full crash log on Pastebin](https://pastebin.com/CctPNxcq) 

**Versions**
- Forge: 1.15.2 - 31.2.50
- IE: 1.15.2-4.0.0-117
- [Other mods installed (pastebin) ](https://pastebin.com/jhqu9FRh) 

**Screenshots**
- [Video of crash](https://user-images.githubusercontent.com/70548908/125689688-6d91e9c1-df44-4c2d-8614-35f94385f392.mp4) 

Thanks for the help 🙏

**Comment by BluSunrize** [comment]
We no longer support 1.15.2. All our development focus is on 1.16.5 and beyond.
