### ISSUE TITLE
[1.16.5/5.0.3] Immersive manual suddenly stopped working

### ISSUE THREAD

**Issue by TheMasterTM69** [BluSunrize/ImmersiveEngineering#4956]
I was playing on a modpack and opened my minecraft like any other day and wanted to start working on some IE but when i wanted to open my manual it just refused and a message appears in chat [1 entries failed to load].
I checked the logs and this is what shows up:

[16:06:11] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Can not set com.electronwill.nightconfig.core.Config field net.minecraftforge.common.ForgeConfigSpec.childConfig to blusunrize.immersiveengineering.common.config.CachedConfig
[16:06:11] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at flaxbeard.immersivepetroleum.common.cfg.IPServerConfig.getRawConfig(IPServerConfig.java:50)
[16:06:11] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at flaxbeard.immersivepetroleum.client.ClientProxy.lambda$completed$0(ClientProxy.java:176)
[16:06:11] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at flaxbeard.immersivepetroleum.client.ClientProxy$$Lambda$47128/2036988314.apply(Unknown Source)
[16:06:11] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at blusunrize.immersiveengineering.client.manual.IEManualInstance.formatConfigEntry(IEManualInstance.java:330)
[16:06:11] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at blusunrize.immersiveengineering.client.manual.IEManualInstance.formatText(IEManualInstance.java:96)
[16:06:11] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at blusunrize.lib.manual.ManualEntry.refreshPages(ManualEntry.java:72)
[16:06:11] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	... 36 more
[16:06:11] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.IllegalArgumentException: Can not set com.electronwill.nightconfig.core.Config field net.minecraftforge.common.ForgeConfigSpec.childConfig to blusunrize.immersiveengineering.common.config.CachedConfig
[16:06:11] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[16:06:11] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[16:06:11] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
[16:06:11] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
[16:06:11] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.reflect.Field.get(Field.java:393)
[16:06:11] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at flaxbeard.immersivepetroleum.common.cfg.IPServerConfig.getRawConfig(IPServerConfig.java:47)
[16:06:11] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:643]: 	... 41 more
[16:06:11] [Render thread/INFO]: Manual reload took 152 ms
[16:06:11] [Render thread/INFO]: [CHAT] 1 entries failed to load! Please report this as an issue with your log file!

Reinstalling mods doesnt help and im not sure what to do to fix this. 
any help? since i need the manual for machines.

**Comment by malte0811** [comment]
It's an interaction between the latest build of Immersive Posts and Immersive Petroleum, see TwistedGate/ImmersivePosts#34. Not on IEs side.
