### ISSUE TITLE
Error with Biomes You Go

### ISSUE THREAD

**Issue by aAndrew3030** [BluSunrize/ImmersiveEngineering#5019]
### Description of the issue:
Game (1.16.5) unable to initialize using the latest version (139) with BYG (v1.3.4), with forge 36.2.8

### Crashlog:
`java.lang.NullPointerException: Initializing game
	at net.minecraft.client.renderer.color.ItemColors.func_199877_a(ItemColors.java:97) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:byg.mixins.json:client.MixinItemColors,pl:mixin:A,pl:runtimedistcleaner:A}
	at corgiaoc.byg.client.textures.ColorManager.onItemColorsInit(ColorManager.java:30) ~[?:1.3.4] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.color.ItemColors.handler$znk000$addBYGItemColors(ItemColors.java:515) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:byg.mixins.json:client.MixinItemColors,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.color.ItemColors.func_186729_a(ItemColors.java:87) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:byg.mixins.json:client.MixinItemColors,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:461) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.8.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$508/1909198389.call(Unknown Source) [forge-1.16.5-36.2.8.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}`

**Comment by BedrockLegends** [comment]
Yep, I kept getting this too. I just never reported it cause I was not sure whos mod was causing the issue

**Comment by malte0811** [comment]
Please provide a full crashlog, not just the stacktrace. It's obvious that you are launching with more than just BYG and IE, and since I can't reproduce it with just BYG and IE I assume one of the others is relevant as well.

**Comment by aAndrew3030** [comment]
It is a error with Immersive Petroleum that is incompatible. Issue has been reported to them.
