### ISSUE TITLE
[1.17.1 | 3a3e148] Change causes FluidRouters guis with Liquids in the filter to crash the game

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#5036]
link: https://github.com/BluSunrize/ImmersiveEngineering/commit/3a3e14813140fa1839599554ba40af8e90dda8a1
as title
as of now I don't know if this affects other stuff, too

**Comment by MalkContent** [comment]
Crashlog:

<details>
<summary>crash-2021-10-14_16.14.52-client.txt (clickme)</summary>

```
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 14.10.21, 16:14
Description: Rendering screen

java.lang.IllegalStateException: Not filled all elements of the vertex
	at com.mojang.blaze3d.vertex.BufferBuilder.endVertex(BufferBuilder.java:249) ~[forge-1.17.1-37.0.90_mapped_parchment_2021.08.22-1.17.1-recomp.jar%2385!:?] {re:classloading,pl:runtimedistcleaner:A}
	at blusunrize.immersiveengineering.client.utils.TransformingVertexBuilder.endVertex(TransformingVertexBuilder.java:130) ~[%2389!:?] {re:classloading}
	at blusunrize.immersiveengineering.client.utils.GuiHelper.drawTexturedColoredRect(GuiHelper.java:78) ~[%2389!:?] {re:classloading}
	at blusunrize.immersiveengineering.client.gui.FluidSorterScreen.drawContainerBackgroundPre(FluidSorterScreen.java:98) ~[%2389!:?] {re:classloading}
	at blusunrize.immersiveengineering.client.gui.IEContainerScreen.renderBg(IEContainerScreen.java:108) ~[%2389!:?] {re:classloading}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.render(AbstractContainerScreen.java:104) ~[forge-1.17.1-37.0.90_mapped_parchment_2021.08.22-1.17.1-recomp.jar%2385!:?] {re:classloading,pl:runtimedistcleaner:A}
	at blusunrize.immersiveengineering.client.gui.IEContainerScreen.render(IEContainerScreen.java:67) ~[%2389!:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:392) ~[forge-1.17.1-37.0.90_mapped_parchment_2021.08.22-1.17.1-recomp.jar%2384%2390!:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:385) ~[forge-1.17.1-37.0.90_mapped_parchment_2021.08.22-1.17.1-recomp.jar%2384%2390!:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:897) ~[forge-1.17.1-37.0.90_mapped_parchment_2021.08.22-1.17.1-recomp.jar%2385!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1066) ~[forge-1.17.1-37.0.90_mapped_parchment_2021.08.22-1.17.1-recomp.jar%2385!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.run(Minecraft.java:664) ~[forge-1.17.1-37.0.90_mapped_parchment_2021.08.22-1.17.1-recomp.jar%2385!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:186) ~[forge-1.17.1-37.0.90_mapped_parchment_2021.08.22-1.17.1-recomp.jar%2385!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.ForgeClientUserdevLaunchHandler.lambda$launchService$0(ForgeClientUserdevLaunchHandler.java:38) ~[fmlloader-1.17.1-37.0.90.jar%233!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%2317!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%2317!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%2317!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%2317!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%2317!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%2317!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%2317!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.blaze3d.vertex.BufferBuilder.endVertex(BufferBuilder.java:249) ~[forge-1.17.1-37.0.90_mapped_parchment_2021.08.22-1.17.1-recomp.jar%2385!:?] {re:classloading,pl:runtimedistcleaner:A}
	at blusunrize.immersiveengineering.client.utils.TransformingVertexBuilder.endVertex(TransformingVertexBuilder.java:130) ~[%2389!:?] {re:classloading}
	at blusunrize.immersiveengineering.client.utils.GuiHelper.drawTexturedColoredRect(GuiHelper.java:78) ~[%2389!:?] {re:classloading}
	at blusunrize.immersiveengineering.client.gui.FluidSorterScreen.drawContainerBackgroundPre(FluidSorterScreen.java:98) ~[%2389!:?] {re:classloading}
	at blusunrize.immersiveengineering.client.gui.IEContainerScreen.renderBg(IEContainerScreen.java:108) ~[%2389!:?] {re:classloading}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.render(AbstractContainerScreen.java:104) ~[forge-1.17.1-37.0.90_mapped_parchment_2021.08.22-1.17.1-recomp.jar%2385!:?] {re:classloading,pl:runtimedistcleaner:A}
	at blusunrize.immersiveengineering.client.gui.IEContainerScreen.render(IEContainerScreen.java:67) ~[%2389!:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:392) ~[forge-1.17.1-37.0.90_mapped_parchment_2021.08.22-1.17.1-recomp.jar%2384%2390!:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:385) ~[forge-1.17.1-37.0.90_mapped_parchment_2021.08.22-1.17.1-recomp.jar%2384%2390!:?] {re:classloading}
-- Screen render details --
Details:
	Screen name: blusunrize.immersiveengineering.client.gui.FluidSorterScreen
	Mouse location: Scaled: (213, 120). Absolute: (427.000000, 240.000000)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Dev'/1, l='ClientLevel', x=-18.59, y=64.00, z=-47.67]]
	Chunk stats: 841, 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (-16,64,-32), Section: (at 0,0,0 in -1,4,-2; chunk contains blocks -16,0,-32 to -1,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 43743 game time, 1 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.fillReportDetails(ClientLevel.java:379) ~[forge-1.17.1-37.0.90_mapped_parchment_2021.08.22-1.17.1-recomp.jar%2385!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.fillReport(Minecraft.java:2307) ~[forge-1.17.1-37.0.90_mapped_parchment_2021.08.22-1.17.1-recomp.jar%2385!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.run(Minecraft.java:681) ~[forge-1.17.1-37.0.90_mapped_parchment_2021.08.22-1.17.1-recomp.jar%2385!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:186) ~[forge-1.17.1-37.0.90_mapped_parchment_2021.08.22-1.17.1-recomp.jar%2385!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.ForgeClientUserdevLaunchHandler.lambda$launchService$0(ForgeClientUserdevLaunchHandler.java:38) ~[fmlloader-1.17.1-37.0.90.jar%233!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%2317!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%2317!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%2317!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%2317!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%2317!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%2317!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%2317!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.2, Eclipse Foundation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Foundation
	Memory: 1236528040 bytes (1179 MiB) / 1790967808 bytes (1708 MiB) up to 4282384384 bytes (4084 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3,79
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce GTX 980
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x13c0
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7168
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 3,60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 3,60
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 26570,14
	Virtual memory used (MB): 19036,45
	Swap memory total (MB): 10240,00
	Swap memory used (MB): 584,23
	JVM Flags: 1 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Launched Version: MOD_DEV
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 980/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.68, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 5800X 8-Core Processor 
	Player Count: 1 / 8; [ServerPlayer['Dev'/1, l='ServerLevel[New World]', x=-18.59, y=64.00, z=-47.67]]
	Data Packs: vanilla, mod:forge, mod:immersiveengineering (incompatible), mod:jei (incompatible)
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclientuserdev
	ModLauncher naming: mcp
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 capability_inject_definalize PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		forge-1.17.1-37.0.90_mapped_parchment_2021.08.22-1|Minecraft                     |minecraft                     |1.17.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		                                                  |Forge                         |forge                         |37.0.90             |DONE      |Manifest: NOSIGNATURE
		main                                              |Immersive Engineering         |immersiveengineering          |1.17.1-7.0.0-137    |DONE      |Manifest: NOSIGNATURE
		jei-1.17.1-8.0.0.14_mapped_parchment_2021.08.22-1.|Just Enough Items             |jei                           |8.0.0.14            |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: e741acdb-9dc7-4824-8662-f793488d9585
	FML: 37.0
	Forge: net.minecraftforge:37.0.90
```
</details>

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/26df458223df7b4f1017d3a5973d4340f4057ca7
