### ISSUE TITLE
client-side CME in pipe code when loading world

### ISSUE THREAD

**Issue by cobra** [BluSunrize/ImmersiveEngineering#513]
Happened during debugging/testing, but I don't see any connection to what I'm doing. I saved and quit my world and after trying to load it again, this happened. I didn't change anything in the neighbourhood of the pipes in this world over the last days, so I guess this is a rather random fail and not caused by anything particular in this world.
````
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
	at com.google.common.collect.AbstractMapBasedMultimap.clear(AbstractMapBasedMultimap.java:288)
	at com.google.common.collect.ArrayListMultimap.clear(ArrayListMultimap.java:66)
	at blusunrize.immersiveengineering.common.blocks.metal.BlockMetalDevices2.onNeighborChange(BlockMetalDevices2.java:545)
	at net.minecraft.world.World.func_147453_f(World.java:4347)
	at net.minecraft.world.World.setTileEntity(World.java:2871)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:934)
	at net.minecraft.world.World.getTileEntity(World.java:2808)
	at net.minecraft.client.network.NetHandlerPlayClient.handleUpdateTileEntity(NetHandlerPlayClient.java:1263)
	at net.minecraft.network.play.server.S35PacketUpdateTileEntity.processPacket(S35PacketUpdateTileEntity.java:61)
	at net.minecraft.network.play.server.S35PacketUpdateTileEntity.processPacket(S35PacketUpdateTileEntity.java:69)
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:241)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:2152)
<snip>
````
I also have the relevant console log snippet in case someone needs it.
I could load the world without any problem after relaunching MC. I just can't remember the state of one pipe connection to a refinery before this crash, I \*think\* this was disconnected by hammering it and is now connected, but I'm really not sure about this.

**Comment by mindforger** [comment]
i spot a new multimap CME issue there :P https://github.com/BluSunrize/ImmersiveEngineering/issues/302 those maps are having serious issues mth multithread
