### ISSUE TITLE
OptiFine Incompatibility (Mixin Issue) [Same as #5246]

### ISSUE THREAD

**Issue by Eleiyas** [BluSunrize/ImmersiveEngineering#5247]
Minecraft: 1.18.2
Mod Version: 8.0.0-146

Issue:
Something in Immersive Engineering is causing an incompatibility with OptiFine.

```
at net.minecraft.client.renderer.ViewArea.m_110864_(ViewArea.java:62) ~[client-1.18.2-20220228.144236-srg.jar%23103!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.ViewArea.<init>(ViewArea.java:37) ~[client-1.18.2-20220228.144236-srg.jar%23103!/:?] {re:classloading,xf:OptiFine:default}

```
`Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [immersiveengineering.mixins.json:coremods.client.RebuildTaskMixin] from phase [DEFAULT] in config [immersiveengineering.mixins.json] FAILED during APPLY`

Fix:
Removing OptFine allows the mod to load, so clearly it's something from I.E interfering with OptiFine (vice-versa).

**Comment by BluSunrize** [comment]
If it's the same as #5246, you needn't have opened it.
