### ISSUE TITLE
Compat module for crafttweaker could not be preInitialized

### ISSUE THREAD

**Issue by Chaos02** [BluSunrize/ImmersiveEngineering#5410]
### Minecraft Version

1.18

### Immersive Engineering Version

8.1.0-150

### Expected Behavior

no error message

### Actual Behavior

Error message in game log
```
[Worker-Main-5/ERROR] [immersiveengineering/]: Compat module for crafttweaker could not be preInitialized. Report this and include the error message below!
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at blusunrize.immersiveengineering.common.util.compat.IECompatModules.constructModules(IECompatModules.java:67) ~[ImmersiveEngineering-1.18.2-8.1.0-150.jar%23232!/:?]
	at blusunrize.immersiveengineering.common.util.compat.IECompatModules.onCommonSetup(IECompatModules.java:77) ~[ImmersiveEngineering-1.18.2-8.1.0-150.jar%23232!/:?]
	at blusunrize.immersiveengineering.ImmersiveEngineering.setup(ImmersiveEngineering.java:223) ~[ImmersiveEngineering-1.18.2-8.1.0-150.jar%23232!/:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.1.73.jar%23408!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.1.73.jar%23407!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/blamejared/crafttweaker/api/event/type/CTCommandRegisterEvent
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
	at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?]
	at java.lang.Class.getMethods(Class.java:2019) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-5.0.3.jar%232!/:?]
	at blusunrize.immersiveengineering.common.util.compat.crafttweaker.CraftTweakerCompatModule.<init>(CraftTweakerCompatModule.java:17) ~[ImmersiveEngineering-1.18.2-8.1.0-150.jar%23232!/:?]
	... 21 more
Caused by: java.lang.ClassNotFoundException: com.blamejared.crafttweaker.api.event.type.CTCommandRegisterEvent
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:138) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
	at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?]
	at java.lang.Class.getMethods(Class.java:2019) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-5.0.3.jar%232!/:?]
	at blusunrize.immersiveengineering.common.util.compat.crafttweaker.CraftTweakerCompatModule.<init>(CraftTweakerCompatModule.java:17) ~[ImmersiveEngineering-1.18.2-8.1.0-150.jar%23232!/:?]
	... 21 more
```

### Steps to reproduce

start game.
forge-40.1.73

### Debug Crash Log

cannot get into game but unrelated to immersieve engineering

**Comment by mindforger** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/5407
Duplicate
