### ISSUE TITLE
Sheetmetal tank comparator output causes server-side NPE

### ISSUE THREAD

**Issue by cobra** [BluSunrize/ImmersiveEngineering#547]
Situation: sheetmetal tank full of water, set to auto-output by a redstone signal, connected by TE superlaminar fluiducts to a bottling machine.

Log:
````
[Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:709) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118) ~[IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752) [MinecraftServer$2.class:?]
Caused by: java.lang.NullPointerException
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntitySheetmetalTank.updateComparatorValuesPart2(TileEntitySheetmetalTank.java:274) ~[TileEntitySheetmetalTank.class:?]
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntitySheetmetalTank.updateEntity(TileEntitySheetmetalTank.java:79) ~[TileEntitySheetmetalTank.class:?]
	at net.minecraft.world.World.updateEntities(World.java:2160) ~[World.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:515) ~[WorldServer.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:703) ~[MinecraftServer.class:?]
	... 4 more (boring minecraft server internals)
````

I'm not going to investigate this immediately, so I'm just dumping it here.

**Comment by BluSunrize** [comment]
Boy am I glad that I didn't write that. x3

*pokes @malte0811 *

**Comment by cobra** [comment]
btw, this crashed every time until I killed the `updateComparatorValuesPart2` call. I'm not quite sure what happened there, it didn't look that NPE-y at the first glance.

**Comment by malte0811** [comment]
Looking at it now, my first guess would be that it is inserting into itself or something like that. A temporary fix would be to comment out the oldCompValues = null statement, but that really should not be necessary.

**Comment by malte0811** [comment]
When i is 1 in that loop, all offsets are 0. It is actually inserting into itself and therefore calling updateComparatorValuesPart2 twice. Adding something like `if (i==1) continue;` right at the beginning of the loop should fix this. (I am not at a computer right now, so i cant test this)

**Comment by cobra** [comment]
That makes wonder whether this should happen at all. Inserting back into the output sounds rather silly.

**Comment by malte0811** [comment]
I just noticed that the oldCompValues array probably should not be nulled anyways, because any transparent (ie pipes, eio ender fluid conduit) fluid transport inserting into the same tank would cause the same npe.

**Comment by cobra** [comment]
removed that line, doesn't crash any more, no matter what I try.

**Comment by malte0811** [comment]
@BluSunrize The same should be done for the Silo, I won't pr this since it is just two lines.

**Comment by BluSunrize** [comment]
hrmm, what now? What am I commenting out?

**Comment by cobra** [comment]
btw, whoever will fix this can also move the "new int[6]" and move that to the field initialisation.

@BluSunrize TileEntitySilo.java, last line, it's the same as for the tank.

**Comment by BluSunrize** [comment]
Is that what you meant?

**Comment by malte0811** [comment]
yes

**Comment by BluSunrize** [comment]
yay.
