### ISSUE TITLE
 AE2 Fluid Crafting Interaction with Treated planks + Molecular assembler

### ISSUE THREAD

**Issue by Sunekaer** [BluSunrize/ImmersiveEngineering#5493]
### Minecraft Version

1.18

### Immersive Engineering Version

1.18.2-8.2.2-154

### Expected Behavior

To not error

### Actual Behavior

The server console gets spammed with this error when someone on the server fluid crafts with AE2 molecular assembler. More specifically, the treated wood recipe 

```
[27Nov2022 21:28:40.030] [Server thread/ERROR] [immersiveengineering/]: IRecipe#getRemainingItems was called with an inventory that does not match the recipe
[27Nov2022 21:28:40.031] [Server thread/ERROR] [immersiveengineering/]: according to IRecipe#matches. This is probably a bug in some mod in the following stacktrace,
[27Nov2022 21:28:40.031] [Server thread/ERROR] [immersiveengineering/]: if in doubt report it to Immersive Engineering
java.lang.IllegalArgumentException: null
	at blusunrize.immersiveengineering.common.crafting.fluidaware.AbstractFluidAwareRecipe.getRemainingItems(AbstractFluidAwareRecipe.java:98) ~[ImmersiveEngineering-1.18.2-8.2.2-154.jar%23132!/:?]
	at blusunrize.immersiveengineering.common.crafting.fluidaware.AbstractFluidAwareRecipe.m_7457_(AbstractFluidAwareRecipe.java:25) ~[ImmersiveEngineering-1.18.2-8.2.2-154.jar%23132!/:?]
	at appeng.crafting.pattern.AECraftingPattern.getRemainingItems(AECraftingPattern.java:417) ~[appliedenergistics2-forge-11.6.6.jar%2346!/:11.6.6]
	at appeng.blockentity.crafting.MolecularAssemblerBlockEntity.tickingRequest(MolecularAssemblerBlockEntity.java:413) ~[appliedenergistics2-forge-11.6.6.jar%2346!/:11.6.6]
	at appeng.me.service.TickManagerService.unsafeTickingRequest(TickManagerService.java:358) ~[appliedenergistics2-forge-11.6.6.jar%2346!/:11.6.6]
	at appeng.me.service.TickManagerService.tickQueue(TickManagerService.java:121) ~[appliedenergistics2-forge-11.6.6.jar%2346!/:11.6.6]
	at appeng.me.service.TickManagerService.tickLevelQueue(TickManagerService.java:93) ~[appliedenergistics2-forge-11.6.6.jar%2346!/:11.6.6]
	at appeng.me.service.TickManagerService.onLevelEndTick(TickManagerService.java:78) ~[appliedenergistics2-forge-11.6.6.jar%2346!/:11.6.6]
	at appeng.me.Grid.onLevelEndTick(Grid.java:262) ~[appliedenergistics2-forge-11.6.6.jar%2346!/:11.6.6]
	at appeng.hooks.ticking.TickHandler.onServerLevelTickEnd(TickHandler.java:282) ~[appliedenergistics2-forge-11.6.6.jar%2346!/:11.6.6]
	at appeng.hooks.ticking.TickHandler.onLevelTick(TickHandler.java:248) ~[appliedenergistics2-forge-11.6.6.jar%2346!/:11.6.6]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onPostWorldTick(ForgeEventFactory.java:911) ~[forge-1.18.2-40.1.84-universal.jar%23264!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:908) ~[server-1.18.2-20220404.173914-srg.jar%23259!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23259!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23259!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23259!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23259!/:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

### Steps to reproduce

    Setup an AE2 setup for auto crafting with molecular assembler and fluid cells.
    Craft treated planks
    Read console output

### Debug Crash Log

n/a

**Comment by malte0811** [comment]
After discussion with an AE2 dev, this is a bug on their end: AppliedEnergistics/Applied-Energistics-2#6804
