### ISSUE TITLE
java.lang.NoClassDefFoundError: net/minecraft/world/level/storage/loot/entries/LootPoolEntry

### ISSUE THREAD

**Issue by Shadowrs** [BluSunrize/ImmersiveEngineering#5531]
### Minecraft Version

1.18

### Immersive Engineering Version

1.18.2-8.3.0-155

### How did it happen?

Crash on client start
```-- MOD immersiveengineering --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraft/world/level/storage/loot/entries/LootPoolEntry
		at blusunrize.immersiveengineering.common.util.loot.IELootFunctions.register(IELootFunctions.java:49) ~[ImmersiveEngineering-1.18.2-8.3.0-155.jar%23209!/:?] {re:classloading}
		at net.minecraftforge.eventbus.ASMEventHandler_612_IELootFunctions_register_Register.invoke(.dynamic) ~[?:?] {}
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
```

i rolled back to build 154 and its fixed

### Crash Log

https://pastebin.com/wGUHJ7t7

Edit by @malte0811: Fix formatting

**Comment by mindforger** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/5509

**Comment by malte0811** [comment]
@mindforger I do not see how this is related to #5509. The error is different, and the conflicting mod from that issue is not installed here.

**Comment by malte0811** [comment]
@Shadowrs Does it always crash when you use build 155 or was this a one-time issue? If it's reproducible, please upload a full client log (`logs/debug.log`) of a crashed launch. This is one of those "this should not be possible" crashes.

**Comment by Shadowrs** [comment]
Yep works fine now, must have been a one time thing. What would cause that out of curiosity? the "shout not be possible" part :) inconsistent MC startup loading order from forge? @malte0811

**Comment by mindforger** [comment]
i am sorry, i mixed up issues when answering it seems
