### ISSUE TITLE
[1.19.2] Client crash by standing garden cloche and using Optifine

### ISSUE THREAD

**Issue by Midnight-Vortex** [BluSunrize/ImmersiveEngineering#5549]
### Minecraft Version

1.19

### Immersive Engineering Version

 ImmersiveEngineering-1.19.2-9.1.1-158

### How did it happen?

`java.lang.NoSuchMethodError: 'void com.mojang.blaze3d.vertex.PoseStack.pushTransformation(com.mojang.math.Transformation)'
	at net.minecraftforge.client.extensions.IForgeTransformation.push(IForgeTransformation.java:51) ~[forge-1.19.2-43.2.4-universal.jar%23368!/:?] {re:classloading}
	at blusunrize.immersiveengineering.client.render.tile.ClocheRenderer.render(ClocheRenderer.java:85) ~[ImmersiveEngineering-1.19.2-9.1.1-158.jar%23305!/:?] {re:classloading}
	at blusunrize.immersiveengineering.client.render.tile.ClocheRenderer.m_6922_(ClocheRenderer.java:39) ~[ImmersiveEngineering-1.19.2-9.1.1-158.jar%23305!/:?] {re:classloading}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112284_(BlockEntityRenderDispatcher.java:116) ~[client-1.19.2-20220805.130853-srg.jar%23363!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.lambda$renderTileEntity$0(BlockEntityRenderDispatcher.java:86) ~[client-1.19.2-20220805.130853-srg.jar%23363!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112278_(BlockEntityRenderDispatcher.java:163) ~[client-1.19.2-20220805.130853-srg.jar%23363!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112267_(BlockEntityRenderDispatcher.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23363!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:546) ~[OptiFine_1.19.2_HD_U_I1.jar%23383!/:?] {re:classloading}
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4995) ~[OptiFine_1.19.2_HD_U_I1.jar%23383!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1505) ~[client-1.19.2-20220805.130853-srg.jar%23363!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1191) ~[client-1.19.2-20220805.130853-srg.jar%23363!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23363!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:client.MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23363!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:client.MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23363!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23363!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.4.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
`

### Crash Log

https://pastebin.com/F3KFXDKE

**Comment by BluSunrize** [comment]
Optifine is not supported

**Comment by Midnight-Vortex** [comment]
please update this with optifine many players use optfine.

**Comment by malte0811** [comment]
As Blu said, Optifine is unsupported and will never be. And even if it was, this particular crash is 100% on Optifine's side. There's nothing we can do to fix it.
