### ISSUE TITLE
Crash relating to Conveyors generated with structures

### ISSUE THREAD

**Issue by brisingraerowing** [BluSunrize/ImmersiveEngineering#5723]
### Minecraft Version

1.19.2

### Immersive Engineering Version

9.2.2-165

### How did it happen?

Went up to a CTOV jungle village, which apparently had an IE house with conveyors. I'm presuming this is similar to a crash I reported to Create where something placed during worldgen gets destroyed by another worldgen part.

### Crash Log

https://gist.github.com/brisingraerowing/2da9927f536236e9930a3e717f66a952

**Comment by Roaring1** [comment]
I had this happen as well, I was in the End Dimension (1.16.5) looting buildings then my computer (I always have task manager open) randomly shot up from 10GB of RAM to 32GB of RAM. .. My CPU (i9 13900k) ALSO shoots up from 15% usage to 100% usage. Same with my GPU (3070).  my entire Minecraft game lags, it gets framey, then I decide to wait for a minute or two, and the game stays frozen, so I then relaunch, then the game reopens, and it has odd lines going through the screen horizontally when I load the world. it looks like the dirt background of Minecraft and the refreshe rate was screwed up on my monitor suddenlyor something. i relaunched, without optifine BSL shaders, and did it again, my game was okay for a second, then I went to open my backpack (sophisticated backpack) and my game crashed. Then, I relaunched, went through JEI, and went to the 38th page or whatever (it was Immersive Engineering) and my game crashed. I went through the Crashy log, and it said it failed to render item Error Info: 1 conveyor_basic immersive-engineering:conveyor_basic ........ ALL times. 

here's the crash log:
https://bytebin.lucko.me/QuN5C4fT6H

Here's a game clip from the fourth relaunch.. EVERYTHING is screwed up. The animations, the textures(look at Waiwla it's a mekanism cardboard box, and all of the other items in my inventory are "not as they seem" , being everywhere.), everything is scrambled. shortly after this clip, the game became a blue-teal dark color (color picker hex #13131d) and froze hahahaha.
https://medal.tv/games/minecraft/clips/1seAoYUExP_F6X/d1337vEqqBVw?invite=cr-MSxqeU4sNjU1ODU4NDUs

Eventually I uninstalled Immersive Engineering entirely, and it fixed it. This is just for yall to know
sorry I said so much just wanted to not be "that guy"

**Comment by mindforger** [comment]
@Roaring1 your issue is completely unrelated and i am pretty sure uninstalling optifine will fix your issue for good, 
so please

Test without optifine, make a new issue if it still happens but dont respond here to not clutter this particular issue any further :)

**Comment by taj1994** [comment]
Did you ever figure this out?

My friends and I are getting the same crash in 1.20.1, playing All the Mods 9

https://mclo.gs/HUoBISQ

**Comment by brisingraerowing** [comment]
I'm presuming ATM9 has the CTOV IE compat datapack. [This modified version](https://cdn.discordapp.com/attachments/270295745230405643/1206978710646030356/ctov-immersive-enginneering-add-on-v2-0-crashfix.zip?ex=65e73405&is=65d4bf05&hm=af922585829de6c0226554365a74988ceae4592fc9c92bae3e5facbb38a6690b&) removes the conveyors from the Jungle Tree village hut, as that's the one with conveyors. If there's another village hut with conveyors, I can remove those as well.

**Comment by conamu** [comment]
We also had our server crash once entering a chunk with some generated conveyor belts. 

```
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 2024-03-16 12:50:43
Description: Feature placement

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.m_7702_(net.minecraft.core.BlockPos)" because the return value of "net.minecraft.world.level.block.entity.BlockEntity.m_58904_()" is null
	at blusunrize.immersiveengineering.common.blocks.metal.conveyors.VerticalConveyor.renderBottomBelt(VerticalConveyor.java:316) ~[ImmersiveEngineering-1.20.1-10.0.0-169.jar%23674!/:?] {re:classloading}
	at blusunrize.immersiveengineering.common.blocks.metal.conveyors.VerticalConveyor.getCollisionShape(VerticalConveyor.java:269) ~[ImmersiveEngineering-1.20.1-10.0.0-169.jar%23674!/:?] {re:classloading}
	at blusunrize.immersiveengineering.common.blocks.metal.ConveyorBeltBlockEntity.getCollisionShape(ConveyorBeltBlockEntity.java:193) ~[ImmersiveEngineering-1.20.1-10.0.0-169.jar%23674!/:?] {re:classloading}
	at blusunrize.immersiveengineering.common.blocks.IEEntityBlock.m_5939_(IEEntityBlock.java:370) ~[ImmersiveEngineering-1.20.1-10.0.0-169.jar%23674!/:?] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour.m_7947_(BlockBehaviour.java:277) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:BlockBehaviourMixin,pl:mixin:APP:chipped-common.mixins.json:BlockBehaviourMixin,pl:mixin:APP:mixins.shetiphiancore.json:SPC_CarpetPassthrough,pl:mixin:APP:gtceu.mixins.json:BlockBehaviourAccessor,pl:mixin:APP:railways-common.mixins.json:MixinBlockBehaviour,pl:mixin:A}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60816_(MixinBlockStateBase.java:688) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.BlockStateBaseMixin,pl:mixin:APP:kubejs-common.mixins.json:BlockStateBaseMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.reduce_blockstate_cache_rebuilds.BlockStateBaseMixin,pl:mixin:APP:useitemonblockevent.mixins.json:BlockStateBaseMixin,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:APP:framedblocks.mixin.json:MixinBlockStateBase,pl:mixin:APP:ars_nouveau.mixins.json:redstone.RedstoneLevelMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:mixins.integrateddynamics.json:MixinBlockStateBase,pl:mixin:APP:twigs.mixins.json:BlockStateBaseMixin,pl:mixin:A}
	at net.minecraft.world.level.block.MultifaceBlock.m_153829_(MultifaceBlock.java:240) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.level.block.VineBlock.m_57853_(VineBlock.java:120) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries-common.mixins.json:VineMixin,pl:mixin:A}
	at net.minecraft.world.level.levelgen.feature.VinesFeature.m_142674_(VinesFeature.java:43) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,re:classloading,pl:mixin:APP:repurposed_structures-common.mixins.json:features.NoVinesInStructuresMixin,pl:mixin:APP:betterjungletemples.mixins.json:NoVinesInTemplesMixin,pl:mixin:A}
	at net.minecraft.world.level.levelgen.feature.Feature.m_225028_(Feature.java:155) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,re:classloading,pl:mixin:APP:aether.mixins.json:common.FeatureMixin,pl:mixin:APP:farmersdelight.mixins.json:KeepRichSoilGiantTreeMixin,pl:mixin:A}
	at net.minecraft.world.level.levelgen.feature.ConfiguredFeature.m_224953_(ConfiguredFeature.java:28) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226362_(PlacedFeature.java:54) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithostitched.mixins.json:common.PlacedFeatureAccessor,pl:mixin:A}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?] {}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?] {}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?] {}
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?] {}
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?] {}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226368_(PlacedFeature.java:53) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithostitched.mixins.json:common.PlacedFeatureAccessor,pl:mixin:A}
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226377_(PlacedFeature.java:42) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithostitched.mixins.json:common.PlacedFeatureAccessor,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_213609_(ChunkGenerator.java:357) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterfortresses.mixins.json:DisableVanillaFortressesMixin,pl:mixin:APP:betterjungletemples.mixins.json:DisableVanillaJungleTempleMixin,pl:mixin:APP:betteroceanmonuments.mixins.json:DisableVanillaMonumentsMixin,pl:mixin:APP:citadel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:gtceu.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:bettermineshafts.mixins.json:DisableVanillaMineshaftsMixin,pl:mixin:APP:betterwitchhuts.mixins.json:DisableVanillaWitchHutsMixin,pl:mixin:APP:betterstrongholds.mixins.json:DisableVanillaStrongholdsMixin,pl:mixin:APP:betterdeserttemples.mixins.json:DisableVanillaPyramidsMixin,pl:mixin:APP:structure_gel.mixins.json:ChunkGeneratorMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkStatus.m_279978_(ChunkStatus.java:108) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:ChunkStatusMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_214024_(ChunkStatus.java:309) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.ChunkStatus.m_280308_(ChunkStatus.java:252) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:ChunkStatusMixin,pl:mixin:A}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:643) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar%2377!/:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$29(ChunkMap.java:634) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Suspected Mod: 
	Immersive Engineering (immersiveengineering), Version: 1.20.1-10.0.0-169
		Issue tracker URL: https://github.com/BluSunrize/ImmersiveEngineering/issues
		at TRANSFORMER/immersiveengineering@1.20.1-10.0.0-169/blusunrize.immersiveengineering.common.blocks.metal.conveyors.VerticalConveyor.renderBottomBelt(VerticalConveyor.java:316)
Stacktrace:
	at blusunrize.immersiveengineering.common.blocks.metal.conveyors.VerticalConveyor.renderBottomBelt(VerticalConveyor.java:316) ~[ImmersiveEngineering-1.20.1-10.0.0-169.jar%23674!/:?] {re:classloading}
	at blusunrize.immersiveengineering.common.blocks.metal.conveyors.VerticalConveyor.getCollisionShape(VerticalConveyor.java:269) ~[ImmersiveEngineering-1.20.1-10.0.0-169.jar%23674!/:?] {re:classloading}
	at blusunrize.immersiveengineering.common.blocks.metal.ConveyorBeltBlockEntity.getCollisionShape(ConveyorBeltBlockEntity.java:193) ~[ImmersiveEngineering-1.20.1-10.0.0-169.jar%23674!/:?] {re:classloading}
	at blusunrize.immersiveengineering.common.blocks.IEEntityBlock.m_5939_(IEEntityBlock.java:370) ~[ImmersiveEngineering-1.20.1-10.0.0-169.jar%23674!/:?] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour.m_7947_(BlockBehaviour.java:277) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:BlockBehaviourMixin,pl:mixin:APP:chipped-common.mixins.json:BlockBehaviourMixin,pl:mixin:APP:mixins.shetiphiancore.json:SPC_CarpetPassthrough,pl:mixin:APP:gtceu.mixins.json:BlockBehaviourAccessor,pl:mixin:APP:railways-common.mixins.json:MixinBlockBehaviour,pl:mixin:A}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60816_(MixinBlockStateBase.java:688) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.BlockStateBaseMixin,pl:mixin:APP:kubejs-common.mixins.json:BlockStateBaseMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.reduce_blockstate_cache_rebuilds.BlockStateBaseMixin,pl:mixin:APP:useitemonblockevent.mixins.json:BlockStateBaseMixin,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:APP:framedblocks.mixin.json:MixinBlockStateBase,pl:mixin:APP:ars_nouveau.mixins.json:redstone.RedstoneLevelMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:mixins.integrateddynamics.json:MixinBlockStateBase,pl:mixin:APP:twigs.mixins.json:BlockStateBaseMixin,pl:mixin:A}
	at net.minecraft.world.level.block.MultifaceBlock.m_153829_(MultifaceBlock.java:240) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.level.block.VineBlock.m_57853_(VineBlock.java:120) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries-common.mixins.json:VineMixin,pl:mixin:A}
	at net.minecraft.world.level.levelgen.feature.VinesFeature.m_142674_(VinesFeature.java:43) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,re:classloading,pl:mixin:APP:repurposed_structures-common.mixins.json:features.NoVinesInStructuresMixin,pl:mixin:APP:betterjungletemples.mixins.json:NoVinesInTemplesMixin,pl:mixin:A}
	at net.minecraft.world.level.levelgen.feature.Feature.m_225028_(Feature.java:155) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,re:classloading,pl:mixin:APP:aether.mixins.json:common.FeatureMixin,pl:mixin:APP:farmersdelight.mixins.json:KeepRichSoilGiantTreeMixin,pl:mixin:A}
	at net.minecraft.world.level.levelgen.feature.ConfiguredFeature.m_224953_(ConfiguredFeature.java:28) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226362_(PlacedFeature.java:54) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithostitched.mixins.json:common.PlacedFeatureAccessor,pl:mixin:A}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?] {}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?] {}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?] {}... (68 KB left)
```

**Comment by ChoiceTheorem** [comment]
I'll temporary remove conveyor belt from the jungle tree building.
