### ISSUE TITLE
Crash When Breaking Bottler

### ISSUE THREAD

**Issue by twhickey** [BluSunrize/ImmersiveEngineering#5845]
### Minecraft Version

1.20.1

### Immersive Engineering Version

10.0.0-169

### How did it happen?

1.20.1, modpack ATM9 version 0.2.36, multiplayer (crash in client, not server)

The crash occurs on the client when I attempt to break the bottler. If it matters, I was using a supremium paxel to break it.

One interesting note - prior to the crash, I was attempting to pipe molds into the bottler using an AE2 export bus, and a mold ended up on the input conveyor belt, but setting vertically instead of flat, and it didn't move with the belt. I was unable to interact with the mold in any way, it was visually on the belt, but looking at it didn't show any Jade date; so I tried to break the bottler to retrieve the mold. 
One other note, I did build the bottler mirrored left-to-right, and one of the entries in the stack trace was: at TRANSFORMER/immersiveengineering@1.20.1-10.0.0-169/blusunrize.immersiveengineering.client.models.mirror.CachedMirroredModel.getQuads(CachedMirroredModel.java:43)

### Crash Log

https://pastebin.com/y3KZNrTW

**Comment by twhickey** [comment]
Note - I went back and attempted breaking the bottler using an engineer's hammer, the same crash occurred.

I also attempted to use an ME Import Bus to remove the stuck mold, but that won't import the mold out of the multiblock.

**Comment by twhickey** [comment]
![2024-01-11_09 07 18](https://github.com/BluSunrize/ImmersiveEngineering/assets/8367542/4a234d3e-dc17-499c-b13f-b09a3d5e4d1e)

Image of the stuck mold

**Comment by BluSunrize** [comment]
Can you remove Embeddium and see if the crash still happens?

**Comment by Radon8472** [comment]
@BluSunrize 
We had the same issue on our server and spend some time to analyse the problem and gather some debug information.

> Can you remove Embeddium and see if the crash still happens?

The crash still happens (see tests below).


we discovered following facts


- removing Embeddium does not change anything 
- destroying and rebuilding the machine does not fix the issue
- it does not matter if the machine is facing south, north, east or west
- the issue is caused in the mirror orientation, and never happens in the "normal" orientation
- in happens everytime when you left-click the maschine, no matter if you do it with a tool or an empty hand
- in creative-mode you can break the machine without any crash
- it is a full client side crash, the server is NOT effected by this and does not show any errors. But the game of all players in view-distance of the maschine crashes
- the chunk or location of the machine does not matter, the problem occurs everywhere in the whole world even in other dimensions (so the problem should not ne located in any region or poi files)
- the issue is caused in singleplayer and in server-game as well

I hope our research can help to reproduce and solve this issue.

If you need any further information to reproduce the problem, just ask.


Everything was testet in

`Immersive Engineering, Version: 1.20.1-10.1.0-171`

**Comment by Radon8472** [comment]
I made more tests to reproduce this.

I can confirm this bug exists in version

-  `1.20.1-10.1.0-171`
-  `1.20.1-10.2.0-183`

But It seems to be fixed in the NeoForg version
- `1.21.1-12.1.0-185`
- and above

I tested it in a complete standalone situation using ONLY immersive no other mods

IMPORTAND TO REPRODUCE:

The Bug Only occurs when building the mashine in reversed orientation like this:

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/529330ed-324e-4a49-9e38-c6ed64ee8506" />

I made a small reproduce- modpack

[IE Bottle machine - reproduce-modpack.zip](https://github.com/user-attachments/files/21436640/IE.Bottle.machine.-.reproduce-modpack.zip)

This also contains the crashlogs für both affected versions.

### Steps To Reproduce
- yust left click in certain Blocks of the formated multiblock structure

The relevant parts of the stacktrace showing a `java.lang.NullPointerException: Tesselating block model` affected by following locations in your code

```
at blusunrize.immersiveengineering.client.models.mirror.CachedMirroredModel.getQuads(CachedMirroredModel.java:43) ~[ImmersiveEngineering-1.20.1-10.1.0-171.jar%23157!/:?] {re:classloading}
at blusunrize.immersiveengineering.api.client.ICacheKeyProvider.getQuads(ICacheKeyProvider.java:42) ~[ImmersiveEngineering-1.20.1-10.1.0-171.jar%23157!/:?] {re:classloading}
at blusunrize.immersiveengineering.client.models.mirror.CachedMirroredModel.getQuads(CachedMirroredModel.java:69) ~[ImmersiveEngineering-1.20.1-10.1.0-171.jar%23157!/:?] {re:classloading}
at blusunrize.immersiveengineering.client.models.CompositeBakedModel.getQuads(CompositeBakedModel.java:88) ~[ImmersiveEngineering-1.20.1-10.1.0-171.jar%23157!/:?] {re:classloading}
at blusunrize.immersiveengineering.client.models.split.BakedDynamicSplitModel.getQuads(BakedDynamicSplitModel.java:62) ~[ImmersiveEngineering-1.20.1-10.1.0-171.jar%23157!/:?] {re:classloading}
```


Thats all I can do to help you to reproduce this.

But I would say this issue seems to be les relevant because it seems to be fixed in the current versions of the mod

**Comment by BluSunrize** [comment]
Yeah, support for 1.20.1 has ceased as well. We're not releasing any further updates.
