### ISSUE TITLE
0.6.0 crash on startup from forestry missing class

### ISSUE THREAD

**Issue by Baughn** [BluSunrize/ImmersiveEngineering#586]
```
[00:25:53] [Server thread/ERROR]: Encountered an unexpected exception
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: forestry/core/config/GameMode

        at cpw.mods.fml.common.LoadController.transition(LoadController.java:163) ~[LoadController.class:?]
        at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744) ~[Loader.class:?]
        at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) ~[FMLServerHandler.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NoClassDefFoundError: forestry/core/config/GameMode
        at blusunrize.immersiveengineering.common.util.compat.ForestryHelper.postInit(ForestryHelper.java:37) ~[ForestryHelper.class:?]
        at blusunrize.immersiveengineering.ImmersiveEngineering.postInit(ImmersiveEngineering.java:105) ~[ImmersiveEngineering.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0-ea]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.8.0-ea]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0-ea]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0-ea]
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0-ea]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0-ea]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0-ea]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.8.0-ea]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0-ea]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0-ea]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:?]
        at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742) ~[Loader.class:?]
        ... 5 more
Caused by: java.lang.ClassNotFoundException: forestry.core.config.GameMode
```

**Comment by Baughn** [comment]
I don't see any version requirement listed anywhere.

**Comment by GirafiStudios** [comment]
Update to Forestry 4.0.+ or disable the Foresty module in the IE config.

**Comment by theunkn0wn1** [comment]
what @GirafiStudios said. 

duplicate #559 and others...

IE 0.6 was, and will continue to be, built against Forestry 4. Due to changes made since Forestry 3, this mod is incompatible with it.

**Comment by Baughn** [comment]
Ok, fair enough. Can you document that in the readme, though?

**Comment by theunkn0wn1** [comment]
Summon @BluSunrize.

**Comment by GirafiStudios** [comment]
@Baughn it's caused by modpacks or users not updating Forestry. It's not really IEs fault. Just update Forestry (And addons if any), and you should be good.

**Comment by BluSunrize** [comment]
Update forestry or disable IE's forestry module in the config. Also, check past issues before opening a new one.
