### ISSUE TITLE
Speedloaders do not play well with enderio's autocrafters

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#6021]
### Minecraft Version

1.20.1

### Immersive Engineering Version

10.1.0-171

### How did it happen?

I attempted to configure an enderio autocrafter to reload revolver speedloaders, and the server immediately went down. It cannot come back up until SpeedloaderLoadRecipe.assemble can handle the absence of a speedloader. It seems to be attempting to check which slots are already filled, which will not work as there is no speedloader to check. Please see the error below:

```
[15Jul2024 00:08:08.769] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking block entity
at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[server-1.20.1-20230612.114412-srg.jar%23141!/:?]
at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23141!/:?]
at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23141!/:?]
at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23141!/:?]
at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23141!/:?]
at java.lang.Thread.run(Thread.java:840) ~[?:?]

Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.ItemStack.m_41777_()" because "speedloader" is null
at blusunrize.immersiveengineering.common.crafting.SpeedloaderLoadRecipe.assemble(SpeedloaderLoadRecipe.java:109) ~[ImmersiveEngineering-1.20.1-10.1.0-171.jar%23130!/:?]
at blusunrize.immersiveengineering.common.crafting.SpeedloaderLoadRecipe.m_5874_(SpeedloaderLoadRecipe.java:27) ~[ImmersiveEngineering-1.20.1-10.1.0-171.jar%23130!/:?]
at com.enderio.machines.common.blockentity.CrafterBlockEntity.getRecipeResult(CrafterBlockEntity.java:175) ~[EnderIO-1.20.1-6.1.6-beta-all.jar%23129!/:6.1.6-beta]
at com.enderio.machines.common.blockentity.CrafterBlockEntity.tryCraft(CrafterBlockEntity.java:137) ~[EnderIO-1.20.1-6.1.6-beta-all.jar%23129!/:6.1.6-beta]
at com.enderio.machines.common.blockentity.CrafterBlockEntity.serverTick(CrafterBlockEntity.java:126)~[EnderIO-1.20.1-6.1.6-beta-all.jar%23129!/:6.1.6-beta]
at com.enderio.core.common.blockentity.EnderBlockEntity.tick(EnderBlockEntity.java:57) ~[EnderIO-1.20.1-6.1.6-beta-all.jar%23129!/:6.1.6-beta]
at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:689) ~[server-1.20.1-20230612.114412-srg.jar%23141!/:?]
at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782) ~[server-1.20.1-20230612.114412-srg.jar%23141!/:?]
at net.minecraft.world.level.Level.m_46463_(Level.java:468) ~[server-1.20.1-20230612.114412-srg.jar%23141!/:?]
at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351) ~[server-1.20.1-20230612.114412-srg.jar%23141!/:?]
at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23141!/:?]
... 5 more
```

### Crash Log

https://gist.github.com/melerva/7b96d6dff880b3ec46f719b0652143b0

**Comment by ghost** [comment]
Ah, sorry, I didn't know 1.20.1 wasn't supported anymore
