### ISSUE TITLE
Crashed when tried to connect server

### ISSUE THREAD

**Issue by sunduck6115-hash** [BluSunrize/ImmersiveEngineering#6030]
### Minecraft Version

1.20.4

### Immersive Engineering Version

IMUSING1.12.2

### How did it happen?

Im having crashed when i tryed to connect server

### Crash Log

https://pastebin.com/y3BxP1Py

**Comment by mindforger** [comment]
>java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Integer
	at blusunrize.immersiveengineering.common.Config.validateAndMapValues(Config.java:594)
	at blusunrize.immersiveengineering.common.Config.validateAndMapValues(Config.java:571)
	at blusunrize.immersiveengineering.common.Config.validateAndMapValues(Config.java:571)
	at pl.pabilo8.immersiveintelligence.common.IIConfigHandler.onConfigChanged(IIConfigHandler.java:1687)
	
you did a typo in your config, not sure where but you can probably use a yaml or json checker ... not sure which format was used in 1.12 anymore, but for anythin else bugwise, 1.12 is way way out of service :) 

propbably a "," instead a "." or you edited a float number that is writen like 10.0 and omitted the "." and wrote 10 instead
