### ISSUE TITLE
Crash when loading existing world on server.

### ISSUE THREAD

**Issue by webmilio** [BluSunrize/ImmersiveEngineering#614]
I've compiled my own version of ImmersiveEngineering (no sourcecode difference) using the latest source as of right now (2:38 EST, November 7th). I can create a world fine on client and I can load an existing save as well. The server loads an existing map but crashes shortly after.

Crash log: 

java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at blusunrize.immersiveengineering.api.energy.ImmersiveNetHandler.getRelevantDimensions(ImmersiveNetHandler.java:109)
	at blusunrize.immersiveengineering.common.IESaveData.func_76187_b(IESaveData.java:84)
	at net.minecraft.world.storage.MapStorage.func_75747_a(SourceFile:87)
	at net.minecraft.world.storage.MapStorage.func_75744_a(SourceFile:75)
	at net.minecraft.world.WorldServer.func_73042_a(WorldServer.java:838)
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:802)
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by webmilio** [comment]
Apparently, updating to Java 8 fixed all of my possible issues.

**Comment by webmilio** [comment]
Apparently, the issue was with Java. I haven't seen Java 8 mentioned anywhere, so I didn't think about it. MatterOverdrive made me update and it fixed this issue at the same time. I don't know if it's written anywhere, but it probably should.

**Comment by malte0811** [comment]
What version where you using when you got that crash? @BluSunrize may be compiling with java 8 unintentionally, the code is set to be java 6 compatible which should therefore be used for building.

**Comment by BluSunrize** [comment]
I compile on J7.

**Comment by webmilio** [comment]
For some reason, updating to Java 8 fixed it, without any changes in my modpack. All I changed was the Java version. I don't know how to enlighten you any further than what I've said on what I've done.
