### ISSUE TITLE
Crash with 6.2 - crash on start up

### ISSUE THREAD

**Issue by TheApologist** [BluSunrize/ImmersiveEngineering#723]
Crashes on start up.

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 12/1/15 5:12 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: blusunrize.immersiveengineering.ImmersiveEngineering
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: blusunrize.immersiveengineering.ImmersiveEngineering
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at cpw.mods.fml.common.ModClassLoader.loadClass(ModClassLoader.java:58)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:440)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 10 more
Caused by: java.lang.UnsupportedClassVersionError: blusunrize/immersiveengineering/ImmersiveEngineering : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 38 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.10.5
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 136030488 bytes (129 MB) / 270716928 bytes (258 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 26 mods loaded, 26 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UC	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UC	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UC	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UC	NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
	UC	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) 
	UC	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UC	BuildCraft|Core{7.1.12} [BuildCraft] (buildcraft-7.1.12-core.jar) 
	UC	BuildCraft|Builders{7.1.12} [BC Builders] (buildcraft-7.1.12-builders.jar) 
	UC	BuildCraft|Energy{7.1.12} [BC Energy] (buildcraft-7.1.12-energy.jar) 
	UC	BuildCraft|Factory{7.1.12} [BC Factory] (buildcraft-7.1.12-factory.jar) 
	UC	BuildCraft|Robotics{7.1.12} [BC Robotics] (buildcraft-7.1.12-robotics.jar) 
	UC	BuildCraft|Silicon{7.1.12} [BC Silicon] (buildcraft-7.1.12-silicon.jar) 
	UC	BuildCraft|Transport{7.1.12} [BC Transport] (buildcraft-7.1.12-transport.jar) 
	UC	DurabilityShow{1.2.0} [Durability Show] (Durability-Show-Mod-1.7.10.jar) 
	UC	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UC	Railcraft{9.8.0.0} [Railcraft] (Railcraft_1.7.10-9.8.0.0.jar) 
	UE	ImmersiveEngineering{0.6.0} [Immersive Engineering] (ImmersiveEngineering-0.6.0.jar) 
	UC	Waila{1.5.3} [Waila] (Waila-Mod-1.7.10.jar) 
	UC	JABBA{1.1.4} [JABBA] (Jabba-1.1.4_1.7.10.jar) 
	UC	MapWriter{2.1.2} [MapWriter] (MapWriter-Mod-1.7.10.jar) 
	UC	roar{1.1} [R.O.A.R. The Root of All Automation. Really.] (roar-1.1.jar) 
	UC	WailaHarvestability{1.1.0} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.0.jar) 
	UC	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UC	WaslieCore{1.1} [WaslieCore] (WaslieCore-1.1_B43.jar) 
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-10.6.33' Renderer: 'Intel HD Graphics 5000 OpenGL Engine'
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291

__________________________

**Comment by BluSunrize** [comment]
1) Spoiler your damn crashlogs, upload to pastebin or something.
2) That log is incomplete, I need everything.
3) It doesn't /look/ like your using 0.6.2 because the log says 0.6.0
4) did you download the deobf version by any chance? Because that would cause this crash.
5) Did you download from CurseForge or somewhere else?

**Comment by TheApologist** [comment]
Sorry about that http://pastebin.com/raw.php?i=LwA5sq8E -- I posted one of the test ones to see if the older files worked this one is up to date.
That is the whole crash log that minecraft supplied me with.
I downloaded the file from curseforge and it is not a deobf file.

**Comment by theunkn0wn1** [comment]
PLEASE edit your OP to remove the pasted crashlog.
the link appears to be the same thing as your OP. Unfortunately that log also appears to be incomplete. Please upload a copy of your 'FML-client-latest.log' after inducing the crash.

**Comment by BluSunrize** [comment]
Try updating to Java 7 or later

**Comment by LemADEC** [comment]
You are using Java 1.6, you need Java 1.7

**Comment by mindforger** [comment]
http://docs.oracle.com/javase/7/docs/webnotes/install/mac/mac-jdk.html
