### ISSUE TITLE
crash with Remain in motion frames, using IE version 6.4

### ISSUE THREAD

**Issue by escman1999** [BluSunrize/ImmersiveEngineering#785]
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 12/14/15 5:35 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at me.planetguy.remaininmotion.core.interop.mod.ImmersiveEngineering.saveConnections(ImmersiveEngineering.java:26)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_8_ImmersiveEngineering_saveConnections_BlockPreMoveEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at me.planetguy.remaininmotion.core.interop.EventPool.postEvent(EventPool.java:145)
	at me.planetguy.remaininmotion.core.interop.EventPool.postBlockPreMoveEvent(EventPool.java:59)
	at me.planetguy.remaininmotion.drive.TileEntityCarriageDrive.doPreMovementModInteraction(TileEntityCarriageDrive.java:465)
	at me.planetguy.remaininmotion.drive.TileEntityCarriageDrive.InitiateMotion(TileEntityCarriageDrive.java:447)
	at me.planetguy.remaininmotion.drive.TileEntityCarriageDrive.func_145845_h(TileEntityCarriageDrive.java:330)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at me.planetguy.remaininmotion.core.interop.mod.ImmersiveEngineering.saveConnections(ImmersiveEngineering.java:26)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_8_ImmersiveEngineering_saveConnections_BlockPreMoveEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at me.planetguy.remaininmotion.core.interop.EventPool.postEvent(EventPool.java:145)
	at me.planetguy.remaininmotion.core.interop.EventPool.postBlockPreMoveEvent(EventPool.java:59)
	at me.planetguy.remaininmotion.drive.TileEntityCarriageDrive.doPreMovementModInteraction(TileEntityCarriageDrive.java:465)
	at me.planetguy.remaininmotion.drive.TileEntityCarriageDrive.InitiateMotion(TileEntityCarriageDrive.java:447)
	at me.planetguy.remaininmotion.drive.TileEntityCarriageDrive.func_145845_h(TileEntityCarriageDrive.java:330)

-- Block entity being ticked --
Details:
	Name: JAKJ_RedstoneInMotion_CarriageEngineEntity // me.planetguy.remaininmotion.drive.TileEntityCarriageEngine
	Block type: ID #239 (tile.JAKJ_RedstoneInMotion_CarriageDrive // me.planetguy.remaininmotion.drive.BlockCarriageDrive)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-1076,6,-225), Chunk: (at 12,0,15 in -68,-15; contains blocks -1088,0,-240 to -1073,255,-225), Region: (-3,-1; contains chunks -96,-32 to -65,-1, blocks -1536,0,-512 to -1025,255,-1)
	Actual block type: ID #239 (tile.JAKJ_RedstoneInMotion_CarriageDrive // me.planetguy.remaininmotion.drive.BlockCarriageDrive)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['Escman1999'/287, l='New World', x=-1076.58, y=6.00, z=-226.27]]
	Chunk stats: ServerChunkCache: 402 Drop: 0
	Level seed: 5394992512326359012
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-1048,4,-287), Chunk: (at 8,0,1 in -66,-18; contains blocks -1056,0,-288 to -1041,255,-273), Region: (-3,-1; contains chunks -96,-32 to -65,-1, blocks -1536,0,-512 to -1025,255,-1)
	Level time: 10939 game time, 10939 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 139721 (now: false), thunder time: 99353 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 506097464 bytes (482 MB) / 695205888 bytes (663 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1566 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1566-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1566} [Minecraft Forge] (forge-1.7.10-10.13.4.1566-1.7.10-universal.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.6.4} [Immersive Engineering] (ImmersiveEngineering-0.6.4.jar) 
	UCHIJAAAA	planetguyLib{1.9} [planetguyLib] (PlanetguyLib-1.9.1.jar) 
	UCHIJAAAA	JAKJ_RedstoneInMotion{2.8.9} [Remain In Motion] (RemainInMotion-2.8.9.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Escman1999'/287, l='New World', x=-1076.58, y=6.00, z=-226.27]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Bitterholz** [comment]
I guess Wires and Multiblocks dont support being on frames, generally that would be silly, since you'd lose all your wire connections on movement.

**Comment by cobra** [comment]
Do NOT EVER move either any part of the energy net or any multiblock. Not with frames and not by any other method. Things will inevitably break rather horribly.

Also: DO NOT PASTE RAW CRASHLOGS! Put them on pastebin or in a gist. If you feel like posting a part of it here, mark it as code. This is very hard to read.

**Comment by BluSunrize** [comment]
1) Spoiler your fucking crashlog.
2) I don't take blame for you being stupid enough to stick IE things on a frame mod.
