### ISSUE TITLE
Minetweaker functionality seems to have broken.

### ISSUE THREAD

**Issue by tehFoxx0rz** [BluSunrize/ImmersiveEngineering#874]
My previous recipe changes for the arc furnace and crusher (at least; those and the squeezer are all I've tweaked) are now producing "null" errors  on 0.7.0.  If something's changed in how they should be formatted, then it doesn't seem to be mentioned anywhere...

Edit: Also noticed that, while functioning perfectly fine still, squeezer tweaks print:
INFO: Adding Squeezer Recipe for Fluid Plant Oil and Item null
to the Minetweaker log; clearly there's meant to be an item name where it says null.  Maybe related?

Examples of my tweaks:
mods.immersiveengineering.ArcFurnace.addRecipe(<GardenStuff:wrought_iron_ingot>,<minecraft:iron_ingot>,<ImmersiveEngineering:material:13>,200,512,[<minecraft:coal:1>]);

mods.immersiveengineering.Squeezer.addRecipe(null,<liquid:plantoil>*80,<plantmegapack:seedBeet>,80);

mods.immersiveengineering.Crusher.addRecipe(<minecraft:sand:1>,<minecraft:stained_hardened_clay:1>,3200);

Error message in minetweaker.log:
ERROR: Error executing Foxxcraft 2.0.zs: null
java.lang.NullPointerException
	at blusunrize.immersiveengineering.common.util.compat.minetweaker.ArcFurnace$Add.describe(ArcFurnace.java:60)
	at minetweaker.runtime.MTTweaker.apply(MTTweaker.java:55)
	at minetweaker.MineTweakerAPI.apply(MineTweakerAPI.java:169)
	at blusunrize.immersiveengineering.common.util.compat.minetweaker.ArcFurnace.addRecipe(ArcFurnace.java:32)
	at Foxxcraft 2.0.__script__(Foxxcraft 2.0.zs:33)
	at __ZenMain__.run(Foxxcraft 2.0.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:163)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:656)
	at minetweaker.MineTweakerImplementationAPI.onServerStart(MineTweakerImplementationAPI.java:566)
	at minetweaker.mc1710.MineTweakerMod.onServerAboutToStart(MineTweakerMod.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.serverAboutToStart(Loader.java:859)
	at cpw.mods.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:273)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:91)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by BluSunrize** [comment]
Spoiler your crashlogs. For gods sake, this is unreadable. I probably fixed this though. Reopen if it persists in coming relases.
