### ISSUE TITLE
Slab crusher crash

### ISSUE THREAD

**Issue by YarikIV** [BluSunrize/ImmersiveEngineering#890]
i was playing and i threw some stone slabs in the crusher and activate it and then the game crashed here's the report

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 17/01/16 11:49 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.put(Unknown Source)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityCrusher.getRecipe(TileEntityCrusher.java:287)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityCrusher.isValidInput(TileEntityCrusher.java:293)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityCrusher.func_145845_h(TileEntityCrusher.java:126)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.put(Unknown Source)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityCrusher.getRecipe(TileEntityCrusher.java:287)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityCrusher.isValidInput(TileEntityCrusher.java:293)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityCrusher.func_145845_h(TileEntityCrusher.java:126)

-- Block entity being ticked --
Details:
	Name: ImmersiveEngineering:Crusher // blusunrize.immersiveengineering.common.blocks.metal.TileEntityCrusher
	Block type: ID #189 (tile.ImmersiveEngineering.metalMultiblock // blusunrize.immersiveengineering.common.blocks.metal.BlockMetalMultiblocks)
	Block data value: 5 / 0x5 / 0b0101
	Block location: World: (168,60,202), Chunk: (at 8,3,10 in 10,12; contains blocks 160,0,192 to 175,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #189 (tile.ImmersiveEngineering.metalMultiblock // blusunrize.immersiveengineering.common.blocks.metal.BlockMetalMultiblocks)
	Actual block data value: 5 / 0x5 / 0b0101
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: IE fuck yeah!
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: -6494499330817211839
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (216,64,248), Chunk: (at 8,4,8 in 13,15; contains blocks 208,0,240 to 223,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2509577 game time, 4017420 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 86240 (now: false), thunder time: 105644 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (x86) version 6.3
	Java Version: 1.8.0_40, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 126024296 bytes (120 MB) / 330014720 bytes (314 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.7.1.1} [Immersive Engineering] (ImmersiveEngineering-0.7.1.1.jar) 
	UCHIJAAAA	ImmibisCore{59.0.1} [Immibis Core] (Immibis-Core-1.7.10.jar) 
	UCHIJAAAA	journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	CoFHCore: -[1.7.10]3.0.3-303
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalDynamics: -[1.7.10]1.1.0-161
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by BluSunrize** [comment]
Have you never reported a crash before? Use pastebin for crying out loud! Don't post unspoilered logs!

Also, I'll direct this to @malte0811 since his crusher efficiency broke this.

**Comment by YarikIV** [comment]
no i havent. sorry
