### ISSUE TITLE
Wierd Error crash

### ISSUE THREAD

**Issue by Mkchief34** [BluSunrize/ImmersiveEngineering#987]
Whenever I launch the game, I get this. Please help!

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 3/2/16 6:41 PM
Description: Registering texture

java.lang.ArrayIndexOutOfBoundsException: 94
	at gcewing.architecture.BaseModClient.onTextureStitchEventPre(BaseModClient.java:657)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_112_BaseModClient_onTextureStitchEventPre_Pre.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPre(ForgeHooksClient.java:271)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:109)
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:97)
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:89)
	at net.minecraft.client.renderer.texture.TextureManager.func_110580_a(TextureManager.java:71)
	at net.minecraft.client.renderer.texture.TextureManager.func_130088_a(TextureManager.java:58)
	at blusunrize.immersiveengineering.client.ClientProxy.init(ClientProxy.java:267)
	at blusunrize.immersiveengineering.ImmersiveEngineering.init(ImmersiveEngineering.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at gcewing.architecture.BaseModClient.onTextureStitchEventPre(BaseModClient.java:657)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_112_BaseModClient_onTextureStitchEventPre_Pre.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPre(ForgeHooksClient.java:271)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:109)
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:97)

-- Resource location being registered --
Details:
	Resource location: minecraft:textures/atlas/immersiveengineering/revolvers.png
	Texture object class: net.minecraft.client.renderer.texture.TextureMap
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:89)
	at net.minecraft.client.renderer.texture.TextureManager.func_110580_a(TextureManager.java:71)
	at net.minecraft.client.renderer.texture.TextureManager.func_130088_a(TextureManager.java:58)
	at blusunrize.immersiveengineering.client.ClientProxy.init(ClientProxy.java:267)
	at blusunrize.immersiveengineering.ImmersiveEngineering.init(ImmersiveEngineering.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 473972112 bytes (452 MB) / 1362673664 bytes (1299 MB) up to 5315035136 bytes (5068 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 1 loaded mod(s)
          - Macro / Keybind Mod version 0.10.12
	LaunchWrapper: 44 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: net.minecraftforge.classloading.FluidIdTransformer
          - Transformer: appeng.transformer.asm.ASMIntegration
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: com.techjar.dvf.ClassTransformer
          - Transformer: DummyCore.ASM.DCASMManager
          - Transformer: atomicstryker.dynamiclights.common.DLTransformer
          - Transformer: fastcraft.asm.FastCraftTransformer
          - Transformer: micdoodle8.mods.miccore.MicdoodleTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: openeye.asm.MultiTransformer
          - Transformer: com.twinklez.se.SEClassTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: openmods.core.OpenModsClassTransformer
          - Transformer: openblocks.asm.OpenBlocksClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: appeng.transformer.asm.ASMTweaker
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: cofh.asm.CoFHAccessTransformer
          - Transformer: net.malisis.core.asm.MalisisCoreAccessTransformer
          - Transformer: micdoodle8.mods.miccore.MicdoodleAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: cofh.asm.CoFHClassTransformer
          - Transformer: net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
          - Transformer: net.malisis.core.util.chunkblock.ChunkBlockTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: net.eq2online.macros.transformers.MacrosTransformer
          - Transformer: net.eq2online.macros.transformers.CollectionPacketTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 115 mods loaded, 115 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHI	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHI	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHI	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHI	PacketLogger{0.0.1} [PacketLogger] (minecraft.jar) 
	UCHI	ivtoolkit{IvToolkit} [1.2] (minecraft.jar) 
	UCHI	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHI	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHI	OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar) 
	UCHI	se{0.4.1} [Super Enchants] (minecraft.jar) 
	UCHI	OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
	UCHI	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHI	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.444.jar) 
	UCHI	SpaceCore{4.1.9} [4Space Core] (4Space-4.1.9.jar) 
	UCHI	ExoCore{0.1.2} [4Space Exoplanets Core] (4Space-4.1.9.jar) 
	UCHI	ExoElipse{0.1.2} [4Space Exoplanets Elipse] (4Space-4.1.9.jar) 
	UCHI	SpaceCallisto{4.1.9} [4Space Callisto] (4Space-4.1.9.jar) 
	UCHI	SpaceEuropa{4.1.9} [4Space Europa] (4Space-4.1.9.jar) 
	UCHI	SpaceVenus{4.1.9} [4Space Venus] (4Space-4.1.9.jar) 
	UCHI	SpaceIo{4.1.9} [4Space Io] (4Space-4.1.9.jar) 
	UCHI	SpaceMercury{4.1.9} [4Space Mercury] (4Space-4.1.9.jar) 
	UCHI	SpacePluto{4.1.9} [4Space Pluto] (4Space-4.1.9.jar) 
	UCHI	lotr{Beta v27.2 for Minecraft 1.7.10} [The Lord of the Rings Mod] ([1.7.10] The Lord of the Rings Mod B27.2.jar) 
	UCHI	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHI	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28(1).jar) 
	UCHI	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) 
	UCHI	StatusEffectHUD{1.27} [StatusEffectHUD] ([1.7.10]StatusEffectHUD-client-1.27(1).jar) 
	UCHI	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHI	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHI	ArchitectureCraft{1.3.1} [ArchitectureCraft] (ArchitectureCraft-1.3.1-mc1.7.10.jar) 
	UCHI	CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar) 
	UCHI	Artifice{1.7.10R1.1.4} [Artifice] (Artifice-1.7.10-1.1.5R-399.jar) 
	UCHI	atum{0.6} [Atum] (Atum-1.7.10-0.6.77.jar) 
	UCHI	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x(1).jar) 
	UCHI	bagginses{2.1.1} [Bagginses] (Bagginses-2.1.1.jar) 
	UCHI	betterstorage{0.13.1.127} [BetterStorage] (BetterStorage-1.7.10-0.13.1.127.jar) 
	UCHI	BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
	UCHI	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHI	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHI	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12(1).jar) 
	UCH	ImmersiveEngineering{0.7.2} [Immersive Engineering] (ImmersiveEngineering-0.7.2.jar) 
	UCH	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCH	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCH	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCH	boilerplate{6.1.0} [Boilerplate] (boilerplate-1.7.10-6.1.0.jar) 
	UCH	Botania{r1.8-249} [Botania] (Botania r1.8-249.jar) 
	UCH	CarpentersBlocks{3.3.8_dev_r7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8_dev_r7 - MC 1.7.10.jar) 
	UCH	BuildMod{v1.0} [Build Mod] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCH	CoroPets{v1.0} [CoroPets] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCH	CoroAI{v1.0} [CoroAI] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCH	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCH	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCH	CustomChestLoot{2.0.0} [Custom Chest Loot] (CustomChestLoot-1.7.10-2.0.0.jar) 
	UCH	CustomPets{1.0.2} [Custom Pets] (custompets-1.7.10-1.0.2-universal.jar) 
	UCH	DragonMounts{r41-1.7.10} [Dragon Mounts] (DragonMounts-r41-1.7.10(1).jar) 
	UCH	DummyCore{1.13} [DummyCore] (DummyCore1.13.jar) 
	UCH	DynamicLights{1.3.9} [Dynamic Lights] (DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_onFire{1.0.5} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) 
	UCH	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCH	Enchiridion{1.3} [Enchiridion] (Enchiridion 2-1.7.10-2.0.2a.jar) 
	UCH	Enchiridion2{2.0.2a} [Enchiridion 2] (Enchiridion 2-1.7.10-2.0.2a.jar) 
	UCH	enhancedportals{3.0.12} [EnhancedPortals] (EnhancedPortals_1.7.10-universal-3.0.12.jar) 
	UCH	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.444.jar) 
	UCH	ExtraPlanets{1.0-3.2} [ExtraPlanets] (ExtraPlanets-1.0-Pre 3.2.jar) 
	UCH	FastCraft{1.21} [FastCraft] (fastcraft-1.21 (1).jar) 
	UCH	FireEmblemCraft{1.7.2} [Fire Emblem Craft By KelcoK22] (fireemblemcraft_1.7.10.jar) 
	UCH	flansmod{4.10.0} [Flan's Mod] (Flans Mod-1.7.10-4.10.0.jar) 
	UCH	Steamcraft{0.28.12} [Flaxbeard's Steam Power] (Flaxbeard'sSteamPower-1.7.10-0.28.12.jar) 
	UCH	fossil{1.7.10 Build 7.2.1} [Fossils and Archeology Revival] (Fossils_Archeology_Revival-1.7.10_Build-7.2.1.jar) 
	UCH	grim3212core{V0.2 - 1.7.10} [Grim3212 Core] (Grim3212 Core-V0.2-1.7.10.jar) 
	UCH	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCH	InventoryPets{1.3.91} [Inventory Pets] (inventorypets-1.7.10-1.3.91-universal(1).jar) 
	UCH	journeymap{5.1.4} [JourneyMap] (journeymap-1.7.10-5.1.4-unlimited.jar) 
	UCH	llibrary{0.3.4-1.7.10} [LLibrary] (LLibrary-0.3.4-1.7.10.jar) 
	UCH	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCH	malisisdoors{1.7.10-1.13.1} [Malisis' Doors] (malisisdoors-1.7.10-1.13.1.jar) 
	UCH	Mekanism{8.1.9} [Mekanism] (Mekanism-1.7.10-8.1.9.264.jar) 
	UCH	MekanismGenerators{8.1.9} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.9.264.jar) 
	UCH	MekanismTools{8.1.9} [MekanismTools] (MekanismTools-1.7.10-8.1.9.264.jar) 
	UCH	MineMenu{1.2.0} [MineMenu] (MineMenu-1.7.10-1.2.0.B44-universal.jar) 
	UCH	MovingWorld{1.7.10-1.8} [Moving World] (movingworld-1.7.10-1.8.jar) 
	UCH	cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.8(1.7.10).jar) 
	UCH	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UCH	galaxymod{1.1.0} [Project Nova] (NovaGalactic-1.1-1.7.10.jar) 
	UCH	numina{0.4.0.119} [Numina] (Numina-0.4.0.119.jar) 
	UCH	Oceancraft{1.4.1} [Oceancraft] (Oceancraft-1.4.1.jar) 
	UCH	OpenMods{0.9.1} [OpenMods] (OpenModsLib-1.7.10-0.9.1.jar) 
	UCH	OpenBlocks{1.5.1} [OpenBlocks] (OpenBlocks-1.7.10-1.5.1.jar) 
	UCH	openmodularturrets{2.1.8-199} [Open Modular Turrets] (OpenModularTurrets-1.7.10-2.1.8-199.jar) 
	UCH	harvestthenether{1.7.10} [Pam's Harvest the Nether] (Pam's Harvest the Nether 1.7.10a.jar) 
	UCH	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
	UCH	RadixCore{2.1.1} [RadixCore] (RadixCore-1.7.10-2.1.1-universal.jar) 
	UCH	RedstoneArsenal{1.7.10R1.1.2} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.2-92.jar) 
	UCH	libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) 
	UCH	xreliquary{1.2} [Reliquary] (Reliquary-1.2(2).jar) 
	UCH	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.413.jar) 
	UCH	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) 
	UCH	kitchen{1.3.18} [The Kitchen Mod] (TheKitchenMod-1.3.18-1.7.2-10.jar) 
	UCH	TravellersGear{1.16.4} [Traveller's Gear] (TravellersGear-1.7.10-1.16.4.jar) 
	UCH	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7(1).jar) 
	UCH	AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.7.10.jar) 
	UCH	taverns{2.2.1-0} [Village Taverns] (VillageTaverns-2.2.1-0.23.jar) 
	UCH	wawla{1.3.3} [What Are We Looking At] (Wawla-1.3.3-1.7.10.jar) 
	UCH	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3 (1).jar) 
	UCH	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCH	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1.8787' Renderer: 'ATI Radeon HD 3200 Graphics     '
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.1.2-325
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	RedstoneArsenal: -[1.7.10]1.1.2-92
	Stencil buffer state: Function set: ARB, pool: forge, bits: 8
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: ATI Radeon HD 3200 Graphics      GL version 2.1.8787, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: On (16)

**Comment by Mkchief34** [comment]
More notes-This happens with version 7.0.12

**Comment by BluSunrize** [comment]
Don't post your crashlogs unspoilered. Put them on pastebin or something.

From the looks of this, the ArchitectureCraft dev is stitching into my revolvermap. This is due to them ignoring the fact that other mods can register custom texturemaps.
Tell the ArchitectureCraft dev to fix their shit, and check for the texture map ID, rather than blindly stitching into it.

**Comment by Mkchief34** [comment]
Thanks for the help.
